### PR TITLE
Avoid hardcoding a limit to the number of args to cxa_find_matching_catch

### LINKED ISSUE #9605: Error: undefined symbol: __cxa_find_matching_catch_24
I am getting the above error when compiling my code with the latest emscripten version.

I traced it to the following parameter, and confirm that I can fix the error by setting `maxExceptionArgs` to 30.

https://github.com/emscripten-core/emscripten/blob/8f2ee09690fe29122bcc7368b873e4b78cdd4ea5/src/library_exceptions.js#L328

----

Is there anything I can do on my side to prevent LLVM from emitting call to this function?

----

The above code was changed in #8040/#8046, ping @juj

### PR DESCRIPTION
**Pull request by kripken**
Instead, generate them on demand.

I'm not sure why we started to hard-code it, but I think it may have been just trickier to write?

Fixes #9605

### CODE REVIEW

File: src/jsifier.js [hunk 1]
```diff
@@ -114,6 +114,16 @@ function JSify(data, functionsOnly) {
 
   // functionStub
   function functionStubHandler(item) {
+    if (!DISABLE_EXCEPTION_THROWING) {
+    // In LLVM, exceptions generate a set of functions of form __cxa_find_matching_catch_1(), __cxa_find_matching_catch_2(), etc.
+    // where the number specifies the number of arguments. In Emscripten, route all these to a single function '__cxa_find_matching_catch'
+    // that variadically processes all of these functions using JS 'arguments' object.
+      if (item.ident.startsWith('___cxa_find_matching_catch_')) {
+        var num = +item.ident.split('_').slice(-1)[0];
+        addCxaCatch(num);
```
Comment (sbc100) [inline src/jsifier.js]: Can we add a return here?

Also can you combine the conditions?:

````
if (!DISABLE_EXCEPTION_THROWING && item.ident.startsWith('___cxa_find_matching_catch_') {
```

Also what happens if we have DISABLE_EXCEPTION_THROWING set but then the module wants one of these functions.. I wonder if we should error here:

```
if (item.ident.startsWith('___cxa_find_matching_catch_')) {
   if (DISABLE_EXCEPTION_THROWING)
      some_kind_of_error?
   ...
   return early;
}
```

That last part is optional :)

Comment (kripken) [reply src/jsifier.js]: Good idea, adding an error.

We can't early return here because we just add library code, but emitting it is handled lower down. I added a comment.

File: src/jsifier.js [hunk 2]
```diff
@@ -114,6 +114,19 @@ function JSify(data, functionsOnly) {
 
   // functionStub
   function functionStubHandler(item) {
+    // In LLVM, exceptions generate a set of functions of form __cxa_find_matching_catch_1(), __cxa_find_matching_catch_2(), etc.
+    // where the number specifies the number of arguments. In Emscripten, route all these to a single function '__cxa_find_matching_catch'
+    // that variadically processes all of these functions using JS 'arguments' object.
+    if (item.ident.startsWith('___cxa_find_matching_catch_')) {
+      if (DISABLE_EXCEPTION_THROWING) {
+        return error('DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but exception catching code appears. Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) or compile all source files with -fno-except (so that no exceptions support code is required); also make sure DISABLE_EXCEPTION_CATCHING is set to the right value - if you want exceptions, it should be off, and vice versa.');
```
Comment (sbc100) [inline src/jsifier.js]: Doesn't error raise an exception?  in which case the return is not needed, right?

File: src/jsifier.js [hunk 3]
```diff
@@ -114,6 +114,19 @@ function JSify(data, functionsOnly) {
...
+      }
+      var num = +item.ident.split('_').slice(-1)[0];
+      addCxaCatch(num);
```
Comment (sbc100) [inline src/jsifier.js]: Given this only has one callsitre why not inline it here?  seems a little strange to have addCxaCatch in a different file but maybe I'm missing something.

File: src/jsifier.js (hunk 2 above)
Comment (kripken) [reply src/jsifier.js]: Oh, no, it does not. It logs and error, and tells the program to exit with an error. But it continues. That's how it can print an error on more than one missing symbol.

Comment (sbc100) [reply src/jsifier.js]: Oh, I see.   Well at least maybe add the `return` on its own line.  Right now it looks like the returning the error is somehow what we are doing.

Comment (kripken) [reply src/jsifier.js]: I can rename `error` to something else if you have a better idea? (separate from this PR)

File: src/jsifier.js (hunk 3 above)
Comment (kripken) [reply src/jsifier.js]: It uses `LibraryExceptions`, so it has to be defined in the same file, with the exceptions library code.

File: src/jsifier.js (hunk 2 above)
Comment (kripken) [reply src/jsifier.js]: Sure, moving the return.
