### PR TITLE
fix(nodefs): renamed files exists with old name

### LINKED ISSUE #10628: NODEFS: renamed file still exists with the old name
With a mounted `NODEFS` filesystem:

```
EM_ASM({FS.writeFile('filetorename',  'renametest');});
rename("filetorename", "renamedfile");
if( access("filetorename", F_OK) == 0 ) {
     // Should never go here - but it does
}
```

File with name `filetorename` still exists.

### PR DESCRIPTION
**Pull request by petersalomonsen**
nodefs renames the file in the filesystem, but does not change the `name` property in the file node.

fixes #10628

### CODE REVIEW

File: src/library_nodefs.js [hunk 1]
```diff
@@ -180,6 +180,7 @@ mergeInto(LibraryManager.library, {
         var newPath = PATH.join2(NODEFS.realPath(newDir), newName);
         try {
           fs.renameSync(oldPath, newPath);
+          oldNode.name = newName;
```
Comment (kripken) [inline src/library_nodefs.js]: please move this out of the `try`, as the try is only looking for FS exceptions.

Comment (petersalomonsen) [reply src/library_nodefs.js]: thanks for the review @kripken , fixed now.
