### PR TITLE
[tsgen] Fix exporting HEAP variables as any in TSD

### LINKED ISSUE #24941: emcc is declaring all exported Heap elements as any
^

### PR DESCRIPTION
**Pull request by brendandahl**
Exporting HEAP elements like HEAP8 inside TypeScript definitions were previously generating as `any` types because TSD emitter fallbacks assumed unknown signatures for runtime methods without docs.

To solve this, move high-level HEAP array definitions into libcore.js with explicit JSDoc type tags, treating them as library symbols. This allows the TSD generation to gather correct typed signatures.

Also includes casts for Closure Compiler warnings encountered.

Fixes #24941

### CODE REVIEW

File: src/parseTools.mjs [hunk 1]
```diff
@@ -521,7 +521,11 @@ function makeSetValueImpl(ptr, pos, value, type) {
   if (slab == 'HEAPU64' || slab == 'HEAP64') {
     value = castToBigInt(value);
   }
-  return `${slab}[${getHeapOffset(offset, type)}] = ${value}`;
+  let left = `${slab}[${getHeapOffset(offset, type)}]`;
```
Comment (sbc100) [inline src/parseTools.mjs]: lhs?

File: src/parseTools.mjs [hunk 2]
```diff
@@ -521,7 +521,11 @@ function makeSetValueImpl(ptr, pos, value, type) {
...
+  if (slab == 'HEAP64' || slab == 'HEAPU64') {
+    left = `/** @type {!Object} */ (${slab})[${getHeapOffset(offset, type)}]`;
```
Comment (sbc100) [inline src/parseTools.mjs]: Is it the offset of the RHS that is the wrong type here (according to closure)?

File: src/runtime_common.js [hunk 3]
```diff
@@ -78,33 +78,6 @@ if (ENVIRONMENT_IS_NODE && {{{ ENVIRONMENT_IS_WORKER_THREAD() }}}) {
...
-  HEAP32,
-/** @type {!Uint32Array} */
-  HEAPU32,
-/** @type {!Float32Array} */
-  HEAPF32,
-/** @type {!Float64Array} */
-  HEAPF64;
-
-#if WASM_BIGINT
-// BigInt64Array type is not correctly defined in closure
```
Comment (sbc100) [inline src/runtime_common.js:100]: Why not persist this commit into the new location?   Making this more of a no-op change?

File: test/test_other.py [hunk 4]
```diff
@@ -3693,7 +3693,7 @@ def test_emit_tsd(self):
                      self.get_cflags())
     self.assertFileContents(test_file('other/test_emit_tsd.d.ts'), read_file('test_emit_tsd.d.ts'))
     # Test that the output compiles with a TS file that uses the definitions.
-    cmd = shared.get_npm_cmd('tsc') + [test_file('other/test_tsd.ts'), '--noEmit']
+    cmd = shared.get_npm_cmd('tsc') + [test_file('other/test_tsd.ts'), '--noEmit', '--skipLibCheck']
```
Comment (sbc100) [inline test/test_other.py]: What does this do?

File: src/runtime_common.js (hunk 3 above)
Comment (brendandahl) [reply src/runtime_common.js:100]: We could leave this current definition, but the TS definitions will be worse. Using `/** not-@type {!BigInt64Array} */` will generate the TS def of `let HEAP64: any;`.

File: test/test_other.py (hunk 4 above)
Comment (brendandahl) [reply test/test_other.py]: Whoops shouldn't be part of this PR. That should speed up the check, but I'll do that in another PR for a few tests.

File: src/runtime_common.js (hunk 3 above)
Comment (sbc100) [reply src/runtime_common.js:100]: True, but maybe we can fix that as a followup if needed.  I imagine those 64-bit views are relatively less used.

File: src/lib/libcore.js [hunk 5]
```diff
@@ -21,6 +21,30 @@
 // new function with an '_', it will not be found.
 
 addToLibrary({
```
Comment (sbc100) [inline src/lib/libcore.js:23]: Maybe add a comment here as to why these are in the library at all?   i.e. its just for TS benefit right?

**Comment by sbc100** [comment]
Interesting/reassuring to see that this has zero codesize change

**Comment by brendandahl** [comment]
@sbc100 do you know why clang-format is failing on this branch?

**Comment by sbc100** [comment]
Sorry, you can ignore that job for now.

Its way too aggressive.
