### PR TITLE
[WasmFS] Eagerly read directory entries when opening directories

### LINKED ISSUE #19106: WasmFS/OPFS: std::filesystem::remove_all() errors out when attempting to remove a non-empty directory
After creating an opfs backend with a call to wasmfs_create_opfs_backend(), we will sometimes see the call to std::filesystem::remove_all() fail with error code '55' when called on a non-empty directory. None of the files in the directory are open. 

Even though error code '55' is returned, some of the files and subfolders in the directory are removed. If we call remove_all() in a loop until we stop seeing error code '55', then the directory is eventually removed in full.

### PR DESCRIPTION
**Pull request by tlively**
This ensures that subsequent getdents calls see a stable set of entries, even as
entries are removed or inserted after the open. Although on its face this sounds
like it would be incorrect behavior, it is in fact allowed by the spec and
solves a bug where deleting entries while iterating through them would cause
some entries to be skipped.

Fixes #19106.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #19556** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/19556" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/19556?utm_source=stack-comment).

File: system/lib/wasmfs/file_table.cpp [hunk 1]
```diff
@@ -60,4 +60,30 @@ FileTable::Handle::addEntry(std::shared_ptr<OpenFileState> openFileState) {
   return -EBADF;
 }
 
+int OpenFileState::create(std::shared_ptr<File> file,
+                          oflags_t flags,
+                          std::shared_ptr<OpenFileState>& out) {
+  assert(file);
```
Comment (kripken) [inline system/lib/wasmfs/file_table.cpp:66]: I see this is moved code, but this assert seems a little excessive? Is there a specific reason to worry about a bug here (and SAFE_HEAP/ASan are not enough)?

File: system/lib/wasmfs/file_table.h [hunk 2]
```diff
@@ -58,21 +58,24 @@ class OpenFileState : public std::enable_shared_from_this<OpenFileState> {
...
-  OpenFileState(private_key, oflags_t flags, std::shared_ptr<File> file)
-    : file(file), flags(flags) {}
+  // Cache directory entries at the moment the directory is opened so that
+  // subsequent getdents calls have a stable view of the contents. Including
+  // files removed after the open and excluding files added after the open is
+  // allowed, and trying to recalculate the directory contents on each getdents
+  // call could lead to missed directory entries if there are concurrent
+  // deletions that effectively move entries back past the current read position
+  // in the open directory.
+  const std::vector<Directory::Entry> dirents;
```
Comment (kripken) [inline system/lib/wasmfs/file_table.h:68]: Perhaps make this private like the other properties on this class? Or is there a fundamental difference compared to them?

File: test/dirent/test_readdir_unlink.c [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+      continue;
+    }
+    char path[10];
+    snprintf(path, 10, "test/%s", dirent->d_name);
+    if (unlink(path)) {
+      printf("Unable to unlink '%s'\n", path);
+      return 1;
+    }
+    printf("Unlinked '%s'\n", path);
+  }
```
Comment (kripken) [inline test/dirent/test_readdir_unlink.c:52]: Maybe also create a new file somewhere in the middle of this loop, to see that we don't end up iterating on it? (then delete it after the loop before the parent)

File: test/test_core.py [hunk 4]
```diff
@@ -5814,6 +5814,9 @@ def test_readdir(self):
   def test_readdir_empty(self):
     self.do_run_in_out_file_test('dirent/test_readdir_empty.c')
 
+  def test_readdir_unlink(self):
+    self.do_run_in_out_file_test('dirent/test_readdir_unlink.c')
```
Comment (kripken) [inline test/test_core.py:5818]: Side note, these tests should probably be in `other` - no reason to slow down CI by running them in all opt modes. But we can think about that separately, eventually.

**Review by kripken — APPROVED** [review]
lgtm % comments

File: system/lib/wasmfs/file_table.h (hunk 2 above)
Comment (tlively) [reply system/lib/wasmfs/file_table.h:68]: This is immutable, so there's no need to access it through the locked handle. I can make it private for consistency if you want, though. We already have a locked handle at the use site, so it shouldn't matter for performance.

File: system/lib/wasmfs/file_table.cpp (hunk 1 above)
Comment (tlively) [reply system/lib/wasmfs/file_table.cpp:66]: No specific reasons, but I do think the assertion is reasonable. The function signature alone does not precisely convey the invariant that `file` should be non-null, and I don't think this assertion adds much cognitive overhead. If anything, I'd say it's helpful as documentation.

File: test/test_core.py (hunk 4 above)
Comment (tlively) [reply test/test_core.py:5818]: Sure, I'll move them in a follow-up.

File: system/lib/wasmfs/file_table.h (hunk 2 above)
Comment (kripken) [reply system/lib/wasmfs/file_table.h:68]: Ah, immutability... makes sense than as is, thanks.

File: test/dirent/test_readdir_unlink.c (hunk 3 above)
Comment (tlively) [reply test/dirent/test_readdir_unlink.c:52]: Hmm, I'm not sure I want to do that because an implementation that did visit such a file would still be valid.

Comment (kripken) [reply test/dirent/test_readdir_unlink.c:52]: True, but then the test would verify our current behavior. It wouldn't be expected to run in all POSIX-compliant systems, but I think we should test more strict things to avoid surprising behavior changes when we refactor.

File: test/test_core.py (hunk 4 above)
Comment (kripken) [reply test/test_core.py:5818]: Yeah, the criteria are fuzzy to me too. We definitely want some testing in `core`. But probably 80% can go in `other`.

For JS, we do need to test multiple opt modes, so in general I agree, those can stay in core.

For C++, aside from some testing of multiple opt modes, most seems fine in `other`.

File: test/dirent/test_readdir_unlink.c (hunk 3 above)
Comment (tlively) [reply test/dirent/test_readdir_unlink.c:63]: Done.

**Review by kripken — APPROVED** [review]

File: test/other/metadce/test_metadce_files_wasmfs.size [hunk 5]
```diff
@@ -1 +1 @@
-47462
+51960
```
Comment (kripken) [inline test/other/metadce/test_metadce_files_wasmfs.size:1]: Quite a large increase compared to the actual change in this PR... looks like strings operations mostly? Not sure we can avoid that.
