### PR TITLE
Asyncify Embind exports

### LINKED ISSUE #11890: Asyncify doesn't work synchronously when called from Embind function
Asyncify no longer works synchronously when it is called from an Embind function.

Here's an example code:

**main.cpp:**
```
#include <stdio.h>
#include <emscripten.h>
#include <emscripten/bind.h>

EM_JS(void, testReadFile, (), {
    Asyncify.handleAsync(async () => {
        FS.createDataFile("/", "foo.txt", "hello world", true, true, true);
        var uint8Array = await FS.readFile("foo.txt");
        var content = new TextDecoder("utf-8").decode(uint8Array);
        console.log(content);
    });
});

void test() {
    testReadFile();
}

EMSCRIPTEN_BINDINGS(my_test) {
    emscripten::function("test", &test);
}

int main()
{
}
```
**index.html:**
```
<!DOCTYPE html>
<html>

<head>
</head>

<body>
  <script>
    var Module
      = {
      onRuntimeInitialized: function () {
        console.log("before");
        Module.test();
        console.log("after");
      } 
   };
  </script>
  <script async src="main.js"></script>
</body>

</html>
```
**build, run:**
```
emcc main.cpp -o main.html --bind -s ASYNCIFY -s "ASYNCIFY_IMPORTS=['testReadFile']" -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"
python3 -m http.server 8080
```
**result:**
```
before
after
hello world
```

As you can see, it doesn't work synchronously.

But if I call `testReadFile()` directly from `main()`, it works synchronously.

Is this a bug? Would there be any workaround to fix this?

Thanks in advance!

### PR DESCRIPTION
**Pull request by RReverser**
Previously, if Embind function called an async function via Asyncify
somewhere in its call stack, it would return garbage default value
(`0` / `false` / class instance with a `NULL` pointer / etc.).

This PR changes such exports to instead return Promises when they
invoke an async function, and direct values otherwise. This preserves
backward compatibility for synchronous exports, while providing a more
useful value for async use-cases.

If Asyncify imports are invoked dynamically and user isn't sure which
exports will end up being async or not, they can simply use `await`
on all Embind exports and it will do the right thing as it works
correctly with both Promises and synchronous values alike.

Fixes #11890.

### CODE REVIEW

File: src/embind/embind.js [hunk 1]
```diff
@@ -1005,24 +1009,38 @@ var LibraryEmbind = {
...
+
+        if (returns) {
+          return argTypes[0].fromWireType(rv);
+        }
       }
 
-#if EMSCRIPTEN_TRACING
-      Module.emscripten_trace_exit_context();
+#if ASYNCIFY
+      if (Asyncify.currData) {
```
Comment (kripken) [inline src/embind/embind.js:1034]: What is this checking specifically? It would probably be better to do something explicit like
```
Asyncify.state === Asyncify.State.Unwinding
```

File: src/embind/embind.js [hunk 2]
```diff
@@ -1097,6 +1121,19 @@ var LibraryEmbind = {
         invokerFnBody += "Module.emscripten_trace_exit_context();\n";
 #endif
     }
+
+#if ASYNCIFY
+    invokerFnBody += "}\n";
+    invokerFnBody += "if (Asyncify.currData) {\n";
```
Comment (kripken) [inline src/embind/embind.js:1127]: (same here)

File: src/embind/embind.js [hunk 3]
```diff
@@ -2058,21 +2095,9 @@ var LibraryEmbind = {
...
-
-                var ptr = invoker.apply(null, args);
-                runDestructors(destructors);
-
-                return argTypes[0]['fromWireType'](ptr);
-            };
+            // Insert empty slot for context type (argTypes[1]).
+            argTypes.splice(1, 0, null);
+            classType.registeredClass.constructor_body[argCount - 1] = craftInvokerFunction(humanName, argTypes, null, invoker, rawConstructor);
             return [];
```
Comment (kripken) [inline src/embind/embind.js:2101]: Is this part of the PR related? If so, how?

**Review by kripken — COMMENTED** [review]
Interesting!

I'm still reading this, but here are some initial comments.

Please update the changelog.

File: src/embind/embind.js (hunk 3 above)
Comment (RReverser) [reply src/embind/embind.js:2101]: Unlike all the other function wrappers, this one for some reason didn't use `craftInvokerFunction` helper, so when I added async finalizers to that helper, class constructors would still return invalid instances instead of Promises.

This change is both a simplification to reuse the same helper, and allows class constructors to be async as well.

File: src/embind/embind.js (hunk 1 above)
Comment (RReverser) [reply src/embind/embind.js:1034]: I essentially followed the example of `async:true` handling in `ccall` here that also checks `Asyncify.currData`: https://github.com/emscripten-core/emscripten/blob/e6f4d495668b7bfea079e03779280ae26f413186/src/preamble.js#L134

I guess the `state` check would be better yeah... need to double-check that it's doing the same thing.

Comment (kripken) [reply src/embind/embind.js:1034]: Ah, good point, we should fix `ccall` as well. I'll look into that.

File: src/embind/embind.js (hunk 3 above)
Comment (kripken) [reply src/embind/embind.js:2101]: I see, thanks. sgtm

File: src/embind/embind.js (hunk 1 above)
Comment (kripken) [reply src/embind/embind.js:1034]: Oh, actually I was wrong. The state we care about here is after unwinding and before rewinding. That's not an asyncify state. And it is indicated as currData not being null. So sgtm as is.

File: tests/test_browser.py [hunk 4]
```diff
@@ -4985,6 +4985,18 @@ def test_embind_with_pthreads(self):
...
+    '': ([],),
+    'no_dynamic_execution': (['-s', 'DYNAMIC_EXECUTION=0'],)
+  })
+  def test_embind_lib_with_asyncify(self, args):
+    self.btest('embind_lib_with_asyncify.cpp', 'ok', args=[
+      '--bind',
+      '-s', 'ASYNCIFY',
+      '-s', 'ASYNCIFY_IMPORTS=["sleep_and_return"]',
+      '--post-js', test_file('embind_lib_with_asyncify.test.js'),
+    ] + args)
```
Comment (kripken) [inline tests/test_browser.py:4998]: It would be better to not do this as a browser test, I think - we can test async things in `test_core.py`. See `test_async_ccall*` there.

**Review by kripken — COMMENTED** [review]
Overall lgtm aside from tests. I am not an expert on the embind code, but looks correct.

cc @billbudge , this might interest you.

File: tests/test_browser.py (hunk 4 above)
Comment (kripken) [reply tests/test_browser.py:4998]: (browser tests are much slower)

File: src/embind/embind.js (hunk 1 above)
Comment (RReverser) [reply src/embind/embind.js:1034]: Ah, thanks for checking.

File: tests/test_browser.py (hunk 4 above)
Comment (RReverser) [reply tests/test_browser.py:4998]: Oh yeah good point. I just put it alongaide the other embind+asyncify test, but I think it was added by me here as well and should've been in core instead also. I'll fix tomorrow.

Comment (RReverser) [reply tests/test_browser.py:4998]: Ah I probably put the previous test here because there was `test_embind_with_pthreads` above. Should we move it as well?

Comment (RReverser) [reply tests/test_browser.py:4998]: I see, `test_embind_with_asyncify` uses `fetch` and probably should remain a browser test. Let's see if I can move at least this one...

Comment (RReverser) [reply tests/test_browser.py]: Yeah moved this test just fine.

**Comment by RReverser** [comment]
Hmm, I don't understand why ASAN variant of those tests is failing with a function signature mismatch... https://app.circleci.com/pipelines/github/emscripten-core/emscripten/14496/workflows/aafdcbda-03cf-4e01-8b7d-efe0500922ca/jobs/441835

**Comment by RReverser** [comment]
Added a test to verify that two async calls in parallel are prohibited like they're in `ccall` + `async:true` and updated the ChangeLog.

File: src/library_async.js [hunk 5]
```diff
@@ -148,6 +148,16 @@ mergeInto(LibraryManager.library, {
       }
     },
 
+    whenDone: function() {
+#if ASSERTIONS
+      assert(Asyncify.currData, 'Tried to wait for an async operation when none is in progress.');
+      assert(!Asyncify.asyncFinalizers.length, 'Cannot have multiple async ccalls in flight at once');
```
Comment (kripken) [inline src/library_async.js:154]:
```suggestion
      assert(!Asyncify.asyncFinalizers.length, 'Cannot have multiple async operations in flight at once');
```

File: tests/test_core.py [hunk 6]
```diff
@@ -8523,6 +8523,20 @@ def test_emscripten_async_call(self):
     self.set_setting('EXIT_RUNTIME')
     self.do_run_in_out_file_test(test_file('core/test_emscripten_async_call.c'))
 
+  @parameterized({
+    '': ([],),
+    'no_dynamic_execution': (['-s', 'DYNAMIC_EXECUTION=0'],)
```
Comment (kripken) [inline tests/test_core.py:8528]: why is DYNAMIC_EXECUTION relevant here?

**Review by kripken — APPROVED** [review]

File: src/library_async.js (hunk 5 above)
Comment (RReverser) [reply src/library_async.js:154]: Oh yeah, good catch. Will need to update test expectation message as well.

BTW, in theory we shouldn't allow even synchronous operations in parallel to async ones, but ccall allowed that so I just mirrored that behaviour.

Do you think we should tighten those restrictions further?

File: tests/test_core.py (hunk 6 above)
Comment (RReverser) [reply tests/test_core.py:8528]: Because as you can see from changes to Embind, it has two different paths that depend on DYNAMIC_EXECUTION=0/1.

One is walking through types each time, another constructs a Function from string at runtime once and then reuses it, I assume for speed-up.

I hope we won't have this in the new binding system as realistically those bindings should be just generated from types AOT, but for now it is what it is...

File: src/library_async.js (hunk 5 above)
Comment (RReverser) [reply src/library_async.js]: Adjusted the error message, but keeping this conversation open for the last question.

Comment (kripken) [reply src/library_async.js]: There are cases where small synchronous calls back into the wasm are necessary, like calling in to do a malloc (to store some data we just downloaded, for example). So we do allow that.

File: tests/test_core.py (hunk 6 above)
Comment (kripken) [reply tests/test_core.py:8528]: I see, thanks. sgtm.

**Review by kripken — APPROVED** [review]

File: src/library_async.js (hunk 5 above)
Comment (RReverser) [reply src/library_async.js]: Hm, do you mean like in callbacks? Otherwise I don't see how malloc could happen at the same time as another call.

**Comment by RReverser** [comment]
Any idea what's going on with function signature mismatch in ASAN builds? I'm not sure which function it's complaining about or why.

**Comment by RReverser** [comment]
Ah I see that some other Asyncify tests are annotated with `@no_asan('asan is not compatible with asyncify stack operations; may also need to not instrument asan_c_load_4, TODO')`.

That's unfortunate, I definitely sometimes need to use both...

I'll disable the test in the same fashion for now.

File: src/library_async.js (hunk 5 above)
Comment (kripken) [reply src/library_async.js]: Yes, it could be say an async network fetch that finishes, and as it finishes it allocates a buffer using malloc and writes that, and then resumes.

File: src/preamble.js [hunk 7]
```diff
@@ -129,35 +129,28 @@ function ccall(ident, returnType, argTypes, args, opts) {
...
 #if ASYNCIFY
   var asyncMode = opts && opts.async;
-  var runningAsync = typeof Asyncify === 'object' && Asyncify.currData;
-  var prevRunningAsync = typeof Asyncify === 'object' && Asyncify.asyncFinalizers.length > 0;
-#if ASSERTIONS
-  assert(!asyncMode || !prevRunningAsync, 'Cannot have multiple async ccalls in flight at once');
-#endif
   // Check if we started an async operation just now.
-  if (runningAsync && !prevRunningAsync) {
+  if (Asyncify.currData) {
```
Comment (justjake) [inline src/preamble.js:139]: I think this introduces a bug so that during an async function, we can no longer ccall a benign sync function like a thin wrapper around malloc, increment a static counter, etc. This makes it very troublesome for a complex loading task to complete.

Comment (justjake) [reply src/preamble.js:139]: I believe this part of the diff is inconsistent with the guidance here: https://github.com/emscripten-core/emscripten/pull/14664#discussion_r672586792

Comment (kripken) [reply src/preamble.js:139]: I think you're right @justjake 

@RReverser was that intentional?

Comment (RReverser) [reply src/preamble.js:139]: I think it was (didn't we settle on direct `Module._foo()` calls as enough for a rare escape hatch?) but I don't remember for sure, and I'm not prepared to dig in right now.

Comment (kripken) [reply src/preamble.js:139]: Ok, no worries, I'll look into it.

Comment (justjake) [reply src/preamble.js:139]: Thanks for looking @kripken - it's awesome you're responsive to a comment on a random commit ❤️ 
I got distracted and forgot to do a full repro/bug report, but this issue is affecting me; currently it's blocking my work here: https://github.com/justjake/quickjs-emscripten/pull/54

Comment (justjake) [reply src/preamble.js:139]: Would more of a write-up be helpful?

Comment (kripken) [reply src/preamble.js:139]: Maybe, but first, can you test if #16370 fixes things for you? (Skimming that link, I think/hope it should.)
