### PR TITLE
[tsgen] Use optional params for trailing std::optional arguments.

### LINKED ISSUE #21776: Support omitting optional arguments in js embind bindings
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.55 (165133b1cc977f0b9a277e42ef809b823157189c)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 6c7805d5d186a6d1263f90b8033ad85e2d2633d7)
Target: wasm32-unknown-emscripten
Thread model: posix
```
**Issue**
When using optional arguments with embind, it would be more intuitive and convenient to allow omitting the optional arguments entirely, rather than requiring passing undefined for the optional parameters.

```cpp
inline std::string testOptional(std::string str, std::optional<std::string> optionalString)
{
}

EMSCRIPTEN_BINDINGS(test)
{
    register_optional<std::string>();
    function("test", &testOptional);
}
```
I would expect the generated JavaScript bindings to allow calling the function like this:

```javascript
testOptional("someString")
```
Instead of requiring the following:
```javascript
testOptional("someString", undefined)
```

I noticed a comment on the original optional implementation pull request ([#21076](https://github.com/emscripten-core/emscripten/pull/21076/files#r1454072957)) mentioning plans to support this feature.

### PR DESCRIPTION
**Pull request by brendandahl**
This replaces `_0: Foo | undefined` with `_0?: Foo` for any optional arguments at the end of function, which allows for more idiomatic TS.

Fixes #21776

### CODE REVIEW

File: test/other/embind_tsgen_ignore_2.d.ts [hunk 1]
```diff
@@ -101,8 +101,9 @@ interface EmbindModule {
   DerivedClass: {};
   a_bool: boolean;
   an_int: number;
-  optional_test(_0: Foo | undefined): number | undefined;
+  optional_test(_0?: Foo): number | undefined;
```
Comment (sbc100) [inline test/other/embind_tsgen_ignore_2.d.ts:104]: Can the return type here also use `?`?

**Review by sbc100 — APPROVED** [review]

File: test/other/embind_tsgen_ignore_2.d.ts (hunk 1 above)
Comment (brendandahl) [reply test/other/embind_tsgen_ignore_2.d.ts:104]: As far as I can tell that's not currently supported. There's a bunch of issues related to this https://github.com/microsoft/TypeScript/issues/51332

**Review by RReverser — APPROVED** [review]
Nice!
