### PR TITLE
[WASM_WORKERS] Don't define pthread function in WASM_WORKERS builds

### LINKED ISSUE #26277: `__cxa_guard_acquire` does not work WASM Workers (depends on pthread functions)
When using `-sWASM_WORKERS`, C++ static local variable initialization (`__cxa_guard_acquire`) can busy-spin indefinitely if two workers trigger the same static init simultaneously. It seems to be caused by libcxxabi getting the GlobalMutex model, while pthread functions are basically stubs

The problem is a mismatch between how `libcxxabi` and `libc` are built for WASM Workers:

- `libcxxabi` is compiled **without** `_LIBCXXABI_HAS_NO_THREADS` (because `is_ww=True` in `system_libs.py:1753`), so `__cxa_guard_acquire` uses the `GlobalMutex` implementation that calls `pthread_mutex_lock()` / `pthread_cond_wait()`
- But `libc` links `library_pthread_stub.c` (because `is_mt=False`), where these are all noops returning 0

So when Worker A starts initializing a static (sets `PENDING_BIT`) and Worker B comes along, Worker B enters the condvar wait loop in `cxa_guard_impl.h` — but `pthread_cond_wait` returns immediately, so it becomes a tight busy-spin until Worker A finishes.

We hit this in practice with `thread_local std::optional<T>` (non-trivial destructor) — first access triggers `__cxa_thread_atexit` → `static DtorsManager manager` → `__cxa_guard_acquire`. Our tests time out when multiple WASM Workers start executing the same startup function simultaneously.

**Version of emscripten/emsdk:** We are using 4.0.20 (as for the LLVM bug), but it seems the same code on main.

**Proposed fix:**

The `InitByteFutex` implementation already exists in `cxa_guard_impl.h` and uses only futex wait/wake — no pthread at all. WASM has native futex support via `__builtin_wasm_memory_atomic_wait32` / `__builtin_wasm_memory_atomic_notify`. The fix is to wire these in:

`system/lib/libcxxabi/src/cxa_guard_impl.h` — add before the `#else` nullptr fallback (after the `SYS_futex` block):
```cpp
#elif defined(__EMSCRIPTEN__) && defined(__EMSCRIPTEN_SHARED_MEMORY__)
void PlatformFutexWait(int* addr, int expect) {
  __builtin_wasm_memory_atomic_wait32(addr, expect, -1);
}
void PlatformFutexWake(int* addr) {
  __builtin_wasm_memory_atomic_notify(addr, __INT_MAX__);
}
```

`tools/system_libs.py` — in class `libcxxabi.get_cflags()`, select the futex implementation for WASM Workers:
```python
    if not self.is_mt and not self.is_ww:
      cflags.append('-D_LIBCXXABI_HAS_NO_THREADS')
    elif self.is_ww:
      cflags.append('-D_LIBCXXABI_USE_FUTEX')
```

Setting `_LIBCXXABI_HAS_NO_THREADS` instead looks very dangerous. 

Side note: as we don't have TLS destructors for WASM Workers,  the `__cxa_thread_atexit` registration that triggers this is effectively dead code — but that's a separate issue.

### PR DESCRIPTION
**Pull request by sbc100**
Using the pthread API with WASM_WORKERS simply will not work.

This also means function-local-static C++ initializes will now fail to link with WASM_WORKERS, at least until we fix #26277.  Note that prior to this change this was already broken but would fail at runtime.

Note that its still possible to build with WASM_WORKERS + pthreads, in which case all the real pthread functions are available, but calling them from a Wasm Worker would be undefined behaviour (with or without this PR).

See #26314

### CODE REVIEW

File: system/lib/libc/emscripten_yield_stub.c [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ * Copyright 2026 The Emscripten Authors.  All rights reserved.
+ * Emscripten is available under two separate licenses, the MIT license and the
+ * University of Illinois/NCSA Open Source License.  Both these licenses can be
+ * found in the LICENSE file.
+ */
+
+#include <features.h>
+
+static void dummy(double now)
+{
```
Comment (kripken) [inline system/lib/libc/emscripten_yield_stub.c]:
```suggestion
static void dummy(double now) {
```

File: ChangeLog.md [hunk 2]
```diff
@@ -45,6 +45,9 @@ See docs/process.md for more on how version tagging works.
   repository.  These scripts are created by the `./bootstrap` script which
   must be run before the toolchain is usable (for folks using a git checkout of
   emscripten). (#26247)
+- When building with `-sWASM_WORKERS` emscripten will no longer include pthread
+  API stub functions.  Instead usage of the pthread API will result in undefined
+  symbols. ()
```
Comment (kripken) [inline ChangeLog.md]: Maybe rephrase this so it does not sound like a reduction of functionality?

**Comment by dschuff** [comment]
Is it possible to create a wasm worker in a build that uses pthreads (was that ever possible)?

**Comment by sbc100** [comment]
> Is it possible to create a wasm worker in a build that uses pthreads (was that ever possible)?

Yes, in that case you get all the pthread functions linked in.

They exist, but bad things would happen if you called them from wasm worker.

We don't have any protection against that though, either before of after this PR.

 I will update the PR description.

File: ChangeLog.md [hunk 3]
```diff
@@ -20,6 +20,10 @@ See docs/process.md for more on how version tagging works.
 
 5.0.3 (in development)
 ----------------------
+- When building with `-sWASM_WORKERS` emscripten will no longer include pthread
+  API stub functions.  These stub functions where never designed to work under
```
Comment (dschuff) [inline ChangeLog.md:24]:
```suggestion
  API stub functions.  These stub functions were never designed to work under
```

**Comment by juj** [comment]
Hmm, it looks like this isn't quite as simple. After this PR, this code fails:

`a.cpp`

```c++
#include <emscripten/html5.h>

int foo(int x)
{
  static int z = emscripten_performance_now();
  ++z;
  if (x <= 0) return 0;
  return foo(x-1) + foo(x-2) + z;
}

int main()
{
  return foo(42);
}
```
em++ a.cpp -o a.html -sWASM_WORKERS
```
on
```
wasm-ld: error: C:\emsdk\emscripten\main\cache\sysroot\lib\wasm32-emscripten\libc++abi-debug-ww-noexcept.a(cxa_guard.o): undefined symbol: pthread_cond_wait
wasm-ld: error: C:\emsdk\emscripten\main\cache\sysroot\lib\wasm32-emscripten\libc++abi-debug-ww-noexcept.a(cxa_guard.o): undefined symbol: pthread_mutex_lock
wasm-ld: error: C:\emsdk\emscripten\main\cache\sysroot\lib\wasm32-emscripten\libc++abi-debug-ww-noexcept.a(cxa_guard.o): undefined symbol: pthread_mutex_unlock
wasm-ld: error: C:\emsdk\emscripten\main\cache\sysroot\lib\wasm32-emscripten\libc++abi-debug-ww-noexcept.a(cxa_guard.o): undefined symbol: pthread_cond_broadcast
```

**Comment by juj** [comment]
Maybe we should then contend to routing these functions to a partial stub implementation in Wasm Workers mode, so that the compiler emitted constructs will be there.

**Comment by sbc100** [comment]
Yes, I believe that is the exact issue described in https://github.com/emscripten-core/emscripten/issues/26277.  

That code has always been broken under Wasm Workers, but would fail in subtle ways at runtime before (because the locked around the initializer was not safe).  Now we get a nice build time failure, which I think its better than a broken program.

I believe fixing #26277 should not be too hard now that we have the futex API available.   

@AndreyRepko would you have time to update your PR (https://github.com/emscripten-core/emscripten/pull/26283) to use the futex API?

**Comment by juj** [comment]
> That code has always been broken under Wasm Workers

Oh right, yeah indeed, before that the pthread lock functions would come out as no-ops.
