### PR TITLE
[WasmFS] Handle 404 error in fetch backend

### LINKED ISSUE #17234: WasmFS: No way to handle 404 error in fetch backend
When trying to fetch a non-existent file from a server, a file is still created in the filesystem and we can succesfully read its content which is the text of 404 error. It would be nice to be able to handle such case and to differentiate between a file that exists on a server and a file that doesn't exist without parsing its content.

**Version of emscripten/emsdk:**

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14-git (f677b2672fa0d3a216068feb0f5ab76192c7d75d)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Failing command line in full:**

```
#include <fstream>
#include <filesystem>
#include <cassert>
#include <iostream>
#include <unistd.h>
#include <emscripten/wasmfs.h>

int main()
{
	const char *filePath = "/non_existent_file.txt";
	const char *url = "http://localhost:8000/non_existent_file.txt";

	backend_t backend = wasmfs_create_fetch_backend(url);
	int fd = wasmfs_create_file(filePath, S_IRWXU | S_IRWXG | S_IRWXO, backend);
	assert(fd);

	std::ifstream input(filePath);
	std::copy(std::istream_iterator<char>(input), {}, std::ostream_iterator<char>(std::cout)); // outputs text of 404 error

	assert(close(fd) == 0);
	assert(std::filesystem::remove(filePath));

	return 0;
}

```

**Full link command and output with `-v` appended:**
<details>
  <summary></summary>
  
```
D:\emscripten>em++ -v -std=c++17 D:/build/test.cpp -o D:/build/test.html -s FORCE_FILESYSTEM=1 -s EXIT_RUNTIME=1 -s WASMFS=1 -s USE_PTHREADS=1 -sPTHREAD_POOL_SIZE=4
 "D:/emsdk/upstream/bin\clang++.exe" -target wasm32-unknown-emscripten -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=14 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=D:\emscripten\cache\sysroot -Xclang -iwithsysroot/include\compat -v -std=c++17 -pthread D:/build/test.cpp -c -o C:\Users\kdots\AppData\Local\Temp\emscripten_temp_4u8u_f7z\test_0.o
clang version 15.0.0 (https://github.com/llvm/llvm-project d61341768cf0cff7ceeaddecc2f769b5c1b901c4)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\emsdk\upstream\bin
 (in-process)
 "D:\\emsdk\\upstream\\bin\\clang++.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name test.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +atomics -target-feature +bulk-memory -target-feature +mutable-globals -target-feature +sign-ext -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v "-fcoverage-compilation-dir=D:\\emscripten" -resource-dir "D:\\emsdk\\upstream\\lib\\clang\\15.0.0" -D __EMSCRIPTEN_SHARED_MEMORY__=1 -D EMSCRIPTEN -D __EMSCRIPTEN_major__=3 -D __EMSCRIPTEN_minor__=1 -D __EMSCRIPTEN_tiny__=14 -isysroot "D:\\emscripten\\cache\\sysroot" -internal-isystem "D:\\emscripten\\cache\\sysroot/include/wasm32-emscripten/c++/v1" -internal-isystem "D:\\emscripten\\cache\\sysroot/include/c++/v1" -internal-isystem "D:\\emsdk\\upstream\\lib\\clang\\15.0.0\\include" -internal-isystem "D:\\emscripten\\cache\\sysroot/include/wasm32-emscripten" -internal-isystem "D:\\emscripten\\cache\\sysroot/include" -Werror=implicit-function-declaration -std=c++17 -fdeprecated-macro "-fdebug-compilation-dir=D:\\emscripten" -ferror-limit 19 -fmessage-length=175 -fvisibility default -pthread -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/SDL "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o "C:\\Users\\kdots\\AppData\\Local\\Temp\\emscripten_temp_4u8u_f7z\\test_0.o" -x c++ D:/build/test.cpp
clang -cc1 version 15.0.0 based upon LLVM 15.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "D:\emscripten\cache\sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "D:\emscripten\cache\sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 D:\emscripten\cache\sysroot/include/SDL
 D:\emscripten\cache\sysroot/include\compat
 D:\emscripten\cache\sysroot/include/c++/v1
 D:\emsdk\upstream\lib\clang\15.0.0\include
 D:\emscripten\cache\sysroot/include
End of search list.
 "D:/emsdk/upstream/bin\wasm-ld.exe" -o D:/build/test.wasm C:\Users\kdots\AppData\Local\Temp\emscripten_temp_4u8u_f7z\test_0.o -LD:\emscripten\cache\sysroot\lib\wasm32-emscripten D:\emscripten\cache\sysroot\lib\wasm32-emscripten\crtbegin.o --whole-archive -lwasmfs-debug-mt --no-whole-archive -lGL-mt -lal -lhtml5 -lstubs-debug -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=_wasmfs_read_file --export=_wasmfs_write_file --export=_wasmfs_mkdir --export=_wasmfs_chdir --export=_wasmfs_symlink --export=_wasmfs_chmod --export=_wasmfs_identify --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=emscripten_proxy_finish --export=__funcs_on_exit --export=malloc --export=free --export=__cxa_is_pointer_type --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "D:/emsdk/upstream\bin\wasm-emscripten-finalize" --dyncalls-i64 D:/build/test.wasm -o D:/build/test.wasm --detect-features
 "D:/emsdk/node/14.18.2_64bit/bin/node.exe" D:\emscripten\src\compiler.js C:\Users\kdots\AppData\Local\Temp\tmpu1_2yrav.json
 "D:/emsdk/upstream/bin\llvm-objcopy.exe" D:/build/test.wasm D:/build/test.wasm --remove-section=.debug* --remove-section=producers
 "D:/emsdk/node/14.18.2_64bit/bin/node.exe" D:\emscripten\tools\preprocessor.js C:\Users\kdots\AppData\Local\Temp\emscripten_temp_4u8u_f7z\settings.js worker.js --expandMacros "D:/emsdk/node/14.18.2_64bit/bin/node.exe" D:\emscripten\tools\preprocessor.js C:\Users\kdots\AppData\Local\Temp\emscripten_temp_4u8u_f7z\settings.js shell.html
```

</details>

Output with WasmFS:
```
<!DOCTYPEHTMLPUBLIC"-//W3C//DTDHTML4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<metahttp-equiv="Content-Type"content="text/html;charset=utf-8">
			<title>Errorresponse</title>
		</head>
		<body>
			<h1>Errorresponse</h1>
			<p>Errorcode:404</p>
			<p>Message:Filenotfound.</p>
			<p>Errorcodeexplanation:HTTPStatus.NOT_FOUND-NothingmatchesthegivenURI.</p>
		</body>
	</html>
```

### PR DESCRIPTION
**Pull request by kd935**
Fixes #17234.

- Added a check for successful fetch
- Return ENOENT in case of 404 error while reading
- Added a new test case

### CODE REVIEW

File: src/library_wasmfs_fetch.js [hunk 1]
```diff
@@ -67,12 +74,14 @@ mergeInto(LibraryManager.library, {
...
+        return getFile(file)
+        .then(() => jsFileOps.read(file, buffer, length, offset))
+        .catch((status) => status === 404 ? -{{{ cDefine('ENOENT') }}} : -{{{ cDefine('EBADF') }}});
       },
       getSize: async(file) => {
-        await getFile(file);
-        return jsFileOps.getSize(file);
+        return getFile(file)
+        .then(() => jsFileOps.getSize(file))
+        .catch((status) => jsFileOps.getSize(file));
```
Comment (kripken) [inline src/library_wasmfs_fetch.js:84]: How about this? (since we call the same code in the end anyhow)
```suggestion
        try {
          await getFile(file);
        } catch(e) {}
        return jsFileOps.getSize(file);
```

File: test/wasmfs/wasmfs_fetch.c [hunk 2]
```diff
@@ -150,13 +150,42 @@ void test_small_reads() {
...
 }
 
+void test_nonexistent() {
+  printf("Running %s...\n", __FUNCTION__);
+
+  const char* dir_path = "/subdir";
+  char url[200];
+  snprintf(url, sizeof(url), "%s%s", url_orig, dir_path);
+
+  backend_t backend = wasmfs_get_backend_by_path(url);
```
Comment (kripken) [inline test/wasmfs/wasmfs_fetch.c:160]: All the other tests seem to call `wasmfs_create_fetch_backend`. Is there a reason not to do that in this new test?

**Review by kripken — COMMENTED** [review]
Thanks for the PR! Will be great to fix this.

File: src/library_wasmfs_fetch.js (hunk 1 above)
Comment (kd935) [reply src/library_wasmfs_fetch.js]: Yes, it looks much better, thanks.

File: test/wasmfs/wasmfs_fetch.c (hunk 2 above)
Comment (kd935) [reply test/wasmfs/wasmfs_fetch.c:160]: Yes, I initially used `wasmfs_create_fetch_backend` as in other tests. But this requires modifying test_browser.py. I had to increase pool size from 5 to 6 and also add '-sINITIAL_MEMORY=32MB' flag to make it work because when running tests I was getting the following error: 
`Cannot enlarge memory arrays to size 17858560 bytes (OOM). Either (1) compile with -sINITIAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -sALLOW_MEMORY_GROWTH which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -sABORTING_MALLOC=0`.

So to avoid modifications to test_browser.py I decided to reuse existing backend. But if you think that we need to use  `wasmfs_create_fetch_backend` here then I can do this along with changes to test_browser.py.

File: src/library_wasmfs_fetch.js [hunk 3]
```diff
@@ -67,11 +71,17 @@ mergeInto(LibraryManager.library, {
...
+          return status === 404 ? -{{{ cDefine('ENOENT') }}} : -{{{ cDefine('EBADF') }}};
+        }
         return jsFileOps.read(file, buffer, length, offset);
       },
-      getSize: async(file) => {
-        await getFile(file);
+      getSize: async (file) => {
+        try {
+          await getFile(file);
+        } catch (e) {}
```
Comment (kd935) [inline src/library_wasmfs_fetch.js:84]: It seems to me that any error should be handled here in `getSize` as well. But I am not sure how to properly do this.
For now if a file is not on the server we just return zero size. But probably we should also return -1 from `fstat` and set the appropriate `errno`. The problem is that we don't check for error from `lockedFile.getSize()` in `__syscall_newfstatat` and so we can't know that something here went wrong and return the appropriate error code.
Should this behavior be changed?

File: test/wasmfs/wasmfs_fetch.c (hunk 2 above)
Comment (kripken) [reply test/wasmfs/wasmfs_fetch.c:160]: I see, good points. Yes, maybe for testing a nonexistent file this is simpler as it is.

File: src/library_wasmfs_fetch.js (hunk 3 above)
Comment (kripken) [reply src/library_wasmfs_fetch.js:84]: Yes, we need to add proper error handling in all these APIs, I think. I believe @tlively has plans to work on that. For this PR, returning a 0 size is good enough for now.

File: src/library_wasmfs_fetch.js [hunk 4]
```diff
@@ -38,8 +38,12 @@ mergeInto(LibraryManager.library, {
         }
       }
       var response = await fetch(url);
-      var buffer = await response['arrayBuffer']();
-      wasmFS$JSMemoryFiles[file] = new Uint8Array(buffer);
+      if (response.ok) {
+        var buffer = await response['arrayBuffer']();
+        wasmFS$JSMemoryFiles[file] = new Uint8Array(buffer);
+      } else {
+        throw (response.status);
```
Comment (kripken) [inline src/library_wasmfs_fetch.js:45]:
```suggestion
        throw response.status;
```

Comment (kripken) [reply src/library_wasmfs_fetch.js:45]: Actually, perhaps we should do this:
```suggestion
        throw response;
```
And then check for `.status` in the catch. That might be clearer than throwing just the status code itself without saying what it is.

**Review by kripken — COMMENTED** [review]
lgtm with that last suggestion to throw the entire object.

File: src/library_wasmfs_fetch.js (hunk 4 above)
Comment (kd935) [reply src/library_wasmfs_fetch.js]: Yes, I agree, we can get more information from a response.

**Review by kripken — APPROVED** [review]
Thanks!

**Comment by kripken** [comment]
CI error on windows looks random, rerunning.
