### PR TITLE
[WasmFS] Add virtual backend utilities

### LINKED ISSUE #17993: WasmFS: Original file case is not preserved when using with CASE_INSENSITIVE_FS
When creating a file or a directory, it's letter case is not preserved for subsequent calls such as `readdir()` or `getcwd()`. Works as expected when not using WASMFS.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (5ae63ce7dd955df449cb419bfe5afc51d1bd57f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/user/src/emsdk/upstream/bin
```

**Failing code:**
```cpp
#include <assert.h>
#include <dirent.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>

void readdir(const char *dname)
{
    printf("Files in '%s': ", dname);
    DIR *d = opendir(dname);
    if (d)
    {
        struct dirent *dir;
        while ((dir = readdir(d)) != NULL)
        {
            if (dir->d_type & (DT_DIR | DT_REG))
                printf("%s ", dir->d_name);
        }
        closedir(d);
    }
    printf("\n");
}

int main()
{
    FILE *fp = fopen("Test.txt", "wt");
    assert(fp);
    readdir(".");
    assert(mkdir("Subdir", 0777) == 0);
    assert(chdir("Subdir") == 0);
    char buf[200] = {};
    assert(getcwd(buf, sizeof(buf)) != nullptr);
    printf("cwd: %s\n", buf);
    return 0;
}
```

**Full link command and output with `-v` appended:**
```sh
rm -rf build
mkdir -p build
export FLAG_WASMFS=-sWASMFS=1
em++ -v -sCASE_INSENSITIVE_FS=1 $FLAG_WASMFS -std=c++11 main.cpp -o build/common.html
ret=$?
if [ $ret -eq 0 ]; then
    echo "ok"
    emrun build/common.html --browser chrome
fi;
```

**Build output:**
<details>
  <summary>Click to expand</summary>

  ```
"/Users/user/src/emsdk/upstream/bin/clang" --version
 "/Users/user/src/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -I/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/Users/user/src/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -v -std=c++11 main.cpp -c -o /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_62rwmxdh/main_0.o
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/user/src/emsdk/upstream/bin
 (in-process)
 "/Users/user/src/emsdk/upstream/bin/clang-16" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/Users/user/src/emdemo/common -resource-dir /Users/user/src/emsdk/upstream/lib/clang/16.0.0 -D EMSCRIPTEN -I /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL -isysroot /Users/user/src/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /Users/user/src/emsdk/upstream/lib/clang/16.0.0/include -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/user/src/emdemo/common -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_62rwmxdh/main_0.o -x c++ main.cpp
clang -cc1 version 16.0.0 based upon LLVM 16.0.0git default target x86_64-apple-darwin21.6.0
ignoring nonexistent directory "/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /Users/user/src/emsdk/upstream/lib/clang/16.0.0/include
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/Users/user/src/emsdk/upstream/bin/wasm-ld" -o build/common.wasm /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_62rwmxdh/main_0.o -L/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lwasmfs-debug-icase --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=_wasmfs_read_file --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/Users/user/src/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers build/common.wasm -o build/common.wasm --detect-features
 "/Users/user/src/emsdk/node/14.18.2_64bit/bin/node" /Users/user/src/emsdk/upstream/emscripten/src/compiler.js /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/tmp97ua1gat.json
user@C02F71SCMD6R common % source build.sh
 "/Users/user/src/emsdk/upstream/bin/clang" --version
 "/Users/user/src/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -I/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/Users/user/src/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -v -std=c++11 main.cpp -c -o /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_ogj1duyy/main_0.o
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/user/src/emsdk/upstream/bin
 (in-process)
 "/Users/user/src/emsdk/upstream/bin/clang-16" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/Users/user/src/emdemo/common -resource-dir /Users/user/src/emsdk/upstream/lib/clang/16.0.0 -D EMSCRIPTEN -I /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL -isysroot /Users/user/src/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /Users/user/src/emsdk/upstream/lib/clang/16.0.0/include -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/user/src/emdemo/common -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_ogj1duyy/main_0.o -x c++ main.cpp
clang -cc1 version 16.0.0 based upon LLVM 16.0.0git default target x86_64-apple-darwin21.6.0
ignoring nonexistent directory "/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/SDL
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /Users/user/src/emsdk/upstream/lib/clang/16.0.0/include
 /Users/user/src/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/Users/user/src/emsdk/upstream/bin/wasm-ld" -o build/common.wasm /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_ogj1duyy/main_0.o -L/Users/user/src/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lwasmfs-debug-icase --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=_wasmfs_read_file --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/Users/user/src/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers build/common.wasm -o build/common.wasm --detect-features
 "/Users/user/src/emsdk/node/14.18.2_64bit/bin/node" /Users/user/src/emsdk/upstream/emscripten/src/compiler.js /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/tmptsr6qoom.json
 "/Users/user/src/emsdk/upstream/bin/llvm-objcopy" build/common.wasm build/common.wasm --remove-section=.debug* --remove-section=producers
 "/Users/user/src/emsdk/node/14.18.2_64bit/bin/node" /Users/user/src/emsdk/upstream/emscripten/tools/preprocessor.js /var/folders/c_/szdjrjm12g5_9vh8ybcndhmm0000gp/T/emscripten_temp_ogj1duyy/settings.js shell.html
ok
  ```
</details>

**Program output:**
```
Files in '.': . .. dev tmp test.txt 
cwd: /subdir
```
Expected output: (when building without WASMFS):
```
Files in '.': . .. tmp home dev proc Test.txt 
cwd: /Subdir
```

### PR DESCRIPTION
**Pull request by tlively**
Add generic subclasses of DataFile, Directory, and Symlink that wrap other files
and pass operations through to them. Use the new utilities in a rewrite of the
ignore-case virtual backend that cleanly separates the underlying "real" file
system from the virtual file system. This also fixes outstanding issues with the
ignore case backend in which the original, non-normalized file names were not
preserved.

Fixes #17993.

### CODE REVIEW

**Comment by tlively** [comment]
cc @mere-human, PTAL!

**Comment by kripken** [comment]
I don't see `virtual.h` - maybe a missing `git add`?

**Comment by tlively** [comment]
Oops! Fixed now.

**Comment by kripken** [comment]
Can you perhaps explain how this works at a high level, and what it solves? I can see what the Virtual stuff does, I think, but it's not obvious to me what it helps to add a layer of indirection, when that layer does 'nothing'. Perhaps some comments in virtual.h could explain the usage?

**Comment by tlively** [comment]
I added a big comment in the backend implementation file. Let me know if it makes sense!

File: system/lib/wasmfs/virtual.h [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+namespace wasmfs {
+
+static inline std::shared_ptr<File> devirtualize(std::shared_ptr<File>);
+
+class VirtualDataFile : public DataFile {
+protected:
+  std::shared_ptr<DataFile> real;
+
+public:
+  VirtualDataFile(std::shared_ptr<DataFile> real, backend_t backend)
```
Comment (mere-human) [inline system/lib/wasmfs/virtual.h:22]: Should it be protected? Unless there is a plan to instantiate it.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 2]
```diff
@@ -20,105 +37,171 @@ std::string normalize(const std::string& name) {
...
-    return BaseClass::getChild(normalize(name));
-  }
+  // Map normalized names to virtual files and their non-normalized names.
+  std::map<std::string, ChildInfo> children;
 
+public:
+  IgnoreCaseDirectory(std::shared_ptr<Directory> real, backend_t backend)
+    : VirtualDirectory(real, backend) {}
+
+  std::shared_ptr<File> getChild(const std::string& name) override;
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:59]: What is the logic to define something in class vs. separate declaration/definiton? Anything except 1-liners should be split?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 3]
```diff
@@ -20,105 +37,171 @@ std::string normalize(const std::string& name) {
...
 
-  ssize_t getNumEntries() override { return baseDirectory->locked().getNumEntries(); }
+int IgnoreCaseDirectory::insertMove(const std::string& name,
+                                    std::shared_ptr<File> file) {
+  auto normalized = normalize(name);
+  if (auto err = real->locked().insertMove(normalized, devirtualize(file))) {
+    return err;
+  }
+  auto oldParent =
+    std::static_pointer_cast<IgnoreCaseDirectory>(file->locked().getParent());
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:160]: Is it safe to use static cast here? Can we have a parent in different backend?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 4]
```diff
@@ -20,105 +37,171 @@ std::string normalize(const std::string& name) {
...
 
-  bool maintainsFileIdentity() override { return true; }
-};
+std::string IgnoreCaseDirectory::getName(std::shared_ptr<File> file) {
+  for (auto& [_, info] : children) {
+    if (info.child == file) {
+      return info.originalName;
+    }
+  }
+  return "";
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:203]: Maybe, fallback to `real->getName()` here?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 5]
```diff
@@ -129,16 +212,21 @@ class IgnoreCaseBackend : public Backend {
...
+    return virtualize(backend->createFile(mode), this);
   }
 
   std::shared_ptr<Directory> createDirectory(mode_t mode) override {
-    return std::make_shared<IgnoreCaseDirectory>(backend->createDirectory(mode),
-                                                 this);
+    auto real = backend->createDirectory(mode);
+    // Inserts into the real backing directory won't work if it doesn't appear
+    // to be linked, so give it a parent.
+    // TODO: Break this reference cycle in a destructor somewhere.
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:222]: Should this be done in the current PR?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 6]
```diff
@@ -20,105 +37,171 @@ std::string normalize(const std::string& name) {
...
+  std::shared_ptr<File> getChild(const std::string& name) override;
   std::shared_ptr<DataFile> insertDataFile(const std::string& name,
-                                           mode_t mode) override {
-    auto name2 = normalize(name);
-    auto baseDirLocked = baseDirectory->locked();
-    auto child = baseDirLocked.insertDataFile(name2, mode);
-    if (child) {
-      insertChild(name2, child);
-      // Directory::Hanlde needs a parent
-      child->locked().setParent(cast<Directory>());
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:53]: Why don't we set a parent anymore?

**Comment by mere-human** [comment]
Looks good, makes ignore case backend and case preservation easier.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 7]
```diff
@@ -3,12 +3,29 @@
...
-// It is a virtual backend that normalizes all file paths to lower case.
+// A virtual backend that adapts any underlying backend to be
+// case-insensitive. IgnoreCaseDirectory intercepts all directory operations,
+// normalizes paths to be lower case, then forwards the operations with the new
+// paths to the underlying backend. It stores the original, non-normalized names
+// internally so they can be returned later, giving the appearance of a
+// case-insensitive but case-preserving file system.
+//
+// DataFiles and Symlinks are also wrapped, although their wrappers pass
+// operations through to the underlying files with not modifications. These
```
Comment (kripken) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:14]:
```suggestion
// operations through to the underlying files with no modifications. These
```

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 8]
```diff
@@ -3,12 +3,29 @@
...
+// backend, which does not know it is being virtualized. In particular, if we
+// did not wrap these files, the WasmFS dcache system would expect the virtual
+// directories to be the parents of the "real" unwrapped files. But the "real"
+// backend may expect that its directories are the parents of those files and
+// may not work correctly otherwise. Introducing the no-op wrappers solves this
+// problem: WasmFS sees a consistent view of virtual directories being the
+// parent of their virtual children, and the "real" underlying backend sees its
+// "real" directories being the parents of their "real" children.
 
 #include "backend.h"
```
Comment (kripken) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:26]: Part of the motivation text here might make sense in `virtual.h`? Or perhaps that header could link to here "see x.cpp for an example of why this is needed".

File: system/lib/wasmfs/virtual.h (hunk 1 above)
Comment (tlively) [reply system/lib/wasmfs/virtual.h:22]: No, unfortunately the constructors need to be public so that they can be called by `std::make_shared`. The usual alternative, `friend`, doesn't work here, because it would require specifying the internal library function that actually calls the constructor, and that's an implementation detail that could change.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 2 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:59]: Yeah, splitting out nontrivial methods is usually a good idea, but less important in .cpp files, I think. In this case, the `virtualize` implementations depended on the full class definitions and the method definitions depended on `virtualize`, so I had to either forward declare the `virtualize` functions or split out the method definitions. I chose the latter.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 3 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:160]: Moves should always be between directories with the same backend, so this should be safe. Maintaining this invariant is why it's necessary to fully layer the virtual backend on top of the underlying backend and not mix them.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 4 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:203]: No, that wouldn't be correct because we must be getting the name of a virtual `File` here, not one of the underlying "real" files. That's because the underlying real `File` objects are visible only to the virtual backend and never escape into the rest of the WasmFS system.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 5 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:222]: Sure, I guess this is easy enough to add to the backend destructor.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 6 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:53]: Great catch. I thought the backend-independent code would set the parent, but that was wrong. I fixed this bug and added a test. I also noticed that we weren't properly clearing the parents of overwritten directories, so I fixed that and added another test.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 8 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:26]: I'll try to clarify the motivation and move the explanation to virtual.h.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 9]
```diff
@@ -3,12 +3,29 @@
...
+// wrappers are important to maintain the clear distinction between the virtual
+// backend, which is visible to the rest of WasmFS, and the underlying "real"
+// backend, which does not know it is being virtualized. In particular, if we
+// did not wrap these files, the WasmFS dcache system would expect the virtual
+// directories to be the parents of the "real" unwrapped files. But the "real"
+// backend may expect that its directories are the parents of those files and
+// may not work correctly otherwise. Introducing the no-op wrappers solves this
+// problem: WasmFS sees a consistent view of virtual directories being the
+// parent of their virtual children, and the "real" underlying backend sees its
+// "real" directories being the parents of their "real" children.
```
[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:25]: Directories have to be wrapped so the virtual layer can reimplement lookup in a case-insensitive manner and so that additional data - the original name - can be stored alongside each "real" directory entry.

DataFiles and Symlinks have to have no-op wrappers so that the backend-independent code observes a consistent backend for the whole tree rooted at the backend's root directory and so that the "real" file system can simultaneously observe that each of its files has a "real" parent. These invariants are necessary for `insertMove` to work correctly both in the backend-independent code and in backend implementations.

[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:15]: Got it now, thanks!

File: system/lib/wasmfs/file.cpp [hunk 10]
```diff
@@ -178,12 +178,13 @@ int Directory::Handle::insertMove(const std::string& name,
       it->second.file->locked().setParent(nullptr);
       it->second = entry;
     }
-    file->locked().setParent(getDir());
   } else {
     // This backend doesn't use the dcache.
     assert(getDir()->maintainsFileIdentity());
   }
 
+  file->locked().setParent(getDir());
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:186]: Is this a separate change?

File: system/lib/wasmfs/virtual.h [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+protected:
+  std::shared_ptr<Directory> real;
+
+public:
+  VirtualDirectory(std::shared_ptr<Directory> real, backend_t backend)
+    : Directory(real->locked().getMode(), backend), real(real) {}
+
+protected:
+  virtual std::shared_ptr<File> getChild(const std::string& name) override {
+    return real->locked().getChild(name);
```
Comment (kripken) [inline system/lib/wasmfs/virtual.h:63]: In theory if the virtual thing owned the real thing, we could rely on the virtual thing being locked to imply the real thing is locked, and avoid a lock here..? But that seems tricky.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 3 above)
Comment (kripken) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:150]: Do moves assert on that property of it being in the same backend?

**Review by kripken — APPROVED** [review]

File: system/lib/wasmfs/file.cpp (hunk 10 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:186]: Somewhat, but it's a fix for a bug that @mere-human noticed [here](https://github.com/emscripten-core/emscripten/pull/18248#discussion_r1032263406) as part of this PR, and this PR also adds a test that requires this change to pass.

File: system/lib/wasmfs/virtual.h (hunk 11 above)
Comment (tlively) [reply system/lib/wasmfs/virtual.h:63]: Yes, and it might be possible to express that by having a private method to get a handle without acquiring the lock then using `friend` to make that method visible to `VirtualDataFile` and friends. That complexity doesn't seem worth it for now, though.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 3 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:150]: Yes. More precisely, `__syscall_rename` returns `-EXDEV` if the parent backends do not match.
