### PR TITLE
Fix glfw's onDrop support: FS detection was incorrect

### LINKED ISSUE #10004: [src/library_glfw.js] onDrop event not processed
Just noted that files drag and drop functionality stop working for [raylib](https://github.com/raysan5/raylib) when compiling for web with emscripten. raylib uses GLFW3 backend for window/input events management.

I compiled my [core_drop_files.c](https://github.com/raysan5/raylib.com/blob/master/examples/web/core/core_drop_files.c) example with `-s FORCE_FILESYSTEM=1` to allow file drag an drop...
```
emcc -o core/core_drop_files.html core/core_drop_files.c -Wall -s USE_GLFW=3 --shell-file C:\GitHub\raylib\src\shell.html -I. -IC:\GitHub\raylib/src -IC:\GitHub\raylib/src/external -L. -LC:\GitHub\raylib/src -LC:\GitHub\raylib/src C:\GitHub\raylib/src/libraylib.bc -DPLATFORM_WEB -s TOTAL_MEMORY=67108864 -s FORCE_FILESYSTEM=1
```
...but it seems the following line on `library_glfw.js`
```
#if '$FS' in addedLibraryItems
```
always evaluates to false. Commenting that line (and the closing `#endif`) everything works as expected.

I tracked the issue to this commit: https://github.com/emscripten-core/emscripten/commit/7cae0636bbe44092b20b3a7679ed4562e31a0b89#diff-ea65b4a414f7c8ccd91dfc0279b0f90c where that `#if` guard was added.

As per my understanding, that guard should be evaluated to true when `-s FORCE_FILESYSTEM=1`.

Also noted that `.glfw_dropped_files` route is added to dropped files, it would be nice to be able to define that route if desired... but not a big deal.

### PR DESCRIPTION
**Pull request by kripken**
`#if '$FS' in addedLibraryItems` makes sense *after* we process
library items, but this was in a library - which is executed before
we add anything from a library (we have to parse the libraries
first...).

Instead, just use the standard deps system.

Fixes #10004

### CODE REVIEW

File: src/library_glfw.js [hunk 1]
```diff
@@ -737,7 +741,6 @@ var LibraryGLFW = {
 
       event.preventDefault();
 
-#if '$FS' in addedLibraryItems
```
Comment (sbc100) [inline src/library_glfw.js]: But we still use `FS` unconditionally below?  Shouldn't we wrap this somehow in `if FILESYSTEM` too?  Maybe I'm missing something?

Comment (kripken) [reply src/library_glfw.js]: Might as well ifdef it, yeah, thanks. Done now.

In practice probably an app wouldn't have drag&drop without filesystem support, but ifdefing is safer (and also smaller).
