### PR TITLE
Fix the dodgy call_sync_on_main_thread tests

### LINKED ISSUE #8620: call_sync_on_main_thread tests are rubbish
Two issues:
1. The js uses `text = document.getElementById("resize").innerHTML`, however that returns the inner html of `<input type="checkbox" id="resize">`, which is nothing (`""`).
2. The c uses `assert(!strstr(dst, "Resize canvas"));`, where dst is erroneously the empty string.

I'll open a PR to actually make these tests work.

### PR DESCRIPTION
**Pull request by VirtualTim**
Previously these tests weren't actually checking the right thing. This should fix the logic to what I think the author was trying to do.
Fixes #8620.

### CODE REVIEW

File: tests/pthread/call_sync_on_main_thread.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ mergeInto(LibraryManager.library, {
   getDomElementInnerHTML__sig: 'viii',
   getDomElementInnerHTML: function(domElementId, dst, size) {
```
Comment (kripken) [inline tests/pthread/call_sync_on_main_thread.js]: Looks good, thanks! But please rename this method so the name isn't misleading, to say `getParentInnerHTML`.

Comment (VirtualTim) [reply tests/pthread/call_sync_on_main_thread.js]: Done.

**Comment by kripken** [comment]
Thanks @VirtualTim!
