### PR TITLE
Fix webgpu warning when configuring swapchain on canvas

### LINKED ISSUE #17416: [WEBGPU] Consider removing the explicit size when creating a GPUCanvasContext
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Here's the browser warning:

> Setting an explicit size when calling configure() on a GPUCanvasContext has been deprecated, and will soon be removed. Please set the canvas width and height attributes instead. Note that after the initial call to configure() changes to the canvas width and height will now take effect without the need to call configure() again.

Emscripten should consider updating it's webgpu context initialization code.

### PR DESCRIPTION
**Pull request by gracicot**
Fixes #17416

Set `size` to `undefined` when no size is specified when creating a context. Won't break current behavior when users still specify the canvas size and will emit a warning.

When the size is specified to be zero by zero, we send no size as the [webgpu specification states](https://www.w3.org/TR/webgpu/#context-sizing) and the context will take `canvas.width` and `canvas.height`.

In my toy project, I automatically set and resize the canvas using the following code:
```js
const canvas = document.querySelector("canvas");
const { width, height } = canvas.getBoundingClientRect();
canvas.width = width * window.devicePixelRatio;
canvas.height = height * window.devicePixelRatio;
const resizeObserver = new ResizeObserver(entries => {
    for (const entry of entries) {
        if (entry.target !== canvas) { continue; }
        canvas.width = entry.devicePixelContentBoxSize[0].inlineSize;
        canvas.height = entry.devicePixelContentBoxSize[0].blockSize;
    }
});
resizeObserver.observe(canvas);
```

cc @shrekshao

### CODE REVIEW

**Comment by gracicot** [comment]
Let me know if the logic is right. It worked flawlessly on my projects. It removes two warnings: 

> Setting an explicit size when calling configure() on a GPUCanvasContext has been deprecated, and will soon be removed. Please set the canvas width and height attributes instead. Note that after the initial call to configure() changes to the canvas width and height will now take effect without the need to call configure() again.

And also:

> The default GPUCanvasAlphaMode will change from "premultiplied" to "opaque". Please explicitly set alphaMode to "premultiplied" if you would like to continue using that compositing mode.

Although I see no way to set that from the C++ side.

**Comment by shrekshao** [comment]
Thanks for the change! LGTM
The alphaMode configure requires updates on webgpu-headers side and emscripten side (falls in my TODO list). Setting them to "opaque" sounds reasonable.
Intended reviewer: @kainino0x

**Comment by shrekshao** [comment]
Similar failure on test-browser-chrome is seen at some commits on main. https://app.circleci.com/pipelines/github/emscripten-core/emscripten/22295/workflows/3f30f701-e23c-4635-9a42-c60849fecde8/jobs/549264

Usually you can do a `git rebase main` and `git push origin HEAD --force` to retrigger the test run and likely it will pass.

File: src/library_webgpu.js [hunk 1]
```diff
@@ -2575,16 +2575,20 @@ var LibraryWebGPU = {
...
         {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.format) }}}],
       "usage": {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.usage) }}},
-      "size": [
-        {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.width) }}},
-        {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.height) }}},
-      ],
+      "size": configurationSize[0] !== 0 && configurationSize[1] !== 0
+        ? configurationSize
+        : undefined,
+        "alphaMode": "opaque",
```
Comment (kainino0x) [inline src/library_webgpu.js:2591]: When the configurationSize is *not* zero, I think we should set the size of the canvas (`context["canvas"]["width"]` etc), because otherwise (at least at the moment) we'll be changing the behavior compared to how this C API is supposed to work on native. That API may change in the future but we should adhere to it for now.

Comment (kainino0x) [reply src/library_webgpu.js:2591]: That is to say - instead of specifying the "size" member in that case, which is deprecated, I think we should actually implement it properly by setting the canvas size attributes.

Comment (gracicot) [reply src/library_webgpu.js:2591]: I can change it, but is there a way to get the current size of the canvas on the C++ side? If there's not would there be a way to set the swapchain to just take the current size of the canvas?

Comment (gracicot) [reply src/library_webgpu.js]: It should be all good now, let me know if there's something else you would change

File: src/library_webgpu.js [hunk 2]
```diff
@@ -2576,15 +2576,25 @@ var LibraryWebGPU = {
       {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.presentMode) }}});
 #endif
 
+    var canvasSize = [
+        {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.width) }}},
+        {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.height) }}}
+    ];
+
+    if (canvasSize[0] !== 0) {
+        context.canvas.width = canvasSize[0];
```
Comment (kainino0x) [inline src/library_webgpu.js:2585]: Use this to indicate to Closure compiler that it shouldn't try to minify these properties. I'm never sure if this is necessary, but I think it can't hurt.

```suggestion
        context["canvas"]["width"] = canvasSize[0];
```

File: src/library_webgpu.js [hunk 3]
```diff
@@ -2576,15 +2576,25 @@ var LibraryWebGPU = {
...
+    }
+
+    if (canvasSize[1] !== 0) {
+        context.canvas.height = canvasSize[1];
```
Comment (kainino0x) [inline src/library_webgpu.js:2589]:
```suggestion
        context["canvas"]["height"] = canvasSize[1];
```

**Review by kainino0x — APPROVED** [review]
LGTM though I'd like to understand the concern about swapchain size before landing to make sure I'm not missing something

File: src/library_webgpu.js (hunk 1 above)
Comment (kainino0x) [reply src/library_webgpu.js]: > I can change it, but is there a way to get the current size of the canvas on the C++ side?

Yes, you can use [`emscripten_get_canvas_element_size`](https://emscripten.org/docs/api_reference/html5.h.html#c.emscripten_get_canvas_element_size) if needed.

> If there's not would there be a way to set the swapchain to just take the current size of the canvas?

Not sure I understand. Passing 0,0 of course skips setting `canvas.width`/`canvas.height`. And `configure()` will no longer change the size since that was the deprecated behavior.

**Comment by gracicot** [comment]
After experiment it's fine to say that all fine according to my tests now. Since the canvas is resized only when the size is non zero, one can always left the size undefined in the C++ side of the swapchain initialization, leaving the canvas with its initial size. I'd say merge it!

**Comment by kainino0x** [comment]
Thanks!
