### PR TITLE
[WasmFS] Follow symlinks and fix fstatat

### LINKED ISSUE #15948: WasmFS: Support symlinks
WasmFS should support symlinks as a third kind of file besides DataFile and Directory.

### PR DESCRIPTION
**Pull request by tlively**
Update path parsing to follow symlinks by default, but add configuration options
necessary for some system calls to opt out of following symlinks at the leaf of
paths.

As a drive-by to get test_fstatat.c working, also rename __syscall_fstatat64 to
its expected name, __syscall_newfstatat, and delete our incorrect previous
version of __syscall_newfstatat, which was performing a statfs operation.

Fixes #15948.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #17241** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/17241" target="_blank">Graphite</a> 
    * **PR #17243** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/17243" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/17243?utm_source=stack-comment).

File: tests/stat/test_fstatat.c [hunk 1]
```diff
@@ -58,7 +58,11 @@ void test() {
   assert(s.st_ctime);
 #ifdef __EMSCRIPTEN__
   assert(s.st_blksize == 4096);
+#ifdef WASMFS
+  assert(s.st_blocks == 8);
+#else
```
Comment (kripken) [inline tests/stat/test_fstatat.c:63]: Maybe add a comment about why these differ? (and what does linux do?)

File: system/lib/wasmfs/paths.cpp [hunk 2]
```diff
@@ -11,38 +11,70 @@
...
+
+static inline constexpr size_t MAX_RECURSIONS = 40;
+
+ParsedFile doParseFile(std::string_view path,
+                       std::shared_ptr<Directory> base,
+                       LinkBehavior links,
+                       size_t& recursions,
+                       bool topLevel = false);
+
+ParsedFile getBase(__wasi_fd_t basefd) {
```
Comment (kripken) [inline system/lib/wasmfs/paths.cpp:24]: The name slightly confuses me because the notation of `dirname, basename` suggests "base" to mean the child and not the dir.

How about `getBaseDir`?

File: system/lib/wasmfs/paths.cpp [hunk 3]
```diff
@@ -11,38 +11,70 @@
...
-                           std::string_view name) {
+namespace {
+
+static inline constexpr size_t MAX_RECURSIONS = 40;
+
+ParsedFile doParseFile(std::string_view path,
+                       std::shared_ptr<Directory> base,
+                       LinkBehavior links,
+                       size_t& recursions,
+                       bool topLevel = false);
```
Comment (kripken) [inline system/lib/wasmfs/paths.cpp:22]: What does "toplevel" mean?

Comment (tlively) [reply system/lib/wasmfs/paths.cpp]: I was actually able to simplify things and get rid of it as well reduce the number of `LinkBehavior` options 🎉

**Review by kripken — APPROVED** [review]

**Comment by tlively** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/17243?utm_source=stack-comment).


Job Reference: FQypeD1u65nVBappKlJC
