### PR TITLE
[WasmFS] Fix URL support in fetch backend

### LINKED ISSUE #16954: URL is ignored in WasmFS Fetch Backend
It is not possible to fetch several different files via WasmFS Fetch Backend.
I wanted to use fetch backend for something like createLazyFile() but with WasmFS.

It seems that `base_url ` parameter is ignored in `wasmfs_create_fetch_backend()`:
https://github.com/emscripten-core/emscripten/blob/2a4e2958792f7978082d310441e3421f318a44fd/system/lib/wasmfs/backends/fetch_backend.cpp#L22
Moreover, the file URL is hardcoded to `data.dat` here: https://github.com/emscripten-core/emscripten/blob/22c23bd81cb3700b531913dc4ee43fb7af5b40f6/src/library_wasmfs_fetch.js#L29
This doesn't allow using multiple files in fetch backend.
How this could work:
* allow fetching several files by using different backends for each file (e.g. use base_url)
* allow fetching several files that are relative to the base URL (e.g. don't hardcode `data.dat`)
* or both of the above

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing code:**
```cpp
#include <assert.h>
#include <emscripten/emscripten.h>
#include <emscripten/wasmfs.h>
#include <stdio.h>
#include <sys/stat.h>

int main()
{
    auto orig = (char *)EM_ASM_INT({
        const origin = self.location.origin;
        const nb = lengthBytesUTF8(origin) + 1;
        const ptr = _malloc(nb);
        stringToUTF8(origin, ptr, nb);
        return ptr;
    });
    backend_t backend = wasmfs_create_fetch_backend(orig);

    int fd1 = wasmfs_create_file("/testfile", 0777, backend);

    struct stat st1 = {};
    assert(fstat(fd1, &st1) != -1);
    printf("file size: %lld\n", st1.st_size);

    int fd2 = wasmfs_create_file("/testfile2", 0777, backend);

    struct stat st2 = {};
    assert(fstat(fd2, &st2) != -1);
    printf("file size: %lld\n", st2.st_size);

    assert(st1.st_size != st2.st_size); // This should not fail!

    return 0;
}
```

**Full link command:**
```bash
rm -rf build
mkdir -p build
em++ -v -std=c++11  -s WASMFS=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD wasmfs_fetch_backend.cpp -o build/wasmfs_fetch_backend.html
cd build
echo 1 > data.dat
echo 12 > testfile
echo 123 > testfile2
emrun wasmfs_fetch_backend.html
```

### PR DESCRIPTION
**Pull request by mere-human**
Use the relative file path as a part of fetch URL.
But do so only in case the base URL is absolute.
This allows fetching several different files using the same backend.

Fix #16954

### CODE REVIEW

File: src/library_wasmfs_fetch.js [hunk 1]
```diff
@@ -23,10 +26,20 @@ mergeInto(LibraryManager.library, {
...
+        try {
+          var u = new URL(fileUrl, _baseUrl);
+          url = u.toString();
+        } catch (e) {
+        }
+      } else {
+        url = _baseUrl;
+      }
+      if (url === '')
+        url = 'data.dat';
```
Comment (tlively) [inline src/library_wasmfs_fetch.js:42]: We probably don't need this part anymore. I think `data.dat` was just a placeholder value.

File: src/library_wasmfs_fetch.js [hunk 2]
```diff
@@ -12,9 +12,12 @@ mergeInto(LibraryManager.library, {
   _wasmfs_create_fetch_backend_js__deps: [
     '$wasmFS$backends',
     '$wasmFS$JSMemoryFiles',
+    '$wasmFS$backendFileNames',
     '_wasmfs_create_js_file_backend_js',
   ],
-  _wasmfs_create_fetch_backend_js: async function(backend) {
+  _wasmfs_create_fetch_backend_js: async function(backend, baseUrl) {
+    var _baseUrl = UTF8ToString(baseUrl);
+    var isAbs = _baseUrl.indexOf('://') !== -1;
```
Comment (tlively) [inline src/library_wasmfs_fetch.js:20]: This is the naming scheme I've used for similar parameters in other WasmFS backends.
```suggestion
  _wasmfs_create_fetch_backend_js: async function(backend, baseUrl_p) {
    var baseUrl = UTF8ToString(baseUrl_p);
    var isAbs = baseUrl.indexOf('://') !== -1;
```

File: system/lib/wasmfs/backends/fetch_backend.cpp [hunk 3]
```diff
@@ -13,15 +13,17 @@
...
 
 extern "C" {
-void _wasmfs_create_fetch_backend_js(wasmfs::backend_t);
+void _wasmfs_create_fetch_backend_js(wasmfs::backend_t, char*);
 }
 
 namespace wasmfs {
 
 extern "C" backend_t wasmfs_create_fetch_backend(char* base_url) {
   // TODO: use base url, cache on JS side
```
Comment (tlively) [inline system/lib/wasmfs/backends/fetch_backend.cpp:22]: This stale comment should be deleted.

File: system/lib/wasmfs/proxied_async_js_impl_backend.h [hunk 4]
```diff
@@ -108,6 +123,22 @@ class ProxiedAsyncJSImplFile : public DataFile {
...
+      if (!name.empty())
+        name.insert(0, "/");
+      name.insert(0, parent->locked().getName(child));
+      if (parent->getBackend() != backend)
+        break;
+      child = parent;
+      parent = parent->locked().getParent();
+    }
+    return name;
+  }
```
Comment (tlively) [inline system/lib/wasmfs/proxied_async_js_impl_backend.h:140]: Reading the parent pointers and constructing file paths breaks the backend abstraction. If we need to keep track of objects across the C++/JS boundary, we should use integer indices into JS arrays rather than strings.

File: tests/wasmfs/wasmfs_fetch.c [hunk 5]
```diff
@@ -17,12 +18,92 @@
 #include <sys/stat.h>
 #include <unistd.h>
 
-static backend_t make_js_file_backend(void* arg) {
-  return wasmfs_create_js_file_backend();
+char url_orig[1024];
+void set_url_origin() {
+  url_orig[0] = 0;
+  EM_ASM(
```
Comment (tlively) [inline tests/wasmfs/wasmfs_fetch.c:24]: We should try to avoid `EM_ASM` since it has a performance cost. It's better to import functions directly from the JS library by writing C function declarations for them.

File: src/library_wasmfs_jsimpl.js [hunk 6]
```diff
@@ -9,6 +9,8 @@ mergeInto(LibraryManager.library, {
   // the JS code that implements them. This is the JS side of the JSImpl* class
   // in C++, together with the js_impl calls defined right after it.
   $wasmFS$backends: {},
+  // Contains a mapping of backend files to their file names.
+  $wasmFS$backendFileNames: {},
```
Comment (tlively) [inline src/library_wasmfs_jsimpl.js:13]: Would it be possible to put any new state in `library_wasmfs_fetch.js` instead?

**Review by tlively — COMMENTED** [review]
Neat, thanks for working on this!

File: system/lib/wasmfs/proxied_async_js_impl_backend.h (hunk 4 above)
Comment (mere-human) [reply system/lib/wasmfs/proxied_async_js_impl_backend.h:140]: But what could be a better way to construct a relative path to the file? I need it to be a part of the URL. I need to somehow obtain names of the path components and make them available to JS.

File: system/lib/wasmfs/backends/fetch_backend.cpp [hunk 7]
```diff
@@ -13,15 +13,17 @@
 // See library_wasmfs_fetch.js
 
 extern "C" {
-void _wasmfs_create_fetch_backend_js(wasmfs::backend_t);
+void _wasmfs_create_fetch_backend_js(wasmfs::backend_t, char*);
```
Comment (sbc100) [inline system/lib/wasmfs/backends/fetch_backend.cpp:16]: Should this be `const char *`? (same below for argument to wasmfs_create_fetch_backend)

File: system/lib/wasmfs/backends/fetch_backend.cpp (hunk 3 above)
Comment (mere-human) [reply system/lib/wasmfs/backends/fetch_backend.cpp:22]: Ok. What about the "cache on JS side" part? I'm not doing it in this PR.

File: system/lib/wasmfs/backends/fetch_backend.cpp (hunk 7 above)
Comment (mere-human) [reply system/lib/wasmfs/backends/fetch_backend.cpp]: Done.

File: src/library_wasmfs_jsimpl.js (hunk 6 above)
Comment (mere-human) [reply src/library_wasmfs_jsimpl.js]: Yes. Done.
Alternatively, I can call `getRelativeFileName()` directly in `getFile()` without caching.

File: tests/wasmfs/wasmfs_fetch.c (hunk 5 above)
Comment (mere-human) [reply tests/wasmfs/wasmfs_fetch.c]: Moved to a separate file.

File: src/library_wasmfs_fetch.js (hunk 2 above)
Comment (mere-human) [reply src/library_wasmfs_fetch.js]: Done.

File: src/library_wasmfs_fetch.js [hunk 8]
```diff
@@ -9,12 +9,18 @@ mergeInto(LibraryManager.library, {
   // will fetch() the data from the network asynchronously. Otherwise, after
   // that fetch it behaves just like JSFile (and it reuses the code from there).
 
+  // Contains a mapping of backend files to their file names.
+  $wasmFS$backendFileNames: {},
+
   _wasmfs_create_fetch_backend_js__deps: [
     '$wasmFS$backends',
     '$wasmFS$JSMemoryFiles',
+    '$wasmFS$backendFileNames',
```
Comment (sbc100) [inline src/library_wasmfs_fetch.js:18]: I don't love the use of `$` in the middle of these identifiers... I wonder if we can switch to using `_`... not related to this PR I guess.. so maybe a followup or a separate prep PR?

File: src/library_wasmfs_fetch.js [hunk 9]
```diff
@@ -23,10 +29,18 @@ mergeInto(LibraryManager.library, {
         // the actual read below.
         return Promise.resolve();
       }
-
+      var fileUrl = wasmFS$backendFileNames[file] ? wasmFS$backendFileNames[file] : '';
```
[the remark this answers is not in the document]
Comment (sbc100) [reply src/library_wasmfs_fetch.js:32]: fileUrl is only uses inside the `isAbs` block below so maybe move it down there?

File: tests/wasmfs/wasmfs_fetch.c [hunk 10]
```diff
@@ -6,23 +6,87 @@
...
+
+  assert(strlen(url_orig) != 0);
+  backend_t backend = wasmfs_create_fetch_backend(url_orig);
+  int fd = wasmfs_create_file("/test.txt", 0777, backend);
+  check_file(fd, "fetch 2");
+  assert(close(fd) == 0);
+}
+
+void test_directory_abs() {
+  backend_t backend = wasmfs_create_fetch_backend(url_orig);
```
Comment (sbc100) [inline tests/wasmfs/wasmfs_fetch.c:57]: Do these backends ever need to get destroyed?   Since each test creates a new one, does this mean that order of the tests matter?

File: tests/test_browser.py [hunk 11]
```diff
@@ -5304,15 +5304,20 @@ def test(args):
     # thread and busy-wait
     'main_thread': (['-sPTHREAD_POOL_SIZE=1'],),
     # using proxy_to_pthread also works, of course
-    'proxy_to_pthread': (['-sPROXY_TO_PTHREAD'],),
+    'proxy_to_pthread': (['-sPROXY_TO_PTHREAD', '-sINITIAL_MEMORY=32MB', '-DPROXYING'],),
```
Comment (sbc100) [inline tests/test_browser.py:5307]: Does the test really need 32mb or memory?  I guess this is because the per-thread overhead in emscripten is so high?

File: tests/wasmfs/wasmfs_fetch.c (hunk 10 above)
Comment (mere-human) [reply tests/wasmfs/wasmfs_fetch.c:57]: I don't think there is a way to destroy a backend through the API currently. Should I add one?

The order of tests doesn't matter. I needed several backends because I wanted to test different URLs.

File: tests/test_browser.py (hunk 11 above)
Comment (mere-human) [reply tests/test_browser.py:5307]: Yes. This is because it needs memory for  all the threads. Now it uses a thread per backend.
I can set the memory to the exact minimum needed by the test.

File: tests/wasmfs/wasmfs_fetch.c (hunk 10 above)
Comment (tlively) [reply tests/wasmfs/wasmfs_fetch.c:57]: No need to add a way to destroy backends. If we decide we need that, we can add it separately from this PR.

File: tests/test_browser.py (hunk 11 above)
Comment (tlively) [reply tests/test_browser.py:5307]: Keeping it at a largish round number like 32MB is better than trying to find the exact number since it will make the test robust against unrelated increases in memory consumption.

File: system/lib/wasmfs/proxied_async_js_impl_backend.h (hunk 4 above)
Comment (tlively) [reply system/lib/wasmfs/proxied_async_js_impl_backend.h:140]: Check out `node_backend.cpp`, which has the same problem of needing to track relative paths.

Comment (mere-human) [reply system/lib/wasmfs/proxied_async_js_impl_backend.h]: Done. Used a similar approach as in `node_backend.cpp`. Now each backend object knows its name.

File: src/library_wasmfs_fetch.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (mere-human) [reply src/library_wasmfs_fetch.js]: Done.

**Review by tlively — COMMENTED** [review]
Looks pretty good! Just a couple small comments.

File: tests/wasmfs/wasmfs_fetch.c [hunk 12]
```diff
@@ -47,5 +120,20 @@ int main() {
...
+  assert(close(fd) == 0);
+  assert(close(fd2) == 0);
+}
+
+int main() {
+  getUrlOrigin(url_orig, sizeof(url_orig));
+  test_default();
+
+  // NOTE: Each fetch backend runs in a separate thread.
+#ifdef PROXYING
```
[the remark this answers is not in the document]
Comment (mere-human) [reply tests/wasmfs/wasmfs_fetch.c:132]: The problem is that when running on the main thread, this option is passed: `-sPTHREAD_POOL_SIZE=1`. 
Each fetch backend instance requires a separate thread, so the test just hangs because it can't spawn more than one.

Should the setting be updated with the actual thread count or removed at all?
It passes with `-sPTHREAD_POOL_SIZE=4`.

File: src/library_wasmfs_fetch.js [hunk 13]
```diff
@@ -14,7 +14,7 @@ mergeInto(LibraryManager.library, {
     '$wasmFS$JSMemoryFiles',
     '_wasmfs_create_js_file_backend_js',
   ],
-  _wasmfs_create_fetch_backend_js: async function(backend) {
+  _wasmfs_create_fetch_backend_js: async function (backend) {
```
[the remark this answers is not in the document]
Comment (mere-human) [reply src/library_wasmfs_fetch.js:17]: Removed. I just wanted to format it the same way as other functions in file.

**Review by tlively — APPROVED** [review]
Sorry for the delayed review. Thanks for working on this!
