### PR TITLE
[pthreads] Initialize TLS on workers in MINIMAL_RUNTIME mode.

### LINKED ISSUE #21528: Memory corruption/segfault with MINIMAL_RUNTIME + std::thread + thread_local variables
We're seeing various issues when using `thread_local` variables in a `std::thread` with `MINIMAL_RUNTIME` enabled. Is there some extra configuration that needs to be done on our end to get this to work?

Often there is no console output in the browser at all (and the browser seemingly hangs), but once in a while it does produce something.

When accessing the `thread_local` from within a `std::thread`:
```
x: 0
x: 1668509029
0df00eb0-d17e-4f29-b29e-e4edde614324:25 worker.js onmessage() captured an uncaught exception: Error: Runtime error: The application has corrupted its heap memory area (address zero)!
err @ 0df00eb0-d17e-4f29-b29e-e4edde614324:25
handleMessage @ emscripten-thread-local-test.worker.js:175
0df00eb0-d17e-4f29-b29e-e4edde614324:25 Error: Runtime error: The application has corrupted its heap memory area (address zero)!
    at abort (0df00eb0-d17e-4f29-b29e-e4edde614324:64:9)
    at checkStackCookie (0df00eb0-d17e-4f29-b29e-e4edde614324:129:5)
    at Object.invokeEntryPoint (0df00eb0-d17e-4f29-b29e-e4edde614324:832:7)
    at handleMessage (emscripten-thread-local-test.worker.js:148:35)
```
See the repro below to understand what x is. It should always be 0.

With `STACK_OVERFLOW_CHECK=0`:
```
x: 0
c95d8ca9-bbd6-4d51-8198-b138beca63e8:14 worker.js onmessage() captured an uncaught exception: Error: segmentation fault
c95d8ca9-bbd6-4d51-8198-b138beca63e8:14 Error: segmentation fault
    at abort (blob:http://localhost:8080/c95d8ca9-bbd6-4d51-8198-b138beca63e8:107:8)
    at segfault (blob:http://localhost:8080/c95d8ca9-bbd6-4d51-8198-b138beca63e8:95:2)
    at emscripten-thread-local-test.wasm.SAFE_HEAP_LOAD_i32_4_4 (wasm://wasm/emscripten-thread-local-test.wasm-00e22446:wasm-function[3071]:0x48407)
    at emscripten-thread-local-test.wasm.task() (wasm://wasm/emscripten-thread-local-test.wasm-00e22446:wasm-function[61]:0x20d0)
    at emscripten-thread-local-test.wasm.decltype(std::declval<void (*)()>()()) std::__2::__invoke[abi:ue170004]<void (*)()>(void (*&&)()) (wasm://wasm/emscripten-thread-local-test.wasm-00e22446:wasm-function[142]:0x563a)
    at emscripten-thread-local-test.wasm.void std::__2::__thread_execute[abi:ue170004]<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, void (*)()>(std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, void (*)()>&, std::__2::__tuple_indices<...>) (wasm://wasm/emscripten-thread-local-test.wasm-00e22446:wasm-function[119]:0x4d9d)
    at invoke_vi (blob:http://localhost:8080/c95d8ca9-bbd6-4d51-8198-b138beca63e8:4050:27)
    at emscripten-thread-local-test.wasm.void* std::__2::__thread_proxy[abi:ue170004]<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, void (*)()>>(void*) (wasm://wasm/emscripten-thread-local-test.wasm-00e22446:wasm-function[72]:0x34b5)
    at Object.invokeEntryPoint (blob:http://localhost:8080/c95d8ca9-bbd6-4d51-8198-b138beca63e8:669:37)
    at handleMessage (http://localhost:8080/emscripten-thread-local-test.worker.js:148:35)
```

When _not_ reading any `thread_local`, the output is correct but when exiting `main` it shows this:
```
Uncaught (in promise) Error: Stack overflow! Stack cookie has been overwritten at 0x00000004, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x00000000 0x02135467
    at abort (cbeda433-4601-4d5e-8cf0-da0512f8acb8:64:9)
    at checkStackCookie (cbeda433-4601-4d5e-8cf0-da0512f8acb8:125:5)
    at run (cbeda433-4601-4d5e-8cf0-da0512f8acb8:5199:3)
    at ready (cbeda433-4601-4d5e-8cf0-da0512f8acb8:31:34)
```

Minimal repro:

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.5)
project(emscripten-thread-local-test
    LANGUAGES CXX)
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".html")

add_executable(${CMAKE_PROJECT_NAME} main.cpp)
target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC
    -fexceptions -pthread)
target_link_options(${CMAKE_PROJECT_NAME} PUBLIC
    -fexceptions -pthread)
target_link_options(${CMAKE_PROJECT_NAME} PUBLIC
    -sMINIMAL_RUNTIME=1
    -sPTHREAD_POOL_SIZE=2)
```

main.cpp:
```cpp
#include <iostream>
#include <thread>
#include <exception>
#include <system_error>
#include <cassert>
#include <emscripten/threading.h>
	
thread_local int x = 0;

void task() {
    try {
        std::cout << "x: " << x << '\n';
        ++x;
    } catch(const std::system_error& e) {
        std::cout << e.what() << '\n';
    }
}

int main() {
    assert(emscripten_has_threading_support());

    task();

    std::thread t1(task);
    t1.join();

    std::thread t2(task);
    t2.join();

    return 0;
}
```

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.55 (165133b1cc977f0b9a277e42ef809b823157189c)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 6c7805d5d186a6d1263f90b8033ad85e2d2633d7)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\dev\emsdk\upstream\bin
```

**Full link command and output with `-v` appended:**
Taken from ninja:
```
em++  -g -fexceptions -pthread -MD -MT CMakeFiles/emscripten-thread-local-test.dir/main.cpp.o -MF CMakeFiles\emscripten-thread-local-test.dir\main.cpp.o.d -o CMakeFiles/emscripten-thread-local-test.dir/main.cpp.o -c C:/dev/emscripten-thread-local/main.cpp
em++.bat -g -fexceptions -pthread -sMINIMAL_RUNTIME=1 -sPTHREAD_POOL_SIZE=2 CMakeFiles/emscripten-thread-local-test.dir/main.cpp.o -o emscripten-thread-local-test.html
```

### PR DESCRIPTION
**Pull request by brendandahl**
TLS was not initialized on workers causing the tls_base address to be 0 and write to the wrong memory location.

Fixes #21528 and is also needed for PR #24565

### CODE REVIEW

File: src/postamble_minimal.js [hunk 1]
```diff
@@ -66,10 +69,6 @@ function initRuntime(wasmExports) {
   writeStackCookie();
 #endif
 
-#if PTHREADS
-  PThread.tlsInitFunctions.push(wasmExports['_emscripten_tls_init']);
```
Comment (kripken) [inline src/postamble_minimal.js:70]: Does this not remove it from the main thread as well? (And the new code only re-adds it for pthreads)

Or is this not needed on the main thread? But from libpthread.js it looks like it is run there.

Comment (brendandahl) [reply src/postamble_minimal.js:70]: It does remove it from the main thread, which was not my intention. I'm amazed that worked. I guess there's not much testing for minimal+pthread.

Ideally this code would be in some shared spot that both minimal runtime + regular runtime would share, but I think that's going to be a bigger refactor.

**Review by kripken — APPROVED** [review]

File: src/postamble_minimal.js (hunk 1 above)
Comment (kripken) [reply src/postamble_minimal.js:70]: Sounds like a hole in testing, yeah... we do have pthreads tests for minimal runtime, but without TLS, I guess, until this PR.

File: test/pthread/test_pthread_c_thread_local.c [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+// Emscripten is available under two separate licenses, the MIT license and the
+// University of Illinois/NCSA Open Source License.  Both these licenses can be
+// found in the LICENSE file.
+
+#include <pthread.h>
+#include <stdlib.h>
+#include <assert.h>
+#include <stdio.h>
+
+static _Thread_local int thread_local = 0;
```
Comment (sbc100) [inline test/pthread/test_pthread_c_thread_local.c:11]: Would it perhaps make sense to do ` = 3` here and assert that `thread_local` starts with this value in moth `main` and in `thread_start?

File: test/test_core.py [hunk 3]
```diff
@@ -2636,6 +2636,13 @@ def test_pthread_thread_local_storage(self):
       self.set_setting('INITIAL_MEMORY', '300mb')
     self.do_run_in_out_file_test('pthread/test_pthread_thread_local_storage.cpp')
 
+  @node_pthreads
+  @also_with_minimal_runtime
+  def test_pthread_c_thread_local(self):
+    if self.get_setting('MINIMAL_RUNTIME') and is_sanitizing(self.cflags):
+      self.skipTest('MINIMAL_RUNTIME + threads + asan does not work')
+    self.do_run_in_out_file_test('pthread/test_pthread_c_thread_local.c')
```
Comment (sbc100) [inline test/test_core.py:2644]: Surely we already have tests that cover this?

Comment (sbc100) [reply test/test_core.py:2644]: It looks like `test/pthread/test_pthread_tls.cpp` is probably what we want.  It happens to use C++ `thread_local` instead of the C's `_Thread_local` but I think it should the same thing from the POV of this PR.
