### PR TITLE
[pthreads] Handle exit exceptions during pthread cleanup.

### LINKED ISSUE #24500: test_dylink_pthread_static_data is flaky
It fairly often fails with:

```

======================================================================
FAIL [0.001s]: test_dylink_pthread_static_data_modularize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/root/project/test/common.py", line 915, in resulting_test
    return func(self, *args)
  File "/root/project/test/common.py", line 366, in decorated
    f(self, *args, **kwargs)
  File "/root/project/test/common.py", line 687, in metafunc
    f(self, *args, **kwargs)
  File "/root/project/test/test_other.py", line 2178, in test_dylink_pthread_static_data
    self.do_runf(
  File "/root/project/test/common.py", line 1943, in do_runf
    return self._build_and_run(filename, expected_output, **kwargs)
  File "/root/project/test/common.py", line 1988, in _build_and_run
    js_output = self.run_js(js_file, engine, args,
  File "/root/project/test/common.py", line 1578, in run_js
    self.fail('JS subprocess failed (%s): %s (expected=%s).  Output:\n%s' % (error.cmd, error.returncode, assert_returncode, ret))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: JS subprocess failed (/root/emsdk/node/22.16.0_64bit/bin/node --stack-trace-limit=50 --trace-uncaught /tmp/emtest_ltr8uczw/emscripten_test_other_3yqtyx97/main.js): 1 (expected=0).  Output:
123

node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
ExitStatus {
  name: 'ExitStatus',
  message: 'Program terminated with exit(0)',
  status: 0
}
Thrown at:
    at node:internal/event_target:1101:28
    at processTicksAndRejections (node:internal/process/task_queues:85:11)


Node.js v22.16.0


----------------------------------------------------------------------
Ran 1455 tests in 1532.146s

FAILED (failures=2, skipped=24)
```

### PR DESCRIPTION
**Pull request by brendandahl**
Thread cleanup can potentially execute the queue mailbox and trigger an ExitStatus exception, so we must wrap cleanup with callUserCallback to handle the exception or node will complain about an unhandled exception.

Fixes #24500,  #22490

### CODE REVIEW

**Comment by brendandahl** [comment]
@sbc and I tried to write a test, but this seems to rely on a very specific order of events of a thread cleaning up and the main thread exiting that doesn't seem feasible to reproduce reliably.

A backtrack of when the failure happens for reference:
```
Error
    at _proc_exit (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1251:19)
    at exitJS (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1304:7)
    at exitOnMainThread (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1273:7)
    at __emscripten_receive_on_main_thread_js (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:5773:17)
    at main.wasm.run_js_func (wasm://wasm/main.wasm-0015e2fa:wasm-function[139]:0x36d5)
    at main.wasm.em_task_queue_execute (wasm://wasm/main.wasm-0015e2fa:wasm-function[101]:0x24b5)
    at main.wasm.emscripten_proxy_execute_queue (wasm://wasm/main.wasm-0015e2fa:wasm-function[113]:0x2923)
    at main.wasm.emscripten_current_thread_process_queued_calls (wasm://wasm/main.wasm-0015e2fa:wasm-function[88]:0x1e09)
    at main.wasm.emscripten_main_thread_process_queued_calls (wasm://wasm/main.wasm-0015e2fa:wasm-function[90]:0x1e5a)
    at main.wasm._emscripten_yield (wasm://wasm/main.wasm-0015e2fa:wasm-function[79]:0x19fd)
    at main.wasm.emscripten_futex_wait (wasm://wasm/main.wasm-0015e2fa:wasm-function[82]:0x1b4f)
    at main.wasm.__timedwait_cp (wasm://wasm/main.wasm-0015e2fa:wasm-function[158]:0x3c17)
    at main.wasm.__timedwait (wasm://wasm/main.wasm-0015e2fa:wasm-function[159]:0x3cbc)
    at main.wasm.__pthread_mutex_timedlock (wasm://wasm/main.wasm-0015e2fa:wasm-function[211]:0x5307)
    at main.wasm.__pthread_mutex_lock (wasm://wasm/main.wasm-0015e2fa:wasm-function[210]:0x5208)
    at main.wasm.dlfree (wasm://wasm/main.wasm-0015e2fa:wasm-function[318]:0xaa8d)
    at main.wasm._emscripten_thread_free_data (wasm://wasm/main.wasm-0015e2fa:wasm-function[199]:0x4c5b)
    at /usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:903:12
    at Object.returnWorkerToPool (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1386:9)
    at cleanupThread (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1135:15)
    at worker.onmessage (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1419:13)
    at Worker.<anonymous> (/usr/local/google/home/dahlb/projects/emscripten/out/test/main.js:1449:49)
    at Worker.emit (node:events:518:28)
    at MessagePort.<anonymous> (node:internal/worker:268:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
```

File: src/lib/libpthread.js [hunk 1]
```diff
@@ -251,7 +251,10 @@ var LibraryPThread = {
         } else if (cmd === 'spawnThread') {
           spawnThread(d);
         } else if (cmd === 'cleanupThread') {
-          cleanupThread(d.thread);
+          // Cleanup can potentially execute the queue mailbox and trigger an
+          // ExitStatus exception, so we must wrap cleanup with callUserCallback
+          // to handle the exception.
```
Comment (sbc100) [inline src/lib/libpthread.js]: How about "cleanupThread needs to be run via callUserCallback since it calls back into user code to free stuff.  Without this its possible the `unwind` or `ExitStatus` exception could escape here".

**Review by sbc100 — APPROVED** [review]

**Review by sbc100 — APPROVED** [review]
Fuck yeah, thank for tracking this down.. hopefully this will address a bunch of the flakes we've been seeing.

**Comment by sbc100** [comment]
Do you think we can mark #22490 as fixes too?

**Comment by brendandahl** [comment]
> Do you think we can mark #22490 as fixes too?

It's probably the same issue, but I haven't been able to reproduce that one locally so I'm not sure.

**Comment by sbc100** [comment]
> > Do you think we can mark #22490 as fixes too?
> 
> It's probably the same issue, but I haven't been able to reproduce that one locally so I'm not sure.

Lets mark it as closed and we can re-open if needed.

**Comment by sbc100** [comment]
Can remove the `@flaky` decorator from `test_dylink_pthread_static_data` as part of this change?   (and `test_pthread_c11_threads` too)
