### PR TITLE
Fix binding of dynamically initialized globals.

### LINKED ISSUE #16275: Embind constants of type std::string results in an empty string
Hi,

First of all, thank you for all the work done on Emscripten & Embind, it's really great!

I have an issue while trying to bind the following global variable:

```cpp
const std::string std_string = "Hello World";
```

With the bindings:

```cpp
EMSCRIPTEN_BINDINGS(m) {
  emscripten::constant("std_string", std_string);
}
```

When inspecting the resulting module I can see:

```cpp
  ...
  std_string: ''
  ...
}
```

I've tried the following without success:

```cpp
namespace em = emscripten;

em::constant("std_string", std_string);
em::constant("std_string", em::val(std_string));
em::constant("std_string", em::val(std_string.c_str()));
em::constant("std_string", em::val(std_string.data()));
```

The last two seem to work fine for `std::string_view`.

How do I go about binding a global `std::string`?

Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```sh
em++ --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.3 (c06156773675b2cb437e41459c12d44bd9a8f235)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

The exact command run:

```sh
em++ -lembind -o m.js src/m.cpp
```

### PR DESCRIPTION
**Pull request by brendandahl**
Embind bindings were being initialized before dynamically initialized
static globals, making it impossible to bind them. This moves the
initialization back into a static struct so the bindings work as expected.

Fixes #16275

### CODE REVIEW

**Comment by xbcnn** [comment]
Looks good to me. 
__attribute__((constructor)) (GCC) is called before globals constructors.  We may use constructor(priority) and __attribute__ ((init_priority(x))) to the globals for desired ordering but seems troublesome.   
Use a static struct instance makes the nature declaring orders.

File: system/include/emscripten/bind.h [hunk 1]
```diff
@@ -1885,9 +1885,12 @@ void constant(const char* name, const ConstantType& v) {
         static_cast<double>(asGenericValue(BT::toWireType(v))));
 }
 
-// EMSCRIPTEN_BINDINGS simple creates a static constructor function which
-// will get included in the program if the translation unit in which it is
-// define gets linked into the program.
-#define EMSCRIPTEN_BINDINGS(name) __attribute__((constructor)) static void __embind_init_##name(void)
+// EMSCRIPTEN_BINDINGS creates a static struct that will initialize the bindings
+// after any other previously defined dynamic initializations, but before main.
```
Comment (sbc100) [inline system/include/emscripten/bind.h:1889]: I think the `..which will get included in the program if..` part is still relevent.  This constructor won't run if the TU is not part of the final program.

Also, perhaps a comment such as "Using a C++ constructor here ensures it occurs after any other C++ constructors in this file, which is not true for `__attribute__((constructor))` (they run before C++ constructors in the same file).

**Review by sbc100 — APPROVED** [review]

File: system/include/emscripten/bind.h [hunk 2]
```diff
@@ -1885,9 +1885,12 @@ void constant(const char* name, const ConstantType& v) {
...
+#define EMSCRIPTEN_BINDINGS(name)                                              \
+  static struct EmscriptenBindingInitializer_##name {                          \
```
[the remark this answers is not in the document]
Comment (brendandahl) [reply system/include/emscripten/bind.h]: SG, this name came from the old way this was done.

File: tests/embind/test_dynamic_initialization.cpp [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+const std::string global_string = "global string";
+
+EMSCRIPTEN_BINDINGS(constants) {
+  emscripten::constant("global_string", global_string);
+}
+
+int main() {
+    EM_ASM(
+        console.log("global_string = " + Module['global_string']);
+    );
```
Comment (sbc100) [inline tests/embind/test_dynamic_initialization.cpp:19]: Does the compiler now warn about missing return here?

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
lgtm.. do you have permission to land yet?
