### PR TITLE
[embind] Manage exceptions' states correctly

### LINKED ISSUE #26290: `val::throw_` linker error with `-fno-exceptions`
Since #26276, `val::throw_` produces a linker error when used with `-fno-exceptions`. This worked fine in the latest release (5.0.1). Note that `val::throw_` is not just for C++ exceptions, but also regular JS exceptions.

`emthrow.cpp`:
```cpp
#include <emscripten/bind.h>
#include <emscripten/val.h>

using namespace emscripten;

static void throwJsError() {
	val::global("Error").new_(val("oopsie")).throw_();
}

EMSCRIPTEN_BINDINGS(myBindings) {
	function("throwJsError", throwJsError);
}
```

```shell
em++ -v -lembind -fno-exceptions ./emthrow.cpp -o./emthrow.js
```

```
 /home/swdv/emsdk/upstream/bin/clang --version
shared:INFO: (Emscripten: Running sanity checks)
 "/home/swdv/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/home/swdv/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v -fno-exceptions -c ./emthrow.cpp -o /tmp/emscripten_temp_0w96ky0c/emthrow.o
clang version 23.0.0git (https:/github.com/llvm/llvm-project 6012aa1d4477b6d3aec8c022f4a2222834e6a0fc)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/swdv/emsdk/upstream/bin
Build config: +assertions
 (in-process)
 "/home/swdv/emsdk/upstream/bin/clang-23" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -main-file-name emthrow.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb -fdebug-compilation-dir=/home/swdv/webtest -v -fcoverage-compilation-dir=/home/swdv/webtest -resource-dir /home/swdv/emsdk/upstream/lib/clang/23 -D EMSCRIPTEN -isysroot /home/swdv/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/swdv/emsdk/upstream/lib/clang/23/include -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include -fdeprecated-macro -ferror-limit 19 -fmessage-length=336 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fignore-exceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_0w96ky0c/emthrow.o -x c++ ./emthrow.cpp
clang -cc1 version 23.0.0git based upon LLVM 23.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/swdv/emsdk/upstream/lib/clang/23/include
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 /home/swdv/emsdk/node/22.16.0_64bit/bin/node /home/swdv/emsdk/upstream/emscripten/tools/compiler.mjs - --symbols-only
 /home/swdv/emsdk/upstream/bin/wasm-ld -o ./emthrow.wasm /tmp/tmp_vlw6po6libemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__getTypeName --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1 -lembind-rtti /tmp/emscripten_temp_0w96ky0c/emthrow.o -L/home/swdv/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -L/home/swdv/emsdk/upstream/emscripten/src/lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-debug-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
 /home/swdv/emsdk/upstream/bin/llvm-objcopy ./emthrow.wasm ./emthrow.wasm '--remove-section=llvm.func_attr.annotate.*' --remove-section=producers --remove-section=name '--remove-section=.debug*'
 /home/swdv/emsdk/node/22.16.0_64bit/bin/node /home/swdv/emsdk/upstream/emscripten/tools/compiler.mjs -
error: undefined symbol: $exceptionLast (referenced by _emval_throw, referenced by root reference (e.g. compiled C/C++ code))
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: exceptionLast may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
    at finalCombiner (file:///home/swdv/emsdk/upstream/emscripten/src/jsifier.mjs:926:13)
    at Module.runJSify (file:///home/swdv/emsdk/upstream/emscripten/src/jsifier.mjs:962:5)
    at file:///home/swdv/emsdk/upstream/emscripten/tools/compiler.mjs:108:17
em++: error: '/home/swdv/emsdk/node/22.16.0_64bit/bin/node /home/swdv/emsdk/upstream/emscripten/tools/compiler.mjs -' failed (returned 1)
```

# Version

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.2-git (8551146567cc15c2d95ed51a8221b6a7b7295659)
clang version 23.0.0git (llvm/llvm-project@6012aa1d4477b6d3aec8c022f4a2222834e6a0fc)

### PR DESCRIPTION
**Pull request by aheejin**
`libemval.js` has two exception-related functions: `_emval_throw` and `_emval_from_current_cxa_exception`, but they haven't been correclty updating various exception-related states. #26276 tried to fix this but it only updated `exceptionLast`.

This updates other internal states correctly. Some of them only apply to Emscripten EH, while others apply to both.

1. To make the uncaught exception count updatable for Wasm EH, this adds `___cxa_in/decrement_uncaught_exception` to `cxa_exception_js_utils.cpp`, and also adds a common interface `in/decrementUncaughtExceptionCount` in `libexceptions.js` so that you can call them regardless of which EH is used. For Wasm EH, the management of the uncaught exception count is done within libc++abi functions (`__cxa_throw`, `__cxa_rethrow`, ...), but here in embind we bypass those functions, so we have to manage them directly.

2. To make refcount work correctly, this adds calls to `in/decrementExceptionRefcount` to exception-related functions. Also, this fixes memory leaks by adding the destructor mechanism that decrements refcount when emvals are destroyed. `_emval_from_current_cxa_exception` is similar to `std::current_exception`, which returns `std::exception_ptr`, whose destructor decrements the refcount so that the exception can be destroyed: https://github.com/emscripten-core/emscripten/blob/62e22652509fbe7a00609ce48a653d0d66f27ba5/system/lib/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp#L16 embind didn't have such a mechanism, so exceptions captured by `_emval_from_current_cxa_exception` leaked memory.

This also fixes #26290.

### CODE REVIEW

File: src/lib/libemval.js [hunk 1]
```diff
@@ -392,37 +399,50 @@ ${functionBody}
...
+  $emval_is_cpp_exception__deps: ['$Emval'],
+  $emval_is_cpp_exception: (object) => {
+    object = Emval.toValue(object);
+#if WASM_EXCEPTIONS
+    return object instanceof WebAssembly.Exception;
+#else
+#if EXCEPTION_STACK_TRACES
+    return object instanceof CppException;
+#else
+    return object === object+0; // Check if it is a number
```
Comment (sbc100) [inline src/lib/libemval.js]: Give that this seems to also return try for numbers maybe it should be `emval_could_be_cpp_exception`?

File: src/lib/libemval.js [hunk 2]
```diff
@@ -80,13 +81,19 @@ var LibraryEmVal = {
...
   #if ASSERTIONS
       assert(emval_handles[handle] !== undefined, `Decref for unallocated handle.`);
   #endif
+      var value = emval_handles[handle];
       emval_handles[handle] = undefined;
+      var destructor = emval_destructors[handle];
+      if (destructor) {
+        emval_destructors[handle] = undefined;
+        destructor(value);
+      }
```
Comment (sbc100) [inline src/lib/libemval.js:105]: Wrap this new code in `#if !DISABLE_EXCEPTION_THROWING || WASM_EXCEPTIONS`?

File: src/lib/libemval.js [hunk 3]
```diff
@@ -11,6 +11,7 @@
 var LibraryEmVal = {
   // Stack of handles available for reuse.
   $emval_freelist: [],
+  $emval_destructors: [],
```
Comment (sbc100) [inline src/lib/libemval.js]: Online define if `#if !DISABLE_EXCEPTION_THROWING || WASM_EXCEPTIONS`.

Also, it might be misleading to simply call this `emval_destructors`.   How about making it less generic and more sepcfic.  e.g. `emval_is_exception` just stores booleans and then  `decrementExceptionRefcount` is called explicitly during `_emval_decref`.

I fear that otherwise this looks too much like how embind handles cleanup / destructors for normal C++ objects (which it is not).

File: system/lib/libcxxabi/src/cxa_exception_js_utils.cpp [hunk 4]
```diff
@@ -123,6 +123,17 @@ char* __get_exception_terminate_message(void* thrown_object) {
   free(type);
   return result;
 }
+
+#ifdef __WASM_EXCEPTIONS__
+void __cxa_increment_uncaught_exception() throw() {
```
Comment (sbc100) [inline system/lib/libcxxabi/src/cxa_exception_js_utils.cpp]: If these are not actually part of the `__cxa` ABI maybe theyu should have a different prefix?

File: src/lib/libexceptions.js [hunk 5]
```diff
@@ -366,6 +366,16 @@ var LibraryExceptions = {
...
 
+  $incrementUncaughtExceptionCount__deps: ['__cxa_increment_uncaught_exception'],
+  $incrementUncaughtExceptionCount: () => {
+    ___cxa_increment_uncaught_exception();
+  },
+
+  $decrementUncaughtExceptionCount__deps: ['__cxa_decrement_uncaught_exception'],
+  $decrementUncaughtExceptionCount: () => {
+    ___cxa_decrement_uncaught_exception();
+  },
```
Comment (sbc100) [inline src/lib/libexceptions.js]: Is there any point in having the these JS wrappers?  Why not have the callsits call the native functions directly?

File: src/lib/libemval.js (hunk 2 above)
Comment (aheejin) [reply src/lib/libemval.js:105]: It's really confusing to which one to wrap in `#if !DISABLE_EXCEPTION_THROWING || WASM_EXCEPTIONS` and which one to wrap in `#if !DISABLE_EXCEPTION_CATCHING || WASM_EXCEPTIONS` in this file. Apparently we only enable refcounting when `EXCEPTION_STACK_TRACES` is true (which implies `!DISABLE_EXCEPTION_CATCHING` so we should be using it here too?

**Comment by aheejin** [comment]
Currently It's really messy to distinguish code between `!DISABLE_EXCEPTION_CATCHING` and `!DISABLE_EXCEPTION_THROWING`, and I'm not even sure what the rationale is for each of them (like, why is this particular variable dependent on `!DISABLE_EXCEPTION_THROWING` and not `!DISABLE_EXCEPTION_CATCHING`?) but the current version tries to match what `libexception.js` has:

Variables/functions dependent on `!DISABLE_EXCEPTION_THROWING`:
- `in/decrementUncaughtExceptionCount` + `uncaughtExceptionCount`
- `ExceptionInfo`

Variables/functions dependent on `!DISABLE_EXCEPTION_CATCHING`:
- `exceptionLast`
- `in/decrementExceptionRefcount` + `emval_exception_decrefs`

File: src/lib/libemval.js (hunk 3 above)
Comment (aheejin) [reply src/lib/libemval.js]: Refcounting is only enabled by `!DISABLE_EXCEPTION_CATCHING` in Emscripten EH now, so I guarded this on `#if !DISABLE_EXCEPTION_CATCHING || WASM_EXCEPTIONS` instead.

> Also, it might be misleading to simply call this `emval_destructors`. How about making it less generic and more sepcfic. e.g. `emval_is_exception` just stores booleans and then `decrementExceptionRefcount` is called explicitly during `_emval_decref`.

Not sure if I understand. Do you want to rename this `emval_destructors` to something else? What do you mean by `emval_is_exception` stores booleans? (Currently this is stored in `_emval_from_current_cxa_exception`, which takes a reference of an exception)

File: src/lib/libemval.js (hunk 2 above)
Comment (aheejin) [reply src/lib/libemval.js:105]: Wrapped in `#if !DISABLE_EXCEPTION_CATCHING || WASM_EXCEPTIONS` for now, because in Emscripten EH refcounting requires `!DISABLE_EXCEPTION_CATCHING`

File: src/lib/libemval.js (hunk 1 above)
Comment (aheejin) [reply src/lib/libemval.js]: I updated the PR to use `CppException` instead after #26519 and we don't check for numbers anymore: https://github.com/emscripten-core/emscripten/pull/26519/changes/1d0c0282df7d08671e0ddd6e4b1534f0006be4d4

File: system/lib/libcxxabi/src/cxa_exception_js_utils.cpp (hunk 4 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception_js_utils.cpp]: Changed to `__in/decrement_uncaught_exception`: https://github.com/emscripten-core/emscripten/pull/26519/changes/8ddb43b2bca5a70b3758ead1d78353fe90df8db9

File: src/lib/libemval.js (hunk 3 above)
Comment (sbc100) [reply src/lib/libemval.js]: Yes I think it should be called something other than `emval_destructors` since `emval_destructors` makes me (the reader) think that this is used for some kind general destructor use case.    But its only use for exceptions, so I think it should something encode that fact in its name.

File: src/lib/libexceptions.js (hunk 5 above)
Comment (sbc100) [reply src/lib/libexceptions.js]: Oh i see this is because we have JS impl for the emscripten EH case. Resolving this.

File: src/lib/libemval.js [hunk 6]
```diff
@@ -392,20 +407,50 @@ ${functionBody}
...
 #endif
   ],
   _emval_throw: (object) => {
+    var orig_object = object;
     object = Emval.toValue(object);
-#if !WASM_EXCEPTIONS && !DISABLE_EXCEPTION_CATCHING
-    // If we are throwing Emcripten C++ exception, set exceptionLast, as we do
-    // in __cxa_throw. C++ exception will be an instance of CppEmscripten.
-    if (object instanceof CppException) {
+    if (emval_is_cpp_exception(orig_object)) {
```
Comment (sbc100) [inline src/lib/libemval.js]: Maybe pass `object` to `emval_is_cpp_exception` since this is the only callsite?

Then `emval_is_cpp_exception` doesn't need to unpack it using `Emval.toValue`. 

Then maybe you can rename `emval_is_cpp_exception` to `$isCppExceptionObject`  ?   (i.e. use camel case for JS-facing APIs like this).

File: src/lib/libexceptions.js (hunk 5 above)
Comment (aheejin) [reply src/lib/libexceptions.js]: Yeah that was in the first commit but I think I deleted it by mistake while resolving conflicts. I restored them: https://github.com/emscripten-core/emscripten/pull/26519/changes/7cb05fb88d4f685dc9c6f726162f7c8b0afdf1e9

File: src/lib/libemval.js (hunk 3 above)
Comment (aheejin) [reply src/lib/libemval.js]: Changed to `emval_exception_decrefs`: https://github.com/emscripten-core/emscripten/pull/26519/changes/c808c408ac22d9a4ace798194319c790c38c00df

File: src/lib/libemval.js (hunk 6 above)
Comment (aheejin) [reply src/lib/libemval.js]: Done: https://github.com/emscripten-core/emscripten/pull/26519/changes/0139122080c037d89fa965f56ca8fcb8d9bfbf55

File: src/lib/libemval.js [hunk 7]
```diff
@@ -392,20 +409,48 @@ ${functionBody}
...
       exceptionLast = object;
-    }
 #endif
+#if !DISABLE_EXCEPTION_THROWING || WASM_EXCEPTIONS
+      incrementUncaughtExceptionCount();
+#endif
+#if !DISABLE_EXCEPTION_CATCHING || WASM_EXCEPTIONS
+      incrementExceptionRefcount(object);
+#endif
+    }
```
Comment (sbc100) [inline src/lib/libemval.js:446]: I think `isCppExceptionObject` itself and this whole block can just be wrapped in `#if !DISABLE_EXCEPTION_CATCHING && !WASM_EXCEPTIONS`

Then you can remove the `return false` from `isCppExceptionObject` since that can never happen.

Sorry to keep going back and forth on this but it seems like could simplify that code a bunch maybe?

Otherwise LGTM!

Comment (aheejin) [reply src/lib/libemval.js:446]: Nice idea! Done: https://github.com/emscripten-core/emscripten/pull/26519/commits/fa085a0bee1ca08e095ca60bb57592c362fae927 + https://github.com/emscripten-core/emscripten/pull/26519/changes/c4724dff121593b1302430a2f4f7a956f26cf1f6

File: src/lib/libexceptions.js [hunk 8]
```diff
@@ -366,6 +366,16 @@ var LibraryExceptions = {
     return ___thrown_object_from_unwind_exception(unwind_header);
   },
 
+  $incrementUncaughtExceptionCount__deps: ['__increment_uncaught_exception'],
+  $incrementUncaughtExceptionCount: () => {
```
Comment (sbc100) [inline src/lib/libexceptions.js]: These can just be single line functions I think?

```
 $incrementUncaughtExceptionCount: () =>___decrement_uncaught_exception(),
```

You might even be able to make them aliases: 

```
$incrementUncaughtExceptionCount: '__decrement_uncaught_exception',
```

Comment (aheejin) [reply src/lib/libexceptions.js]: Changed them to aliases: https://github.com/emscripten-core/emscripten/pull/26519/changes/f8c4137edb13d402176ef76683472ba9afe6510a

**Comment by aheejin** [comment]
Thanks for the review!
