### PR TITLE
[JSPI] Automatically add promising JSPI wrappers to thread entry points.

### LINKED ISSUE #22354: JSPI and pthreads shows RuntimeError - invalid suspender object for suspend
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.64 (a1fe3902bf73a3802eae0357d273d0e37ea79898)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 4d8e42ea6a89c73f90941fd1b6e899912e31dd34)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/jspanchu/dev/emsdk/upstream/bin

**Failing command line in full:**
```
emcc ./main.c -sJSPI -pthread -sPROXY_TO_PTHREAD -o index.html
```

Note that it works when I use ASYNCIFY.

```cpp
#include <emscripten/emscripten.h>
#include <stdio.h>

int main(int argc, char** argv)
{
    int counter = 0;
    while (counter < 4)
    {
        emscripten_sleep(1);
        printf("counter=%d\n", counter);
        ++counter;
    }
    printf("counter=%d\n", counter);
    return 0;
}
```

Error:
```
worker: onmessage() captured an uncaught exception: RuntimeError: invalid suspender object for suspend
index.js:364 
RuntimeError: invalid suspender object for suspend
    at index.wasm.main (index.wasm)
    at index.wasm.__main_void (index.wasm)
    at index.wasm._main_thread (index.wasm)
    at invokeEntryPoint (index.js:1734:42)
    at handleMessage (index.js:459:11)

index.js:1579 Pthread 0x000123b0 sent an error! http://localhost:8000/index.js:489: Uncaught RuntimeError: invalid suspender object for suspend
index.js:1580 Uncaught 
ErrorEvent {isTrusted: true, message: 'Uncaught RuntimeError: invalid suspender object for suspend', filename: 'http://localhost:8000/index.js', lineno: 489, colno: 7, …}
(index):195 [post-exception status] Exception thrown, see JavaScript console
index.js:489 Uncaught 
RuntimeError: invalid suspender object for suspend
    at index.wasm.main (index.wasm)
    at index.wasm.__main_void (index.wasm)
    at index.wasm._main_thread (index.wasm)
    at invokeEntryPoint (index.js:1734:42)
    at handleMessage (index.js:459:11)
```

### PR DESCRIPTION
**Pull request by brendandahl**
Use a WebAssembly.Promising wrapper on the thread entry points to allow
JSPI to be used from worker threads. The code that invokes the wrapper
also adds async/await to handle this async call to entry point.

Fixes https://github.com/emscripten-core/emscripten/issues/22354

### CODE REVIEW

File: src/runtime_pthread.js [hunk 1]
```diff
@@ -90,7 +90,7 @@ if (ENVIRONMENT_IS_PTHREAD) {
   // notified about them.
   self.onunhandledrejection = (e) => { throw e.reason || e; };
 
-  function handleMessage(e) {
+  {{{ asyncIf(ASYNCIFY == 2) }}} function handleMessage(e) {
```
Comment (sbc100) [inline src/runtime_pthread.js:93]: It seems like these fixes would apply to JSPI using in the main function of any pthread, not just the PROXY_TO_PTHREAD mode.   Is there something specific to PROXY_TO_PTHREAD here?

Comment (brendandahl) [reply src/runtime_pthread.js:93]: Yeah, it's not totally specific to PROXY_TO_PTHREAD, more it showed up as an issue there since the entry point for the main proxy is not the users actual main. 

With a user defined entry point there were ways of handling this (see core.test_pthread_join_and_asyncify). I think I can actually change that test now to not require the user to specify that the entry function is JSPI. Hower, this makes me wonder if we should automatically JSPI wrap thread entry functions or require the user to specify that they need JSPI. FWIW, we currently auto JSPI wrap main.

Comment (sbc100) [reply src/runtime_pthread.js:93]: Do an alternative solution to this one would be to auto-wrap ` _main_thread` which is used in `_emscripten_proxy_main` ?

If the clang annotation was working we could use that there?

Comment (brendandahl) [reply src/runtime_pthread.js:93]: > So an alternative solution to this one would be to auto-wrap ` _main_thread` which is used in `_emscripten_proxy_main` ?

Yeah, we'd need `EMSCRIPTEN_KEEPALIVE` or add it to `EXPORTED_FUNCTIONS` and also add it to `DEFAULT_ASYNCIFY_EXPORTS`.

> If the clang annotation was working we could use that there?

Yeah, I still need to fix binaryen to handle the annotation.

**Review by kripken — APPROVED** [review]

**Comment by brendandahl** [comment]
Per discussion in meeting, we'll auto wrap all thread entry points. I've removed my new test, but updated the original test to cover the case of suspending on them main thread too. 

(sorry for the force push, but I wanted to amend to make sure I removed all new code)

File: test/core/test_pthread_join_and_asyncify.c [hunk 2]
```diff
@@ -13,15 +13,17 @@ EM_ASYNC_JS(int, async_call, (), {
...
-EMSCRIPTEN_KEEPALIVE void *run_thread(void *args) {
+void *run_thread(void *args) {
   int ret = async_call();
   assert(ret == 42);
   return NULL;
 }
 
 int main() {
   pthread_t id;
+  // Test that JSPI works on main thread.
```
Comment (kripken) [inline test/core/test_pthread_join_and_asyncify.c:24]:
```suggestion
  // Test that JSPI works on the main thread.
```

**Review by kripken — APPROVED** [review]

**Review by sbc100 — APPROVED** [review]

**Comment by brendandahl** [comment]
Wasm64 was broken since it was trying to do `WebAssembly.promising(func)` where func was a wrapper and not the actual wasm export. I added an option to makeDynCall to add the `WebAssembly.promising` there instead.

**Review by sbc100 — APPROVED** [review]

**Review by kripken — APPROVED** [review]
