### PR TITLE
fix dynamic linking int64 exceptions

### LINKED ISSUE #21758: Int64 return functions with dynamic linking crashes on exception
When library_dylink.js creates dynamic invoke functions, they don't work with int64 return types.

This needs the fix which was done in https://github.com/emscripten-core/emscripten/pull/16233 applying to library_dylink.js also.

https://github.com/emscripten-core/emscripten/blob/main/src%2Flibrary_dylink.js#L76

I should hopefully get a chance to fix this on Monday; I need it for pyarrow.

### PR DESCRIPTION
**Pull request by joemarshall**
Currently if you dynamic link to something, and throw an exception in a function which returns int64, a javascript exception is thrown. 

This is the same bug that was fixed in #15974 but in this case the dynamic linker is creating the invoke functions in javascript, rather than it being created in advance.

Fixes #21758

### CODE REVIEW

**Comment by joemarshall** [comment]
@sbc100 If you look at the code for this, I added a one line check on exceptions thrown, as opposed to adding two function generators, one for bigint return and one for normal, as I think code size is a priority here right? I don't think there's a massive overhead given it is only in the exception thrown case anyway.

Other than that, I think this is pretty uncontroversial; it would be good to get it in soon if possible; I'll submit a patch to it in pyodide until it's in.

File: src/library_dylink.js [hunk 1]
```diff
@@ -92,6 +92,10 @@ var LibraryDylink = {
         if (e !== e+0) throw e;
 #endif
         _setThrew(1, 0);
+        // In theory this if could be done on creating the function, 
+        // but I just added this to save wasting code space
+        // and it only happens on an exception
+        if(sig[0]=="j")return BigInt(0);
```
Comment (sbc100) [inline src/library_dylink.js:98]: Can you wrap this new code in `#if WASM_BIGINT`?   Also please add a space after the `if` and before the `return`.

Also, you can just write `0n` instead of spelling out `BigInt` I believe.

Comment (joemarshall) [reply src/library_dylink.js]: Ok, done

**Comment by joemarshall** [comment]
@sbc100 I added a test for this - it was quite fiddly to force the invoke call to happen, but the test fails before the fix and works after now..

File: test/test_core.py [hunk 2]
```diff
@@ -4813,6 +4813,68 @@ def test_dylink_exceptions_try_catch_6(self):
...
+    return 0;
+}
+extern "C" int64_t side(int a,int b) {
+      // object with destructor to force invoke
+      std::string x("YAY");
+
+      should_throw=1;
+      kaboom(1,2,3);
+      return 0;
+}
```
Comment (sbc100) [inline test/test_core.py:4861]: Can you format this file like that above one? .e.g 2 space indentation and the whole file indented to match?

File: test/test_core.py [hunk 3]
```diff
@@ -4813,6 +4813,68 @@ def test_dylink_exceptions_try_catch_6(self):
...
+      #include <cstdint>
+      #include <iostream>
+      int main() {
+        void* handle = dlopen("liblib.so", RTLD_LAZY);
+        int64_t (*side)(int,int) = (int64_t (*)(int,int))dlsym(handle, "side");
+        try{
+          (side)(1,2);
+        }catch(int x){
+            std::cout << "Caught int " << x << std::endl;
+        }
```
Comment (sbc100) [inline test/test_core.py:4831]: Can you do all of the try/catch stuff in the side module and simply call the side function here?

i.e. I don't think you need to try/catch across the module boundary the reproduce this issue right?

File: test/test_core.py [hunk 4]
```diff
@@ -4813,6 +4813,68 @@ def test_dylink_exceptions_try_catch_6(self):
 
     self.do_runf("main.cpp", "side: caught int 3\n")
 
+  @with_both_eh_sjlj
+  @needs_dylink
+  def test_dylink_exceptions_try_catch_64_bit(self):
+    self.set_setting('WASM_BIGINT')
```
Comment (sbc100) [inline test/test_core.py:4819]: Can you run this test both with and without `WASM_BIGINT` enabled?

I'm actually curious to see if it works in the that case.

File: test/test_core.py [hunk 5]
```diff
@@ -4813,6 +4813,68 @@ def test_dylink_exceptions_try_catch_6(self):
...
+#include <stdio.h>
+#include <emscripten.h>
+#include <string>
+
+static volatile int should_throw = 0;
+
+int64_t kaboom(int64_t j,int k,int64_t l) {
+    if (should_throw) {
+        throw 3;
+    }
```
Comment (sbc100) [inline test/test_core.py:4851]: Does this need the global variable that the conditional throw here?

**Review by sbc100 — COMMENTED** [review]
Thanks for putting in the effort to make that test case.  It looks like it it is indeed quite hard to reproduce!

I was wondering if there are any existing test that test this feature explictly.. I'll see if I can find one.

**Comment by sbc100** [comment]
It looks like we do have some existing tests for this part of the code:

```
coer0.test_dylink_i64_invoke
coer0.test_dylink_i64_invoke_bigint
coer0.test_dylink_raii_exceptions
coer0.test_pthread_dylink_exceptions

other.test_main_module_without_exceptions_message
other.test_metadce_hello_dylink
```

At least these are the tests that fail when I disable the `createInvokeFunction` stuff.

I wonder if we can extend/update these tests to cover this corner case?  (I think `test_dylink_i64_invoke` looks like the one)

File: test/test_core.py (hunk 5 above)
Comment (joemarshall) [reply test/test_core.py]: I've simplified it loads actually now.

File: test/test_core.py (hunk 3 above)
Comment (joemarshall) [reply test/test_core.py]: yep

**Comment by joemarshall** [comment]
Ha ha, you were right. Now I know how to trigger it, it took 3 line changes to that existing test.

**Comment by joemarshall** [comment]
Incidentally, it appears empty throw statements don't always work in emscripten. I don't think that is necessarily a bad thing, as who does that... but it may be an inconsistency from standard C++ behaviour and thus another bug?

**Comment by joemarshall** [comment]
@sbc100 I updated this to main again, can we merge it now?

**Review by sbc100 — APPROVED** [review]
