### PR TITLE
Fix for resize events when building with ASSERTIONS

### LINKED ISSUE #21091: Event.detail is used even if is not set (like in the case of Resize event)
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)
clang version 18.0.0git (https://github.com/llvm/llvm-project f2464ca317bfeeedddb7cbdea3c2c8ec487890bb)
Target: wasm32-unknown-emscripten
Thread model: posix

**Build command line:**
emcc --bind --profiling -g -sASSERTIONS=2 \
-sSHARED_MEMORY \
-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 \
-L/J/FFMPEG_SRC/FFmpeg/testcpp/libs/ffmpeg/lib \
-I/J/FFMPEG_SRC/FFmpeg/testcpp/libs/ffmpeg/include \
-s EXPORTED_RUNTIME_METHODS="[FS, cwrap, ccall, getValue, setValue, writeAsciiToMemory, run]" \
-lx264 -lx265 -lvpx -lmp3lame -logg -ltheora -lvorbis -lvorbisenc -lvorbisfile -lopus -lz -lwebp -lfreetype -lfribidi -lharfbuzz -lass -lzimg -lm \
-lavcodec -lavfilter -lavformat -lavutil -lswresample -lswscale \
-Wno-deprecated-declarations \
-sWASM_BIGINT \
-sUSE_SDL=2 \
-sINITIAL_MEMORY=32MB -sALLOW_MEMORY_GROWTH \
-s USE_PTHREADS=1 -sPTHREAD_POOL_SIZE=4 -sPTHREAD_POOL_SIZE_STRICT=2 -sSTACK_OVERFLOW_CHECK=2 \
-o www/mp4info.js \
mp4info-wrapper.cpp

** The Issue **

I'm using SDL2 to output a frame to a texture.
Now it seems like emscripten checks events with Event.detail which is fine for MouseEvents and other usual events.
But if you resize the window it will trigger the function with a Event that doesn't have a detail member causing an error a detail is undefined:

** Callstack **
image

** UIEventHandlerFunc **
```js
 var uiEvent = targetThread ? _malloc(36) : JSEvents.uiEvent;
  GROWABLE_HEAP_I32()[((uiEvent) >> 2)] = e.detail; // <-------------- Another access
  checkInt32(e.detail); // <-------------- Here is the access
  GROWABLE_HEAP_I32()[(((uiEvent) + (4)) >> 2)] = b.clientWidth;
  checkInt32(b.clientWidth);
  GROWABLE_HEAP_I32()[(((uiEvent) + (8)) >> 2)] = b.clientHeight;
  checkInt32(b.clientHeight);
```

** Handler func **
```js
 var jsEventHandler = function jsEventHandler(event) {
   ++JSEvents.inEventHandler;
   JSEvents.currentEventHandler = eventHandler;
   JSEvents.runDeferredCalls();
   eventHandler.handlerFunc(event); // < ----------------------------- The error is here as the event resize doesn't have detail
   JSEvents.runDeferredCalls();
   --JSEvents.inEventHandler;
  };
  if (eventHandler.callbackfunc) {
   eventHandler.eventListenerFunc = jsEventHandler;
   eventHandler.target.addEventListener(eventHandler.eventTypeString, jsEventHandler, eventHandler.useCapture);
   JSEvents.eventHandlers.push(eventHandler);
   JSEvents.registerRemoveEventListeners();
```

### PR DESCRIPTION
**Pull request by cwoffenden**
Building with `ASSERTIONS` is failing the safe heap checks for resize events given that `e.detail` is seen as `undefined` (the specs say `UIEvent.detail` [should be zero](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail)). Seen here with the latest Emscripten 3.1.54, tested in Safari and Chrome on Mac.

detail

The resulting error is:
```
Uncaught RuntimeError: Aborted(Assertion failed: attempt to write non-integer (undefined) into integer heap)
```
It's reported specifically in #21091 which is closed in favour of #20992. This fixes #21091 which fails without SDL, just with a simple `emscripten_set_resize_callback()` and `-s ASSERTIONS`.

### CODE REVIEW

File: src/library_html5.js [hunk 1]
```diff
@@ -710,7 +710,7 @@ var LibraryHTML5 = {
       var uiEvent = JSEvents.uiEvent;
 #endif
       // e.detail is seen as undefined
-      {{{ makeSetValue('uiEvent', C_STRUCTS.EmscriptenUiEvent.detail, '((typeof e.detail !== "undefined") ? e.detail : 0), 'i32') }}};
+      {{{ makeSetValue('uiEvent', C_STRUCTS.EmscriptenUiEvent.detail, '(typeof e.detail !== "undefined") ? e.detail : 0', 'i32') }}};
```
Comment (sbc100) [inline src/library_html5.js:713]: Can this just be `e.detail || 0`?

**Comment by cwoffenden** [comment]
A simple test, which also shows issues from #20992 is to build the HTML5 test, which already tests the resize:

https://github.com/emscripten-core/emscripten/blob/7cdfa8d9f22562e7c08789a5ae29ad9a1025a8e4/test/test_html5_core.c#L261

Building with `-s ASSERTIONS=2` will assert when resizing (it also asserts for other events, which I can probably look into as I come across them).

**Review by sbc100 — COMMENTED** [review]
Thanks for the PR!

Do you think we write a test for this?

I think we have some tests that simulate events.. perhaps we could simulate and event without any detail?

File: src/library_html5.js (hunk 1 above)
Comment (cwoffenden) [reply src/library_html5.js:713]: Yes, it has the same result in the end.

**Comment by cwoffenden** [comment]
> I think we have some tests that simulate events.. perhaps we could simulate and event without any detail?

It's been a while since I've used Emscripten but I don't recall this being broken last year (we build with asserts for debug at work and it would have cropped up), or why this wouldn't be to spec.

`test_html5_core.c` does test everything with some manual intervention, showing other asserts which will need fixing. The first I see is for the orientation, which is still `-1` as it reaches here:
https://github.com/emscripten-core/emscripten/blob/7cdfa8d9f22562e7c08789a5ae29ad9a1025a8e4/src/library_html5.js#L942
Which then asserts for the `i32` test.

I guess the answer is to first see why `detail` isn't defined (which I don't mind delving into, just not today).

**Comment by sbc100** [comment]
The reason this didn't occur in older versions of emscripten is that these asserts were only added in #19251.    And that PR didn't get included in a release until 3.1.38.

**Comment by sbc100** [comment]
I wonder if we can / should simply remove this line?

It looks like the `detail` property is only set for `mousedown` and `click` UIEvents (https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) but this code is only used for `resize` and `scroll`.

**Comment by sbc100** [comment]
Indeed, it looks like we should maybe completely remove this line.  Or maybe just set it 0 in all cases.

Ideally we would even remove the field from the EmscriptenUiEvent struct, but that could break folks who are reading it for some reason.

Perhaps add a comment to the field in `html5.h` saying that this field is deprecated and will always be zero?

**Comment by sbc100** [comment]
(Can you also remove the documentation for this field from `site/source/docs/api_reference/html5.h.rst`?)

**Comment by cwoffenden** [comment]
I'll take a proper look next week. The docs do say: _For all other UIEvent objects, UIEvent.detail is always zero_, so I guess setting the struct field to zero is the best option, ignoring the `detail` completely and updating the docs to say just this. It keeps backwards compatibility and passes assertions.

**Comment by cwoffenden** [comment]
I updated the PR as per @sbc100's comments, notes as follows:

- I didn't remove `.detail` since it would probably cause breakage for people, but since the spec says zero I just set it to zero (no point even checking if the browser's event contains a `detail`).
- I updated the docs to reflect this.
- Scroll events in the same section of code are broken with `ASSERTIONS` since `pageXOffset` and `pageYOffset` are floats, and the `EmscriptenUiEvent`'s `scrollTop` and `scrollLeft` are ints. It would also probably cause breakage if these were changed from ints, so to keep the behaviour the same I truncated them (which is the same as `HEAP32[((ptr) >> 2)] = value` is doing when they're set).

The existing HTML5 test does cover both these cases.

If this an acceptable fix, I can take a look at #20992 in a week or so when I have from free time (it's the same, just requires testing).

**Review by sbc100 — APPROVED** [review]
