### PR TITLE
[FS] Fix resolvePath handling of .. up from fs mountpoint

### LINKED ISSUE #23983: Relative path lookups don't work anymore in a directory mounted with IDBFS with emscripten 3.1.74
The attached program tries to lookup some relative existing pathes with `FS.lookupPath()` (see in `pre.js`)
There are 3 directories created
```
/app
/home
/persist
```
`/app` is in MEMFS, the 2 others mounted with IDBFS.
When `FS.cwd()` is in `/home`, the lookup for `../app` fails.
This did work previously with emscripten 3.1.67, so the attached program runs without errors up to 3.1.73, but raises `console.error` since  3.1.74 . 

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 4.0.5 (53b38d0c6f9fce1b62c55a8012bc6477f7a42711)
clang version 21.0.0git (https:/github.com/llvm/llvm-project 553da9634dc4bae215e6c850d2de3186d09f9da5)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/leo/w/github/emsdk/upstream/bin
```

**Full link command and output with `-v` appended:**
```
emcc -v \
         -O2 \
         --pre-js pre.js \
         -s MAIN_MODULE=1 \
         -s FORCE_FILESYSTEM=1 \
         -s EXPORT_ALL=1 \
         -s ASSERTIONS=1 \
         -s STACK_SIZE=200000 \
         -s SAFE_HEAP \
         -s ASYNCIFY \
         -s ASYNCIFY_STACK_SIZE=200000 \
         -s MAXIMUM_MEMORY=4GB \
         -s STACK_OVERFLOW_CHECK=2 \
         -s EXIT_RUNTIME=1 \
         -s ALLOW_MEMORY_GROWTH=1 \
 -lidbfs.js \
 -lproxyfs.js \
          main.c -o main.html
/Users/leo/w/github/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fPIC -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v -O2 -c main.c -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main_0.o
clang version 21.0.0git (https:/[github.com/llvm/llvm-project](http://github.com/llvm/llvm-project) 553da9634dc4bae215e6c850d2de3186d09f9da5)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/leo/w/github/emsdk/upstream/bin
(in-process)
"/Users/leo/w/github/emsdk/upstream/bin/clang-21" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +mutable-globals -target-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/Users/leo/w/gwa/test/mountproblem -v -fcoverage-compilation-dir=/Users/leo/w/gwa/test/mountproblem -resource-dir /Users/leo/w/github/emsdk/upstream/lib/clang/21 -D EMSCRIPTEN -isysroot /Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot -I/usr/local/include -internal-isystem /Users/leo/w/github/emsdk/upstream/lib/clang/21/include -internal-isystem /Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include -O2 -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fignore-exceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main_0.o -x c main.c
clang -cc1 version 21.0.0git based upon LLVM 21.0.0git default target x86_64-apple-darwin24.3.0
ignoring nonexistent directory "/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
/usr/local/include
/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include/compat
/Users/leo/w/github/emsdk/upstream/lib/clang/21/include
/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
/Users/leo/w/github/emsdk/upstream/bin/clang --version
/Users/leo/w/github/emsdk/upstream/bin/wasm-ld -o main.wasm --whole-archive /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main_0.o -L/Users/leo/w/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic -L/Users/leo/w/github/emsdk/upstream/emscripten/src/lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets --no-whole-archive -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export-if-defined=setThrew --export-if-defined=_emscripten_stack_restore --export-if-defined=emscripten_stack_get_current --export-if-defined=calloc --export-if-defined=strerror --export-if-defined=malloc --export-if-defined=free --export-if-defined=_emscripten_stack_alloc --export-if-defined=_emscripten_tempret_get --export-if-defined=_emscripten_tempret_set --export-if-defined=htons --export-if-defined=ntohs --export-if-defined=htonl --export-if-defined=_emscripten_timeout --export-if-defined=emscripten_stack_get_base --export-if-defined=emscripten_stack_get_end --export-if-defined=__cxa_can_catch --export-if-defined=__cxa_increment_exception_refcount --export-if-defined=__cxa_get_exception_ptr --export-if-defined=__cxa_decrement_exception_refcount --export-if-defined=fileno --export-if-defined=emscripten_builtin_memalign --export-if-defined=__dl_seterr --export-if-defined=memcmp --export-if-defined=memcpy --export-if-defined=emscripten_stack_set_limits --export-if-defined=realloc --export-if-defined=__errno_location --export-if-defined=__cxa_demangle /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/tmp7h4taxczlibemscripten_js_symbols.so --import-memory --export-dynamic --export=sbrk --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_set_limits --export=_emscripten_stack_alloc --export=emscripten_get_sbrk_ptr --export=__funcs_on_exit --export=__wasm_call_ctors --export=setThrew --export=_emscripten_stack_restore --export=calloc --export=strerror --export=malloc --export=free --export=_emscripten_tempret_get --export=_emscripten_tempret_set --export=htons --export=ntohs --export=htonl --export=_emscripten_timeout --export=__cxa_can_catch --export=__cxa_increment_exception_refcount --export=__cxa_get_exception_ptr --export=__cxa_decrement_exception_refcount --export=fileno --export=emscripten_builtin_memalign --export=__dl_seterr --export=memcmp --export=memcpy --export=realloc --export=__errno_location --export=__cxa_demangle --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=__wasm_apply_data_relocs --export-if-defined=fflush --experimental-pic --unresolved-symbols=import-dynamic -pie -z stack-size=200000 --max-memory=4294967296 --initial-memory=16777216 --no-entry
/Users/leo/w/github/emsdk/upstream/bin/llvm-objcopy main.wasm main.wasm --remove-section=.debug* --remove-section=producers --remove-section=name
/Users/leo/w/github/emsdk/upstream/bin/wasm-emscripten-finalize --bigint --no-legalize-javascript-ffi --check-stack-overflow main.wasm -o main.wasm --detect-features
/Users/leo/w/github/emsdk/upstream/bin/wasm-emscripten-finalize --bigint --no-legalize-javascript-ffi --check-stack-overflow main.wasm -o main.wasm --detect-features
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/compiler.mjs -
/Users/leo/w/github/emsdk/upstream/bin/wasm-opt --strip-target-features --safe-heap --post-emscripten -O2 --low-memory-unused --asyncify --pass-arg=asyncify-relocatable --pass-arg=asyncify-asserts --pass-arg=asyncify-propagate-addlist --pass-arg=asyncify-imports@env.invoke_*,env.__asyncjs__*,*.$asyncLoad,*.fd_sync,*.emscripten_promise_await,*.emscripten_async_load_script,*.emscripten_async_wget_data,*._dlopen_js,*.emscripten_idb_load,*.emscripten_idb_store,*.emscripten_idb_delete,*.emscripten_idb_exists,*.emscripten_idb_clear,*.emscripten_idb_load_blob,*.emscripten_idb_store_blob,*.emscripten_sleep,*.emscripten_wget_data,*.emscripten_scan_registers,*.emscripten_lazy_load_code,*._load_secondary_module,*.emscripten_fiber_swap,*.SDL_Delay --zero-filled-memory --pass-arg=directize-initial-contents-immutable main.wasm -o main.wasm --mvp-features --enable-bulk-memory --enable-bulk-memory-opt --enable-call-indirect-overlong --enable-multivalue --enable-mutable-globals --enable-nontrapping-float-to-int --enable-reference-types --enable-sign-ext
/Users/leo/w/github/emsdk/upstream/bin/wasm-opt --strip-target-features --safe-heap --post-emscripten -O2 --low-memory-unused --asyncify --pass-arg=asyncify-relocatable --pass-arg=asyncify-asserts --pass-arg=asyncify-propagate-addlist --pass-arg=asyncify-imports@env.invoke_*,env.__asyncjs__*,*.$asyncLoad,*.fd_sync,*.emscripten_promise_await,*.emscripten_async_load_script,*.emscripten_async_wget_data,*._dlopen_js,*.emscripten_idb_load,*.emscripten_idb_store,*.emscripten_idb_delete,*.emscripten_idb_exists,*.emscripten_idb_clear,*.emscripten_idb_load_blob,*.emscripten_idb_store_blob,*.emscripten_sleep,*.emscripten_wget_data,*.emscripten_scan_registers,*.emscripten_lazy_load_code,*._load_secondary_module,*.emscripten_fiber_swap,*.SDL_Delay --zero-filled-memory --pass-arg=directize-initial-contents-immutable main.wasm -o main.wasm --mvp-features --enable-bulk-memory --enable-bulk-memory-opt --enable-call-indirect-overlong --enable-multivalue --enable-mutable-globals --enable-nontrapping-float-to-int --enable-reference-types --enable-sign-ext
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.js unsignPointers -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso1.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.js unsignPointers -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso1.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso1.js safeHeap -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso2.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso1.js safeHeap -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso2.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso2.js --minify-whitespace -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso3.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/acorn-optimizer.mjs /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso2.js --minify-whitespace -o /var/folders/fv/7l4yvm9d2bvbsvl80kmhp8b40000gn/T/emscripten_temp_r00d263m/main.jso3.js
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/tools/preprocessor.mjs - shell.html
/Users/leo/tmp/node/bin/node /Users/leo/w/github/emsdk/upstream/emscripten/node_modules/.bin/html-minifier-terser main.html -o main.html --collapse-whitespace --remove-comments --remove-tag-whitespace --sort-attributes --sort-class-name --decode-entities --collapse-boolean-attributes --remove-attribute-quotes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype --minify-css true --minify-js true
```

### PR DESCRIPTION
**Pull request by hoodmane**
node.parent doesn't actually give us the parent if the node is a FS root. In that case, instead of using `node.parent` we should start over from the beginning.

Resolves #23983.

### CODE REVIEW

File: src/lib/libfs.js [hunk 1]
```diff
@@ -199,7 +199,12 @@ FS.staticInit();
 
           if (parts[i] === '..') {
             current_path = PATH.dirname(current_path);
-            current = current.parent;
+            if (FS.isRoot(current)) {
+              path = current_path + '/' + parts.slice(i + 1).join('/');
```
Comment (sbc100) [inline src/lib/libfs.js:203]: If the current node is the root node can we just assume current path is `/` here and do `path = '/' + parts.slice(i + 1).join('/')`

File: src/lib/libfs.js [hunk 2]
```diff
@@ -199,7 +199,12 @@ FS.staticInit();
...
+              continue linkloop;
+            } else {
+              current = current.parent;
```
Comment (sbc100) [inline src/lib/libfs.js:206]: If `parts[i] === '..'` and the current not is the FS root shouldn't we be failing?  (Since there is no parent of the root?)

File: src/lib/libfs.js (hunk 1 above)
Comment (hoodmane) [reply src/lib/libfs.js:203]: No, because `FS.isRoot()` returns `true` if it's the root of a mount. So in the test, because we mounted NODEFS at `/working`, `FS.isRoot()` will return true when processing the `..` in the path `"/working/../other"`.

File: src/lib/libfs.js (hunk 2 above)
Comment (hoodmane) [reply src/lib/libfs.js:206]: This is not consistent with linux's stat. If a `..` is seen at the root, it is ignored:
```
$ stat /../lib
  File: /../lib -> usr/lib
  Size: 7         	Blocks: 0          IO Block: 4096   symbolic link
```

**Review by sbc100 — APPROVED** [review]

**Comment by hoodmane** [comment]
I'm still having a lot of trouble with the "Check Expectations" job...

**Comment by sbc100** [comment]
> I'm still having a lot of trouble with the "Check Expectations" job...

You did `./emsdk install tot` and `./tools/maint/rebaseline_tests.py`

**Comment by hoodmane** [comment]
Yes. I haven't sourced `emsdk_env.sh` but in `.emscripten` `LLVM_ROOT` and `BINARYEN_ROOT` point into emsdk/upstream.

**Comment by hoodmane** [comment]
Well I went ahead and manually applied the changes reported in the CI.

**Comment by kleisauke** [comment]
> I'm still having a lot of trouble with the "Check Expectations" job...

FWIW, you're not the only one. The `*.gzsize`  code sizes always cause slight differences when I run `tools/maint/rebaseline_tests.py` on my Fedora 41 workstation, likely because [zlib was replaced with zlib-ng](https://fedoraproject.org/wiki/Changes/ZlibNGTransition). :sweat_smile:

File: test/other/codesize/test_codesize_cxx_ctors1.size [hunk 3]
```diff
@@ -1 +1,2 @@
 129195
+129206
```
Comment (kleisauke) [inline test/other/codesize/test_codesize_cxx_ctors1.size:2]:
```suggestion
129206
```

File: test/other/codesize/test_codesize_cxx_ctors2.size [hunk 4]
```diff
@@ -1 +1,2 @@
 128588
+128599
```
Comment (kleisauke) [inline test/other/codesize/test_codesize_cxx_ctors2.size:2]:
```suggestion
128599
```

File: test/other/codesize/test_codesize_cxx_except_wasm.size [hunk 5]
```diff
@@ -1 +1,2 @@
 144571
+144582
```
Comment (kleisauke) [inline test/other/codesize/test_codesize_cxx_except_wasm.size:2]:
```suggestion
144582
```

File: test/other/codesize/test_codesize_cxx_except_wasm_legacy.size [hunk 6]
```diff
@@ -1 +1,2 @@
 142146
+142157
```
Comment (kleisauke) [inline test/other/codesize/test_codesize_cxx_except_wasm_legacy.size:2]:
```suggestion
142157
```

**Comment by kleisauke** [comment]
> I went ahead and manually applied the changes reported in the CI.

It looks like you need to replace the old value instead of appending the new value (i.e. there should be no newline in these files).

**Comment by hoodmane** [comment]
Oops.

**Comment by sbc100** [comment]
> Yes. I haven't sourced `emsdk_env.sh` but in `.emscripten` `LLVM_ROOT` and `BINARYEN_ROOT` point into emsdk/upstream.

That should be enough, yes.  As long as `emsdk/upstream` matches `emsdk install tot`.   You can also check that the version of the SDK that `emsdk install tot` installs for you locally matches the one that is used in the CI.

For example, it should say something like `Installing SDK 'sdk-releases-5f2af795eae65fbcb0ebf4c5f1b460fe288f05c9-64bit'..`

If you cannot get your local results to match that is certainly worth investigating and fixing.

@kleisauke for the zlib issues is there an open ticket?   I wonder how we could fix it?  We use python's `with gzip.open(f_gz, 'wb') as gzf: ` to generate those file?  Perhaps we could switch to something else?

**Comment by kleisauke** [comment]
> @kleisauke for the zlib issues is there an open ticket? I wonder how we could fix it? We use python's `with gzip.open(f_gz, 'wb') as gzf: ` to generate those file? Perhaps we could switch to something else?

I still need to open an issue for this. The solution is unclear as gzip compressed data may not be bit-identical across different zlib versions (see also https://github.com/zlib-ng/zlib-ng/discussions/905). Commit https://github.com/emscripten-core/emscripten/pull/23998/commits/995c887f02f439c8f04e067b1b1903c36177fea7 (in PR #23998) demonstrates this.

**Comment by sbc100** [comment]
> > @kleisauke for the zlib issues is there an open ticket? I wonder how we could fix it? We use python's `with gzip.open(f_gz, 'wb') as gzf: ` to generate those file? Perhaps we could switch to something else?
> 
> I still need to open an issue for this. The solution is unclear as gzip compressed data may not be bit-identical across different zlib versions (see also [zlib-ng/zlib-ng#905](https://github.com/zlib-ng/zlib-ng/discussions/905)). Commit [995c887](https://github.com/emscripten-core/emscripten/commit/995c887f02f439c8f04e067b1b1903c36177fea7) (in PR #23998) demonstrates this.

Mabye we ship our own zip implementation as a wasm file :)

**Comment by hoodmane** [comment]
Now the failure says: 
```
code_size/random_printf_wasm.json: 12494 => 12494 [+0 bytes / +0.00%]
code_size/random_printf_wasm2js.json: 17262 => 17262 [+0 bytes / +0.00%]
```

**Comment by sbc100** [comment]
> Now the failure says:
> 
> ```
> code_size/random_printf_wasm.json: 12494 => 12494 [+0 bytes / +0.00%]
> code_size/random_printf_wasm2js.json: 17262 => 17262 [+0 bytes / +0.00%]
> ```

Oh I think the report generator doesn't know how to parse the those json files.  Thats a bug in the script.  If you look further up the output for test_random_printf_wasm you should see an actual difference I think.

**Comment by sbc100** [comment]
I think maybe the first thing to do is switch back the upstream main branch and try to confirm that you can replicate the current results.

i.e. can you run those tests and see no changes?   Since we know that the main branch if up-to-date at this point, if you cannot replicate the results then there must be something up with your config.

Can you perhaps try with `export EM_CONFIG=/path/to/emsdk/.emscripten`?      That is how I recommend configuring emscripten to use emsdk binaries.

**Comment by hoodmane** [comment]
It seems as if `export EM_CONFIG=/path/to/emsdk/.emscripten` may have helped.

**Comment by sbc100** [comment]
> It seems as if `export EM_CONFIG=/path/to/emsdk/.emscripten` may have helped.

Perhaps the version of node is also important?  I guess it depends what else is in your local `.emscripten`?

**Comment by kleisauke** [comment]
FWIW, I worked around that zlib issue with this Dockerfile:

<details>
  <summary>Details</summary>

```Dockerfile
# Build and run with:
# docker build -t emscripten --build-arg EMSDK_VERSION=$(cat test/emsdk_version.txt) .
# docker run -v ${PWD}:/src -v ~/.gitconfig:/root/.gitconfig emscripten
FROM docker.io/library/ubuntu:24.04

# Install needed dependencies
RUN \
  apt-get update -qq && \
  apt-get install -qqy --no-install-recommends \
    ca-certificates \
    curl \
    git \
    python3 \
    python3-psutil \
    xz-utils \
    && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/* 

WORKDIR /opt

ARG EMSDK_VERSION=tot

# Install emsdk
ENV EM_CONFIG=/opt/emsdk/.emscripten
RUN \
  git clone https://github.com/emscripten-core/emsdk.git emsdk && \
  cd emsdk && \
  ./emsdk install $EMSDK_VERSION && \
  ./emsdk activate $EMSDK_VERSION && \
  echo "JS_ENGINES = [NODE_JS]" >> $EM_CONFIG

# The emscripten dir is mounted here
WORKDIR /src

CMD ["./tools/maint/rebaseline_tests.py"]
```
</details>

**Comment by sbc100** [comment]
> FWIW, I worked around that zlib issue with this Dockerfile:
> 
> Details
> ```dockerfile
> # Build and run with:
> # docker build -t emscripten --build-arg CACHEBUST=$(date +%s) .
> # docker run -v ${PWD}:/src -v ~/.gitconfig:/root/.gitconfig emscripten
> FROM docker.io/library/ubuntu:24.04
> 
> # Install needed dependencies
> RUN \
>   apt-get update -qq && \
>   apt-get install -qqy --no-install-recommends \
>     ca-certificates \
>     curl \
>     git \
>     python3 \
>     xz-utils \
>     && \
>   apt-get clean -y && \
>   rm -rf /var/lib/apt/lists/* 
> 
> WORKDIR /opt
> 
> ARG CACHEBUST=1
> 
> # Install emsdk tip-of-tree
> ENV EM_CONFIG=/opt/emsdk/.emscripten
> RUN \
>   git clone https://github.com/emscripten-core/emsdk.git emsdk && \
>   cd emsdk && \
>   ./emsdk install tot && \
>   ./emsdk activate tot && \
>   echo "JS_ENGINES = [NODE_JS]" >> $EM_CONFIG
> 
> # The emscripten dir is mounted here
> WORKDIR /src
> 
> CMD ["./tools/maint/rebaseline_tests.py"]
> ```

OGM!   Impressive solution.
