### PR TITLE
[WasmFS] Support case-insensitive paths

### LINKED ISSUE #17079: WasmFS should support case insensitive file paths
The  flag `-s CASE_INSENSITIVE_FS=1` doesn't seem to  work with WasmFS.

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/src/emsdk/upstream/bin`

**Failing code:**
```cpp
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <ctype.h>

int main()
{
    char fileName[] = "Test.txt";
    FILE *fp1 = fopen(fileName, "wt");
    assert(fp1);
    printf("Writing to '%s'...\n", fileName);
    fputs("test", fp1);
    fclose(fp1);

    fileName[0] = tolower(fileName[0]);  // make file path lower case
    FILE *fp2 = fopen(fileName, "rt");
    assert(fp2);
    char buffer[10] = {};
    assert(fgets(buffer, sizeof(buffer), fp2) != nullptr);
    printf("Read '%s' from '%s'\n", buffer, fileName);
    assert(strcmp(buffer, "test") == 0);
    fclose(fp2);
    return 0;
}

```

**Full link command and output with `-v` appended:**
Build command:
```bash
emsdk install latest && emsdk activate latest
rm -rf build
mkdir -p build
cd build
em++ -v ../fs_case.cpp -s CASE_INSENSITIVE_FS=1 -s WASMFS=1 -o a.html
emrun a.html
cd ..
```
Program output:
```
Writing to 'Test.txt'...
a.js:1451 Aborted(Assertion failed: fp2, at: ../fs_case.cpp,17,main)
abort @ a.js:1451
a.js:34 Uncaught RuntimeError: Aborted(Assertion failed: fp2, at: ../fs_case.cpp,17,main)
    at abort (a.js:1466:11)
    at ___assert_fail (a.js:1800:7)
    at a.wasm:0x86f
    at a.wasm:0x9a1
    at a.js:1510:22
    at callMain (a.js:2366:15)
    at doRun (a.js:2423:23)
    at a.js:2434:7
```

### PR DESCRIPTION
**Pull request by mere-human**
Create a class path_string that represents the file path.
It holds a string and defines different comparison operators depending on
WASMFS_CASE_INSENSITIVE macro.
The macro is defined only if CASE_INSENSITIVE_FS setting is enabled.
Add a test case which checks case-insensitive path behavior in default JS FS and
WasmFS.

Fix #17079

### CODE REVIEW

File: system/lib/wasmfs/file.h [hunk 1]
```diff
@@ -20,6 +20,43 @@
 
 namespace wasmfs {
 
+class path_string {
+  std::string path;
+
+public:
+  path_string() = default;
+  path_string(const std::string& p) : path(p) {}
```
Comment (mere-human) [inline system/lib/wasmfs/file.h:28]: Should this be `explicit`?

File: tools/system_libs.py [hunk 2]
```diff
@@ -1545,6 +1545,12 @@ class libwasmfs(DebugLibrary, AsanInstrumentedLibrary, MTLibrary):
 
   includes = ['system/lib/wasmfs', 'system/lib/pthread']
 
+  def get_cflags(self):
```
Comment (mere-human) [inline tools/system_libs.py:1548]: Should this be using `variations`?

File: system/lib/wasmfs/syscalls.cpp [hunk 3]
```diff
@@ -878,8 +878,8 @@ int __syscall_getdents64(int fd, intptr_t dirp, size_t count) {
         result->d_type = DT_UNKNOWN;
         break;
     }
-    assert(entry.name.size() + 1 <= sizeof(result->d_name));
-    strcpy(result->d_name, entry.name.c_str());
+    assert(entry.name.str().size() + 1 <= sizeof(result->d_name));
+    strcpy(result->d_name, entry.name.str().c_str());
```
Comment (tlively) [inline system/lib/wasmfs/syscalls.cpp:882]: It would be good to implement `size` and `c_str` as helper methods on `path_string`.

File: test/test_browser.py [hunk 4]
```diff
@@ -5316,6 +5316,14 @@ def test_wasmfs_opfs(self):
     self.btest_exit(test, args=args + ['-DWASMFS_SETUP'])
     self.btest_exit(test, args=args + ['-DWASMFS_RESUME'])
 
+  @parameterized({
+    'default': (['-sCASE_INSENSITIVE_FS=1'],),
+    'wasmfs': (['-sWASMFS', '-sCASE_INSENSITIVE_FS=1', '-DWASMFS'],),
+  })
+  def test_path_icase(self, args):
```
[the remark this answers is not in the document]
Comment (tlively) [reply test/test_browser.py:5323]: All the changes are in backend-independent code, so it should be fine to just test the in-memory backend. It would be good to add more testing for things like opening the same file multiple times with different capitalizations.

File: system/lib/wasmfs/file.h (hunk 1 above)
Comment (tlively) [reply system/lib/wasmfs/file.h:28]: I don't mind keeping it implicit.

File: system/lib/wasmfs/file.h [hunk 5]
```diff
@@ -20,6 +20,43 @@
...
+  path_string(const char* p) : path(p) {}
+  const std::string& str() const { return path; }
+};
+
+inline bool operator==(const path_string& x, const path_string& y) {
```
Comment (tlively) [inline system/lib/wasmfs/file.h:33]: I would implement these as methods rather than separate inline functions.

File: system/lib/wasmfs/file.h [hunk 6]
```diff
@@ -20,6 +20,43 @@
...
+#ifdef WASMFS_CASE_INSENSITIVE
+  return strcasecmp(x.str().c_str(), y.str().c_str()) < 0;
+#else
+  return x.str() < y.str();
+#endif
+}
+
+inline bool operator>(const path_string& x, const path_string& y) {
+  return y < x;
+}
```
Comment (tlively) [inline system/lib/wasmfs/file.h:58]: Do we need this operator? I would have thought that `operator<` would be enough for the dcache map.

File: system/lib/wasmfs/file.h [hunk 7]
```diff
@@ -20,6 +20,43 @@
 
 namespace wasmfs {
 
+class path_string {
```
Comment (tlively) [inline system/lib/wasmfs/file.h:23]: Let's name this `PathString` to match the convention of using PascalCase for user types. It would also be good to add a comment explaining that it exists solely to support case insensitivity.

File: system/lib/wasmfs/memory_backend.h [hunk 8]
```diff
@@ -44,18 +44,19 @@ class MemoryFile : public DataFile {
 class MemoryDirectory : public Directory {
   // Use a vector instead of a map to save code size.
   struct ChildEntry {
-    std::string name;
+    path_string name;
```
Comment (tlively) [inline system/lib/wasmfs/memory_backend.h:47]: Would it be possible to keep using `std::string` here and keep the use of `path_string` to the target-independent code only?

**Review by tlively — COMMENTED** [review]
Nice! Just a few comments.

File: system/lib/wasmfs/file.h (hunk 6 above)
Comment (mere-human) [reply system/lib/wasmfs/file.h:58]: I added it to mirror `operator<`. But I agree, we don't need it.

File: system/lib/wasmfs/file.h (hunk 5 above)
Comment (mere-human) [reply system/lib/wasmfs/file.h:33]: I decided to make it non-member because it's a symmetrical operator.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c161-use-non-member-functions-for-symmetric-operators
But I can make them members. I think it doesn't matter since both operands have the same type.

File: test/test_browser.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (mere-human) [reply test/test_browser.py:5323]: I think fetch backend is already case-insensitive. Because URLs are case-insensitive.

But what about other backends, such as node backend? I don't know. It seems for Node.js, it depends on the host platform FS. And using `-sCASE_INSENSITIVE-FS` for Node.js with case sensitive FS makes little sense.
https://nodejs.org/en/docs/guides/working-with-different-filesystems/

Anyway, if there will be some problems, they can be fixed separately.

File: system/lib/wasmfs/memory_backend.h (hunk 8 above)
Comment (mere-human) [reply system/lib/wasmfs/memory_backend.h:47]: If `std::string` is used in `ChildEntry` some operations such as `unlink()` won't work correctly.
For example, this line in test will not delete anything:
https://github.com/emscripten-core/emscripten/blob/1d568bcbfcc4818d554d3269f0a742078c2c96a6/test/test_path_icase.c#L93
And the subsequent check that the `subdir` is empty will fail:
` Aborted(Assertion failed: get_dir_files("subdir") == 0, at: emscripten/test/test_path_icase.c,99,main)`

File: test/test_browser.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (tlively) [reply test/test_browser.py:5323]: Hmm, it seems that doing the totally correct thing on Node would involve detecting case sensitivity at runtime on a per-directory basis. Otherwise when running in case-sensitive mode on top of a case-insensitive file system, it would be possible to get multiple file handles to the same underlying file, and when running in case-insensitive mode on top of a case-sensitive file system, there could be files that couldn't be opened. A simpler fix might be to keep only mounted directories in the dcache for node directories and have the node backend handle all name resolution and manage `File` identity.

But handling node case sensitivity correctly is a little different from your use case here, right? Getting node right is about matching the underlying file system behavior, but what you're trying to do is update WasmFS to provide a case-insensitive interface so that applications above it that expect case insensitivity still work.

What do you expect should happen if there are two IDBFS files `foo.txt` and `FOO.TXT` and WasmFS is started in case-insensitive mode? Or should that never happen?

File: system/lib/wasmfs/memory_backend.h (hunk 8 above)
Comment (tlively) [reply system/lib/wasmfs/memory_backend.h]: Would it be acceptable behavior for WasmFS to normalize all filenames to be all lowercase (or all uppercase) when in case-insensitive mode? That way we could have the backend-independent code perform normalization and backends wouldn't have to think about it.

Actually, if we can do that, then maybe we could even implement case-insensitivity via a virtual backend that performs case normalization before forwarding operations to another backend. That way neither the core code nor the other backends would have to think about case insensitivity! (Except for the node backend, as discussed in that other comment)

File: test/test_browser.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (mere-human) [reply test/test_browser.py:5323]: > Hmm, it seems that doing the totally correct thing on Node would involve detecting case sensitivity at runtime on a per-directory basis.

I think adding a check at the time the backend is mounted should be enough.

> A simpler fix might be to keep only mounted directories in the dcache for node directories and have the node backend handle all name resolution and manage File identity.

Does it work differently now? Sorry, I haven't used node backend yet.

> But handling node case sensitivity correctly is a little different from your use case here, right? 
> but what you're trying to do is update WasmFS to provide a case-insensitive interface so that applications above it that expect case insensitivity still work.

That's right.

> What do you expect should happen if there are two IDBFS files foo.txt and FOO.TXT and WasmFS is started in case-insensitive mode?

If IDBFS mounts all the keys it has in the DB, then I'd expect it should mount the first file `foo.txt` and then it should ignore the second file `FOO.TXT` because such file node already exists.

File: system/lib/wasmfs/memory_backend.h (hunk 8 above)
Comment (mere-human) [reply system/lib/wasmfs/memory_backend.h]: > Would it be acceptable behavior for WasmFS to normalize all filenames to be all lowercase (or all uppercase) when in case-insensitive mode?

I think it's fine and could save some work. 
But wouldn't that make such calls as `FS.readdir('.')` return only lower-case files?

Comment (tlively) [reply system/lib/wasmfs/memory_backend.h]: Yes, `FS.readdir` would only return lowercase files if we did that and your example would return false. Maybe this would cause too many problems to be worth it.

**Comment by tlively** [comment]
Ok I think I'm convinced that adding this new string type to the core system and backends that need it is the best solution. Can you 1) move `PathString` to a new header so it can be included independently by things that need it, and 2) move the test to test_other.py rather than test_browser.py to make it faster and easier to run? Also, any additional testing you think would be helpful would be great. Other than that, LGTM!

**Comment by mere-human** [comment]
> Also, any additional testing you think would be helpful would be great.

I've added a test for the case when we use the result of `readdir()` for file comparison to ensure the file case is preserved.

Should I add tests for WasmFS backends using `wasmfs_all_backends`?

**Comment by mere-human** [comment]
I have an experimental custom IndexedDB backend implementation.
It is implemented using the same concepts as Node backend.
It has an internal buffer of file data. When reading it calls `emscripten_idb_async_load()` and when writing it calls `emscripten_idb_async_store()` via proxying.

The test case from this PR passes successfully.
Also, I tried this test (pseudocode):
```cpp
IDBStoreData("foo.txt", ...);
IDBStoreData("FOO.TXT", ...);
GetIDBKeys(); // { L"FOO.TXT", L"foo.txt", ...}
IDBSync(...);
GetFolderFiles(); // { L"FOO.TXT", ... }
```
So it works like I expected. Second file overwrites the first one.

The only problem I observed was that after moving a file, `rename("tesT.Txt", "test2.txt")` IndexedDB contains "test.txt" while FS reports that "test.txt" doesn't exist and "test2.txt" exists.
I think this is expected, because my implementation inherits from `MemoryDirectory` and doesn't override `insertMove()`.
Maybe, there are more similar problem, but I haven't' found them yet.

In general, it seems like each backend should handle the case sensitivity at some basic level. So a new bug/PR could be created to address that.

**Comment by tlively** [comment]
@mere-human, I'd really like to avoid creating any burden that backend authors would have to reason about, and thinking more about how case preservation would work, it seems like it really would be a nontrivial amount of work in each of the OPFS backend, IndexedDB backend, and any other persistent backend.

It looks like the legacy Emscripten file system does not have case preservation. Instead, it just normalizes all user input to lowercase before doing anything else. I think the best thing to do here would be to try to match that simpler behavior in the legacy FS, despite the issues you pointed out above.

One solution would be to modify just the core system with #ifdefs similar to what this PR currently does, but an even better solution would be to add a virtual backend that normalizes all path names and otherwise just forwards operations and results to and from another backend. The user-facing API for such a virtual backend should be similar to `wasmfs_create_proxied_backend`. The advantage of using a virtual backend for this is that there would be no need to have two separate builds of libwasmfs, and we wouldn't even need a link time flag.

**Comment by mere-human** [comment]
> I'd really like to avoid creating any burden that backend authors would have to reason about, and thinking more about how case preservation would work

In theory, all they have to do is to use the `PathString` class for storing paths. Is that acceptable? We can try to use it more widespread in FS code.

> I think the best thing to do here would be to try to match that simpler behavior in the legacy FS, despite the issues you pointed out above.

I understand the idea behind the virtual backend. Do you think case-insensitive paths should still be implemented that way even if the original case is not preserved?

**Comment by mere-human** [comment]
>  The user-facing API for such a virtual backend should be similar to wasmfs_create_proxied_backend.

**Comment by tlively** [comment]
> @tlively
> 
> > I'd really like to avoid creating any burden that backend authors would have to reason about, and thinking more about how case preservation would work
> 
> In theory, all they have to do is to use the `PathString` class for storing paths. Is that acceptable? We can try to use it more widespread in FS code.

Unfortunately it's more complicated than that. Persistent backends like OPFS and IDBFs could use `PathString` for the in-memory part, but they would still have to find the corresponding file in the underlying case-sensitive storage API, which would require listing the parent directory and scanning through its contents at every step of a path traversal. This is a lot of extra logic and for some backends can be less efficient than doing a direct lookup of the child.

> > I think the best thing to do here would be to try to match that simpler behavior in the legacy FS, despite the issues you pointed out above.
> 
> I understand the idea behind the virtual backend. Do you think case-insensitive paths should still be implemented that way even if the original case is not preserved? Or should I try implementing case preservation via the virtual backend?

I would start by just doing the case normalization without trying to implement any case preservation. AFAICT, implementing case preservation correctly in a way that works with persistent backends like OPFS and IndexedDB would require saving the non-normalized file names in some sort of extra metadata file and that sounds more complicated than necessary to start out.

**Comment by tlively** [comment]
> > The user-facing API for such a virtual backend should be similar to wasmfs_create_proxied_backend.
> 
> How will it work if I need case-insensitive paths for all backends, even for memory backend (files under root directory)?

The downside of using a virtual backend for this is that it won't work for builtin files like `/dev/null` or any other direct children of the root directory, but you should be able to mount new in-memory backends in combination with the case-insensitive virtual backend.

If that's not a complete enough solution, we could use the `CASE_INSENSITIVE_FS` flag to install the case-insensitive virtual backend by on the root directory by default.

**Comment by mere-human** [comment]
> an even better solution would be to add a virtual backend that normalizes all path names and otherwise just forwards operations and results to and from another backend

@tlively  So I was trying to implement an `IgnoreCaseBackend`. The main logic would be in directory subclass unlike `ProxiedAsyncJSBackend` and `ProxiedBackend` where it's in file subclass.

There is a method `Directory::insertDirectory()`. It accepts a directory name as a parameter. There are several ways to implement ignore case here.

1. Forward insertDirectory() call to underlying directory object.
Problem: Underlying directory will cache a child directory of wrong type which will not ignore case.

2. Create an underlying child directory object using `Backend::createDirectory()`, pass it to a
constructor of a child ignore-case directory object and cache it in `dcache` of ignore-case parent. 
Problem: If underlying backend has different implementation for `Backend::insertDirectory()` and `Directory::insertDirectory()` the latter would not be called. This is the case for `FetchBackend`, `NodeBackend`, etc.

Considering that, I will try to implement case normalization using #ifdefs in common code e.g. `doMkdir()`. However, it would be good to concentrate ignore-case logic in one place. But it seems spread between files in JS filesystem implementation as well.

**Comment by tlively** [comment]
I think what we need to do is pretty close to what you described in (1).

The virtual `CaseInsensitive` backend should normalize the case then call `insertDirectory` on the underlying directory object. That underlying directory caches the child using the normalized name, which is what we want. Then we wrap that newly inserted and returned underlying directory with a new `CaseInsensitiveDirectory` object and return it back up to the core system. I think the creation of that new `CaseInsensitiveDirectory` wrapper is what you were missing.

But we still have a problem. Consider what happens when we create "parent/Foo/" and then try to open "parent/FOO/".

 - After creating "parent/Foo/":
     - parent outer dcache: "Foo" -> CaseInsensitive(foo)
     - parent inner dcache: "foo" -> foo

- After opening "parent/FOO/":
    - parent outer dcache: "Foo" -> CaseInsensitive(foo), "FOO" -> CaseInsensitive(foo)
    - parent inner dcache: "foo" -> foo

There are a couple things to note here: First of all, our virtual backend needs to return the same instance of `CaseInsensitive(foo)` whether it's looked up by "Foo", "FOO", or any other capitalization, since the file identity is the same. That means it needs to maintain a 1:1 mapping between underlying files and their wrappers. Second, it's not great that we're littering the outer dcache with multiple entries for the same file foo. In particular, if you try to delete one of them (e.g "FOO"), the others (e.g. "Foo") will not be cleared from the outer dcache and you'll end up with what would essentially be dangling references in the dcache. Not good!

I think the best solution to this would be to provide backends the ability to opt out of using the dcache if they promise to internally maintain the 1:1 mapping between `File` objects and underlying files. All the in-memory backends could also opt out since their files already naturally correspond to in-memory `File` objects 1:1.

I can upload a separate PR that adds that opt-out mechanism on Monday so you can build on top of it. In the meantime, you can keep trying to get everything besides file deletion working via a virtual backend.

**Comment by mere-human** [comment]
I think I got the gist of this idea. 

> That underlying directory caches the child using the normalized name, which is what we want. Then we wrap that newly inserted and returned underlying directory with a new CaseInsensitiveDirectory object and return it back up to the core system. 

It could cause more problems. For example, how to avoid duplicates in `Directory::Handle::getEntries()`?

I have another idea of backend-agnostic case-insensitive implementation. We can do the normalization in the `Directory::Handle` since it's the interface between a sys call (which provides mixed case name) and a directory object (which needs normalized name).
This way we can keep backends from knowing about case-sensitivity and avoid more work.

File: system/lib/wasmfs/file.cpp [hunk 9]
```diff
@@ -40,44 +40,51 @@ void DataFile::Handle::preloadFromJS(int index) {
 // Directory
 //
 
-void Directory::Handle::cacheChild(const std::string& name,
+void Directory::Handle::cacheChild(const PathString& name,
```
Comment (mere-human) [inline system/lib/wasmfs/file.cpp:43]: Using the `PathString` in each method is not strictly necessary. But I find it easier to enforce which name to use.

File: system/lib/wasmfs/file.h [hunk 10]
```diff
@@ -177,6 +178,9 @@ class Directory : public File {
   struct DCacheEntry {
     DCacheKind kind;
     std::shared_ptr<File> file;
+#ifdef WASMFS_CASE_INSENSITIVE
+    std::string originalName;  // Used for case preservation.
```
Comment (mere-human) [inline system/lib/wasmfs/file.h:182]: Case preservation is limited by in-memory cache and can be removed if it looks bad. But for me this looks better than nothing.

**Comment by mere-human** [comment]
There are 5 failed pthread tests. Seems unrelated to my changes.
`FAIL: test_pthread_run_on_main_thread (test_browser.browser)`
https://app.circleci.com/pipelines/github/emscripten-core/emscripten/23240/workflows/440759d9-02e4-45d0-8de7-a8c2efd0bc4d/jobs/562609?invite=true#step-109-1714

**Comment by tlively** [comment]
> I think I got the gist of this idea.
> 
> > That underlying directory caches the child using the normalized name, which is what we want. Then we wrap that newly inserted and returned underlying directory with a new CaseInsensitiveDirectory object and return it back up to the core system.
> 
> It could cause more problems. For example, how to avoid duplicates in `Directory::Handle::getEntries()`?

This has to be solved either way, since the underlying case-sensitive backend might come pre-populated with duplicate entries with different capitalizations. 

> I have another idea of backend-agnostic case-insensitive implementation. We can do the normalization in the `Directory::Handle` since it's the interface between a sys call (which provides mixed case name) and a directory object (which needs normalized name). This way we can keep backends from knowing about case-sensitivity and avoid more work.

This is a good idea if the virtual backend doesn't work out. Even though getting the virtual backend to work is complicated because it requires opting out of using the dcache, I realized that solving the similar problem of correctly handling case-insensitive underlying file systems in the node backend requires that same opt-out mechanism. Since we need to be able to opt out of using the dcache anyway, it makes sense to use that as part of a virtual backend solution here.

You can see the PR for the opt-out mechanism here: https://github.com/emscripten-core/emscripten/pull/17754

**Comment by mere-human** [comment]
> Since we need to be able to opt out of using the dcache anyway, it makes sense to use that as part of a virtual backend solution here.
> 
> You can see the PR for the opt-out mechanism here: #17754

Ok, should I wait until the "dcache opt-out" is merged? Or try to rebase on top of that?

**Comment by tlively** [comment]
@mere-human, I think the best thing to do would be to rebase and change the target branch of this PR to `wamsfs-dcache-opt-out`, which would let you build on top of that PR before it is merged but still only have the diff for this further change in this PR.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+  std::shared_ptr<DataFile> createFile(mode_t mode) override {
+    return backend->createFile(mode);
+  }
+
+  std::shared_ptr<Directory> createDirectory(mode_t mode) override {
+    return std::make_shared<IgnoreCaseDirectory>(backend->createDirectory(mode),
+                                                 this);
+  }
+
+  std::shared_ptr<Symlink> createSymlink(std::string target) override {
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:112]: There is no way to create a symlink directly from a backend. Only through `Directory::insertSymlink()`.

File: test/other/test_fs_icase.cpp [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+  // Check parent directory contents.
+  auto contents = readdir(".");
+  assert(contents.size() == 2);
+  assert(std::find(contents.begin(), contents.end(), "test2.txt") !=
+         contents.end());
+#ifdef WASMFS
+  assert(std::find(contents.begin(), contents.end(), "subdir") !=
+         contents.end());
+#else
+  assert(std::find(contents.begin(), contents.end(), "Subdir") !=
```
Comment (mere-human) [inline test/other/test_fs_icase.cpp:101]: It seems test_other and test_browser have a slightly different behavior. Because, if I make this test to run in browser, this assert fails:
`+/report_result?abort:Assertion failed: std::find(contents.begin(), contents.end(), "Subdir") != contents.end(), at: .../emscripten/test/other/test_fs_icase.cpp,102,main`

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+    auto child = baseDirectory->insertSymlink(name2, target);
+    insertChild(name2, child);
+    return child;
+  }
+
+  int insertMove(const std::string& name, std::shared_ptr<File> file) override {
+    return BaseClass::insertMove(normalize(name), file);
+  }
+
+  bool removeChild(const std::string& name) override {
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:74]: Found a problem: `Directory::Handle::removeChild()` doesn't call `maintainsFileIdentity()` and `setParent()`: https://github.com/emscripten-core/emscripten/blob/main/system/lib/wasmfs/file.cpp#L195
For backends which maintain file identity, there would be no entry in `dcache` so no parent reset would happen.
Is this a bug?

**Comment by mere-human** [comment]
So, I implemented a virtual ignore case backend with "dcache opt-out". But it looks fragile. Also, there is a problem that a file is duplicated both in underlying backend and in the virtual backend itself. This probably could be solved if it doesn't inherit from MemoryDirectory.
Also, original case is not preserved which is desirable but would require more hard work.

File: system/lib/wasmfs/wasmfs.cpp [hunk 14]
```diff
@@ -67,9 +75,14 @@ WasmFS::~WasmFS() {
...
 std::shared_ptr<Directory> WasmFS::initRootDirectory() {
+  
+#ifdef WASMFS_CASE_INSENSITIVE
+  auto rootBackend = wasmfs_create_icase_backend(make_mem_backend, nullptr);
+#else
   auto rootBackend = createMemoryFileBackend();
-  auto rootDirectory =
-    std::make_shared<MemoryDirectory>(S_IRUGO | S_IXUGO | S_IWUGO, rootBackend);
+#endif
+  auto rootDirectory = reinterpret_cast<wasmfs::Backend*>(rootBackend)
```
Comment (tlively) [inline system/lib/wasmfs/wasmfs.cpp:84]: There shouldn't be any need for the `reinterpret_cast` here.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+    insertChild(name2, child);
+    return child;
+  }
+
+  std::shared_ptr<Directory> insertDirectory(const std::string& name,
+                                             mode_t mode) override {
+    auto name2 = normalize(name);
+    auto baseChild = baseDirectory->insertDirectory(name2, mode);
+    auto child = std::make_shared<IgnoreCaseDirectory>(baseChild, getBackend());
+    insertChild(name2, std::static_pointer_cast<File>(child));
```
Comment (tlively) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:58]: There shouldn't be any need for `std::static_pointer_cast` here.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 11 above)
Comment (tlively) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:112]: The `create*` methods on backends are mostly for creating new backend roots to mount onto other backends. We might want to consider removing `createFile` and only supporting `createDirectory` so that only directories can be backend roots. That's more similar to how native file systems work. On the other hand, if we do want to keep `createFile`, it probably makes sense to add `createSymlink` as well.

Comment (mere-human) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:112]: Ok, I see, so `createSymlink` is just for parity with `createFile`.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+    auto name2 = normalize(name);
+    BaseClass::removeChild(name2);
+    return baseDirectory->removeChild(name2);
+  }
+
+  size_t getNumEntries() override { return BaseClass::getNumEntries(); }
+
+  // TODO: preserve original name, denormalize, and use it here
+  std::vector<Directory::Entry> getEntries() override {
+    return BaseClass::getEntries();
```
[the remark this answers is not in the document]
Comment (mere-human) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:84]: Ok, I agree.
I thought that maybe `IgnoreCaseDirectory` shouldn't inherit from `MemoryDirectory` at all. But in that case there would be some code duplication.

File: test/other/test_fs_icase.cpp (hunk 12 above)
Comment (mere-human) [reply test/other/test_fs_icase.cpp:101]: Turns out, I was just running with default JS filesystem in browser. So it's slightly different from what I originally thought.
But anyway, JS filesystem returns original names preserving cases which can be seen in this tests (`ifdef WASMFS`).

File: system/lib/wasmfs/file.cpp [hunk 17]
```diff
@@ -223,6 +235,20 @@ std::vector<Directory::Entry> Directory::Handle::getEntries() {
       entries.push_back({name, entry.file->kind, entry.file->getIno()});
     }
   }
+
+#ifdef WASMFS_CASE_INSENSITIVE
+  // Restore the original name of the entries (case preservation).
```
[the remark this answers is not in the document]
Comment (mere-human) [reply system/lib/wasmfs/file.cpp]: Which option do you think is the best: normalizing in `Directory::Handle` or in a virtual backend?
Personally, I find virtual backend implementation more problematic since it's hard to maintain both backend directory entries and underlying directory entries. But maybe, it's only because it inherits from `MemoryDirectory`.
The version which uses `Directory::Handle` got deleted from this PR. But it's available here https://github.com/emscripten-core/emscripten/commit/1714fd76a6dd9a51d8340c9565e0af4cf547ec1e

File: system/lib/wasmfs/wasmfs.cpp (hunk 14 above)
Comment (mere-human) [reply system/lib/wasmfs/wasmfs.cpp:84]: We need it because the declaration of `wasmfs_create_icase_backend()` refers to `backend_t` which are both under `extern "C"`:

```
wasmfs.cpp:76:35: error: member access into incomplete type 'struct Backend'
  auto rootDirectory = rootBackend->createDirectory(S_IRUGO | S_IXUGO | S_IWUGO);
                                  ^
emscripten/cache/sysroot/include/emscripten/wasmfs.h:17:16: note: forward declaration of 'Backend'
typedef struct Backend* backend_t;
               ^
1 error generated.
```
This is not the case for `createMemoryFileBackend()`.
I can add another declaration of a factory function to avoid reinterpret cast.

File: test/other/test_fs_icase.cpp [hunk 18]
```diff
@@ -0,0 +1,193 @@
...
+  assert(std::find(contents.begin(), contents.end(), "Test.txt") !=
+         contents.end());
+#endif
+
+  // Delete a file from a directory.
+#ifdef WASMFS
+  assert(unlink("SUBDIR/TEST.TXT") == 0);
+#else
+  // bug in FS.unlink()
+  assert(unlink("subdir/Test.txt") == 0);
```
Comment (mere-human) [inline test/other/test_fs_icase.cpp:126]: Reported separately: https://github.com/emscripten-core/emscripten/issues/17827

File: system/lib/wasmfs/wasmfs.cpp (hunk 14 above)
Comment (tlively) [reply system/lib/wasmfs/wasmfs.cpp:84]: Oh I see 👍

File: test/other/test_fs_icase.cpp (hunk 12 above)
Comment (tlively) [reply test/other/test_fs_icase.cpp:101]: Makes sense, thanks. I think we could add code to `IgnoreCaseDirectory::getEntries` to map back to the original names, but I'm fine leaving that for a later PR if you prefer.

File: system/lib/wasmfs/wasmfs.cpp [hunk 19]
```diff
@@ -13,6 +13,14 @@
 #include "special_files.h"
 #include "wasmfs.h"
 
+#ifdef WASMFS_CASE_INSENSITIVE
+#include <emscripten/wasmfs.h>
+
+static backend_t make_mem_backend(void* arg) {
```
Comment (tlively) [inline system/lib/wasmfs/wasmfs.cpp:19]: Please add a comment here mentioning what this is used for.

File: system/lib/wasmfs/file.h [hunk 20]
```diff
@@ -242,6 +243,8 @@ class Directory : public File {
   //  3. Implementing `getName`, since it cannot be implemented in terms of the
   //     dcache.
   virtual bool maintainsFileIdentity() { return false; }
+  
+  friend class IgnoreCaseDirectory;
```
Comment (tlively) [inline system/lib/wasmfs/file.h:247]: Yikes! This looks like a bad abstraction leak. Why do we need this?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 21]
```diff
@@ -0,0 +1,142 @@
...
+}
+} // namespace
+
+namespace wasmfs {
+
+// Problem: Child entries are stored both in IgnoreCaseDirectory and in baseDirectory.
+//
+// Original name case preservation could be possible if MemoryDirectory::entries
+// were accesible. Then, we would store the original case there but search
+// ignoring case.
```
Comment (tlively) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:31]: Let's just go ahead and make everything in `MemoryDirectory` public. If we're going to use it as a general utility, then we should lean into that.

File: system/lib/wasmfs/wasmfs.cpp (hunk 14 above)
Comment (tlively) [reply system/lib/wasmfs/wasmfs.cpp:84]: Maybe we can add a simpler C++ interface for this (like `createMemoryFileBackend()` for the in-memory backend) so we don't need to use the more complex C API here?

@kripken, wdyt about this? I know we had discussed not having a separate case-insensitive version of libwasmfs and not supporting a case-insensitive root directory going forward, but this seems fairly simple and avoids regressing functionality that we currently support.

**Review by tlively — COMMENTED** [review]
Thanks for your patience, @mere-human! This is looking pretty good to me. I agree that overall this is much more complex as a virtual backend, but I think it's worth it for keeping the core system simpler. I hope to have a lot of virtual backends in the future, so it's good to have one now that we can use to test and improve the backend API.

File: system/lib/wasmfs/file.h (hunk 20 above)
Comment (mere-human) [reply system/lib/wasmfs/file.h:247]: I know. We need to forward some calls to `baseDirectory` in `IgnoreCaseDirectory`. For example, `insertDirectory()`:
https://github.com/emscripten-core/emscripten/blob/7d5b438340dea4814778b9b34399053f559b0524/system/lib/wasmfs/backends/ignore_case_backend.cpp#L53
We could have used `Directory::Hanlde` in that case. But it seems bad because:
* Working with `Directory::Handle` means some additional code would run instead of directly calling `Directory` method. 
  * `insertDirectory()` for a root won't work because the directory doesn't have parent: https://github.com/emscripten-core/emscripten/blob/7d5b438340dea4814778b9b34399053f559b0524/system/lib/wasmfs/file.cpp#L115
  * `dcache` of a child will be used but we don't need it.
* `baseDirectory` is a part of the `IgnoreCaseDirectory` object so locking it seems redundant

Do you have any better ideas how to solve that without a need of a friend class?

File: system/lib/wasmfs/backends/ignore_case_backend.cpp (hunk 21 above)
Comment (mere-human) [reply system/lib/wasmfs/backends/ignore_case_backend.cpp:31]: I'd suggest to work on case preservation separately. This PR is pretty big and takes too long already.

File: system/lib/wasmfs/wasmfs.cpp (hunk 19 above)
Comment (mere-human) [reply system/lib/wasmfs/wasmfs.cpp]: Removed that and used a lambda instead.

File: test/other/test_fs_icase.cpp (hunk 12 above)
Comment (mere-human) [reply test/other/test_fs_icase.cpp:101]: I'd prefer to do that in a separate PR.

File: system/lib/wasmfs/wasmfs.cpp (hunk 14 above)
Comment (kripken) [reply system/lib/wasmfs/wasmfs.cpp]: C++ APIs for backend creation that have more type info sgtm.

File: system/lib/wasmfs/file.h (hunk 20 above)
Comment (tlively) [reply system/lib/wasmfs/file.h:248]: For now I would just use `Directory::Handle` like normal and set the parent manually so that `insertDirectory` works. It would be good to add TODO comments about making that nicer, though. These are good usability problems to surface and fix before we create a bunch more virtual backends.

File: system/lib/wasmfs/backends/ignore_case_backend.cpp [hunk 22]
```diff
@@ -82,32 +82,33 @@ class IgnoreCaseDirectory : public MemoryDirectory {
   int insertMove(const std::string& name, std::shared_ptr<File> file) override {
     auto newName = normalize(name);
     // Remove entry with the new name (if any) from this directory.
-    if (!removeChild(newName))
-      return -EPERM;
+    if (auto err = removeChild(newName))
```
Comment (mere-human) [inline system/lib/wasmfs/backends/ignore_case_backend.cpp:85]: This change from bool to int caused some trouble.

**Comment by tlively** [comment]
Let's land this and continue iterating as necessary in further PRs. @mere-human, can you merge in the latest main to try to fix the CI tests?

**Comment by mere-human** [comment]
I don't understand why these test fail? I've rebased on top of the latest main branch. 
It passes locally if I run  as `test/runner 'browser.test_pthread_run_on_main_thread' --browser chrome`

```
test-browser-chrome - Failed
...
test_browser: 621 run, 0 errors, 5 failures, 299 skipped
...
======================================================================
FAIL: test_pthread_run_on_main_thread (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/test/common.py", line 1600, in run_browser
    self.assertContained(expected, output)
  File "/root/project/test/common.py", line 941, in assertContained
    additional_info
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Expected to find '/report_result?exit:0
' in '[no http server activity]
', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?exit:0
+[no http server activity]
...
```

**Comment by kripken** [comment]
Unfortunately there are sometimes random errors on those particular tests. Re-running that test suite should fix it.

**Review by tlively — APPROVED** [review]
