### PR TITLE
Fix stack buffer overrun in websocket_to_posix_proxy. Closes #10684.

### LINKED ISSUE #10684: Stack buffer overrun vulnerability in websocket_to_posix_proxy
https://github.com/emscripten-core/emscripten/blob/318c0e24fa6e3d0ac8acd8fead7cac923d58767f/tools/websocket_to_posix_proxy/src/main.cpp#L55

The size of the "key" buffer is not passed to GetHttpHeader.
Clients can overwrite the stack by sending a header value that is longer than 128 bytes in the header "Sec-WebSocket-Key" which is potentially dangerous.

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

File: tools/websocket_to_posix_proxy/src/main.cpp [hunk 1]
```diff
@@ -34,26 +34,28 @@ static void base64_encode(void *dst, const void *src, size_t len) // thread-safe
...
 }
 
 // Sends WebSocket handshake back to the given WebSocket connection.
 void SendHandshake(int fd, const char *request)
 {
-  char key[128];
-  GetHttpHeader(request, "Sec-WebSocket-Key: ", key);
-  const char webSocketGlobalGuid[] = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
+  const char webSocketGlobalGuid[] = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"; // 36 characters long
+  char key[128+36];
```
Comment (sbc100) [inline tools/websocket_to_posix_proxy/src/main.cpp:57]: I think you can do `128+sizeof(webSocketGlobalGuid)`

**Review by sbc100 — APPROVED** [review]

File: tools/websocket_to_posix_proxy/src/main.cpp (hunk 1 above)
Comment (juj) [reply tools/websocket_to_posix_proxy/src/main.cpp]: Not that hot on sizeoffing strings even though they are in []s, I find that to be refactor brittle, but adapted to that.
