### PR TITLE
fixes to strptime to: a)handle %% correctly, and b)handle time zones correctly

### LINKED ISSUE #20466: strptime fails with double percent format strings
`strptime("5/1/2020 %z","%m/%d/%Y %%z",&result);`

If a double percent is used in strptime, to mean a literal percent, it crashes out.

### PR DESCRIPTION
**Pull request by joemarshall**
Fixes (and additional tests) to strptime to fix things that failed in Apache arrow test suite.

Fixes #20466 and #20467

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
I wonder if there is some way to add this support without increasing the JS codesize as much?   Maybe its fine since this function is already pretty huge.

Style notes:

- add space after all for/if/etc keywords.
- We avoid `const`, `let` and `for .. of` in our JS library code for now.
- Also put opening bracket on the same line as `if/for/etc`
- Put spaces on both sides of operators like `+=`.

**Comment by joemarshall** [comment]
There's a few bits where I could trivially lose a line or two I think - like the hhmm processing could probably use a smarter regex in the first place to save having to regex it again. And the percent processing loop could be more succinctly written.

I'll take a look tomorrow while i do those style things.

File: src/library.js [hunk 1]
```diff
@@ -1185,7 +1209,12 @@ addToLibrary({
       {{{ makeSetValue('tm', C_STRUCTS.tm.tm_wday, 'fullDate.getDay()', 'i32') }}};
       {{{ makeSetValue('tm', C_STRUCTS.tm.tm_yday, 'arraySum(isLeapYear(fullDate.getFullYear()) ? MONTH_DAYS_LEAP : MONTH_DAYS_REGULAR, fullDate.getMonth()-1)+fullDate.getDate()-1', 'i32') }}};
       {{{ makeSetValue('tm', C_STRUCTS.tm.tm_isdst, '0', 'i32') }}};
-
+      #if MEMORY64
+        {{{ makeSetValue('tm', C_STRUCTS.tm.tm_gmtoff, 'date.gmtoff', 'i64') }}};
+      #else
+        {{{ makeSetValue('tm', C_STRUCTS.tm.tm_gmtoff, 'date.gmtoff', 'i32') }}};
```
Comment (sbc100) [inline src/library.js:1215]: You can use `*` here instead of `i32` or `i64`.. this avoids the needs for the if/else.

File: test/core/test_strptime_tm.out [hunk 2]
```diff
@@ -16,3 +16,7 @@ oct: 9
 nov: 10
 november: 10
 december: 11
+1
+3600
+0
+-9000
```
Comment (sbc100) [inline test/core/test_strptime_tm.out:22]: Add a newline here at the end of the file.

File: src/library.js [hunk 3]
```diff
@@ -987,43 +987,51 @@ addToLibrary({
...
-    }
-
-    // take care of capturing groups
+    var pattern_out = "";
+    var in_percent = false;
     var capture = [];
-    for (var i=pattern.indexOf('%'); i>=0; i=pattern.indexOf('%')) {
-      capture.push(pattern[i+1]);
-      pattern = pattern.replace(new RegExp('\\%'+pattern[i+1], 'g'), '');
+    for (let i = 0; i < pattern.length; i++) {
```
Comment (sbc100) [inline src/library.js:1018]: Can you use `var` instead of let here?

Comment (sbc100) [reply src/library.js:1018]: Maybe add a comment about this block?  It seems like its need to handle the %% .. but its not clear why the old approach doesn't work.

File: src/library.js (hunk 1 above)
Comment (joemarshall) [reply src/library.js:1215]: Oh yeah. Fixed it in localtime also.

File: src/library.js (hunk 3 above)
Comment (joemarshall) [reply src/library.js]: Oh yeah, have done. I actually moved the code to handle EQUIVALENT_MATCHES down into that loop too now, as that failed in similar circumstances - if you did e.g. %%D, it would replace that with %%m/%d/%y, which is a bug.

**Comment by joemarshall** [comment]
Done those review changes now.

File: src/library.js [hunk 4]
```diff
@@ -967,63 +967,78 @@ addToLibrary({
...
+      'h':  '%b',
+      'R':  '%H\\:%M',
+      'r':  '%I\\:%M\\:%S\\s%p',
+      'T':  '%H\\:%M\\:%S',
+      'x':  '%m\\/%d\\/(?:%y|%Y)',
+      'X':  '%H\\:%M\\:%S'
     };
-    for (var matcher in EQUIVALENT_MATCHERS) {
-      pattern = pattern.replace(matcher, EQUIVALENT_MATCHERS[matcher]);
-    }
```
Comment (sbc100) [inline src/library.js:985]: Why change the way EQUIVALENT_MATCHERS work?  Why not keep these three lines and avoid needing the new EQUIVALENT_MATCHERS code below?

Comment (joemarshall) [reply src/library.js:985]: Because that existing code has a bug. If you put e.g. `%%D`, it gets converted to '%%m/%d/%y`, whereas it should be left as matching a literal % followed by a capital D. I added a test case for this bug, try it in the previous emscripten and it will fail. Doing everything character by character is just way less fragile than repeated find calls.

Comment (RReverser) [reply src/library.js:985]: Would a regex help here? So you'd do

```js
var pattern_out =
  str
  .replace(/%(.)/g, (m, c) => EQUIVALENT_MATCHERS[c] || m)
  .replace(/%(.)/g, (_, c) => {
    let pat = DATE_PATTERNS[c];
    return pat ? `(${pat})` : c;
  });
```

Something like this should handle `%%` pairs correctly, and thanks to splitting into 2 passes would be simpler to follow than a manual loop.

File: src/library.js [hunk 5]
```diff
@@ -967,63 +967,78 @@ addToLibrary({
...
+          // reset the loop to this position
+          pattern=pattern.slice(0,i-1)+EQUIVALENT_MATCHERS[c]+pattern.slice(i+1)
+          i=i-2;
+        }else if (c in DATE_PATTERNS) {
+          capture.push(c)
+          pattern_out += "(" + DATE_PATTERNS[c] + ")";
+        }
+        in_percent = false;
+      } else {
+        pattern_out += c;
```
Comment (RReverser) [inline src/library.js:1037]: Btw after writing my implementation in that comment I figured there is a bug here - this doesn't add `\` to escape the character, so special symbols like `.` will be preserved in the final pattern and will match arbitrary character instead of just a dot.

Same in the previous implementation which didn't have any handling for those special characters.

File: src/library.js (hunk 4 above)
Comment (RReverser) [reply src/library.js:985]: (also see comment below on handling special regex chars, that applies to all 3 possible implementations)

File: src/library.js (hunk 5 above)
Comment (joemarshall) [reply src/library.js:1037]: The special symbols are escaped at the top no?

Comment (RReverser) [reply src/library.js:1037]: Sigh, you're right. I expected to see that done only for remaining literals after % replacements so didn't look there, and didn't see any tests in the test file ensuring that eg dot doesn't accidentally match unrelated character.

File: src/library.js (hunk 4 above)
Comment (joemarshall) [reply src/library.js:985]: Brilliant. That sorts it with a small addition to make the capture list.

**Comment by joemarshall** [comment]
@sbc100 I implemented the regex suggested by @RReverser and now it a) fixes all the %% bugs I can think of, and b) has minimal increase in code size. Cross fingers we're ready to merge now.

File: src/library.js [hunk 6]
```diff
@@ -1163,6 +1161,20 @@ addToLibrary({
         }
       }
 
+      // time zone
+      if ((value = getMatch('z'))) {
+        // GMT offset as either 'Z' or +-HH:MM or +-HH or +-HHMM
+        if (value.toLowerCase() === 'z'){
+          date.gmtoff = 0;
+        } else {          
+          var match = value.match(/^(?<hours>(?:\-|\+)\d\d):?(?<mins>\d\d)?/);
```
Comment (RReverser) [inline src/library.js:1170]: Unfortunately, we still target ES5. We use some ES6 features where possible by transpiling them via Closure Compiler, but it looks like named capture groups are not one of such features.

image

I'm afraid this will need to be converted to regular old capture group.

File: src/library.js [hunk 7]
```diff
@@ -967,64 +967,61 @@ addToLibrary({
...
+      /* weekday name */    'a': '(?:Sun(?:day)?)|(?:Mon(?:day)?)|(?:Tue(?:sday)?)|(?:Wed(?:nesday)?)|(?:Thu(?:rsday)?)|(?:Fri(?:day)?)|(?:Sat(?:urday)?)',
+      /* month name */      'b': '(?:Jan(?:uary)?)|(?:Feb(?:ruary)?)|(?:Mar(?:ch)?)|(?:Apr(?:il)?)|May|(?:Jun(?:e)?)|(?:Jul(?:y)?)|(?:Aug(?:ust)?)|(?:Sep(?:tember)?)|(?:Oct(?:ober)?)|(?:Nov(?:ember)?)|(?:Dec(?:ember)?)',
+      /* century */         'C': '\\d\\d',
+      /* day of month */    'd': '0[1-9]|[1-9](?!\\d)|1\\d|2\\d|30|31',
+      /* hour (24hr) */     'H': '\\d(?!\\d)|[0,1]\\d|20|21|22|23',
+      /* hour (12hr) */     'I': '\\d(?!\\d)|0\\d|10|11|12',
+      /* day of year */     'j': '00[1-9]|0?[1-9](?!\\d)|0?[1-9]\\d(?!\\d)|[1,2]\\d\\d|3[0-6]\\d',
+      /* month */           'm': '0[1-9]|[1-9](?!\\d)|10|11|12',
+      /* minutes */         'M': '0\\d|\\d(?!\\d)|[1-5]\\d',
+      /* whitespace */      'n': '\\s',
```
Comment (RReverser) [inline src/library.js:995]: Btw unless I'm missing something again (totally possible), this seems like a (pre-existing) bug. From `strptime` docs:

> All other characters in the format string must have
 a matching character in the input string, except for whitespace,
 which matches zero or more whitespace characters in the input
 string.  There should be whitespace or other alphanumeric
 characters between any two field descriptors.

If I'm reading this correctly, `%n`, `%t` and even regular whitespace character in the format string without the `%` prefix all should map to `\s*` (zero or more whitespace character) not `\s` (exactly one whitespace character).

File: src/library.js (hunk 6 above)
Comment (joemarshall) [reply src/library.js]: Have done. Also added a test for regex characters in the string which passes which is nice..

File: src/library.js (hunk 7 above)
Comment (RReverser) [reply src/library.js:995]: This can be left for separate PR though as it's not directly relevant to fixes here.

Comment (joemarshall) [reply src/library.js]: right you are. Pushed a fix and a test now.

File: src/library.js [hunk 8]
```diff
@@ -992,15 +992,15 @@ addToLibrary({
       /* day of year */     'j': '00[1-9]|0?[1-9](?!\\d)|0?[1-9]\\d(?!\\d)|[1,2]\\d\\d|3[0-6]\\d',
       /* month */           'm': '0[1-9]|[1-9](?!\\d)|10|11|12',
       /* minutes */         'M': '0\\d|\\d(?!\\d)|[1-5]\\d',
-      /* whitespace */      'n': '\\s',
+      /* whitespace */      'n': '\\s*',
```
Comment (RReverser) [inline src/library.js:995]: Since you have that pass below anyway, these could probably just be `'n': ' '` and `'t': ' '` as slight simplification. Not sure if it matters though.

**Comment by RReverser** [comment]
@joemarshall I rebased your PR, I think this is good to go, just needs those final nits fixed.

**Comment by joemarshall** [comment]
@RReverser okay, done those two changes above, hopefully we're good to go. Thanks.

**Comment by sbc100** [comment]
It looks like this change brakes the roller.  The new test fails there (and on my local machine): https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8764972969074118673/+/u/Emscripten_testsuite__core3_/stdout  
```
strftime zone test #1: 0

ERROR: strftime zone test #1 ("+7777")
```

I've got a cleanup PR open (https://github.com/emscripten-core/emscripten/pull/20657) but its not a fix.
