### PR TITLE
Fix unescaped NUL character in JS

### LINKED ISSUE #19230: 3.1.35+ contains NUL characters in JS
In 3.1.35+ output seems to have escape sequences unescaped. It's hard to demonstrate by copy-pasting the code so I'll paste screenshot from an editor that shows that a comment on `UTF8ToString` now has a literal NUL (0) character:

image

and this is what it looked like before:

image

This caused problems in a C program that reads the JS file as a string and then tries to process it as a C string (that is, by stopping at said NUL character).

I narrowed it down to #19097 which moved code & comments into JS strings, but now that `\0` is inside a JS string, it gets unescaped by the engine: https://github.com/emscripten-core/emscripten/commit/f18834086059f098f987b69efd712e14b16682bd#diff-9b6499e625a2216c99e6a18e621462ba263fc408745bd38487fb9cefef61e1d0R104 cc @sbc100

### PR DESCRIPTION
**Pull request by RReverser**
It seems to be the only such occurence, but I might have missed more.

Fixes #19230.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Interesting... I'm not sure what tool turns that into a literal 0, but sgtm to escape it. We could also just write "0" there I guess, which would be human-readable enough.

File: src/library_strings.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ mergeInto(LibraryManager.library, {
    * @param {number} ptr
    * @param {number=} maxBytesToRead - An optional length that specifies the
    *   maximum number of bytes to read. You can omit this parameter to scan the
-   *   string until the first \0 byte. If maxBytesToRead is passed, and the string
+   *   string until the first \\0 byte. If maxBytesToRead is passed, and the string
```
Comment (sbc100) [inline src/library_strings.js:104]: How about `null` or `NULL` instead?

**Comment by RReverser** [comment]
> I'm not sure what tool turns that into a literal 0

It's literally part of a JS string now and JS strings support escapes, so a string `'something \0 something`` gets nul character unescaped, just like it would be in string literals in most other langs.

File: src/library_strings.js (hunk 1 above)
Comment (RReverser) [reply src/library_strings.js:104]: Yeah that works for me too, just wasn't sure if you'd be open to that. Or, as @kripken says, just "0 byte" also sounds good, I'll probably go with that.

**Review by kripken — APPROVED** [review]
