### PR TITLE
Handle WGPU_WHOLE_SIZE in SetIndexBuffer/SetVertexBuffer

### LINKED ISSUE #20167: Issue when calling WebGPU's SetVertexBuffer without size parameter
There seems to be issues converting the size parameter, either when setting it explicitly 
`renderPassEncoder.SetVertexBuffer(index, buffer, offset, WGPU_WHOLE_SIZE);`
or by skipping it:
`renderPassEncoder.SetVertexBuffer(index, buffer, offset);`

Presumably the issue happens because we are trying to convert an 64 unsigned into to javascript and values are overflown.

When inspecting the debugger, the size value is transformed into -1 when calling the corresponding emscripten function.
Other parameters seem to be correctly resolved, including the Buffer

```
 // size_low = -1 and size_high = -1
function _wgpuRenderPassEncoderSetVertexBuffer(passId, slot, bufferId, offset_low, offset_high, size_low, size_high) {
 passId >>>= 0;
 bufferId >>>= 0;
 var offset = convertI32PairToI53Checked(offset_low, offset_high);
 var size = convertI32PairToI53Checked(size_low, size_high);
 var pass = WebGPU.mgrRenderPassEncoder.get(passId);
 var buffer = WebGPU.mgrBuffer.get(bufferId);
 // size = -1
 pass["setVertexBuffer"](slot, buffer, offset, size);
}
```

which throws `Uncaught TypeError: Failed to execute 'setVertexBuffer' on 'GPURenderPassEncoder': Value is outside the 'unsigned long long' value range.`

This function call was correctly working in `3.1.33`

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.45 (ef3e4e3b044de98e1811546e0bc605c65d3412f4)`

### PR DESCRIPTION
**Pull request by kainino0x**
Fixes #20167

### CODE REVIEW

File: src/library_webgpu.js [hunk 1]
```diff
@@ -2144,6 +2144,7 @@ var LibraryWebGPU = {
   wgpuRenderPassEncoderSetIndexBuffer: (passId, bufferId, format, offset, size) => {
     var pass = WebGPU.mgrRenderPassEncoder.get(passId);
     var buffer = WebGPU.mgrBuffer.get(bufferId);
+    {{{ gpu.convertSentinelToUndefined('size') }}}
```
Comment (kohakukun) [inline src/library_webgpu.js:2147]: Works for my use case but, I think you should apply it to the offset, since it is also an optional value that defaults to 0

**Review by kripken — APPROVED** [review]

File: src/library_webgpu.js (hunk 1 above)
Comment (kainino0x) [reply src/library_webgpu.js:2147]: It's not necessary for offset, because in the JS API, 0 and undefined do the same thing - the WebIDL code in the spec also defines the default value as 0. So when C passes 0, we can pass it through directly and it passes through correctly. We only need the special casing for WGPU_WHOLE_SIZE which is a special 0xFFFF_FFFF_FFFF_FFFF which is a placeholder for the JS `undefined`. (it's unsigned in C but when we receive it in JS it's been cast to signed, so we actually receive it as -1, and translate that to `undefined`.)
