### PR TITLE
Make readlink system call not resolve the link

### LINKED ISSUE #22999: Readlink incorrectly returns fully qualified path
Considering the following:
```C
#include <fcntl.h>
#include <string.h>
#include <stdio.h>
#include <assert.h>
#include <unistd.h>

static void create_file(const char *path, const char *buffer, int mode) {
  int fd = open(path, O_WRONLY | O_CREAT | O_EXCL, mode);
  assert(fd >= 0);

  int err = write(fd, buffer, sizeof(char) * strlen(buffer));
  assert(err ==  (sizeof(char) * strlen(buffer)));

  close(fd);
}

int main() {
    char buf[20];

    create_file("symlink_target", "xyz", 0777);
    symlink("symlink_target", "symlink_src");
    readlink("symlink_src", buf, 20);
    printf("buf: '%s'\n", buf);
    unlink("symlink_src");
    unlink("symlink_target");
}
```
Running with `gcc` we just the contents of the link vs running with `emcc` we get a fully qualified path:
```
$ gcc a.c
$ ./a.out
buf: 'symlink_target'
$ emcc a.c
$ node a.out.js
buf: '/symlink_target'
```
Note the initial `/` in the emcc run.

### PR DESCRIPTION
**Pull request by hoodmane**
Readlink in linux does not resolve the link, it returns the exact link contents. Resolves #22999.

### CODE REVIEW

**Comment by hoodmane** [comment]
@sbc100 test failure looks like it may be a flake?

File: src/library_fs.js [hunk 1]
```diff
@@ -904,7 +904,11 @@ FS.staticInit();
       if (!link.node_ops.readlink) {
         throw new FS.ErrnoError({{{ cDefs.EINVAL }}});
       }
-      return PATH_FS.resolve(FS.getPath(link.parent), link.node_ops.readlink(link));
+      const target = link.node_ops.readlink(link);
```
Comment (sbc100) [inline src/library_fs.js:907]: We tend to avoid `let` and `const` in JS library code still.   Sadly using `var` everywhere lends to better minified code size.

File: src/library_fs.js [hunk 2]
```diff
@@ -895,7 +895,7 @@ FS.staticInit();
       }
 #endif
     },
-    readlink(path) {
+    readlink(path, opts = {}) {
```
Comment (sbc100) [inline src/library_fs.js:898]: Do we need the old behaviour?  i.e. Are there other callsites beside `__syscall_readlinkat`?

**Review by sbc100 — COMMENTED** [review]
lgtm!  great to see the test simplification!

File: src/library_fs.js (hunk 2 above)
Comment (hoodmane) [reply src/library_fs.js:898]: Just that and `test_fs_readlink` which would need to be updated. It's also documented public API but the documentation was wrong before and this updates the behavior to match what the documentation says.

Comment (hoodmane) [reply src/library_fs.js:898]: Actually `test_fs_readlink` doesn't cover relative links.

**Review by sbc100 — APPROVED** [review]
I love how simple this fix is!   Thanks.
