### PR TITLE
Fix Closure compile of small builds that use legacy DYNCALLS mode

### LINKED ISSUE #13858: compiling with -s ASYNCIFY and --closure 1 fails with undeclared dynCall_*
Using 2.0.16 (52ed04f424ff0db7d8085c35df3afd7f7b1c9eb7), I'm compiling this minimal C code:
```c
#include <stdio.h>
#include <emscripten.h>

int main() {
  printf("Hello, world!\n");
}
```

When I build with Asyncify + Closure optimization, I get:
```
$ emcc -s ASYNCIFY --closure 1 hello.c -o hello.js
building:ERROR: Closure compiler run failed:

building:ERROR: tmpc2sg7vit.js:1810:27: ERROR - [JSC_UNDEFINED_VARIABLE] variable dynCall_v is undeclared
  1810|             (function() {  dynCall_v.call(null, func); })();
                                   ^^^^^^^^^

tmpc2sg7vit.js:1812:29: ERROR - [JSC_UNDEFINED_VARIABLE] variable dynCall_vi is undeclared
  1812|             (function(a1) {  dynCall_vi.apply(null, [func, a1]); })(callback.arg);
                                     ^^^^^^^^^^

2 error(s), 0 warning(s)

emcc: error: closure compiler failed (rc: 2): /home/dev/emsdk/node/14.15.5_64bit/bin/node --max_old_space_size=8192 /hom
e/dev/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --l
anguage_in ECMASCRIPT_2020 --language_out NO_TRANSPILE --emit_use_strict=false --externs tmpgm9p6ex7.js --externs tmpaff
kn6t9.js --externs tmp8bybq20t.js --externs tmp03_7rkmp.js --externs tmpod4ictzi.js --externs tmpcxlk_bv3.js --externs t
mpqu9gj0cy.js --externs tmp65p65c0k.js --externs tmpx33k798f.js --externs tmplf9hgc4v.js --externs tmp9ghfy38_.js --exte
rns tmpfk441d1l.js --externs tmpc8_nsbvv.js --externs tmp_g7a36t8.js --externs tmp1tmh7qq9.js --externs tmpvz2n8w95.js -
-externs tmpum_ggeb6.js --externs tmpiofwu7h6.js --externs tmpr_rgrgkz.js --externs tmp714r4b0d.js --externs tmpnkj8inws
.js --externs tmprxa17291.js --externs tmp5suzw_5u.js --externs tmp2896h20q.js --externs tmp8lmfmv5s.js --externs tmp5pi
s_q7m.js --externs tmpr3uule80.js --externs tmp6c48g27d.js --externs tmpfijl40q8.js --externs tmp6y_5x_ea.js --externs t
mpm94qid1b.js --externs tmpw2sswmjd.js --js_output_file tmpku06pakj.cc.js --formatting PRETTY_PRINT --js tmpc2sg7vit.js
```

In my real code where I first encountered the problem, I only saw `dynCall_v` undeclared; I didn't see an error for `dynCall_vi` until simplifying the test case. The compilation succeeds if either the Asyncify or the Closure flags are removed. I have not used any previous distributions so I don't know if this is a regression.

I am attaching the EMCC_DEBUG=2 console output and temporary files.
[emcc-bug.zip](https://github.com/emscripten-core/emscripten/files/6288577/emcc-bug.zip)

### PR DESCRIPTION
**Pull request by juj**
Fix Closure compile of small builds that use legacy DYNCALLS mode but do not export any wasm function with signature 'v' or 'vi'.

Fixes #13858

### CODE REVIEW

**Comment by rhashimoto** [comment]
Thanks for the fix!

What does "small builds" mean? The minimal reproduction case I created for the bug is indeed small, but the project that caused the problem for me is a variant of SQLite, which I wouldn't consider small. I did have at least one function in my source returning void with no arguments:

```c
extern "C" void EMSCRIPTEN_KEEPALIVE register_idb_vfs() {
  ...
}
```

Is it the case that these "normal" functions aren't the ones using the legacy mode?

Also, the problem commit removed 'vii' and 'iii' as well. Would these signatures never be produced?

**Comment by juj** [comment]
> What does "small builds" mean?

"small builds" means applications that do not export any wasm functions with signature 'v' or 'vi'.

In other words, in larger applications, there generally are some exported functions with that signature, which would not exhibit the issue.

> I did have at least one function in my source returning void with no arguments:

That is surprising, I am not sure why that would still complain about `dynCall_v` not being present.

If you can test the branch to confirm it fixes your issue, that would be great!

> Is it the case that these "normal" functions aren't the ones using the legacy mode?

Whether the legacy DYNCALLS mode is used or not does not occur on a function-by-function basis, but rather it depends on the build mode. In this case, using ASYNCIFY is what requires using the legacy DYNCALLS mode.

> Also, the problem commit removed 'vii' and 'iii' as well. Would these signatures never be produced?

Code producing any `dynCall_*` signatures can occur. But the issue here was that if there was a particular piece of code injected that invoked `dynCall_*` without that signature being emitted in the generated code. That kind of scenario is a kind of an impossibility: if we emit a call to say `dynCall_iii`, in order to execute that line of code, there must exist at least one export of a function pointer with that signature `iii` as well. (otherwise we don't have a valid function pointer to pass in as an argument, which would fail at runtime!)

But Closure does not know that. In this case, the `dynCall_v` and `dynCall_vi` functions would never actually be able to get executed, as there was nothing those functions could be called with (since nothing suitable was exported), so the code was ok. But Closure just does a static analysis of the code, so it won't know that.

Whether there are other places in code that statically emit calls to `dynCall_iii` and other signatures without ensuring there exists an appropriate export, I don't know - however the old "fix" to that by disabling Closure minification altogether on that was a bad bandaid to avoid the proper fix, which is why those Closure externs were removed in the earlier PR. If some code pattern showcases that there is, the same machinery that is used in this PR can likely be extended to cover those cases as well.

**Comment by rhashimoto** [comment]
I will see if I can successfully build your branch. I never succeeded in getting the build to work to do the bisection (finally just used `emsdk install` and manually picked out hashes) so you may have to bear with me.

In the meantime could you please try this with `-s ASYNCIFY --closure 1`:

```c
#include <stdio.h>
#include <emscripten.h>

void EMSCRIPTEN_KEEPALIVE test_func() {
  printf("returns nothing");
}

void EMSCRIPTEN_KEEPALIVE test_func1(int foo) {
  printf("returns nothing");
}
```

This has functions with 'v' and 'vi' signatures. It fails with undeclared `dynCall_v` and `dynCall_vi` on 2.0.14 but works on 2.0.13, just like the other example. If I understand you correctly, this should be impossible?

**Comment by rhashimoto** [comment]
I neglected to thank you for your detailed and newbie-friendly explanations. So thank you!

It looks like your branch works on my main code base. I got this binaryen version warning, which I'm guessing is expected because I only changed `EMSCRIPTEN_ROOT` in my otherwise 2.0.14 `.emscripten` file:
```
emcc: warning: unexpected binaryen version: 99 (expected 100) [-Wversion-check]
```

Other than that my project built and ran successfully.

File: src/library.js [hunk 1]
```diff
@@ -3532,9 +3532,26 @@ LibraryManager.library = {
...
       if (typeof func === 'number') {
         if (callback.arg === undefined) {
+          // Run the wasm function ptr with signature 'v'. If no function
+          // with such signature was exported, this call does not need
+          // to be emitted (and would confuse Closure)
+#if !DYNCALLS || hasLlvmExportedFunction('dynCall_v')
           {{{ makeDynCall('v', 'func') }}}();
+#else
+#if ASSERTIONS
+          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "v", but no such functions should have gotten exported!';
```
Comment (kripken) [inline src/library.js:3542]:
```suggestion
          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "v", but no such functions have gotten exported!';
```

File: src/library.js [hunk 2]
```diff
@@ -3532,9 +3532,26 @@ LibraryManager.library = {
...
+#endif
+#endif
         } else {
+          // If any function with signature 'vi' was exported, run
+          // the callback with that signature.
+#if !DYNCALLS || hasLlvmExportedFunction('dynCall_vi')
           {{{ makeDynCall('vi', 'func') }}}(callback.arg);
+#else
+#if ASSERTIONS
+          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "vi", but no such functions should have gotten exported!';
```
Comment (kripken) [inline src/library.js:3552]:
```suggestion
          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "vi", but no such functions have gotten exported!';
```

File: src/parseTools.js [hunk 3]
```diff
@@ -1222,10 +1222,16 @@ function makeAsmImportsAccessInPthread(variable) {
   return variable;
 }
 
+// Returns true if the given function is exported out in the generated JS Module object.
 function hasExportedFunction(func) {
   return Object.keys(EXPORTED_FUNCTIONS).indexOf(func) != -1;
 }
 
+// Returns true if LLVM produced the given function into compiled code as a Wasm export.
+function hasLlvmExportedFunction(func) {
```
Comment (kripken) [inline src/parseTools.js:1231]: How about `hasLLVMExportedFunction`? (LLVM capitalized)

File: tests/test_other.py [hunk 4]
```diff
@@ -10004,6 +10004,12 @@ def test_old_makeDynCall_syntax(self):
     err = self.run_process([EMCC, test_file('test_old_dyncall_format.c'), '--js-library', test_file('library_test_old_dyncall_format.js')], stderr=PIPE).stderr
     self.assertContained('syntax for makeDynCall has changed', err)
 
+  # Tests that dynCalls are produced in Closure-safe way in DYNCALLS mode when no actual dynCalls are used
+  def test_closure_no_dynCalls_generated(self):
+    self.run_process([EMCC, test_file('hello_world.c'), '--closure=1'])
+    self.run_process([EMCC, test_file('hello_world.c'), '-s', 'ASYNCIFY', '--closure=1'])
+    self.run_process([EMCC, test_file('hello_world.c'), '-s', 'ASYNCIFY', '-s', 'WASM_BIGINT', '--closure=1'])
+
```
Comment (kripken) [inline tests/test_other.py:10012]: This could be
```python
  @parameterized({
    'plain': [[]],
    'asyncify': [['-sASYNCIFY']],
    'asyncify-bigint': [['-sASYNCIFY', '-sWASM_BIGINT']]})
  def test_closure_no_dynCalls_generated(self, args):
    self.run_process([EMCC, test_file('hello_world.c'), '--closure=1'] + args)

**Comment by juj** [comment]
Resolved as suggested, ptal.

File: tests/test_other.py [hunk 5]
```diff
@@ -10004,6 +10004,14 @@ def test_old_makeDynCall_syntax(self):
     err = self.run_process([EMCC, test_file('test_old_dyncall_format.c'), '--js-library', test_file('library_test_old_dyncall_format.js')], stderr=PIPE).stderr
     self.assertContained('syntax for makeDynCall has changed', err)
 
+  # Tests that dynCalls are produced in Closure-safe way in DYNCALLS mode when no actual dynCalls are used
+  @parameterized({
+    'plain': [[]],
+    'asyncify': [['-sASYNCIFY']],
+    'asyncify-bigint': [['-sASYNCIFY', '-sWASM_BIGINT']]})
```
Comment (kripken) [inline tests/test_other.py:10011]: Huh, I'm surprised this works... `-` is not valid in a python name (these become part of the name of the test), but it does not error...

Still, I think we should use `_` here since I think it won't be possible to run the test with `./tests/runner.py other.test_NAME`?

```suggestion
    'asyncify_bigint': [['-sASYNCIFY', '-sWASM_BIGINT']]})
```

**Review by kripken — APPROVED** [review]
Applied suggestion, marking lgtm, which I think means autocommit will do the right thing...

File: emscripten.py [hunk 6]
```diff
@@ -275,6 +275,10 @@ def emscript(in_wasm, out_wasm, outfile_js, memfile, DEBUG):
 
   metadata = finalize_wasm(in_wasm, out_wasm, memfile, DEBUG)
 
+  # Store all exports into an internal Settings variable so that JS preamble can
+  # configure codegen based on which functions are generated
+  shared.Settings.LLVM_EXPORTS = metadata['exports']
```
Comment (sbc100) [inline emscripten.py:280]: We already have `shared.Settings.IMPLEMENTED_FUNCTIONS` for this I believe.

File: src/parseTools.js [hunk 7]
```diff
@@ -1222,10 +1222,16 @@ function makeAsmImportsAccessInPthread(variable) {
...
 }
 
+// Returns true if the given function is exported out in the generated JS Module object.
 function hasExportedFunction(func) {
   return Object.keys(EXPORTED_FUNCTIONS).indexOf(func) != -1;
 }
 
+// Returns true if LLVM produced the given function into compiled code as a Wasm export.
+function hasLLVMExportedFunction(func) {
+  return LLVM_EXPORTS.indexOf(func) != -1;
```
Comment (sbc100) [inline src/parseTools.js:1232]: I think we can do `LLVM_EXPORTS.includes(func)` these days.  (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

File: tests/test_other.py [hunk 8]
```diff
@@ -10004,6 +10004,14 @@ def test_old_makeDynCall_syntax(self):
     err = self.run_process([EMCC, test_file('test_old_dyncall_format.c'), '--js-library', test_file('library_test_old_dyncall_format.js')], stderr=PIPE).stderr
     self.assertContained('syntax for makeDynCall has changed', err)
 
+  # Tests that dynCalls are produced in Closure-safe way in DYNCALLS mode when no actual dynCalls are used
+  @parameterized({
+    'plain': [[]],
+    'asyncify': [['-sASYNCIFY']],
+    'asyncify_bigint': [['-sASYNCIFY', '-sWASM_BIGINT']]})
+  def test_closure_no_dynCalls_generated(self, args):
```
Comment (sbc100) [inline tests/test_other.py:10012]: Maybe just call this `test_closure_safe` or `test_closure_error_free` .. there could be other configurations we want to test are also closure safe .. and its not just dynCalls but any undefined symbol that could be problem right?  (i.e. missing library deps or just missing symbols in non-taken branches).

File: src/library.js [hunk 9]
```diff
@@ -3532,9 +3532,26 @@ LibraryManager.library = {
...
           {{{ makeDynCall('v', 'func') }}}();
+#else
+#if ASSERTIONS
+          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "v", but no such functions have gotten exported!';
+#endif
+#endif
         } else {
+          // If any function with signature 'vi' was exported, run
+          // the callback with that signature.
+#if !DYNCALLS || hasLLVMExportedFunction('dynCall_vi')
```
Comment (sbc100) [inline src/library.js:3548]: I think this can then just be:

```#if !DYNCALLS || ('dynCall_vi' in IMPLEMENTED_FUNCTIONS)```  (like we do elsewhere in JS libraries)?

File: src/parseTools.js [hunk 10]
```diff
@@ -1264,6 +1264,16 @@ function hasExportedFunction(func) {
   return Object.keys(WASM_EXPORTS).includes(_asmjsDemangle(func));
 }
 
+// Returns true if the given function is exported out in the generated JS Module object.
+function hasExportedFunction(func) {
+  return Object.keys(EXPORTED_FUNCTIONS).includes(func);
+}
```
Comment (sbc100) [inline src/parseTools.js:1270]: I reverted my change that removed `hasExportedFunction` in #14024.  Since its based on `WASM_EXPORTS` and not `EXPORTED_FUNCTIONS` I think it does what you want here.

File: src/library.js [hunk 11]
```diff
@@ -3552,9 +3552,26 @@ LibraryManager.library = {
...
         if (callback.arg === undefined) {
+          // Run the wasm function ptr with signature 'v'. If no function
+          // with such signature was exported, this call does not need
+          // to be emitted (and would confuse Closure)
+#if !DYNCALLS || ('dynCall_v' in IMPLEMENTED_FUNCTIONS)
           {{{ makeDynCall('v', 'func') }}}();
+#else
+#if ASSERTIONS
+          throw 'Internal Error! Attempted to invoke wasm function pointer with signature "v", but no such functions have gotten exported!';
+#endif
```
Comment (sbc100) [inline src/library.js:3563]: Would it make sense to make this logic be part of `makeDynCall` itself so all callsites can benefit?

**Review by sbc100 — APPROVED** [review]

File: src/library.js (hunk 11 above)
Comment (juj) [reply src/library.js]: That will result in worse codegen, since it will need to generate a dummy function. Though this is in the large runtime path and in DYNCALLS mode, so I don't particularly mind.

**Review by sbc100 — APPROVED** [review]

File: src/library.js (hunk 11 above)
Comment (sbc100) [reply src/library.js]: Ah I see.  LGTM either way.

**Review by sbc100 — APPROVED** [review]
