### PR TITLE
Fix JS pthreads proxying + WASM_BIGINT

### LINKED ISSUE #12079: Support for BigInt in pthreads proxy code
A call to `fseek` within a thread compiled with support for JS BigInt to Wasm i64 integration (`-s WASM_BIGINT=1`) seems to fail. Here is a simplified test case:

```python
  def test_noderawfs_pthread_bigint(self):
    fopen_write = open(path_from_root('tests', 'asmfs', 'fopen_write.cpp')).read()
    create_test_file('main.cpp', fopen_write)
    self.run_process([EMCC, 'main.cpp', '-s', 'EXIT_RUNTIME=1', '-s', 'NODERAWFS=1', '-s', 'USE_PTHREADS=1', '-s', 'PROXY_TO_PTHREAD', '-s', 'WASM_BIGINT=1'])
    out = self.run_js('a.out.js', engine=NODE_JS + ['--experimental-wasm-threads', '--experimental-wasm-bigint'])
    self.assertContained("read 11 bytes. Result: Hello data!", out)

    # NODERAWFS should directly write on OS file system
    self.assertEqual("Hello data!", open('hello_file.txt').read())
```

```javascript
a.worker.js:1 TypeError: Cannot convert a BigInt value to a number
    at _emscripten_proxy_to_main_thread_js (a.out.js:9)
    at _fd_seek (a.out.js:9)
```

<details>
  <summary>Output</summary>
  
```
$ python tests/runner.py other.test_noderawfs_pthread_bigint
shared:INFO: (Emscripten: Running sanity checks)
test_noderawfs_pthread_bigint (test_other.other) ... FAIL

======================================================================
FAIL: test_noderawfs_pthread_bigint (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kleisauke/emscripten/tests/test_other.py", line 7643, in test_noderawfs_pthread_bigint
    self.assertContained("read 11 bytes. Result: Hello data!", out)
  File "/home/kleisauke/emscripten/tests/runner.py", line 740, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
AssertionError: Expected to find 'read 11 bytes. Result: Hello data!' in 'worker.js onmessage() captured an uncaught exception: TypeError: Cannot convert a BigInt value to a number
pthread sent an error! undefined:undefined: Cannot convert a BigInt value to a number
', diff:

--- expected
+++ actual
@@ -1 +1,3 @@
-read 11 bytes. Result: Hello data!
+worker.js onmessage() captured an uncaught exception: TypeError: Cannot convert a BigInt value to a number
+pthread sent an error! undefined:undefined: Cannot convert a BigInt value to a number
+



----------------------------------------------------------------------
Ran 1 test in 0.510s

FAILED (failures=1)
Test suites:
['test_other']
Running test_other: (1 tests)
(checking sanity from test runner)
```
</details>

Removing the `-s WASM_BIGINT=1` compiler flag in the above test case will make it pass.

### PR DESCRIPTION
**Pull request by kripken**
The proxying of JS methods has no type info. It used to just use a JS
Number (a double) for everything, which works, except with BigInts
that's no longer enough.

We have to serialize type info in this case. This does a simple thing of
prefixing each argument with a non-zero value if it is a bigint. This is
not very compact, but is maybe good enough for now.

Also add a `HEAP64` global array which is useful here (and will be
with wasm64 too).

Fixes #12079

### CODE REVIEW

File: src/library_pthread.js [hunk 1]
```diff
@@ -1368,12 +1368,31 @@ var LibraryPThread = {
...
+    var args = stackAlloc(serializedNumCallArgs * 8);
     var b = args >> 3;
     for (var i = 0; i < numCallArgs; i++) {
-      HEAPF64[b + i] = arguments[2 + i];
+      var arg = arguments[2 + i];
+#if WASM_BIGINT
+      if (typeof arg === 'bigint') {
+        // The prefix is non-zero to indicate a bigint.
+        HEAP64[b + 2*i] = BigInt(1);
+        HEAP64[b + 2*i + 1] = arg;
```
Comment (sbc100) [inline src/library_pthread.js:1385]: Assigning a bigint to a slot in HEAP64 just works?

File: system/lib/pthread/library_pthread.c [hunk 2]
```diff
@@ -745,16 +745,20 @@ EMSCRIPTEN_KEEPALIVE double emscripten_run_in_main_runtime_thread_js(int index,
   c->calleeDelete = 1-sync;
   c->functionEnum = EM_PROXIED_JS_FUNCTION;
   c->functionPtr = (void*)index;
-  // We write out the JS doubles into args[], which must be of appropriate size - JS will assume that.
+  // The types are only known at runtime in these calls, so we store values that
+  // must be able to contain any valid JS value, including a 64-bit BigInt if
+  // BigInt support is enabled.
   assert(sizeof(em_variant_val) == sizeof(double));
```
Comment (sbc100) [inline system/lib/pthread/library_pthread.c:751]: Does it still make sense to have this first assert?     Also shouldn't these but `>=`?   It seems like if you include both of these you are needlessly asserting that `double` and `int64_t` are the same size which is not really important to this code is it?

I assume this assert its trying to say "Make sure that the size of the variant is at least is a big as the biggest thing I need to store in it?

I'm actually not sure you need these assertions at all since you are not doing any kind of casting.. the type system should take care of these invariants, no?

If you decide to keep them how about `static_assert()`?

**Review by sbc100 — APPROVED** [review]

File: src/library_pthread.js (hunk 1 above)
Comment (kripken) [reply src/library_pthread.js:1385]: Yes, `HEAP64` is a `BigInt64Array`. That's the only thing you can assign to it without erroring basically.

File: system/lib/pthread/library_pthread.c (hunk 2 above)
Comment (kripken) [reply system/lib/pthread/library_pthread.c:751]: Yes, basically these are just asserting that the slot size is big enough for the biggest JS things.

Maybe these have little value, as there is no real chance a double would not be 64 bits... I'll remove them.

**Comment by kleisauke** [comment]
Could this PR fix issue https://github.com/emscripten-core/emscripten/issues/12079?

**Comment by kripken** [comment]
@kleisauke Yes, thanks! I didn't look at existing issues, but I should have, and my memory isn't great for stuff like this...
