### PR TITLE
[embind] Update exceptionLast in _emval_throw

### LINKED ISSUE #26213: Cannot catch C++ exception rethrown from JS outside catch with Emscripten EH
How to reproduce:

- Compile with Emscripten EH
- Throw exception from C++
- Catch in C++
- In the C++ catch, rethrow in JS and catch as JS object
- Save JS `val` in C++
- Outside of C++ catch, rethrow `val`
- Try to catch in C++
- `RuntimeError: memory access out of bounds`

```cpp
#include <iostream>
#include <emscripten/val.h>
using namespace emscripten;

int main() {
	val error;
	try {
		throw std::runtime_error("oopsie");
	} catch (const std::runtime_error &) {
		// Internal API: see https://github.com/emscripten-core/emscripten/issues/25963
		error = val::take_ownership(emscripten::internal::_emval_from_current_cxa_exception());
	}
	try {
		error.throw_();
	} catch (const std::runtime_error &ex) {
		std::clog << "Caught: " << ex.what() << '\n';
	}
}
```

```shell
em++ ./rethrow.cpp -o ./rethrow -lembind -fexceptions -std=c++20 -v
```

<details>
<summary>Compile log</summary>

```
 "/home/swdv/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/home/swdv/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -fexceptions -std=c++20 -v -c ./rethrow.cpp -o /tmp/emscripten_temp_pi6iqhvl/rethrow.o
clang version 23.0.0git (https:/github.com/llvm/llvm-project b6e5e8ecb57088dcdc0a72515869a52d24669bdd)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/swdv/emsdk/upstream/bin
Build config: +assertions
 (in-process)
 "/home/swdv/emsdk/upstream/bin/clang-23" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -main-file-name rethrow.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb -fdebug-compilation-dir=/home/swdv/webtest -v -fcoverage-compilation-dir=/home/swdv/webtest -resource-dir /home/swdv/emsdk/upstream/lib/clang/23 -D EMSCRIPTEN -isysroot /home/swdv/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/swdv/emsdk/upstream/lib/clang/23/include -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include -std=c++20 -fdeprecated-macro -ferror-limit 19 -fmessage-length=120 -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_pi6iqhvl/rethrow.o -x c++ ./rethrow.cpp
clang -cc1 version 23.0.0git based upon LLVM 23.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/swdv/emsdk/upstream/lib/clang/23/include
 /home/swdv/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 /home/swdv/emsdk/upstream/bin/clang --version
 /home/swdv/emsdk/upstream/bin/wasm-ld -o ./rethrow.wasm /tmp/tmpazlgyhzilibemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__getTypeName --export=__cxa_can_catch --export=__cxa_increment_exception_refcount --export=__cxa_decrement_exception_refcount --export=setThrew --export=__cxa_free_exception --export=__wasm_call_ctors --export=_emscripten_stack_restore --export=__get_exception_message --export=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1 /tmp/emscripten_temp_pi6iqhvl/rethrow.o -lembind-rtti -L/home/swdv/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -L/home/swdv/emsdk/upstream/emscripten/src/lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-debug -lc++abi-debug -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
 /home/swdv/emsdk/upstream/bin/llvm-objcopy ./rethrow.wasm ./rethrow.wasm '--remove-section=.debug*' --remove-section=producers --remove-section=name
 /home/swdv/emsdk/node/22.16.0_64bit/bin/node /home/swdv/emsdk/upstream/emscripten/tools/compiler.mjs -
```
</details>

```
RuntimeError: memory access out of bounds
    at wasm://wasm/00128e82:wasm-function[1445]:0x428ec
    at /home/swdv/webtest/rethrow:609:12
    at getExceptionMessageCommon (/home/swdv/webtest/rethrow:4706:7)
    at getExceptionMessage (/home/swdv/webtest/rethrow:4719:38)
    at new CppException (/home/swdv/webtest/rethrow:334:21)
    at ___resumeException (/home/swdv/webtest/rethrow:1165:25)
    at wasm://wasm/00128e82:wasm-function[54]:0x1b32
    at wasm://wasm/00128e82:wasm-function[99]:0x2dde
    at /home/swdv/webtest/rethrow:609:12
    at callMain (/home/swdv/webtest/rethrow:5726:15)
```

Compare with `-fwasm-exceptions`, which prints `Caught: oopsie`, as intended.

# Probable cause

It seems the cause may be as follows:

- `___cxa_end_catch` sets `exceptionLast = 0;` after the first C++ catch
  https://github.com/emscripten-core/emscripten/blob/3407c1926169f66efacf45bc57b1d5e87525717e/src/lib/libexceptions.js#L172-L173
- Later in JS `findMatchingCatch` sees `exceptionLast` is not set, causing the error
  https://github.com/emscripten-core/emscripten/blob/3407c1926169f66efacf45bc57b1d5e87525717e/src/lib/libexceptions.js#L218-L229

When thrown from C++, `___cxa_throw`/`___cxa_rethrow` would set `exceptionLast`, but that doesn't happen when rethrown from JS.

I don't think removing `exceptionLast = 0;` would solve it, because then I think it may rethrow the wrong exception. EDIT: It will rethrow the wrong exception and already does in other cases, see comment below.

# Version

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.1-git (14fc538fa0947e5e1b1097df6b36eedd5b3b68f7)
clang version 23.0.0git (llvm/llvm-project@b6e5e8ecb57088dcdc0a72515869a52d24669bdd)

### PR DESCRIPTION
**Pull request by aheejin**
When `_emval_throw` throws an instance of C++ exception in Emscripten EH mode, it needs to update `exceptionLast` accordingly, as we do in `__cxa_throw` and `__cxa_rethrow` in `src/lib/libexceptions.js`: 
https://github.com/emscripten-core/emscripten/blob/2d257177915c49c807a3e03d6f404173bb4e5e72/src/lib/libexceptions.js#L100

Here we can't use `storeException` because we are not creating a C++ exception from scratch; we are throwing an already created C++ exception.

Fixes #26213.

### CODE REVIEW

File: src/lib/libemval.js [hunk 1]
```diff
@@ -395,6 +395,20 @@ ${functionBody}
...
+#if !WASM_EXCEPTIONS
+    // If we are throwing Emcripten C++ exception, set exceptionLast, as we do
+    // in __cxa_throw. When EXCEPTION_STACK_TRACES is set, a C++ exception is an
+    // instance of EmscriptenEH, and when it is not set, a number.
+#if EXCEPTION_STACK_TRACES
+    if (object instanceof EmscriptenEH) {
+      exceptionLast = object;
+    }
+#else
+    if (object === object+0) { // Check if it is a number
```
Comment (sbc100) [inline src/lib/libemval.js:421]: Why check if its a number?    Is this trying to check if its a pointer maybe?

File: test/embind/test_embind_throw_cpp_exception.cpp [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+    error = val::take_ownership(
+      emscripten::internal::_emval_from_current_cxa_exception());
+  }
+  try {
+    throw std::runtime_error("this is bad");
+  } catch (const std::runtime_error&) {
+    try {
+      error.throw_(); // Rethrow oopsie
+    } catch (const std::runtime_error& ex) {
+      std::clog << "Caught: " << ex.what() << '\n';
```
Comment (sbc100) [inline test/embind/test_embind_throw_cpp_exception.cpp]: Maybe these should be Caught1 and Caught2 so there appear separate in the output?

File: src/lib/libemval.js [hunk 3]
```diff
@@ -395,6 +395,20 @@ ${functionBody}
   _emval_throw__deps: ['$Emval'],
   _emval_throw: (object) => {
     object = Emval.toValue(object);
+#if !WASM_EXCEPTIONS
+    // If we are throwing Emcripten C++ exception, set exceptionLast, as we do
+    // in __cxa_throw. When EXCEPTION_STACK_TRACES is set, a C++ exception is an
+    // instance of EmscriptenEH, and when it is not set, a number.
```
Comment (sbc100) [inline src/lib/libemval.js]: Maybe need some more context in the comment here regarding why we cannot share code with `__cxa_rethrow` `__cxa_throw`, `storeException`, etc?

File: src/lib/libemval.js (hunk 1 above)
Comment (aheejin) [reply src/lib/libemval.js:421]: It's checking whether it's a C++ exception. Generated `invoke_`s would look like, when `EXCEPTION_STACEK_TRACES==1`,
```js
function invoke_vi(index,a1) {
  var sp = stackSave();
  try {
    getWasmTableEntry(index)(a1);
  } catch(e) {
    stackRestore(sp);
    if (!(e instanceof EmscriptenEH)) throw e;
    _setThrew(1, 0);
  }
}
```
When `EXCEPTION_STACK_TRACES==0`,
```js
function invoke_vi(index,a1) {
  var sp = stackSave();
  try {
    getWasmTableEntry(index)(a1);
  } catch(e) {
    stackRestore(sp);
    if (e !== e+0) throw e;
    _setThrew(1, 0);
  }
}
```

This is generated here:
https://github.com/emscripten-core/emscripten/blob/2d257177915c49c807a3e03d6f404173bb4e5e72/tools/js_manipulation.py#L138-L146

Updated the comment a little: https://github.com/emscripten-core/emscripten/pull/26276/commits/49e5c2aae5b077b5ec14a039f21798182a5d167c

File: test/embind/test_embind_throw_cpp_exception.cpp (hunk 2 above)
Comment (aheejin) [reply test/embind/test_embind_throw_cpp_exception.cpp]: Done: https://github.com/emscripten-core/emscripten/pull/26276/commits/e327a563746198c2da095a0035b92ad24f5c975f

File: src/lib/libemval.js (hunk 3 above)
Comment (aheejin) [reply src/lib/libemval.js]: Done: https://github.com/emscripten-core/emscripten/pull/26276/commits/dc7af59bcd37c3aaec68faf02ffaffb826bb25cb
Basically, if we use `storeException` here, we can do something like `CppException(CppException)`, wrapping an already existing `CppException` with `CppException` again.

**Review by sbc100 — COMMENTED** [review]
Seems reasonable to me.   Thanks for the extra context.   Maybe @brendandahl can give final lgtm

File: src/lib/libemval.js [hunk 4]
```diff
@@ -395,6 +395,30 @@ ${functionBody}
   _emval_throw__deps: ['$Emval'],
```
Comment (brendandahl) [inline src/lib/libemval.js]: Do we need to add a conditional dependency on `$exceptionLast` here?

Comment (aheejin) [reply src/lib/libemval.js]: I guess so..? Done: https://github.com/emscripten-core/emscripten/pull/26276/commits/44605ab5d5756742773898b769c3c2fc1cfe5a2e

File: src/lib/libemval.js [hunk 5]
```diff
@@ -392,9 +392,37 @@ ${functionBody}
     return delete object[property];
   },
 
-  _emval_throw__deps: ['$Emval'],
+  _emval_throw__deps: ['$Emval'
+#if !WASM_EXCEPTIONS
```
Comment (brendandahl) [inline src/lib/libemval.js:396]: style nit: most places use trailing commas e.g. https://github.com/emscripten-core/emscripten/blob/7e9b3ba12e952f42cebbebc17cc6bcb3ad54ec8c/src/lib/libcore.js#L2318-L2323

**Review by brendandahl — APPROVED** [review]
r+ w/ minor nit

File: src/lib/libemval.js (hunk 5 above)
Comment (aheejin) [reply src/lib/libemval.js:396]: Done: https://github.com/emscripten-core/emscripten/pull/26276/changes/6fecaecfe9ecea91adcf1ada144dced301d456f8

**Comment by stevenwdv** [comment]
Thanks for the fix!
I guess this does mean that JS users of bindings are not supposed to re-`throw` Emscripten exceptions inside code called from C++, as a regular JS `throw` will not set `exceptionLast`?
