### PR TITLE
Zero sin_zero when writing a sockaddr_in

### LINKED ISSUE #12998: getaddrinfo() doesn't set sin_zero in emulation
A funny bug that took a bit of time to track down:

`sockaddr_in` is described in POSIX as:

```
sa_family_t     sin_family   AF_INET. 
in_port_t       sin_port     Port number. 
struct in_addr  sin_addr     IP address. 
```
(https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html)

What it doesn't describe, it what happens with the last 8 bytes. In most OSes (Linux, BSD, Windows, ..) this is defined as `sin_zero`, and is zero'd.

For most functions dealing with `sockaddr_in`, the application is in charge of memory management, and as such, can zero the structure before it is being filled. Sadly, there is one function (that I know of) where the memory management is done by the library: `getaddrinfo`. And emscripten does not zero the last 8 bytes of `sockaddr_in`, resulting in funny bugs :)

In many applications, it is common to compare `sockaddr_in` with each other, to see if they are in fact the same address. It is quick, it is simple. The length used for this, is `sizeof(sockaddr_in)`. So .. I think you can see the problem now :D

With emscripten, comparing addresses does not work, well, it randomly works, heavily depending on what memory got `malloc`'d. It is very unpredictable.

So although not defined by POSIX, but implemented by any OS I know of, would it be wise for emscripten to also zero these bytes? (honest question, as it is not by any specs; but is by convention).

The malloc is done here:
https://github.com/emscripten-core/emscripten/blob/9e0303729419d2beac5143dd68c3e3a361fd574e/src/library.js#L2458
And no zero'ing is done. Neither in `_write_sockaddr`.

This is btw an old problem .. searching online shows the frustration people have with the POSIX specs:
https://silviocesare.wordpress.com/2007/10/22/setting-sin_zero-to-0-in-struct-sockaddr_in/
http://lists.kernelnewbies.org/pipermail/kernelnewbies/2011-February/000966.html

For good measure, here is libc doing the zero'ing:
https://code.woboq.org/userspace/glibc/sysdeps/posix/getaddrinfo.c.html#1114

Tnx for considering!

### PR DESCRIPTION
**Pull request by TrueBrain**
Although not strictly defined by POSIX, it is done by most (all?)
other implementations, most often in patches over the years as
places got forgotten.
This is mostly useful to allow quick comparing between sockaddr_in
to see if they are the same address.

Fixes #12998

----

I made the change for `write_sockaddr`, as this is basically what the linux kernel is doing too: when ever `sin_family`/`sin_addr`/`sin_port` is written, also write `sin_zero`. But this is open for preference, I guess.

Examples of this can be found throughout libc and the kernel. It is fun to run a `git blame` on those lines, just to see how often this got fixed over time again and again in :)
https://github.com/torvalds/linux/blob/9ff9b0d392ea08090cd1780fb196f36dbb586529/net/ipv4/raw.c#L789

### CODE REVIEW

**Comment by sbc100** [comment]
C_STRUCTS.sockaddr_in.sin_size.__size__ should work..  at least it seems to be present in the json:

cache/wasm/generated_struct_info.json:

```
        "sockaddr_in": {                                                         
            "__size__": 16,                                                      
            "sin_addr": {                                                        
                "__size__": 4,                                                   
                "s_addr": 4                                                      
            },                                                                   
            "sin_family": 0,                                                     
            "sin_port": 2,                                                       
            "sin_zero": 8                                                                                            
        },  
```

So the json file knows that its 8 bytes in size.

**Comment by sbc100** [comment]
You wrong `sin_size` rather than `sin_zero` in your PR description.. maybe that is the reason?

**Comment by TrueBrain** [comment]
If I do:
`{{{ C_STRUCTS.sockaddr_in.sin_zero.__size__ }}}`

It returns with:

```
error: failure to process js library "library.js": TypeError: Cannot read property 'toString' of undefined,
error: use -s VERBOSE to see more details
```

`{{{ C_STRUCTS.sockaddr_in.sin_zero }}}` for example does work. Not sure how to look further into that error?

(and oops, that is a typo in the PR description, let me fix that too :D)

**Comment by sbc100** [comment]
Oh .. maybe the size of each element of a struct isn't reported via that system.

I guess we can choose between using `{{{ C_STRUCTS.sockaddr_in.sin_zero }}}` and hardcoding 8 or calling out to memset the whole thing?

**Comment by TrueBrain** [comment]
Okay, that brings me to the next question: `_memset` is not working, as in, it tells me it cannot find `memset` during the tests. I do not really know how to fix that, as the other examples that do use `memset` do it magically :D (I am very good at looking at existing code and copying from it .. but understanding it, I do not :D)

I also don't know if `memset` is needed btw, or that my currently solution is fine too.

**Comment by sbc100** [comment]
Getting memset to work from here depends on injecting the memset dependency via `tools/deps_info.py`.

The problem is that memset is a native function and so the native linker (lld) needs to be aware that it should not DCE it at link time.    Native linking occurs before the JS library file are parsed.   

I think the solution is to add `memset` to all JS functions that indirectly call `_write_sockaddr` in `tools/deps_info.py`.

**Comment by TrueBrain** [comment]
Thank you for the pointers! That does make sense, but I would not have figured that out myself :D

I calculated the size simply by doing the total size of `sockaddr_in` minus the position of `sin_zero`. That is also 8, and looks a bit nicer I think :)

Yippie, it is a `memset` now, the world is sane again :D

**Comment by TrueBrain** [comment]
Hello!

I just rebased this PR, to resolve the conflicts; hopefully making life a bit easier on you :)

Is there is anything else I can do to help this PR get merged? Please do let me know if so; would love to have this merged upstream, as it would remove a few hacks in our own codebase :D

Tnx!

File: src/library.js [hunk 1]
```diff
@@ -2304,6 +2304,7 @@ LibraryManager.library = {
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_family, 'family', 'i16') }}};
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_addr.s_addr, 'addr', 'i32') }}};
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_port, '_htons(port)', 'i16') }}};
+        _memset(sa + {{{ C_STRUCTS.sockaddr_in.sin_zero }}}, 0, {{{ C_STRUCTS.sockaddr_in.__size__ - C_STRUCTS.sockaddr_in.sin_zero }}});
```
Comment (sbc100) [inline src/library.js:2307]: We use makeSetValue with i64 to avoid the `_memset` dependency?   

We can add a compile time assert to check its valid.   `{{{ assert(C_STRUCTS.sockaddr_in.__size__ - C_STRUCTS.sockaddr_in.sin_zero == 8) }}}`

Comment (TrueBrain) [reply src/library.js:2307]: Sure, I will do that in a bit.

Just for my education, is there any issue with creating the `_memset` dependency? Other places uses it too, which makes me wonder why that would be an issue :)

Comment (sbc100) [reply src/library.js:2307]: Its just that it adds code size I think.

We should probably audit the various places we use it in JavaScript and try to be consistent.  There are several places IIRC where we use a loop in JS instead.  For example: https://github.com/emscripten-core/emscripten/blob/585c5e6990c6bb54c437ee18dc658bc4f958c36b/src/library_pthread.js#L757

@kripken @juj do you two think?  When should we use _memset and when should we not?  Is it just a code size consideration?  Perhaps we could make a `{{{ doMemset }}}` replacement that could do `if (memset_exported) return "_memset" else return "memsetInJs` ?

Comment (TrueBrain) [reply src/library.js]: Yeah, adding code size over this would be a bit unneeded :)

Changed it to `makeSetValue` with an `assert` guarding it; works as well as memset, and makes the PR looks nice and tiny :D Tnx!

File: src/library.js [hunk 2]
```diff
@@ -2304,6 +2304,9 @@ LibraryManager.library = {
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_family, 'family', 'i16') }}};
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_addr.s_addr, 'addr', 'i32') }}};
         {{{ makeSetValue('sa', C_STRUCTS.sockaddr_in.sin_port, '_htons(port)', 'i16') }}};
+        /* Use makeSetValue instead of memset to avoid adding memset dependency for all users of _write_sockaddr. */
+        assert({{{ C_STRUCTS.sockaddr_in.__size__ - C_STRUCTS.sockaddr_in.sin_zero }}} == 8);
```
Comment (juj) [inline src/library.js:2308]: I wonder if this would work as a "static assert", like `{{{ assert(C_STRUCTS.sockaddr_in.__size__ - C_STRUCTS.sockaddr_in.sin_zero) == 8); }}}`?

If not, then let's wrap this line behind
```
#if ASSERTIONS
assert(...);
#endif
```
block, since in release build in MINIMAL_RUNTIME, the assert() function does not exist.

File: src/library.js (hunk 1 above)
Comment (juj) [reply src/library.js]: A `{{{ doMemSet(ptr, align, size) }}}` function does sound fine to me - it could compile-time unroll some small values in -O1 and higher, cutoff value perhaps depending on the -On level, and in -Os values beyond the cutoff could call to a JS function to do the job, if memset was not exported.

Btw, is there a way to have a generic `#if is_exported('memset')` functionality in JS code? Would prefer that over special-casing `memset` symbol specifically for this. That might allow creating quite tight code size aware codegen in user JS libraries.

File: src/library.js (hunk 2 above)
Comment (TrueBrain) [reply src/library.js:2308]: It works if I do this:

`{{{ assert(C_STRUCTS.sockaddr_in.__size__ - C_STRUCTS.sockaddr_in.sin_zero == 8), '' }}}`

I just have no clue what that `, ''` is doing; I just searched for existing instances of `{{{ assert` and `library_syscall.js` does it like this :D Would that be fine?

Otherwise I can ifdef it indeed, many other places do it like that too :)

File: src/library.js (hunk 1 above)
Comment (sbc100) [reply src/library.js]: Yes you can say `#if '_malloc' in IMPLEMENTED_FUNCTIONS`

File: src/library.js (hunk 2 above)
Comment (sbc100) [reply src/library.js]: I think the thing in the `{{{ ... }}}` has to resolve to a string.   Perhaps we could make it more flexible?  But it seems OK for now.

**Review by sbc100 — APPROVED** [review]

File: src/library.js (hunk 1 above)
Comment (kripken) [reply src/library.js]: A `doMemSet` sounds good to me too.

@juj 

> Btw, is there a way to have a generic #if is_exported('memset')

Yes, you can do stuff like
```
#if hasExportedFunction('_main')
```
