### PR TITLE
[EH] Print message for uncaught exceptions

### LINKED ISSUE #6330: throw exception with message in cpp
I have a cpp file test.cpp:
```
#include <stdio.h>
#include <iostream>
#include <emscripten/bind.h>
#include <emscripten/val.h>

int main()
{
  throw std::invalid_argument("test error");
  
  printf("\ndone\n");
  return 0;
}
```
Compiled with `emcc --bind -fexceptions -std=c++11 test.cpp -o test.js`

I would like the code to print out the exception message in some way so the user has a description of the error.
When I run it I get `exception thrown: 5246984` and `Uncaught 5246984`.
It does not appear as though emscripten will print any distinguishable message.
Does emscripten have this feature?

If not, I was thinking of adding a `thow` method to `val` that would accept a message and possibly a javascript exception class.

### PR DESCRIPTION
**Pull request by aheejin**
After #17979, when `ASSERTIONS` is set, uncaught exceptions carry stack traces that are printed to the screen for debugging help. This adds an exception message to the exception objects in addition to that.

The message it adds is produced by `__get_exception_message` function: https://github.com/emscripten-core/emscripten/blob/f6c46570e3780e52050bf822a07b342ec4bdddbe/system/lib/libcxxabi/src/cxa_exception_emscripten.cpp#L75-L111

If an exception is a subclass of `std::exception`, it returns `std::exception::what()`. If not, it just prints its type.

If an exception is uncaught and its type is a subclass of `std::exception`, now we print the `what()` message along with the stack trace when `ASSERTION` is set. In case our exception is `std::runtime_error` and the message is "my exception", when uncaught, this prints:
```console
exiting due to exception: [object WebAssembly.Exception],Error: std::runtime_error,my exception
    at __cxa_throw (wasm://wasm/009a7c9a:wasm-function[1551]:0x24367)
    ...
```

Fixes #6330.

### CODE REVIEW

File: system/lib/libcxxabi/src/cxa_exception.cpp [hunk 1]
```diff
@@ -293,7 +293,7 @@ __cxa_throw(void *thrown_object, std::type_info *tinfo, void (*dest)(void *)) {
 #else
     // In debug mode, call a JS library function to use WebAssembly.Exception JS
     // API, which enables us to include stack traces
-    __throw_exception_with_stack_trace(&exception_header->unwindHeader, true);
+    __throw_exception_with_stack_trace(&exception_header->unwindHeader);
```
Comment (aheejin) [inline system/lib/libcxxabi/src/cxa_exception.cpp:296]: This is what I should've deleted in #17979 and forgot.

**Comment by aheejin** [comment]
Will convert this as a draft while fixing CI errors.

**Review by sbc100 — APPROVED** [review]

File: test/test_other.py [hunk 2]
```diff
@@ -7921,8 +7923,8 @@ def test_wasm_exceptions_stack_trace(self):
     emcc_args = ['-g', '-fwasm-exceptions']
     self.v8_args.append('--experimental-wasm-eh')
 
-    # Stack trace example for this example code:
-    # exiting due to exception: [object WebAssembly.Exception],Error
+    # Stack trace and message example for this example code:
+    # exiting due to exception: [object WebAssembly.Exception],Error: std::runtime_error, my message
```
Comment (RReverser) [inline test/test_other.py:7927]: Unrelated, but I wonder if we could drop the `[object WebAssembly.Exception],` here. It seems to be just unnecessary visual noise.

**Review by RReverser — APPROVED** [review]
This is great, thanks!

**Review by kripken — APPROVED** [review]
Nice!

File: test/test_other.py (hunk 2 above)
Comment (aheejin) [reply test/test_other.py:7927]: I don't think It's easy to consistently take out that part, because different engines can have different error formats. For example, d8 prints:
```console
main
foo
bar
exiting due to exception: [object WebAssembly.Exception],Error: std::runtime_error,my message
    at __cxa_throw (wasm://wasm/00462286:wasm-function[44]:0x3b0f)
    at bar() (wasm://wasm/00462286:wasm-function[9]:0x98c)
    at foo() (wasm://wasm/00462286:wasm-function[10]:0x992)
    at __original_main (wasm://wasm/00462286:wasm-function[11]:0x9c4)
    at main (wasm://wasm/00462286:wasm-function[12]:0x9e1)
    at test.js:934:22
    at callMain (test.js:1874:15)
    at doRun (test.js:1928:23)
    at run (test.js:1943:5)
```

Whereas Node prints:
```console
/usr/local/google/home/aheejin/test/stack/test.js:147
      throw ex;
      ^

WebAssembly.Exception: std::runtime_error,my message
    at __cxa_throw (wasm://wasm/00462286:wasm-function[44]:0x3b0f)
    at bar() (wasm://wasm/00462286:wasm-function[9]:0x98c)
    at foo() (wasm://wasm/00462286:wasm-function[10]:0x992)
    at __original_main (wasm://wasm/00462286:wasm-function[11]:0x9c4)
    at main (wasm://wasm/00462286:wasm-function[12]:0x9e1)
    at /usr/local/google/home/aheejin/test/stack/test.js:934:22
    at callMain (/usr/local/google/home/aheejin/test/stack/test.js:1874:15)
    at doRun (/usr/local/google/home/aheejin/test/stack/test.js:1928:23)
    at run (/usr/local/google/home/aheejin/test/stack/test.js:1943:5)

Node.js v17.5.0
```

So while both of them have `WebAssembly.Exception`, their printing formats differ, making taking it out in a consistent way difficult. We can just simply replace `WebAssembly.Exception` with an empty string, but not sure if that's better..?

Comment (sbc100) [reply test/test_other.py:7927]: Leaving it as is sounds fine for to me then.   We can attempt to refine in a followup perhaps.
