### PR TITLE
fix(mmap): handle over-allocated files

### LINKED ISSUE #10527: mmap on expanded files writes beyond allocated memory
When appending to a file, the buffer size is increased in chunks, and so the actual length of the file could be less than the length of the allocated buffer.

When using mmap on an such a file, content from the over-allocated buffer is being written beyond the allocated memory - causing corruption.

### PR DESCRIPTION
**Pull request by petersalomonsen**
fix for not writing buffer contents from expanded files beyond allocated memory
    
fixes #10527

### CODE REVIEW

File: tests/fs/test_mmap.c [hunk 1]
```diff
@@ -176,5 +176,53 @@ int main() {
...
+        assert(stream.node.contents.length > stream.node.usedBytes,
+          'Used bytes on the expanded file (' + stream.node.usedBytes+ ') ' +
+          'should be less than the length of the content buffer (' + stream.node.contents.length + ')'
+        );
+        stream.node.contents[stream.node.usedBytes] = 98; // 'b', we don't want to see this in the mmap area
+    }, textsize);
+
+    char *map;
+    
+    map = (char*)mmap(NULL, textsize, PROT_READ, 0, fd, 0);
```
Comment (sbc100) [inline tests/fs/test_mmap.c]: these two lines can be a single line.

File: tests/fs/test_mmap.c [hunk 2]
```diff
@@ -176,5 +176,53 @@ int main() {
...
+   * When appending to a file, the buffer is expanded in chunks, and so the actual length
+   * of the file could be less than the buffer length.
+   * 
+   * When using mmap for an expanded file, we have to make sure that content from the buffer
+   * is not written beyond the allocated memory area for the mmap operation.
+   */
+  {
+    const char* path = "/yolo/expandedfile.txt";
+
+    int fd = open(path, O_RDWR | O_CREAT, (mode_t)0600);
```
Comment (sbc100) [inline tests/fs/test_mmap.c]: Just inline path since its only used once.

File: tests/fs/test_mmap.c [hunk 3]
```diff
@@ -176,5 +176,53 @@ int main() {
...
+    assert(fd != -1);
+
+    size_t textsize = 33;
+
+    // multiple calls to write so that the file is expanded
+    for(int n=0;n<textsize;n++) {
```
Comment (sbc100) [inline tests/fs/test_mmap.c]: space after `for` and between all the operators.

File: tests/fs/test_mmap.c [hunk 4]
```diff
@@ -176,5 +176,53 @@ int main() {
     printf("/yolo/sharedoffset.txt content=%s %d\n", buffer + offset, offset);
     fclose(fd);
   }
+
+  /**
+   * MMAP to and expanded file
```
Comment (sbc100) [inline tests/fs/test_mmap.c]: Is "expanded file" terminology that is used elsewhere?  How about "over-allocated memfs file"?

Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: I chose the term `expanded file` because the "expansion" is done by a method called `expandFileStorage` which you can see here:

https://github.com/emscripten-core/emscripten/blob/0e4bb329e5eba4e7b16e3ceaaa0aae7a09e257ad/src/library_memfs.js#L115

File: tests/fs/test_mmap.c (hunk 1 above)
Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: should be ok now

File: tests/fs/test_mmap.c (hunk 2 above)
Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: should be ok now

File: tests/fs/test_mmap.c (hunk 3 above)
Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: looking better now?

**Comment by petersalomonsen** [comment]
thanks for the review @sbc100  :-) Would be great to have this merged.

https://github.com/libgit2/libgit2/pull/5345 depends on this

**Comment by sbc100** [comment]
@kripken  can you give final lgtm here?

File: tests/fs/test_mmap.c (hunk 4 above)
Comment (sbc100) [reply tests/fs/test_mmap.c]: To me `expanded file` doesn't hold the right meaning.    The `expandFileStorage` may or may not over-allocate, right?  But its the fact the you over-allocate the storage that is key here IIUC, no?      I could be wrong.. I didn't write the memfs code so maybe `expanded file` means more to the authors of this code.

Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: when appending to a file `expandFileStorage` will increase the buffer size for that file more than the bytes requested to be written. This is to avoid having to increase the buffer for every call to write (which would be very slow). So instead the actual file size is tracked in a separate property called `usedBytes`.

mmap allocates memory based on the `usedBytes`, and calls javascripts ArrayBuffer `set` method on the heap with the files buffer as parameter. The `set` method has no parameter for the length, and so it copies the full contents of the file buffer. To avoid copying more than the actual file size the file buffer is sliced before calling `set`, but before this fix, slicing would only occur if the requested length was less than used bytes (which is mostly not the case if mapping the entire file). So instead the criteria for slicing must be if the requested length is less than the length of the file buffer - which is normally more than `usedBytes` for `expanded files`.

Comment (petersalomonsen) [reply tests/fs/test_mmap.c]: but yes - `expandFileStorage` does over-allocate file storage in that sense. Just wouldn't confuse it with over-allocating of heap, since the case here is that mmap writes beyond what it allocated on the heap.

not sure what the best term here is though. Maybe we need more opinions?

Comment (sbc100) [reply tests/fs/test_mmap.c]: I guess you could call it "over-sized" if you prefer?  But I think over-allocated is pretty clear and applies to any object that is larger than needs to be to make room for future expansion.    We can let @kripken have the final say :)

Comment (kripken) [reply tests/fs/test_mmap.c]: I don't have a strong opinion on the term, but "over-allocated" does seem pretty reasonable, let's change to that?

Also `and` should be `an` in the comment.

**Comment by petersalomonsen** [comment]
`over-allocated` it is then :-)

Thanks for reviewing!
