### PR TITLE
Fixes PROXYFS error check

### LINKED ISSUE #18715: PROXYFS bug (with a fix)
As I tried to make multiple modules sharing FS of one Main module using PROXYFS, I had a strange bug and traced it up to syscalls.

The reason was that `e instanceof FS.ErrnoError` returned false, even though the `e` was the `FS.ErrnoError`.

That was because `e` was actually `instanceof` *another* `FS.ErrnoError`, coming from another FS. As each FS object has its own `FS.ErrnoError`.

This problem is typical for JS, and the solution is also typical: replace `e instanceof FS.ErrnoError` with `e.constructor.name == 'ErrnoError'`.

Filed PR.

### PR DESCRIPTION
**Pull request by iliakan**
Make the check work reliably cross-FS.

Fixes #18715

### CODE REVIEW

File: src/library_fs.js [hunk 1]
```diff
@@ -1421,6 +1421,7 @@ FS.staticInit();` +
     ensureErrnoError: () => {
       if (FS.ErrnoError) return;
       FS.ErrnoError = /** @this{Object} */ function ErrnoError(errno, node) {
+        this.name = 'ErrnoError';
```
Comment (kripken) [inline src/library_fs.js:1424]: Please add a comment here explaining why we prefer to use the name to identify instances.

**Review by kripken — CHANGES_REQUESTED** [review]
Thanks, this looks good to me with one minor comment.

File: src/library_fs.js (hunk 1 above)
Comment (iliakan) [reply src/library_fs.js:1430]: Added.

File: src/library_syscall.js [hunk 2]
```diff
@@ -1061,7 +1061,7 @@ function wrapSyscallFunction(x, library, isWasi) {
     pre += 'try {\n';
     handler +=
     "} catch (e) {\n" +
-    "  if (typeof FS == 'undefined' || !(e instanceof FS.ErrnoError)) throw e;\n";
+    "  if (typeof FS == 'undefined' || !(e.name === 'ErrnoError')) throw e;\n";
```
Comment (sbc100) [inline src/library_syscall.js:1064]: I think we maybe need to think a little more carefully about this.  I think maybe the arguments made in https://github.com/emscripten-core/emscripten/pull/16994#discussion_r960379197 may apply here.

If we do want to make this code work between 2 different emscripten instances I think we should have some testing of that mode, and also make sure that doesn't effect the code size for folks who don't need/want that.

Comment (kripken) [reply src/library_syscall.js:1064]: I agree with @sbc100 that a test would be good for this. Otherwise I think this makes sense to do for the reasons you said @iliakan - `instanceof` is just brittle in JS, unfortunately (due to iframes etc.).

Comment (iliakan) [reply src/library_syscall.js:1064]: > I agree with @sbc100 that a test would be good for this. Otherwise I think this makes sense to do for the reasons you said @iliakan - `instanceof` is just brittle in JS, unfortunately (due to iframes etc.).

So you suggest to write a test that fails without my PR, but succeeds with it?

Comment (sbc100) [reply src/library_syscall.js:1064]: I'm actually not sure about this patch at all.   If you are trying to import/use the FS object from another module why wouldn't you also import its `FS.ErrnoError`?   In that mode wouldn't you want to completely avoid declaring `FS` (or `FS.ErrnoError`) in the consumer module?

Comment (sbc100) [reply src/library_syscall.js:1064]: i.e. if you want module to somehow share and FS then only one of them should declare the FS, right?

Comment (iliakan) [reply src/library_syscall.js:1064]: I added the test that demonstrates the bug on the current HEAD, and it's fixed in my branch.

P.S. Thank you for fast consideration of the PR. I almost forgot what the issue was exactly, but easily managed to remember and write it out.

File: test/test_other.py [hunk 3]
```diff
@@ -3294,6 +3293,22 @@ def test_proxyfs(self):
...
+section = "child m1 accesses local file.";
+print("m1 access existing");
+m1.ccall('myaccess1existing','number',[],[]);
+print("m1 access absent");
+m1.ccall('myaccess1absent','number',[],[]);
+
+
+
+
+
```
Comment (sbc100) [inline test/test_other.py:3311]: Remove all but one of these newlines?

**Review by sbc100 — APPROVED** [review]
I see this is needed for the existing PROXYFS filesystem.

File: test/test_other.py (hunk 3 above)
Comment (iliakan) [reply test/test_other.py]: Whoops. Done.

**Comment by sbc100** [comment]
@kripken I think you need to accept these changes before we can land.

**Review by kripken — APPROVED** [review]
