### PR TITLE
mmap() fixes

### LINKED ISSUE #11565: mmap() doesn't zero-fill to next page boundary
In the Chrome Wasm Debugging extension we're running LLDB compiled to WebAssembly, and with `ASSERTIONS=1` we are constantly hitting an `assert` inside of LLVM. It seems that LLVM expects `mmap()` to zero fill up to page boundaries and that's what the `assert` is checking for.

```
Error in debugger language plugin: abort(Assertion failed: (!RequiresNullTerminator || BufEnd[0] == 0) && "Buffer is not null terminated!", at: /usr/local/google/home/bmeurer/Projects/devtools/devtools-frontend/back_end/CXXDWARFSymbols/third_party/llvm/llvm/lib/Support/MemoryBuffer.cpp,48,init) at Error
    at jsStackTrace (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.js:1905:12)
    at stackTrace (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.js:1920:11)
    at abort (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.js:1743:43)
    at ___assert_fail (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.js:1926:2)
    at llvm::ErrorOr<std::__2::unique_ptr<llvm::MemoryBuffer, std::__2::default_delete<llvm::MemoryBuffer> > > getOpenFileImpl<llvm::MemoryBuffer>(int, llvm::Twine const&, unsigned long long, unsigned long long, long long, bool, bool) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[60681]:0x2e89001)
    at llvm::ErrorOr<std::__2::unique_ptr<llvm::MemoryBuffer, std::__2::default_delete<llvm::MemoryBuffer> > > getFileAux<llvm::MemoryBuffer>(llvm::Twine const&, long long, unsigned long long, unsigned long long, bool, bool) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[60678]:0x2e8891b)
    at llvm::MemoryBuffer::getFile(llvm::Twine const&, long long, bool, bool) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[60680]:0x2e88a56)
    at lld::wasm::readFile(llvm::StringRef) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[31072]:0x1956c2f)
    at lld::wasm::(anonymous namespace)::LinkerDriver::addFile(llvm::StringRef) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[31001]:0x19514c3)
    at lld::wasm::(anonymous namespace)::LinkerDriver::link(llvm::ArrayRef<char const*>) (chrome-extension://fflabmagbbdmpbpdplhpedlmnbjgakhm/SymbolsBackend.wasm:wasm-function[30992]:0x194ea9b) (EXTENSION_ERROR)
```

Looking into `mmap(2)` on my Linux box I see this

```
A file is mapped in multiples of the page size.  For a file that is not a multiple of the page size, the  remaining
memory  is  zeroed  when mapped, and writes to that region are not written out to the file.
```

so it seems that the assumption in LLVM makes sense.

Emscripten however (with MEMFS) doesn't zero-fill up to the next page boundary, and in fact, doesn't even allocate in page granularity, but just uses `_malloc(length)`.

cc @pfaffe

### PR DESCRIPTION
**Pull request by kripken**
Fixes  #11565 

The issue noticed there is that we don't expand to the page size, and don't
zero out memory. Those are fixed here. It's hard to test that though as those
details are really only noticeable internally or through undefined behavior
IIUC (e.g. we could mmap, munmap, then mmap again and check that it
was zeroed, but we'd need to ensure it wasn't just given a new block of
memory by malloc which is zeroes anyhow - other ideas?).

Also fixes `other.test_mmap_and_munmap` which this showed was
depending on *not* zero-initializing: it was off by one, and got lucky that
we didn't zero and also we got malloced the exact same region as before,
where the data we expected was present.

### CODE REVIEW

**Comment by sbc100** [comment]
I wonder if all the mmap code can be moved in native code?   It seems like since its completely fake it should be possible implement simple based on malloc+open+read avoiding any JS imports.   Then it would work in standalone mode too (assuming we move open+read to wasi syscalls too).   Not related to this PR I guess though.

File: tests/mmap_and_munmap/test.cpp [hunk 1]
```diff
@@ -74,16 +74,19 @@ int test_mmap_write() {
 
     char *m = (char *)mmap(NULL, file_len(), PROT_READ | PROT_WRITE, MAP_SHARED, fileno(f_rw), 0);
     ASSERT(m != MAP_FAILED, "Failed to mmap file");
+    // Reverse the data in the mapped file in memory, which should be written
+    // out.
     for (size_t i = 0; i < file_len(); ++i) {
-        size_t k = file_len() - i;
+        size_t k = file_len() - i - 1;
```
Comment (sbc100) [inline tests/mmap_and_munmap/test.cpp:80]: How did this bug not fail the test previously?

Comment (kripken) [reply tests/mmap_and_munmap/test.cpp:80]: See the last paragraph in the description: it was off by one, and got lucky that we didn't zero and also we got malloced the exact same region as before, where the data we expected was present. So it wrote some data to memory, then read that data back - in the middle we were supposed to zero out the memory as part of mmap, but didn't, so it still had the data.

**Comment by kripken** [comment]
It's a little hard to move the current mmap code into C since it's part of the JS filesystem support. But perhaps in the new AsmFS we can do it better.

File: src/library_fs.js [hunk 2]
```diff
@@ -2021,6 +2021,15 @@ FS.staticInit();` +
...
       };
       openRequest.onerror = onerror;
+    },
+
+    // Allocate memory for an mmap operation. This allocates space of the right
+    // page-aligned size, and clears it.
+    mmapAlloc: function(size) {
+      size = alignMemory(size, {{{ POSIX_PAGE_SIZE }}});
+      var ptr = _malloc(size);
+      Array.prototype.fill.call(HEAP8, 0, ptr, ptr + size)
```
Comment (bmeurer) [inline src/library_fs.js:2031]: This is quite slow for two reasons:

1. We zero the full memory, even though it would be sufficient to zero out the last page (actually just the padding bytes).
2. `Array#fill()` on a typed array is not particularly fast in today's JSVMs. it'd be better to just have a handrolled loop here.

WDYT?

Comment (kripken) [reply src/library_fs.js:2031]: Huh, it's not fast? Yes, I did some benchmarking now and indeed it isn't, that's disappointing...

A loop is much better, and typed array fill much better still, so let's ifdef over those two I guess, #11570

Comment (kripken) [reply src/library_fs.js:2031]: About point (1), that would take some extra refactoring to move the zeroing around to the specific FSes as opposed to a single shared place, which is a little unfortunate.

Meanwhile I measure that typed array fill can do 100MB of zeroing in ~10ms on my machine, which seems to indicate further optimization may not be worth it?

Comment (bmeurer) [reply src/library_fs.js:2031]: We actually only care about v8 here, since we're working on a Chrome extension. Why not simply always use the loop though? (the #ifdef's look pretty terrible to me TBH).

100MB in 10ms is quite a bummer given that we currently read 1GB via mmap in ~16ms. So we'd add 100ms to that for nothing. If you remember original and aligned size, you can just fill from original size to aligned size, that should be really fast.

Comment (kripken) [reply src/library_fs.js:2031]: The loop is 10x slower than typed array fill. But yes, if we want to just do the alignment area, I can look into a larger refactoring for that, which avoids the speed issue entirely.

Comment (sbc100) [reply src/library_fs.js:2031]: To avoid the refactor can we just zero the final page?   (I assume the padding is at most one page?)

Comment (sbc100) [reply src/library_fs.js:2031]: I do hope to completely remove mmap from JS though and implement this in terms of malloc+open+read.
Basically just copy https://github.com/WebAssembly/wasi-libc/blob/master/libc-bottom-half/mman/mman.c.

Comment (kripken) [reply src/library_fs.js:2031]: #11576
