### PR TITLE
Workaround Safari WebGL issue: After successfully acquiring WebGL con…

### LINKED ISSUE #13295: Unexpected "OpenGL ES 3.0 (WebGL 1.0)" reported by glGetString(GL_VERSION)
I have observed a strange behavior of a sample 3D viewer application on Safari 14 (on both macOS and iOS) and Chrome (iOS 12.5.1).
`glGetString(GL_VERSION)` in application returns `"OpenGL ES 3.0 (WebGL 1.0)"` which makes no sense to me.

Application is build with `-s USE_WEBGL2=1` option, which in my understanding should report OpenGL ES 2.0 when browser creates WebGL 1.0 context and OpenGL ES 3.0 for WebGL 2.0. And this is how it actually works on desktop browsers (like disabling `webgl.enable-webgl2` in Firefox browser), but for some reason - not on iPad.

First, I would like to understand if it is a bug or expected behavior. In latter case - I would appreciate some details what does it mean, as created "OpenGL ES 3.0 (WebGL 1.0)" is certainly broken. I have also tried to enable WebGL 2.0 in iPad experimental features, which bring "OpenGL ES 3.0 (WebGL 2.0)" with proper GLSL compiler, but has been broken in other GLES 3.0 aspects - but this is kind of expected, as it is "experimental". What I don't expect is "OpenGL ES 3.0 (WebGL 1.0)" thing - as far as I understand, this string is generated by Emscripten, so it couldn't be a Browser bug...

By the way, I have suddenly found that `-s USE_WEBGL2=1` is no more listed in recent documentation. I see there is `-s MAX_WEBGL_VERSION=2` now, but cannot find when this has been changed and if there is a difference between old/new flags.
So far I've tried Emscripten 2.0.11.

image

### PR DESCRIPTION
**Pull request by juj**
…text on a canvas, calling .getContext() will always return that context independent of which 'webgl' or 'webgl2' context version was passed. See https://bugs.webkit.org/show_bug.cgi?id=222758. Fixes #13295

### CODE REVIEW

File: src/library_webgl.js [hunk 1]
```diff
@@ -592,6 +592,21 @@ var LibraryGL = {
...
+      // BUG: Workaround Safari WebGL issue: After successfully acquiring WebGL context on a canvas,
+      // calling .getContext() will always return that context independent of which 'webgl' or 'webgl2'
+      // context version was passed. See https://bugs.webkit.org/show_bug.cgi?id=222758 and
+      // https://github.com/emscripten-core/emscripten/issues/13295.
+      // TODO: Once the bug is fixed and shipped in Safari, adjust the Safari version field in above check.
+      if (!canvas.getContextSafariWebGL2Fixed) {
+        canvas.getContextSafariWebGL2Fixed = canvas.getContext;
+        canvas.getContext = function(ver, attrs) {
+          var gl = canvas.getContextSafariWebGL2Fixed(ver, attrs);
+          return ((ver == 'webgl') == (gl instanceof WebGLRenderingContext)) && gl;
```
Comment (kenrussell) [inline src/library_webgl.js:605]: Will this end up returning "false" for getContext if this fails, rather than null? I'd suggest writing this more clearly with if-statements.

Comment (juj) [reply src/library_webgl.js]: Surprised if that matters, but sure, adjusted to return `null`.

**Review by kripken — APPROVED** [review]
