### PR TITLE
Fix errant return and argument list in wgpuQueueOnSubmittedWorkDone

### LINKED ISSUE #15521: cannot get correct function from wasmTable when invoke `wgpuQueueOnSubmittedWorkDone`
Hi, guys, 

I'm working on webgpu with emscripten, and when I call wgpuQueueOnSubmittedWorkDone:

image

I can't get the correct id of `callback` and `userdata`, with `return queue["onSubmittedWorkDone"]();` removed:

> Uncaught (in promise) TypeError: wasmTable.get(...) is not a function

Kai's commit here solved this issue: https://github.com/emscripten-core/emscripten/pull/15515
I apply this change and still got: 

image

somehow I noticed in library_webgpu.js:

```
  wgpuQueueOnSubmittedWorkDone: function(queueId, callback, userdata) {
    var queue = WebGPU.mgrQueue.get(queueId);
    return queue["onSubmittedWorkDone"]();
    queue.onSubmittedWorkDone().then(function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Success }}}, userdata);
    }, function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Error }}}, userdata);
    });
  },
```

there's a QueueWorkDoneStatus as one of params in callback, so I add a placeholder in wgpuQueueOnSubmittedWorkDone, now it's:

```
  wgpuQueueOnSubmittedWorkDone: function(queueId, signalValue, placeholder,callback, userdata) {
    var queue = WebGPU.mgrQueue.get(queueId);
    queue.onSubmittedWorkDone().then(function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Success }}}, userdata);
    }, function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Error }}}, userdata);
    });
  },
```

it works.

------

test on emsdk 2.0.26.

### PR DESCRIPTION
**Pull request by kainino0x**
- This return prevents the result from actually being handled.
- The argument list didn't match the C header.

Fixes #15521

### CODE REVIEW

**Comment by kainino0x** [comment]
PTAL @shrekshao @sbc100

**Review by sbc100 — APPROVED** [review]
rubberstamp lgtm

**Comment by kainino0x** [comment]
I'm going to wait on landing this until I've investigated #15521 and then re-request review from Shrek.

**Comment by shrekshao** [comment]
How does the `signalValue` work?

**Comment by kainino0x** [comment]
> How does the `signalValue` work?

It doesn't do anything and I should put an assert that it's 0. It's there for futureproofing when we have a fence system that signals to particular values, but we removed it from the JS API.
https://github.com/webgpu-native/webgpu-headers/issues/130

File: src/library_webgpu.js [hunk 1]
```diff
@@ -1375,9 +1375,12 @@ var LibraryWebGPU = {
     '$runtimeKeepalivePush', '$runtimeKeepalivePop',
 #endif
   ],
-  wgpuQueueOnSubmittedWorkDone: function(queueId, callback, userdata) {
+  wgpuQueueOnSubmittedWorkDone: function(queueId, {{{ defineI64Param('signalValue') }}}, callback, userdata) {
     var queue = WebGPU.mgrQueue.get(queueId);
-    return queue["onSubmittedWorkDone"]();
+#if ASSERTIONS
+    assert(signalValue_low === 0 && signalValue_hight === 0, 'signalValue not supported, must be 0');
```
Comment (jrprice) [inline src/library_webgpu.js:1381]: Typo: `s/hight/high/`

**Review by jrprice — COMMENTED** [review]
Works for me after the typo fix.

File: src/library_webgpu.js (hunk 1 above)
Comment (shrekshao) [reply src/library_webgpu.js:1381]: Same for the typo. `return name + '_low, ' + name + '_high';`
Other than that LGTM

**Review by shrekshao — CHANGES_REQUESTED** [review]

File: src/library_webgpu.js (hunk 1 above)
Comment (kainino0x) [reply src/library_webgpu.js:1381]: wow, I tested the assert but since signalValue_low was not 0, signalValue_hight wasn't resolved and didn't throw a ReferenceError. Thanks for catching this!
