### PR TITLE
Fix stringToNewUTF8() with null or empty string

### LINKED ISSUE #10494: Erroneous glGetString call throws TypeError
```
WebGL: INVALID_ENUM: getParameter: invalid parameter name, WEBGL_debug_renderer_info not enabled
Uncaught TypeError: Cannot read property 'length' of null
    at lengthBytesUTF8 (taisei.js:formatted:5053)
    at stringToNewUTF8 (taisei.js:formatted:12107)
    at _glGetString (taisei.js:formatted:14009)
    at wasm-function[2316]:0x190c9d
```

A null value is passed to `stringToNewUTF8` here: https://github.com/emscripten-core/emscripten/blob/430c2911dbe0104beab264cd19a971a2a7c6b793/src/library_webgl.js#L1165

Would it be a good idea to make `stringToNewUTF8` return a null pointer if the argument is null? I think it at least warrants an assertion.

### PR DESCRIPTION
**Pull request by juj**
Fix calling stringToNewUTF8() with a null or empty input parameter. Optimize code size of glGetString(). Fixes #10494.

### CODE REVIEW

File: src/library.js [hunk 1]
```diff
@@ -41,10 +41,13 @@ LibraryManager.library = {
 
   $stringToNewUTF8__deps: ['malloc'],
   $stringToNewUTF8: function(jsString) {
-    var length = lengthBytesUTF8(jsString)+1;
-    var cString = _malloc(length);
-    stringToUTF8(jsString, cString, length);
-    return cString;
+    if (jsString) {
```
Comment (kripken) [inline src/library.js:44]: Is this intended to handle an empty string, a null, or both? Atm it will handle both, but it seems odd to turn an empty string into a 0 pointer?

Comment (juj) [reply src/library.js:44]: The intent is to handle both, I think it is a good optimization to avoid running dummy `malloc(0)`s on empty strings? That is something that one would generally do in C programs to optimize empty strings as well.

Comment (kripken) [reply src/library.js:44]: Sounds reasonable. But it means we need to audit all the callers of this method to verify that they handle a 0 now?

File: src/library.js [hunk 2]
```diff
@@ -41,10 +41,13 @@ LibraryManager.library = {
...
+      var length = lengthBytesUTF8(jsString)+1;
+      var cString = _malloc(length);
+      stringToUTF8(jsString, cString, length);
+      return cString;
+    }
+    // Return implicit undefined to be coerced to a 0 pointer in WebAssembly side.
```
Comment (kripken) [inline src/library.js:50]: This method is not called from wasm, I don't think? Do you mean if/when the value reaches wasm indirectly later?

Comment (juj) [reply src/library.js:50]: Yeah, that's right.

File: src/library.js (hunk 1 above)
Comment (juj) [reply src/library.js:44]: I did go through all the call sites of the function, and the test suite seems to agree. After all, JS side code does not really have any use of the returned integer value, its only use will be to flow that number directly to wasm (maybe cache it in some structure).

Comment (kripken) [reply src/library.js:44]: Makes sense. What about all the wasm users, though? Calling `free(0)` is fine, but if they do something like `strcpy` or `printf` of NULL that could error.

Comment (juj) [reply src/library.js:44]: In musl a printf of null string ptr prints out `(null)`. strcpy of null would be a problem.

stringToNewUTF8() is not publicly documented out to external users (though that would not prevent it from being used externally). If external users unconditionally strcpying is worrying, we need to reconsider. In such case, maybe `stringToNewUTF8(null/undefined)` should also allocate a dummy pointer that holds a zero.

Comment (kripken) [reply src/library.js:44]: The same would be needed for `stringToNewUTF8('')` (the empty string)? If so then that would revert the change to this file.

Overall this seems a little risky to me for little benefit (as it increases code size in this file acually). Is it worth it for the benefits in `library_webgl.js` to figure out a safe way to avoid allocating for falsey inputs here?

Comment (juj) [reply src/library.js]: > Is it worth it for the benefits in `library_webgl.js` to figure out a safe way to avoid allocating for falsey inputs here?

The reason for placing the check inside `stringToNewUTF8()` is the same as why [UTF8ToString() checks for null input](https://github.com/emscripten-core/emscripten/blob/cbc974264e0b0b3f0ce8020fb2f1861376c66545/src/runtime_strings.js#L112): it is better for code size to have that check exist only once for all callers, rather than require all callers to pre-validate first.

Updated the code to always return an allocated string.

> Overall this seems a little risky to me for little benefit (as it increases code size in this file acually).

This is the right location to fix this. Otherwise we would either increase code size for all callers when the would each need to validate, or require that callers statically write code that never produce empty strings. Only if we know that our users build programs that do not have any call sites that feed in falsey strings, it would be smaller for general code size. If they had one, it would be all the same whether `stringToNewUTF8()` checks or if caller checks, and if they have two or more, it is more optimal to check here. So we have to pick for the types of programs we optimize size for: are we optimizing size for programs that have 0, 1 or >= 2 such call sites?

Comment (juj) [reply src/library.js]: Actually, maybe we don't have any other callers that do need to rely on `stringToNewUTF8(null/undefined/false/0)` to work. Hoisted the check to library_webgl.js on that assumption. If we do get more of such call sites, then it would be best to locate the check inside `stringToNewUTF8()`.

**Review by kripken — APPROVED** [review]
lgtm. I agree that if we find other callers need a similar "don't allocate if the string is empty/null" approach then we should find a way to do that (perhaps a new method).
