### PR TITLE
Fix infinite wait bug in test_pthread_proxying_cpp.cpp

### LINKED ISSUE #18353: Flaky test: test_pthread_proxying_cpp
Looks like test_pthread_proxying_cpp is flaky on the CI too, probably similar to #18307 / #18314.

### PR DESCRIPTION
**Pull request by tlively**
The tests in test_pthread_proxying_cpp proxy functions that increment local
variables. For the async proxying functions, the proxying is followed by a wait
on a condition variable so the test can assert that the proxied work was
completed. However, the incrementing of the local variables was not protected by
the lock used with the condition variable, so it was possible for the variable
to be incremented and the condition variable notified after checking the wait
condition but before waiting. Since the condition variable would not be notified
again, the test would wait on the condition variable forever.

Fix the bug by taking the lock before incrementing the variable in tests where
this could cause problems.

Fixes #18353.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #18358** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/18358" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/18358?utm_source=stack-comment).

**Review by kripken — APPROVED** [review]

File: test/pthread/test_pthread_proxying_cpp.cpp [hunk 1]
```diff
@@ -68,7 +71,10 @@ void test_proxy_async() {
   // Proxy to returner.
   {
     queue.proxyAsync(returner.native_handle(), [&]() {
-      i = 3;
+      {
+        std::unique_lock<std::mutex> lock(mutex);
+        i = 3;
+      }
```
Comment (sbc100) [inline test/pthread/test_pthread_proxying_cpp.cpp:77]: Despite reading you description I've having trouble seeing how putting a lock around this one assignment fixes the issue.  Would making `i` and atomic also fix the issue?

Comment (sbc100) [reply test/pthread/test_pthread_proxying_cpp.cpp:77]: After reading https://stackoverflow.com/questions/17101922/do-i-have-to-acquire-lock-before-calling-condition-variable-notify-one I think i understand..  I had never known this about cond vars..

**Review by sbc100 — APPROVED** [review]

File: test/pthread/test_pthread_proxying_cpp.cpp [hunk 2]
```diff
@@ -184,7 +193,10 @@ void test_proxy_async_with_callback(void) {
     queue.proxyAsyncWithCallback(
       returner.native_handle(),
       [&]() {
-        i = 3;
+        {
+          std::unique_lock<std::mutex> lock(mutex);
+          i = 3;
+        }
         executor = std::this_thread::get_id();
         cond.notify_one();
```
[the remark this answers is not in the document]
Comment (tlively) [reply test/pthread/test_pthread_proxying_cpp.cpp:201]: No, it's actually a pessimization to hold the lock while calling notify because then the other thread wakes up just to immediately block on acquiring the lock.

**Comment by kripken** [comment]
I thought the idea was that the outside holds the mutex so that the thread blocks until the right time, but reading it again, I think I misunderstood it before as the outside grabs the mutex after firing off the async event, so they actually race. So I'm also not sure about this change, and not sure why it was failing before...

File: test/pthread/test_pthread_proxying_cpp.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (sbc100) [reply test/pthread/test_pthread_proxying_cpp.cpp:201]: TIL!

File: test/pthread/test_pthread_proxying_cpp.cpp (hunk 1 above)
Comment (tlively) [reply test/pthread/test_pthread_proxying_cpp.cpp:77]: No, the lock is important because of the condition variable. The condition variable needs to atomically check the condition and block if the condition is not met. The mechanism for combining those into an atomic action is the lock, so if the condition can change without the lock being held, the condition variable doesn't work as intended.

**Comment by tlively** [comment]
Right, since the proxying is async, the proxied work races with the following code on the proxying thread. To resolve the race, we use explicit condition variables to wait for the proxied work to be completed. The bug was that we weren't using the condition variables properly. Condition variables only work if the condition is protected by the same lock passed to `wait`, and in this case it was not.

**Comment by sbc100** [comment]
You can go ahead and land without waiting for the restarted sockets tests if you like.. that failure was clearly unrelated.

**Review by kripken — APPROVED** [review]
