### PR TITLE
Fix sse tests with `-mnontrapping-fptoint`

### LINKED ISSUE #22892: test_sse1 fails with -mnontrapping-fptoint
```
$ EMCC_CFLAGS=-mnontrapping-fptoint ./test/runner core0.test_sse1 2> output
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
...
--- expected
+++ actual
@@ -15701,17 +15701,17 @@
 _mm_cvtt_ss2si([0.800000012,1,1.5,2.5]) = 0x00000002
 _mm_cvtt_ss2si([1,1.5,2.5,3.5]) = 0x00000003
 _mm_cvtt_ss2si([1.5,2.5,3.5,3.5999999]) = 0x00000003
-_mm_cvtt_ss2si([2.5,3.5,3.5999999,3.40282347e+38]) = 0x80000000
-_mm_cvtt_ss2si([3.5,3.5999999,3.40282347e+38,inf]) = 0x80000000
-_mm_cvtt_ss2si([3.5999999,3.40282347e+38,inf,NaN(0x7FC00000)]) = 0x80000000
+_mm_cvtt_ss2si([2.5,3.5,3.5999999,3.40282347e+38]) = 0x7FFFFFFF
+_mm_cvtt_ss2si([3.5,3.5999999,3.40282347e+38,inf]) = 0x7FFFFFFF
+_mm_cvtt_ss2si([3.5999999,3.40282347e+38,inf,NaN(0x7FC00000)]) = 0x00000000
 _mm_cvtt_ss2si([3.40282347e+38,inf,NaN(0x7FC00000),2.38793926e-38]) = 0x00000000
 _mm_cvtt_ss2si([inf,NaN(0x7FC00000),2.38793926e-38,-0]) = 0x00000000
-_mm_cvtt_ss2si([NaN(0x7FC00000),2.38793926e-38,-0,NaN(0x7FFFFFFF)]) = 0x80000000
-_mm_cvtt_ss2si([2.38793926e-38,-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF)]) = 0x80000000
+_mm_cvtt_ss2si([NaN(0x7FC00000),2.38793926e-38,-0,NaN(0x7FFFFFFF)]) = 0x00000000
+_mm_cvtt_ss2si([2.38793926e-38,-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF)]) = 0x00000000
 _mm_cvtt_ss2si([-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38]) = 0x80000000
 _mm_cvtt_ss2si([NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21]) = 0x00000000
-_mm_cvtt_ss2si([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x80000000
-_mm_cvtt_ss2si([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x80000000
+_mm_cvtt_ss2si([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x7FFFFFFF
+_mm_cvtt_ss2si([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x7FFFFFFF
 _mm_cvtt_ss2si([-3.29950007e-21,3.40282002e+38,3.38211008e+19,-inf]) = 0x80000000
 _mm_cvtt_ss2si([3.40282002e+38,3.38211008e+19,-inf,-3.40282347e+38]) = 0x80000000
 _mm_cvtt_ss2si([3.38211008e+19,-inf,-3.40282347e+38,-2.5]) = 0xFFFFFFFE
@@ -15733,17 +15733,17 @@
 _mm_cvttss_si32([0.800000012,1,1.5,2.5]) = 0x00000002
 _mm_cvttss_si32([1,1.5,2.5,3.5]) = 0x00000003
 _mm_cvttss_si32([1.5,2.5,3.5,3.5999999]) = 0x00000003
-_mm_cvttss_si32([2.5,3.5,3.5999999,3.40282347e+38]) = 0x80000000
-_mm_cvttss_si32([3.5,3.5999999,3.40282347e+38,inf]) = 0x80000000
-_mm_cvttss_si32([3.5999999,3.40282347e+38,inf,NaN(0x7FC00000)]) = 0x80000000
+_mm_cvttss_si32([2.5,3.5,3.5999999,3.40282347e+38]) = 0x7FFFFFFF
+_mm_cvttss_si32([3.5,3.5999999,3.40282347e+38,inf]) = 0x7FFFFFFF
+_mm_cvttss_si32([3.5999999,3.40282347e+38,inf,NaN(0x7FC00000)]) = 0x00000000
 _mm_cvttss_si32([3.40282347e+38,inf,NaN(0x7FC00000),2.38793926e-38]) = 0x00000000
 _mm_cvttss_si32([inf,NaN(0x7FC00000),2.38793926e-38,-0]) = 0x00000000
-_mm_cvttss_si32([NaN(0x7FC00000),2.38793926e-38,-0,NaN(0x7FFFFFFF)]) = 0x80000000
-_mm_cvttss_si32([2.38793926e-38,-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF)]) = 0x80000000
+_mm_cvttss_si32([NaN(0x7FC00000),2.38793926e-38,-0,NaN(0x7FFFFFFF)]) = 0x00000000
+_mm_cvttss_si32([2.38793926e-38,-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF)]) = 0x00000000
 _mm_cvttss_si32([-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38]) = 0x80000000
 _mm_cvttss_si32([NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21]) = 0x00000000
-_mm_cvttss_si32([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x80000000
-_mm_cvttss_si32([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x80000000
+_mm_cvttss_si32([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x7FFFFFFF
+_mm_cvttss_si32([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x7FFFFFFF
 _mm_cvttss_si32([-3.29950007e-21,3.40282002e+38,3.38211008e+19,-inf]) = 0x80000000
 _mm_cvttss_si32([3.40282002e+38,3.38211008e+19,-inf,-3.40282347e+38]) = 0x80000000
 _mm_cvttss_si32([3.38211008e+19,-inf,-3.40282347e+38,-2.5]) = 0xFFFFFFFE
@@ -15765,7 +15765,7 @@
 _mm_cvttss_si64([0.800000012,1,1.5,2.5]) = 0x0000000000000002
 _mm_cvttss_si64([1,1.5,2.5,3.5]) = 0x0000000000000003
 _mm_cvttss_si64([1.5,2.5,3.5,3.5999999]) = 0x0000000000000003
-_mm_cvttss_si64([2.5,3.5,3.5999999,3.40282347e+38]) = 0x8000000000000000
+_mm_cvttss_si64([2.5,3.5,3.5999999,3.40282347e+38]) = 0x7FFFFFFFFFFFFFFF
 _mm_cvttss_si64([3.5,3.5999999,3.40282347e+38,inf]) = 0x8000000000000000
 _mm_cvttss_si64([3.5999999,3.40282347e+38,inf,NaN(0x7FC00000)]) = 0x8000000000000000
 _mm_cvttss_si64([3.40282347e+38,inf,NaN(0x7FC00000),2.38793926e-38]) = 0x0000000000000000
@@ -15774,8 +15774,8 @@
 _mm_cvttss_si64([2.38793926e-38,-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF)]) = 0x8000000000000000
 _mm_cvttss_si64([-0,NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38]) = 0x8000000000000000
 _mm_cvttss_si64([NaN(0x7FFFFFFF),NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21]) = 0x0000000000000000
-_mm_cvttss_si64([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x8000000000000000
-_mm_cvttss_si64([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x8000000000000000
+_mm_cvttss_si64([NaN(0xFFFFFFFF),-2.70497005e+38,-3.29950007e-21,3.40282002e+38]) = 0x7FFFFFFFFFFFFFFF
+_mm_cvttss_si64([-2.70497005e+38,-3.29950007e-21,3.40282002e+38,3.38211008e+19]) = 0x7FFFFFFFFFFFFFFF
 _mm_cvttss_si64([-3.29950007e-21,3.40282002e+38,3.38211008e+19,-inf]) = 0x8000000000000000
 _mm_cvttss_si64([3.40282002e+38,3.38211008e+19,-inf,-3.40282347e+38]) = 0x8000000000000000
 _mm_cvttss_si64([3.38211008e+19,-inf,-3.40282347e+38,-2.5]) = 0xFFFFFFFFFFFFFFFE



----------------------------------------------------------------------
Ran 1 test in 2.866s

FAILED (failures=1)
```

### PR DESCRIPTION
**Pull request by sbc100**
Turns out we were relying on the explicit llvm bounds check here to give use the defined SSE behavior, but normal C semantics don't give us that so we need explicit bounds checks here.

Fixes #22892

### CODE REVIEW

File: system/include/compat/xmmintrin.h [hunk 1]
```diff
@@ -9,6 +9,8 @@
 
 #include <wasm_simd128.h>
 
+#include <limits.h>
+#include <stdio.h>
```
Comment (dschuff) [inline system/include/compat/xmmintrin.h:13]: was this for debug print?

File: system/include/compat/xmmintrin.h [hunk 2]
```diff
@@ -605,9 +607,11 @@ static __inline__ int __attribute__((__always_inline__, __nodebug__, DIAGNOSE_SL
...
 static __inline__ int __attribute__((__always_inline__, __nodebug__, DIAGNOSE_SLOW)) _mm_cvttss_si32(__m128 __a)
 {
-  int x = lrint(((__f32x4)__a)[0]);
-  if (x != 0 || fabsf(((__f32x4)__a)[0]) < 2.f)
-    return (int)((__f32x4)__a)[0];
+  float e = ((__f32x4)__a)[0];
+  if (isnanf(e) || e > INT_MAX || e < INT_MIN) return (int)0x80000000;
+  int x = lrint(e);
+  if ((x != 0 || fabsf(e) < 2.f))
+    return (int)e;
```
Comment (dschuff) [inline system/include/compat/xmmintrin.h:614]: if we used `__builtin_wasm_trunc_s_i32_f32` instead of just the C cast here, we could avoid having LLVM insert checks redundant to these in the backend.

Comment (sbc100) [reply system/include/compat/xmmintrin.h:614]: Aren't those checks going away though?

File: system/include/compat/xmmintrin.h (hunk 1 above)
Comment (sbc100) [reply system/include/compat/xmmintrin.h]: Removed.

File: system/include/compat/xmmintrin.h (hunk 2 above)
Comment (sbc100) [reply system/include/compat/xmmintrin.h:613]: Done!

File: test/test_core.py [hunk 3]
```diff
@@ -6528,14 +6532,18 @@ def test_sse1(self):
   @is_slow_test
   @no_ubsan('https://github.com/emscripten-core/emscripten/issues/19688')
   @no_asan('local count too large')
-  def test_sse2(self):
+  @parameterized({
+    '': ([],),
```
Comment (dschuff) [inline test/test_core.py:6536]: let's make this an explicit `-mno-nontrapping-fptoint' so that when we flip the default, it will still be testing the same case.

File: test/test_core.py [hunk 4]
```diff
@@ -6511,12 +6511,16 @@ def test_neon_wasm_simd(self):
   @requires_native_clang
   @no_safe_heap('has unaligned 64-bit operations in wasm')
   @no_ubsan('test contains UB')
-  def test_sse1(self):
+  @parameterized({
+    '': ([],),
```
Comment (dschuff) [inline test/test_core.py:6515]: and here (same as below)

File: test/test_core.py (hunk 3 above)
Comment (sbc100) [reply test/test_core.py:6536]: I think maybe better to explicitly change these tests when we make that change, since the variant will want to be renamed so the default is still empty string and the non-default becomes perhaps `-trapping`?  Or `-no-nontrapping`?

Comment (dschuff) [reply test/test_core.py:6536]: or we could just name both variants I guess.

Comment (sbc100) [reply test/test_core.py:6536]: I'm kind keen on the idea of always having an unnamed variant for the default.  Then there is always a test you can run that matches the name of the test in python.  i.e. if I see `def test_foo_bar` i know I can run a test called `test_foo_bar` without any suffix.   Maybe no a necessarily things, but it seems nice to have.

**Review by dschuff — APPROVED** [review]
This seems fine either way.
There does still seem to be a fair amount of opportunity to optimize in here. But I guess there are also plenty of `//TODO: optimize` so no change :)

File: test/test_core.py (hunk 3 above)
Comment (sbc100) [reply test/test_core.py:6536]: We already have other tests here like `test_fasta_nontrapping` that will need to be inverted when we change the default.
