### PR TITLE
[pthreads] Fix memory leak in mailbox await loop during shutdown

### LINKED ISSUE #20920: __emscripten_thread_mailbox_await causes memory leak in multi-threaded builds
**Repro** (with more detailed build/run instructions): [sessamekesh/emscripten-worker-leak-demo](https://github.com/sessamekesh/emscripten-worker-leak-demo)

**TL;DR** - Emscripten-generated glue JavaScript code holds onto a reference of the entire SharedArrayBuffer used to instantiate a WASM module, via the `wasmMemory` variable. I've tracked it down to the `__emscripten_thread_mailbox_await` function. If I comment out the entire function body, I no longer observe the memory leak. Tested in Chrome and Firefox.

-----------------------------------------------------------------------------------

**Context:** I found this bug working on [sessamekesh/wasm-ecs-game-profile](https://github.com/sessamekesh/wasm-ecs-game-profile), which is part of an Angular single-page app. Single-page apps care a _lot_ about pages/components cleaning up after themselves, since they can't rely on page navigation to force an entire browser memory reset.

**My Hunch**: `__emscripten_thread_mailbox_await` calls `GROWABLE_HEAP_I32()` which itself (correctly) has a reference to `wasmMemory`. There's a few other places in the `Module` object that do this without any problem, presumably because all the closures are never attached to anything that ends up stuck on a global scope.

I don't know where or how `__emscripten_thread_mailbox_await` is getting attached to a global scope, I'm digging into the problem further myself. I'll post any updates in this bug, but I figured I've narrowed down the issue enough to make a useful bug report.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.50 (047b82506d6b471873300a5e4d1e690420b582d0)
clang version 18.0.0 (https://github.com/llvm/llvm-project 14028ec0a62210d68a4dd7a046ac79c8c3b7727e)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Full link command and output with `-v` appended:**

```bash
emcc -sWASM -sMODULARIZE -sENVIRONMENT="web,worker" -sALLOW_MEMORY_GROWTH -sEXIT_RUNTIME=0 -sFILESYSTEM=0 -sEXPORT_NAME="HeavyObjectDemoModuleMT" -sUSE_PTHREADS -sPTHREAD_POOL_SIZE=4 -sASSERTIONS=0 -sRUNTIME_DEBUG=0 --no-entry --bind -pthread sample.cc -o builds/sample-multi-threaded.js
```

**Code** (Code itself is not really relevant, but it vaguely has the shape of what I want to work)

```cpp
class HeavyObject {
  public:
  HeavyObject() { val_.resize(10000000, 'a'); }
  int len() const { return val_.size(); }
 private:
  std::string val_;
};

EMSCRIPTEN_BINDINGS(IgDemoModule) {
  class_<HeavyObject>("HeavyObject")
    .smart_ptr_constructor("HeavyObject", &std::make_shared<HeavyObject>)
    .function("len", &HeavyObject::len);
}
```

### PR DESCRIPTION
**Pull request by sbc100**
Introduce PThread.terminateRuntime which is called during runtime exit. This function not only terminates all workers but also clears the thread state of the main thread and sends a final notification to its mailbox.

By clearing the thread state, _pthread_self() will now return 0, which causes the mailbox checking loop to terminate instead of re-registering a new Atomics.waitAsync promise. This allows the Wasm memory and module instance to be garbage collected.

Fixes: #20920

### CODE REVIEW

File: test/pthread/test_pthread_mem_leak_post.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  await (async () => {
+    const instance = await Module();
+    console.log('GOT INSTANCE');
+    // Once this scope exits we expect the instance and its memory to be
+    // collected.
+    registry.register(instance.wasmMemory.buffer, "wasmMemory");
+  })();
+
+  // Force GC
+  if (global.gc) {
```
Comment (tlively) [inline test/pthread/test_pthread_mem_leak_post.js]: Should we instead assert that this is available, since the test is not expected to pass otherwise?

**Review by tlively — APPROVED** [review]

File: test/pthread/test_pthread_mem_leak_post.js (hunk 1 above)
Comment (sbc100) [reply test/pthread/test_pthread_mem_leak_post.js]: Good point.  I thought of that too actually when reviewing this test (which Gemini wrote :)

**Comment by sbc100** [comment]
Pretty cool to see this bug of 2.5 years being fixed!
