### PR TITLE
WebGPU: runtime keepalive, callUserCallback

### LINKED ISSUE #15246: Should `wgpuInstanceRequestAdapter()` imply keeping runtime alive?
[`wgpuInstanceRequestAdapter()`](https://github.com/emscripten-core/emscripten/blob/e274e49bfb2022313f5697dc5560c19f5f13d81a/src/library_webgpu.js#L2048) is similar to [`emscripten_async_call()`](https://github.com/emscripten-core/emscripten/blob/e274e49bfb2022313f5697dc5560c19f5f13d81a/src/library_browser.js#L1171) in that it takes a callback, and the callback has to be scheduled after `main()` exits. The "Emscripten runtime" is automatically [kept alive](https://github.com/emscripten-core/emscripten/blob/e274e49bfb2022313f5697dc5560c19f5f13d81a/src/library.js#L3592) in `emscripten_async_call()`, so I wonder if `wgpuInstanceRequestAdapter()` (and its friends) should be responsible for this too?

Besides, I'm seeing an uncaught `'unwind'` exception when calling `emscripten_set_main_loop()` from my registered callback, while `emscripten_async_call()` has the magic to mute this exception.

### PR DESCRIPTION
**Pull request by kainino0x**
Also:
- Add a missing `return` in an error condition in `wgpuInstanceRequestAdapter`
- Change `["then"]` to `.then`

----

The "[Hide whitespace changes](https://github.com/emscripten-core/emscripten/pull/15251/files?diff=split&w=1)" option is useful here.

~Currently blocked on #15256.~

Fixes #15246

### CODE REVIEW

File: src/library_webgpu.js [hunk 1]
```diff
@@ -660,39 +660,50 @@ var LibraryWebGPU = {
...
+        } else {
 #if ASSERTIONS
-        assert(gpuError instanceof GPUValidationError);
+          assert(gpuError instanceof GPUValidationError);
 #endif
-        var messagePtr = allocateUTF8(gpuError.message);
-        {{{ makeDynCall('viii', 'callback') }}}({{{ gpu.ErrorType.Validation }}}, messagePtr, userdata);
-        _free(messagePtr);
-      }
+          var messagePtr = allocateUTF8OnStack(gpuError.message);
```
Comment (kainino0x) [inline src/library_webgpu.js:685]: Are these usages of allocateUTF8OnStack (from the event loop, not from a WASM call into JS) valid? Convenient if so, as they should avoid a malloc.

**Comment by sbc100** [comment]
> We wouldn't typically expect the runtime to exit after most of these operations, but we would expect it to briefly be the _only_ thing preventing the runtime from exiting. For example, in the test, main() requests an adapter, then the program does nothing while waiting, then it continues once it has an adapter.

If it returns from `main` and expects to continue later then that is exactly what those APIs are intended for.

File: src/library_webgpu.js [hunk 2]
```diff
@@ -660,39 +660,52 @@ var LibraryWebGPU = {
...
-  wgpuDevicePopErrorScope__deps: ['$allocateUTF8'],
+    '$allocateUTF8OnStack',
+#else
+    '$runtimeKeepalivePush', '$runtimeKeepalivePop',
 #endif
+  ],
   wgpuDevicePopErrorScope: function(deviceId, callback, userdata) {
     var device = WebGPU.mgrDevice.get(deviceId);
+    {{{ runtimeKeepalivePush() }}}
     device["popErrorScope"]()["then"](function(gpuError) {
```
Comment (sbc100) [inline src/library_webgpu.js:674]: Is there reason this "then" is in quotes like that?

File: src/library_webgpu.js (hunk 1 above)
Comment (sbc100) [reply src/library_webgpu.js:687]: If you use `allocateUTF8OnStack` (or any function that calls `allocStack` internally like that), I think you also need to wrap with `var stackTop = stackSave();` and `stackRestore(stackTop);`.

File: src/library_webgpu.js [hunk 3]
```diff
@@ -703,32 +714,39 @@ var LibraryWebGPU = {
       });
     }
     deviceWrapper.lostCallback = function(info) {
-      var messagePtr = allocateUTF8(info.message);
-      {{{ makeDynCall('viii', 'callback') }}}(
-          WebGPU.DeviceLostReason[info.reason], messagePtr, userdata);
-      _free(messagePtr);
+      // This will skip the callback if the runtime is no longer alive.
```
[the remark this answers is not in the document]
Comment (sbc100) [reply src/library_webgpu.js:719]: callUserCallback does this:

```
    if (ABORT) {                                                                    
#if ASSERTIONS                                                                      
      err('user callback triggered after application aborted.  Ignoring.');         
#endif                                                                              
      return;                                                                       
    }      
```

I'm not sure if that is exactly the same is checking the runtime is alive... but in any case if there is any checking to be done it should happen in `callUserCallback` itself and not here.

File: src/library_webgpu.js (hunk 2 above)
Comment (sbc100) [reply src/library_webgpu.js:674]: I think we just use `then()` normally everywhere else in the codebase.  I would tend of avoid being speculatively against potential closure issues and instead let testing tell is when its actually needed (but maybe I'm wrong about that approach?).

File: src/library_webgpu.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (sbc100) [reply src/library_webgpu.js:719]: Yes, I think we could add an assert for that (since if that happens I think it would be programmer error).   Separate PR for that makes sense I think.

[the remark this answers is not in the document]
Comment (kainino0x) [reply src/library_webgpu.js:719]: Draft PR was: https://github.com/emscripten-core/emscripten/pull/15256

[the remark this answers is not in the document]
Comment (sbc100) [reply src/library_webgpu.js:719]: If we exit the runtime shouldn't unregistered any callbacks we have with the browser.  Is that possible?

[the remark this answers is not in the document]
Comment (kainino0x) [reply src/library_webgpu.js:721]: It is possible in principle for the `onuncapturederror` since that's an event handler (if we have a place to do work on exiting the runtime), but it's not possible for DeviceLost, here, because promise.then isn't cancellable. We can only cancel it by checking something (like `runtimeExited`) inside the .then callback.

**Comment by sbc100** [comment]
Why abandon allocateUTF8OnStack?

File: tests/webgpu_basic_rendering.cpp [hunk 4]
```diff
@@ -365,6 +361,9 @@ int main() {
         run();
     });
 
-    // result will be reported when the main_loop completes
-    emscripten_exit_with_live_runtime();
+    // Result will be reported when the main_loop completes.
+    // emscripten_exit_with_live_runtime isn't needed because the WebGPU
+    // callbacks should all automatically keep the runtime alive until
+    // emscripten_set_main_loop, and that should keep it alive until
+    // emscripten_cancel_main_loop.
```
Comment (sbc100) [inline tests/webgpu_basic_rendering.cpp:368]: I usually put `return 99` here to make sure the return code from main is not used.

File: tests/webgpu_basic_rendering.cpp [hunk 5]
```diff
@@ -27,7 +27,7 @@ void GetDevice(void (*callback)(wgpu::Device)) {
         }
         if (status == WGPURequestAdapterStatus_Unavailable) {
             printf("WebGPU unavailable; exiting cleanly\n");
-            exit(0);
+            return;
```
Comment (sbc100) [inline tests/webgpu_basic_rendering.cpp:30]: Why not `exit(0)` here?

File: tests/webgpu_basic_rendering.cpp [hunk 6]
```diff
@@ -327,7 +323,7 @@ void frame() {
     // check the result.
 
     emscripten_cancel_main_loop();
-    emscripten_async_call(finishTest, (void*)0, 100);
+    // Runtime will exit now that there is nothing left to do.
```
Comment (sbc100) [inline tests/webgpu_basic_rendering.cpp:326]: `exit(0)` here?

File: tests/webgpu_basic_rendering.cpp (hunk 5 above)
Comment (kainino0x) [reply tests/webgpu_basic_rendering.cpp:30]: This helps test that the runtime-keepalive is working correctly. If the runtime doesn't exit implicitly after this return, then the test times out. Adding a comment.

**Comment by kainino0x** [comment]
> Of course. I was also wondering if we want some kind of helper for save/restore stack in JS. `withStackUsage(function() { ...})`?

We could certainly use it here! It would definitely be less error prone. I'm not going to prioritize a change to use allocateUTF8OnStack in this code right now though.

File: tests/webgpu_basic_rendering.cpp [hunk 7]
```diff
@@ -365,6 +367,10 @@ int main() {
...
     });
 
-    // result will be reported when the main_loop completes
-    emscripten_exit_with_live_runtime();
+    // Result will be reported when the main_loop completes.
+    // emscripten_exit_with_live_runtime isn't needed because the WebGPU
+    // callbacks should all automatically keep the runtime alive until
+    // emscripten_set_main_loop, and that should keep it alive until
+    // emscripten_cancel_main_loop.
+    return 99; // Return code gets ignored if the runtime correctly stays alive.
```
[the remark this answers is not in the document]
Comment (kainino0x) [reply tests/webgpu_basic_rendering.cpp:375]: Aha, that makes sense, because visually the test is completing (it shows the triangle and prints the right text) so this isn't preventing the runtime from continuing.

Perhaps it's best to stick to the usual structure then, return 99 and later exit(0). I could have another test for implicit exits.

[the remark this answers is not in the document]
Comment (kainino0x) [reply tests/webgpu_basic_rendering.cpp:375]: Hm, perhaps another test for implicit exit isn't needed. If I forget a runtimeKeepalivePop, it hangs even with `exit(0)`. It was the `emscripten_force_exit(0)` that was hiding that error condition before, but I don't think I need that.
