### PR TITLE
[wasmfs] Fix data race in thread initialization.

### LINKED ISSUE #24370: wasmfs_create_opfs_backend() hangs on low end devices
Calls to wasmfs_create_opfs_backend() seem to not return on certain low end devices, or only return once every x reloads.

Tested on a dell 3100 chromebook (2 core machine) 

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.71 (4171ae200b77a6c266b0e1ebb507d61d1ade3501)
clang version 20.0.0git (https:/github.com/llvm/llvm-project d6344c1cd0d099f8d99ee320f33fc9254dbe8288)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/lib/emsdk/upstream/bin
```

Compiling with `emcc Emscripten.c -o index.html -s WASM=1 -s USE_PTHREADS=1 -sWASMFS -sPTHREAD_POOL_SIZE=2`

```c
#include <assert.h>
#include <emscripten/console.h>
#include <emscripten/proxying.h>
#include <emscripten/threading.h>
#include <emscripten/wasmfs.h>
#include <pthread.h>
#include <stdio.h>

int mount_opfs() {
  emscripten_console_log("mount_opfs: starting");
  backend_t opfs = wasmfs_create_opfs_backend();
  emscripten_console_log("mount_opfs: created opfs backend");
  int ret = wasmfs_create_directory("/libsdl", 0777, opfs);
  emscripten_console_log("mount_opfs: mounted opfs");
  return ret;
}

void *thread_main(void *arg) {
  emscripten_console_log("trying to mount\n");
  mount_opfs();
  emscripten_console_log("finished mount\n");
}

int main() {
  int arg = 42;

  pthread_t thread;
  if (pthread_create(&thread, NULL, thread_main, &arg) != 0) {
    perror("pthread_create failed");
    return 1;
  }

  emscripten_console_log("Main thread continues\n");

  /* pthread_join(thread, NULL); */

  emscripten_console_log("Main thread done\n");
  return 0;
}
```

On my development PC, the log reaches `finished mount`, but on a lower end device it only hits `mount_opfs: starting` . The main thread continues however.

From my understanding it's spawning the proxy worker that fails, but I'm not sure how I would fix or work around this

### PR DESCRIPTION
**Pull request by brendandahl**
The `ProxyWorker` was creating a thread in the constructor initializer list and using a captured reference to the `started` member variable. This is problematic because it is not guaranteed that the class has been fully constructed during the initializer list.

What happens:
1) `ProxyWorker` initializers run
2) Thread starts and sets `started = true`
3) `ProxyWorker` finishes construction and sets `started = false`
4) `ProxyWorker` waits for `started` to be `true`

Step 4 will never finish in this case since the thread already ran.

To fix this we simply need to move the thread creation into the constructor body where the class is guaranteed to be fully constructed.

Fixes #24370, #24676, #20650

### CODE REVIEW

File: system/lib/wasmfs/thread_utils.h [hunk 1]
```diff
@@ -34,32 +34,36 @@ class ProxyWorker {
...
   // Spawn the worker thread.
   ProxyWorker()
-    : queue(), thread([&]() {
-        // Notify the caller that we have started.
-        {
-          std::unique_lock<std::mutex> lock(mutex);
-          started = true;
-        }
-        cond.notify_all();
+    : queue() {
```
Comment (sbc100) [inline system/lib/wasmfs/thread_utils.h]: Does clang-format not put this onto a single line now?

**Comment by sbc100** [comment]
Nice work!!!!

File: system/lib/wasmfs/thread_utils.h [hunk 2]
```diff
@@ -34,32 +34,36 @@ class ProxyWorker {
...
+    // Initialize the thread in the constructor to ensure the object has been
+    // fully constructed before thread starts using the object to avoid a data
+    // race. See #24370.
+    thread = std::thread([&]() {
+      // Notify the caller that we have started.
+      {
+        std::unique_lock<std::mutex> lock(mutex);
+        started = true;
```
Comment (tlively) [inline system/lib/wasmfs/thread_utils.h:47]: I suspect this is still technically incorrect because the initialization write of `started` is not protected by the mutex, so it will not synchronize with this mutex-protected read on the worker thread. (Unless the `std::thread` constructor introduces some synchronization, but the documentation doesn't say.) Let's get rid of the lock and make the bool atomic in addition to the changes here.

**Comment by brendandahl** [comment]
As mentioned in chat, I tried fixing this by moving `started` to the top of the decls list, but that didn't work. After thinking about it, I realized the thread also relies on the mutex and and condition variable too. I tried moving `std::thread thread` declaration to the end and that also fixes the issue.

Anyone have a preference on solution? I lean towards the current PR since any new members and dependencies will work as expected.

**Comment by sbc100** [comment]
I think using the correct decl order is better, but please also a comment about the decl order being important.

**Comment by sbc100** [comment]
Actually maybe apply both fixes, since didn't you also read the starting threads in initializers is bad?   Either way please add comments in the decl order.

File: system/lib/wasmfs/thread_utils.h (hunk 2 above)
Comment (brendandahl) [reply system/lib/wasmfs/thread_utils.h:47]: From what I interpret from the class initialization rules, `started` is guaranteed to be initialized before the thread is created, so we shouldn't need a lock at that point.

Comment (brendandahl) [reply system/lib/wasmfs/thread_utils.h:47]: https://isocpp.org/wiki/faq/ctors#using-this-in-ctors

Comment (tlively) [reply system/lib/wasmfs/thread_utils.h:47]: Yes, initialized on the current thread, but that initialization write does not necessarily become visible on any other thread without some form of synchronization.

Comment (brendandahl) [reply system/lib/wasmfs/thread_utils.h:47]: It took me a little while to dig this up, but thread creation is a [synchronization point](https://timsong-cpp.github.io/cppwp/thread.thread.constr#6).

Initializing (unguarded) data before thread creation is pretty common pattern, so I was going to be surprised if that was actually UB.

Comment (tlively) [reply system/lib/wasmfs/thread_utils.h:47]: Nice find, that makes sense.

**Review by tlively — APPROVED** [review]

**Review by sbc100 — APPROVED** [review]
