### PR TITLE
Fix 9068 newlines emcc error

### LINKED ISSUE #9057: test_js_optimizer_parse_error fails on windows
E.g. https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8907205937125136752/+/steps/Emscripten_testsuite__upstream__other_/0/stdout

We thought this was due to `\r\n` on windows, but #9052 failed to fix that, so it needs further investigation.

### PR DESCRIPTION
**Pull request by yeputons**
This fixes a patch applied to `acorn.js` for quoting error-causing text in parse errors (https://github.com/acornjs/acorn/pull/793). Previously it splitted binary data on `\n` to get lines, which was inconsistent with the rest of the parser and caused excess `\r` in the error message on Windows, which caused #9057. Now it uses the same regex as the rest of acorn.js (e.g. `getLineInfo` used by error reporting).

It also fixes #9057 automatically, hence I enabled corresponding test and removed unnecessary change from #9052.

Tests ran on Windows:

```
python2 runner.py other.test_js_optimizer_parse_error
```

### CODE REVIEW

File: tools/node_modules/acorn/dist/acorn.js [hunk 1]
```diff
@@ -2769,7 +2769,7 @@ pp$4.raise = function(pos, message) {
   message += " (" + loc.line + ":" + loc.column + ")";
   // XXX EMSCRIPTEN: add a quote of the error text, point to where
   // https://github.com/acornjs/acorn/pull/793
-  var lines = this.input.split('\n');
+  var lines = this.input.split(lineBreak);
   message = message + '\n' + lines[loc.line - 1] + '\n';
```
Comment (yeputons) [inline tools/node_modules/acorn/dist/acorn.js]: Note that this `\n` goes to the error message string, which is later displayed by Node exception handler. Hence, it's a usual string, not bytes, newlines are transformed automatically.

**Comment by kripken** [comment]
Great find @yeputons!

This is totally my fault - this is the local patch we have for acorn. I should have noticed they have a `lineBreak`...
