### PR TITLE
nodefs: Fix O_NOFOLLOW

### LINKED ISSUE #15786: nodefs: O_NOFOLLOW fails for existing files
Opening existing files with `O_NOFOLLOW` doesn't work.

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1-git (ad282f9824f37f3efdf0646ef0d514e1f568e749)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Failing command line in full:**
Compiling
```C
#include <assert.h>
#include <fcntl.h>
#include <stdio.h>

int main() {
    assert(open("/dev/pts/0", O_NOFOLLOW) != -1);
    printf("success\n");
    return 0;
}
```

 with
`emcc main.cpp -lnodefs.js -o main.js -s NODERAWFS=1`
fails with a RuntimeError.

### PR DESCRIPTION
**Pull request by gl84**
Fixes #15786.

Adds O_NOFOLLOW to NODEFS.flagsForNodeMap and adds a simple test case.

### CODE REVIEW

File: src/library_nodefs.js [hunk 1]
```diff
@@ -25,7 +25,8 @@ mergeInto(LibraryManager.library, {
         "{{{ cDefine('O_RDWR') }}}": flags["O_RDWR"],
         "{{{ cDefine('O_DSYNC') }}}": flags["O_SYNC"],
         "{{{ cDefine('O_TRUNC') }}}": flags["O_TRUNC"],
-        "{{{ cDefine('O_WRONLY') }}}": flags["O_WRONLY"]
+        "{{{ cDefine('O_WRONLY') }}}": flags["O_WRONLY"],
+        "{{{ cDefine('O_NOFOLLOW') }}}": flags["O_NOFOLLOW"]
```
Comment (sbc100) [inline src/library_nodefs.js:29]: Add a trailing comma on the final element too... to help keep diff small when adding new elements line this.

**Review by sbc100 — APPROVED** [review]
Thanks!
