### PR TITLE
Use wrapper functions for growable heap views

### LINKED ISSUE #9190: USE_PTHREADS=1 and ALLOW_MEMORY_GROWTH=1 restricts --js-library file in ES5.
Hi.

When you compile with options "-s USE_PTHREADS=1 -s ALLOW_MEMORY_GROWTH=1 --js-library your_library.js", if your_library.js is written as ES2015, you will get the following error.

    JS optimizer error:
    Unexpected token: name (GraphModelWrapper) (line: 3363, col: 16, pos: 142778)
    
    ================================
    
          setTempRet0(($i) | 0);
        }
    
      
      function method_support() {
              class GraphModelWrapper {
                    ^
    ================================
    
    
    /Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282
            throw new JS_Parse_Error(message, line, col, pos);
            ^
    Error
        at new JS_Parse_Error 
    (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:260:22)
        at js_error (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282:15)
        at croak (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:752:17)
        at token_error 
    (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:760:17)
        at unexpected 
    (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:766:17)
        at Arguments.semicolon 
    (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:786:51)
        at prog1 (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1325:29)
        at simple_statement 
    (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:917:35)
        at /Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:827:35
        at block_ (/Users/XX/emsdk/fastcomp/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1010:32)
    Traceback (most recent call last):
      File "/Users/XX/emsdk/fastcomp/emscripten/emcc.py", line 3492, in <module>
        sys.exit(run(sys.argv))
      File "/Users/XX/emsdk/fastcomp/emscripten/emcc.py", line 2359, in run
    optimizer)
      File "/Users/XX/emsdk/fastcomp/emscripten/emcc.py", line 2896, in do_binaryen
        final = shared.Building.apply_wasm_memory_growth(final)
      File "/Users/XX/emsdk/fastcomp/emscripten/tools/shared.py", line 2710, in apply_wasm_memory_growth
        fixed = Building.js_optimizer_no_asmjs(js_file, ['growableHeap'])
      File "/Users/XX/emsdk/fastcomp/emscripten/tools/shared.py", line 2339, in js_optimizer_no_asmjs
        run_process(cmd, stdout=open(next, 'w'))
      File "/Users/XX/emsdk/fastcomp/emscripten/tools/shared.py", line 181, in run_process
    result.check_returncode()
      File "/Users/XX/emsdk/fastcomp/emscripten/tools/shared.py", line 161, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
    tools.shared.Py2CalledProcessError: Command '['/Users/XX/emsdk/node/8.9.1_64bit/bin/node', '/Users/XX/emsdk/fastcomp/emscripten/tools/js-optimizer.js', '/tmp/emscripten_temp_wuwpaB/index.wasm.o.js', 'growableHeap']' returned non-zero exit status 1

If you write your_library.js in ES5, there are no problems.

My environment is,

1. macOS 10.14.6
1. using latest-upstream
   - emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.40
   - clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 10dad95a75592717d2f7c0ebc181fb8a970a8df7)

What is wierd is that I am using latest-upstream but "JS optimizer" is using parse-js.js whose path includes fastcomp.

Thanks.

### LINKED ISSUE #9963: emscripten_futex_wake fails with pthreads & memory growth
A number of pthreads library functions access `HEAP8` or `HEAP32` without guards for memory growth. I found that `emscripten_futex_wake` caused hangs using the dav1d AV1 decoder with pthreads & memory growth enabled together, as it would fail out when called with a futex address above the current `HEAP8` view's size.

Adding a guard like this:

```js
    if (addr > HEAP8.length) {
      updateGlobalBufferAndViews(wasmMemory.buffer);
    }
```

at the top of the function seems to resolve it for me, but there are other functions similarly affected.

### PR DESCRIPTION
**Pull request by brion**
Fixes pthreads + memory growth for some cases where the `HEAP*` views were used with Atomics or other ways that didn't get caught by the accessor transformations before.

For example `HEAP8.length` is transformed to use an accessor as `GROWABLE_HEAP_I8().length` which updates the views if necessary.

This should work for other library code which uses the `HEAP*` views as well.

Fixes #9963

The second commit switched it from js-optimizer to acorn-optimizer, and also to simplify things reduces the transformations to use the heap views instead of load and store functions. Let me know if that's problematic for performance or any other reason and I'll change it to use the existing load/store functions in the acorn version.

Should fix #9190 though I've not tested actual ES6 code on it.

### CODE REVIEW

File: tools/acorn-optimizer.js [hunk 1]
```diff
@@ -764,6 +764,103 @@ function applyDCEGraphRemovals(ast) {
   });
 }
 
+function createNode(props) {
+  var fakeParser = {
```
Comment (kripken) [inline tools/acorn-optimizer.js]: is this object modified by `Node()`? if not, could it be in the global scope, to avoid allocation here?

File: tools/acorn-optimizer.js [hunk 2]
```diff
@@ -764,6 +764,103 @@ function applyDCEGraphRemovals(ast) {
...
+}
+
+// Instrument heap accesses to call GROWABLE_HEAP_* helper functions instead, which allows
+// pthreads + memory growth to work (we check if the memory was grown on another thread
+// in each access), see #8365.
+function growableHeap(ast) {
+  recursiveWalk(ast, {
+    AssignmentExpression: function(node) {
+      if (node.left.type === 'Identifier' &&
+          node.left.name[0] === 'H'
```
Comment (kripken) [inline tools/acorn-optimizer.js]: maybe `.startsWith('HEAP')`?

File: tools/acorn-optimizer.js [hunk 3]
```diff
@@ -764,6 +764,103 @@ function applyDCEGraphRemovals(ast) {
...
+      node.declarations.forEach(function(decl) {
+        // but do transform anything that sets a var to
+        // something from HEAP8 etc
+        if (decl.init) {
+          growableHeap(decl.init);
+        }
+      });
+    },
+    Identifier: function(node) {
+      if (node.name[0] === 'H') {
```
Comment (kripken) [inline tools/acorn-optimizer.js]: also here

File: tools/acorn-optimizer.js (hunk 1 above)
Comment (brion) [reply tools/acorn-optimizer.js]: It's not modified no, so could allocate once. Just need something with an empty 'options' object property on it to let the constructor pass. :) Will adjust that.

File: tools/acorn-optimizer.js (hunk 2 above)
Comment (brion) [reply tools/acorn-optimizer.js]: Yeah that'll be clearer.

File: tools/acorn-optimizer.js (hunk 1 above)
Comment (brion) [reply tools/acorn-optimizer.js]: Actually it was easy to just allocate a real Parser for safety, and it works the same. Just did that and kept it. :)

**Comment by brion** [comment]
Added a test case for the acorn optimizer growableHeap pass.

**Comment by kripken** [comment]
Tests passed! :tada:
