### PR TITLE
Fix flaky pthread_proxying_refcount test

### LINKED ISSUE #19795: Flakiness in core2.test_pthread_proxying_refcount
See https://app.circleci.com/pipelines/github/emscripten-core/emscripten/29174/workflows/e3fe5072-068b-4775-9d62-0a3bbf0c8ad2/jobs/657474

```
AssertionError: JS subprocess failed (/root/emsdk/node/16.20.0_64bit/bin/node --stack-trace-limit=50 --trace-uncaught /tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js): 7.  Output:
start
Aborted(Assertion failed: frees_after_cull > frees_before_cull, at: /root/project/test/pthread/test_pthread_proxying_refcount.c,100,main)
/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1
var Module=typeof Module!="undefined"?Module:{};var moduleOverrides=Object.assign({},Module);var arguments_=[];var thisProgram="./this.program";var quit_=(status,toThrow)=>{throw toThrow};var ENVIRONMENT_IS_WEB=typeof window=="object";var ENVIRONMENT_IS_WORKER=typeof importScripts=="function";var ENVIRONMENT_IS_NODE=typeof process=="object"&&typeof process.versions=="object"&&typeof process.versions.node=="string";var ENVIRONMENT_IS_PTHREAD=Module["ENVIRONMENT_IS_PTHREAD"]||false;var _scriptDir=[..]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [..]

RuntimeError: Aborted(Assertion failed: frees_after_cull > frees_before_cull, at: /root/project/test/pthread/test_pthread_proxying_refcount.c,100,main). Build with -sASSERTIONS for more info.
    at abort (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:7649)
    at ___assert_fail (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:17949)
    at wasm://wasm/00015f42:wasm-function[23]:0xb6c
    at Module._main (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:24517)
    at callMain (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:27699)
    at doRun (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:28138)
    at run (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:28306)
    at runCaller (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:27568)
    at removeRunDependency (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:7455)
    at /tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:13724
```

### PR DESCRIPTION
**Pull request by tlively**
Remove the use of a timer to wait for a worker thread to destroy two proxying
queues and replace it with an asynchronous task to set flags that will now
deterministically let the main thread continue after the queues have been
destroyed.

Fixes #19795.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #19797** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/19797" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/19797?utm_source=stack-comment).

File: test/pthread/test_pthread_proxying_refcount.c [hunk 1]
```diff
@@ -74,17 +76,11 @@ int main() {
   }
   should_execute = 1;
 
-  // Wait for the tasks to be executed.
+  // Wait for the tasks to be executed. The queues will have been destroyed
+  // after this.
   while (!executed[0] || !executed[1]) {
```
Comment (sbc100) [inline test/pthread/test_pthread_proxying_refcount.c:81]: Should we put a shed_yeild / emscripten_yield in this loop?

**Review by sbc100 — APPROVED** [review]
