### PR TITLE
Fix side module exception handling

### LINKED ISSUE #16302: Side module calls __cxa_find_matching_catch_n which is missing from main module
When I have a main module and a side module with exception support, I get an error like `Cannot read properties of undefined (reading 'apply')` because `resolveGlobalSym` fails to find a global symbol called `__cxa_find_matching_catch_14`, since the main module only defines e.g., `__cxa_find_matching_catch_2`, `__cxa_find_matching_catch_3`, and `__cxa_find_matching_catch_5`.

Adding the following to the end of `resolveGlobalSym`:
```js
    if(!sym && symName.startsWith("__cxa_find_matching_catch")){
      sym = Module.___cxa_find_matching_catch;
    }
```
fixes it.

### PR DESCRIPTION
**Pull request by hoodmane**
Resolves #16302. I am happy to add tests if you want, but would appreciate some guidelines for how to make them.

Exception handling for C++ code calls a bunch of functions with names like
`__cxa_find_matching_catch_##`. In Emscripten all of these functions are defined
to be the same function. Emscripten statically defines the set of these that are used
by C++ code in the main module, but it is possible that a side module will need extra
ones. This fixes the problem by updating `resolveGlobalSymbol` so that in a side module
every `__cxa_find_matching_catch_##` will resolve to `__cxa_find_matching_catch`.

### CODE REVIEW

File: src/library_dylink.js [hunk 1]
```diff
@@ -33,6 +33,9 @@ var LibraryDylink = {
       sym = createInvokeFunction(symName.split('_')[1]);
     }
 
+    if(!sym && symName.startsWith("__cxa_find_matching_catch")){
```
Comment (kripken) [inline src/library_dylink.js:36]:
```suggestion
    if (!sym && symName.startsWith("__cxa_find_matching_catch")) {
```

**Review by kripken — COMMENTED** [review]
For testing, I'm curious why `test_dylink_exceptions_try_catch` and `test_dylink_exceptions_try_catch_2` that already exist, pass. It seems like they should need this as well..?

Hopefully that is easy to figure out. And then maybe adding something to one of those tests could cover the situation this PR fixes.

**Comment by kripken** [comment]
(also there appear to be test failures here that need to be looked at - let me know if you need help there)

**Comment by hoodmane** [comment]
How do I run one specific test?

**Comment by hoodmane** [comment]
Okay I got it: `./tests/runner core2.test_dylink_exceptions_try_catch`

**Comment by kripken** [comment]
(more test docs here if you need them: https://emscripten.org/docs/getting_started/test-suite.html#debugging-test-failures)

File: src/library_dylink.js (hunk 1 above)
Comment (sbc100) [reply src/library_dylink.js:36]: Nice!  lgtm assuming we can write a test for it.

**Comment by hoodmane** [comment]
Okay, so the reason that `test_dylink_exceptions_try_catch` works is that the main module and the side module both use `__cxa_find_matching_catch_2`. But even if they didn't both use `__cxa_find_matching_catch_3`, the side module is compiled first and then the main module is compiled with `em++ main.cpp -o main.js liblib.so -sMAIN_MODULE=2`. So emscripten looks in `liblib.so` and finds that it needs `__cxa_find_matching_catch_2` and throws that in.

To reproduce this problem you need to compile the main module instead with `em++ main.cpp -o main.js -sMAIN_MODULE=1`. Then the other issue is that apparently `__cxa_find_matching_catch_2` and `__cxa_find_matching_catch_3` are always included so you need two catch clauses to get up to `__cxa_find_matching_catch_4`.

So altogether a test case that fails on main and succeeds on this branch is as follows:
```C++
#include <dlfcn.h>
int main() {
  void* handle = dlopen("liblib.so", RTLD_LAZY);
  void (*side)(void) = (void (*)(void))dlsym(handle, "side");
  (side)();
  return 0;
}
```

Side module:
```C++
#include <stdio.h>
extern "C" void side() {
  try {
    throw 3;
  } catch (int x){
    printf("side: caught int %d\n", x); 
  } catch (float x){
    printf("side: caught float %f\n", x); 
  }
}
```
and compile with:
```sh
em++ liblib.cpp -o liblib.wasm -sDISABLE_EXCEPTION_CATCHING=0 -sSIDE_MODULE -O2
em++ main.cpp -o main.js -sDISABLE_EXCEPTION_CATCHING=0 -sMAIN_MODULE=1 -O2
```

**Comment by sbc100** [comment]
I see.  Does that mean that you can also solve #16302 by including your side module on the command line when linking your main module? 

I'm not saying we shouldn't land this change anyway.. but just so you are aware building with MAIN_MODULE=2 and passing the side module on the command line produce much better results.

**Comment by sbc100** [comment]
It sounds like in you will need to write a test that is not based on `dylink_test` because those test always pass the side module on the command line.   It should be easy enough to write such a test.

**Comment by hoodmane** [comment]
We have a hard time building the side modules before building the main module because we have so many side modules. scipy alone has 99 different side modules files. I suppose it might be worth considering trying to link in some of the side modules, but I think we also wish to allow people to build additional side modules without rebuilding our main module, just like the way it isn't necessary to rebuild your system Python every time you build a binary extension.

**Comment by hoodmane** [comment]
> not for the dlopen case which I think yours is.

Exactly. Though it looks like with `-sAUTOLOAD_DYLIBS=0` you could probably use `-sMAIN_MODULE=2` for `dlopen`, if you know ahead of time which libraries you might load.

File: src/library_dylink.js [hunk 2]
```diff
@@ -33,6 +33,11 @@ var LibraryDylink = {
       sym = createInvokeFunction(symName.split('_')[1]);
     }
 
+#if !DISABLE_EXCEPTION_CATCHING
+    if (!sym && symName.startsWith("__cxa_find_matching_catch")) {
+      sym = Module["___cxa_find_matching_catch"];
```
Comment (sbc100) [inline src/library_dylink.js:38]: Can use use single quotes for the strings here?

File: tests/test_core.py [hunk 3]
```diff
@@ -4539,6 +4539,48 @@ def test_dylink_exceptions_try_catch_2(self):
...
 
+  @with_both_eh_sjlj
+  @needs_dylink
+  def test_dylink_exceptions_try_catch_3(self):
+    main = r'''
+      #include <dlfcn.h>
+      int main() {
+        void* handle = dlopen("liblib.so", RTLD_LAZY);
+        void (*side)(void) = (void (*)(void))dlsym(handle, "side");
+        (side)();
```
Comment (sbc100) [inline tests/test_core.py:4550]: You don't need the braces around side here.

**Review by sbc100 — APPROVED** [review]
Great! 

(I assume that test fails without your change?)

**Comment by hoodmane** [comment]
> I assume that test fails without your change?

Yup:
```
TypeError: Cannot read property 'apply' of undefined
    at stubs.<computed> (/tmp/emscripten_test/main.js:1:28426)
    at side (<anonymous>:wasm-function[11]:0x221)
    at __original_main (<anonymous>:wasm-function[157]:0x76044)
    at main (<anonymous>:wasm-function[158]:0x7604c)
    at Module._main (/tmp/emscripten_test/main.js:1:651651)
    at callMain (/tmp/emscripten_test/main.js:1:2955748)
    at doRun (/tmp/emscripten_test/main.js:1:2956272)
    at run (/tmp/emscripten_test/main.js:1:2956444)
    at runCaller (/tmp/emscripten_test/main.js:1:2955382)
    at removeRunDependency (/tmp/emscripten_test/main.js:1:16499)
    at receiveInstance (/tmp/emscripten_test/main.js:1:18516)
    at receiveInstantiationResult (/tmp/emscripten_test/main.js:1:18637)
```

**Comment by hoodmane** [comment]
Thanks again @sbc100 and @kripken!
