### PR TITLE
Properly set addrlen in accept(), getsockname(), getpeernam() and recvfrom(). Fixes #12996.

### LINKED ISSUE #12996: accept(), getsockname(), getpeername(), and recvfrom() don't set addrlen in emulated mode
The man pages on linux say:
https://linux.die.net/man/2/getsockname
https://linux.die.net/man/2/recvfrom

`The addrlen argument should be initialized to indicate the amount of space (in bytes) pointed to by addr. On return it contains the actual size of the socket address. `

This is not what emscripten does; the `addrlen` is never set in `accept()`, `getsockname()`, `getpeernam()`, and `recvfrom()`. On its own this is not too much of an issue, but if you feed the unchanged `addrlen` back in a function that calls `__read_sockaddr`, like `getnameinfo`, the call fails (and can even crash an application).

This is only a problem if you deal with IPv4 and IPv6 in your application, as it is likely you will be using `sockaddr_storage`; if you are IPv4 only, it is likely you use `sockaddr_in`, avoiding this problem.

The problem seems to be around https://github.com/emscripten-core/emscripten/blob/master/src/library_syscall.js#L624 , but I have a hard time understanding how to write back to `addrlen` (writing back to `addr` is done by `__write_sockaddr`, which is magic to me).

Example application below. Expected output is `0.0.0.0` as last line. It returns nothing with emscripten + node (and from porting other applications, I know it corrupts the heap in most cases).

```c
#include <sys/socket.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <string.h>
#include <netdb.h>


int main() {
    struct sockaddr_in addr;

    int s = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);

    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(12345);
    inet_pton(AF_INET, "127.0.0.1", &addr.sin_addr);

    connect(s, (struct sockaddr *)&addr, sizeof(addr));

    struct sockaddr_storage adr_inet;
    socklen_t len_inet = sizeof adr_inet;
    getsockname(s, (struct sockaddr *)&adr_inet, &len_inet);

    printf("%d (should be %ld)\n", len_inet, sizeof(struct sockaddr_in));
// Enabling this line, something that `getsockname` should have done, fixes the problem:
//    len_inet = sizeof(struct sockaddr_in));

    char hostname[80];
    getnameinfo((struct sockaddr *)&adr_inet, len_inet, hostname, sizeof(hostname), NULL, 0, NI_NUMERICHOST);
    printf("%s\n", hostname);

    return 0;
}
```

### PR DESCRIPTION
**Pull request by Milek7**
Fixes https://github.com/emscripten-core/emscripten/issues/12996

### CODE REVIEW

File: src/library_syscall.js [hunk 1]
```diff
@@ -608,6 +610,7 @@ var SyscallsLibrary = {
 #if ASSERTIONS
         assert(!res.errno);
 #endif
+        {{{ makeSetValue('addrlen', 0, 'res.salen', 'i32') }}};
```
Comment (sbc100) [inline src/library_syscall.js:613]: Given that all four of the call sites do this, eight not pass this the `res.salen` as an extra argument to __write_sockaddr?

Then it can just return errno rather than a JS object.

Also, since they are JS-only functions these should probably be called
`$writeSockaddr` and `$readSockaddr` to avoid conflict or confusion with native symbols (which start with `_`).   But we can do that a followup if you prefer.

Comment (Milek7) [reply src/library_syscall.js]: I changed it to extra argument and returning errno.
I'm sure if I want to rename it, I don't even know how this ends up being called `__write_sockaddr` while declared `_write_sockaddr`...

Comment (sbc100) [reply src/library_syscall.js]: sgtm

**Review by sbc100 — COMMENTED** [review]
lgtm!

maybe @juj has an opinion on this?

**Comment by juj** [comment]
Looks great!

**Review by juj — APPROVED** [review]
