### PR TITLE
Fix flake in test_pthread_proxying_refcount

### LINKED ISSUE #19795: Flakiness in core2.test_pthread_proxying_refcount
See https://app.circleci.com/pipelines/github/emscripten-core/emscripten/29174/workflows/e3fe5072-068b-4775-9d62-0a3bbf0c8ad2/jobs/657474

```
AssertionError: JS subprocess failed (/root/emsdk/node/16.20.0_64bit/bin/node --stack-trace-limit=50 --trace-uncaught /tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js): 7.  Output:
start
Aborted(Assertion failed: frees_after_cull > frees_before_cull, at: /root/project/test/pthread/test_pthread_proxying_refcount.c,100,main)
/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1
var Module=typeof Module!="undefined"?Module:{};var moduleOverrides=Object.assign({},Module);var arguments_=[];var thisProgram="./this.program";var quit_=(status,toThrow)=>{throw toThrow};var ENVIRONMENT_IS_WEB=typeof window=="object";var ENVIRONMENT_IS_WORKER=typeof importScripts=="function";var ENVIRONMENT_IS_NODE=typeof process=="object"&&typeof process.versions=="object"&&typeof process.versions.node=="string";var ENVIRONMENT_IS_PTHREAD=Module["ENVIRONMENT_IS_PTHREAD"]||false;var _scriptDir=[..]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [..]

RuntimeError: Aborted(Assertion failed: frees_after_cull > frees_before_cull, at: /root/project/test/pthread/test_pthread_proxying_refcount.c,100,main). Build with -sASSERTIONS for more info.
    at abort (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:7649)
    at ___assert_fail (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:17949)
    at wasm://wasm/00015f42:wasm-function[23]:0xb6c
    at Module._main (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:24517)
    at callMain (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:27699)
    at doRun (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:28138)
    at run (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:28306)
    at runCaller (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:27568)
    at removeRunDependency (/tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:7455)
    at /tmp/emtest_y_ikdp25/emscripten_test_core2_rv_ej3hp/test_pthread_proxying_refcount.js:1:13724
```

### PR DESCRIPTION
**Pull request by tlively**
It apparently takes more than one turn of the worker thread's event loop
to ensure that the notifications on the zombie task queues have been
cleared so the zombies can be culled. Update the test to wait two turns
of the event loop instead of one.

Also add new synchronization forcing the main thread to wait until the
worker thread has entered Wasm before proxying work to it. This prevents
the proxied work notifications from somehow being cleared before the
worker thread destroys the proxy queues, which would prevent the task
queues from ever being placed on the zombie list in the first place.

Finally, generally improve comments and make the test assertions more
specific.

Fixes #19795.

### CODE REVIEW

**Comment by juj** [comment]
Very nice, thanks for the attention. Ran this several times on Windows, Linux and macOS, and it does look watertight now.

**Review by juj — APPROVED** [review]

File: test/pthread/test_pthread_proxying_refcount.c [hunk 1]
```diff
@@ -29,22 +34,28 @@ void __attribute__((noinline)) free(void* ptr) {
 
 #endif // SANITIZER
 
+_Atomic int worker_started = 0;
 _Atomic int should_execute = 0;
```
Comment (sbc100) [inline test/pthread/test_pthread_proxying_refcount.c]: Can you use `bool` for these two atomics to make the purpose more clear?

Comment (tlively) [reply test/pthread/test_pthread_proxying_refcount.c]: Done.

File: test/pthread/test_pthread_proxying_refcount.c [hunk 2]
```diff
@@ -29,22 +34,28 @@ void __attribute__((noinline)) free(void* ptr) {
...
+}
 
-// Delay setting the flag until the next turn of the event loop so it can be set
-// after the proxying queue is destroyed.
-void task(void* arg) { emscripten_async_call(set_flag, arg, 0); }
+void task(void* arg) { emscripten_async_call(increment_flag, arg, 0); }
 
 void* execute_and_free_queue(void* arg) {
+  // Signal the main thread to proxy work to us.
+  worker_started = 1;
```
Comment (sbc100) [inline test/pthread/test_pthread_proxying_refcount.c]: (I assumed you could use true/false in the all the assignment too).

Comment (tlively) [reply test/pthread/test_pthread_proxying_refcount.c]: Done.
