### PR TITLE
Fix #24982: emsymbolizer failed to parse symbol map from C++ project

### LINKED ISSUE #24982: emsymbolizer failed to parse symbol map from C++ project
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 4.0.13 (2659582941bef14008476903f48941909db1b196)                                                                                                                                                                                                 ─╯
clang version 22.0.0git (https:/github.com/llvm/llvm-project 177f27d22092cb64e871e6cd2f8981d24e823186)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/landerl/Applications/emsdk/upstream/bin
```

**Failing command line in full:**

```
$EMSDK/upstream/emscripten/emsymbolizer -s symbolmap -f cmake-build-wasm/dist/markxx.js.symbols cmake-build-wasm/dist/markxx.wasm 0x15452
```

**`emsymbolizer` utility failed with the output**
```cpp
Traceback (most recent call last):bolizer -s symbolmap -f cmake-build-wasm/dist/markxx.js.symbols cmake-build-wasm/dist/markxx.wasm 0x15452                                                                                                                                                                              ─╯
  File "/Users/landerl/Applications/emsdk/upstream/emscripten/emsymbolizer.py", line 295, in <module>
    rv = main(get_args())
  File "/Users/landerl/Applications/emsdk/upstream/emscripten/emsymbolizer.py", line 265, in main
    symbolize_address_symbolmap(module, address, args.file)
  File "/Users/landerl/Applications/emsdk/upstream/emscripten/emsymbolizer.py", line 226, in symbolize_address_symbolmap
    index, name = line.split(':')
ValueError: too many values to unpack (expected 2)
```

Turns out c++ symbol map has the namespace delimtier `::` which render the python code `index, name = line.split(':')` to fail

example symbol map `markxx.js.symbols`:
```
12457:std::length_error::~length_error\28\29_12457
12458:std::out_of_range::~out_of_range\28\29
12459:std::overflow_error::~overflow_error\28\29
12460:std::bad_cast::~bad_cast\28\29_12460
12461:std::bad_cast::what\28\29\20const
```

### PR DESCRIPTION
**Pull request by LanderlYoung**
1. fix symbol map line parse
2. unescape ascii code
3. update tests: test/runner "other.test_emsymbolizer*"

This PR fixes #24982

### CODE REVIEW

File: test/test_symbolmap.cpp [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#include <emscripten.h>
```
Comment (kripken) [inline test/test_symbolmap.cpp]: Maybe put this file in `test/other`?

File: emsymbolizer.py [hunk 2]
```diff
@@ -218,12 +218,33 @@ def symbolize_address_sourcemap(module, address, force_file):
...
+      index = line.find(':')
+      if index == -1:
+          raise ValueError(f'invalid symbolmap line: {line}')
+      return line[:index], unescape_ascii_codes(line[index + 1:])
+
+  def unescape_ascii_codes(input_str):
+      """
+      input:  std::out_of_range::~out_of_range\28\29
+      output: std::out_of_range::~out_of_range()
+      """
```
Comment (kripken) [inline emsymbolizer.py]: This part is a breaking change, I think? I agree it is convenient, and consistent with the Name section, but if we decide it is worth it, we'll need to mention it in the Changelog.

@dschuff thoughts?

Comment (dschuff) [reply emsymbolizer.py]: I think this is a good change, for consistency, and because the escaped form of the demangled name doesn't seem super useful to me. I doubt emsymbolizer has so many users and workflows that it would be a problem to change it. A changelog entry would be good though.

Really, I think the symbol map should probably store the mangled name rather than the demangled name anyway. Demangled names are not unique. And then emsymbolizer could have the option to demangle them or not. The linker has an option to store mangled or demangled names in the name section (I forget which is the default), but everything that carries semantic meaning (e.g. symbol tables) has to be mangled, and IMO demangling should happen as close to the "display things to the user" stage as possible.
That would be a bigger breaking change though, since probably a lot more people are using the symbol map format already.

File: test/test_symbolmap.cpp (hunk 1 above)
Comment (LanderlYoung) [reply test/test_symbolmap.cpp]: sure

File: emsymbolizer.py (hunk 2 above)
Comment (LanderlYoung) [reply emsymbolizer.py]: Ok, I've added a line in the change log.

File: ChangeLog.md [hunk 3]
```diff
@@ -29,6 +29,9 @@ See docs/process.md for more on how version tagging works.
 - The wasm offset converter was removed along with the `WASM_OFFSET_CONVERTER`
   setting. This feature only existed to work around an old v8 bug that was fixed
   back in 2019. (#24963)
+- emsymbolizer will now escape char in symbolmap, for example:
```
Comment (kripken) [inline ChangeLog.md]:
```suggestion
- emsymbolizer will now escape names in symbol maps, for example:
```

**Comment by sbc100** [comment]
Is there some reason we cannot or should not just update the symbol map to avoid this mangling in the first place.

What is the source of the mangling in the first place?   What style of mangling is `std::out_of_range::~out_of_range\28\29` ?

**Comment by dschuff** [comment]
I don't know what kind of mangling that is; it doesn't exactly match others that I'm familiar with. 
My assumption was that there are users that are depending on the contents of the symbol map. and would have some kind of workflow that would be broken if we were to change it. Maybe I'm wrong and we could just do that. Or, maybe it's ess of a breaking change to remove the special mangling than to go to a fully-C++-mangled state, since presumably users who depend on the current format would have their own demangling, so if we just stopped adding the mangling, maybe they wouldn't be broken?

**Comment by sbc100** [comment]
> I don't know what kind of mangling that is; it doesn't exactly match others that I'm familiar with. My assumption was that there are users that are depending on the contents of the symbol map. and would have some kind of workflow that would be broken if we were to change it. Maybe I'm wrong and we could just do that. Or, maybe it's ess of a breaking change to remove the special mangling than to go to a fully-C++-mangled state, since presumably users who depend on the current format would have their own demangling, so if we just stopped adding the mangling, maybe they wouldn't be broken?

I'd be tempted to make that change to the symbol map to include fully demanged symbols.   @kripken do you remember why we have these strange escape codes in the map file?

**Comment by kripken** [comment]
I'm not sure. But isn't the symbol map just copying the name section? It should contain whatever is there iirc.

**Comment by sbc100** [comment]
So maybe the issue is that the name section is broken?

**Comment by sbc100** [comment]
> So maybe the issue is that the name section is broken?

The name sections is fine.  The problem seems to stem from the `wasm-opt --print-function-map` command.. I guess binaryen doesn't like those symbols.

I think we should file a binaryen bug, or maybe just avoid binaryen for this purpose (since we don't need to run process the whole wasm file, only the name section.

**Comment by kripken** [comment]
@sbc100 do you want this PR to wait until we figure that out, or can this land?

**Comment by sbc100** [comment]
> @sbc100 do you want this PR to wait until we figure that out, or can this land?

I don't think we we should land this since it would only act to further lock in the strange escaping behavior

**Comment by kripken** [comment]
Oh, I think the first part of this PR is still important though:

> fix symbol map line parse

That handles splitting when the line contains `::` as a separator.

We can refocus this PR on just that?

**Comment by sbc100** [comment]
> Oh, I think the first part of this PR is still important though:
> 
> > fix symbol map line parse
> 
> That handles splitting when the line contains `::` as a separator.
> 
> We can refocus this PR on just that?

Ah, yes that could make sense.

**Comment by LanderlYoung** [comment]
Thanks guys! The name escape part has been reverted. Please review :rose:

File: test/test_other.py [hunk 4]
```diff
@@ -11031,6 +11031,24 @@ def check_symbolmap_info(address, func):
     # The name section will not show bar, as it's inlined into main
     check_symbolmap_info(unreachable_addr, '__original_main')
 
+    # 3. Test symbol map on C++ name mangling
+    self.run_process([EMCC, test_file('other/test_symbolmap.cpp'),
```
Comment (dschuff) [inline test/test_other.py]:
```suggestion
    self.run_process([EMXX, test_file('other/test_symbolmap.cpp'),
```

File: test/test_other.py [hunk 5]
```diff
@@ -11031,6 +11031,24 @@ def check_symbolmap_info(address, func):
...
+                      '-O1', '--emit-symbol-map', '-o', 'test_symbolmap.js'])
+    self.assertExists('test_symbolmap.js.symbols')
+
+    out_to_js_call_addr = self.get_instr_addr('call\t0', 'test_symbolmap.wasm')
+    unreachable_addr = self.get_instr_addr('unreachable', 'test_symbolmap.wasm')
+
+    def check_cpp_symbolmap_info(address, func):
```
Comment (dschuff) [inline test/test_other.py:11055]: Could we maybe combine this with `check_symbolmap_info` above?

File: test/test_other.py [hunk 6]
```diff
@@ -11031,6 +11031,24 @@ def check_symbolmap_info(address, func):
...
+      out = self.run_process([emsymbolizer, '--source=symbolmap', '-f', 'test_symbolmap.js.symbols', 'test_symbolmap.wasm', address], stdout=PIPE).stdout
+      self.assertIn(func, out)
+
+    check_cpp_symbolmap_info(out_to_js_call_addr, 'Namespace::foo')         # the function name
+    check_cpp_symbolmap_info(out_to_js_call_addr, 'Namespace::ClassA')      # the parameter
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::bar')            # the function name
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::ClassA')         # the type parameter
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::ClassB')         # the parameter
```
Comment (dschuff) [inline test/test_other.py]: Can you also check for `out_to_js`? Names for JS imports is one feature of symbol maps that DWARF and sourcemaps don't have.

**Review by dschuff — COMMENTED** [review]
Looks good overall, just a couple of nits on the test.

File: test/test_other.py (hunk 5 above)
Comment (sbc100) [reply test/test_other.py:11055]: We already have a test called `test_symbol_map`  and I just added `other/test_symbol_map.out` which goes with that test.

So calling this `test_symbolmap` is a little confusing.

Maybe move the code from `test_symbol_map` into its own file in `test/other/test_symbol_map.cpp` and then reference that file here?

Comment (LanderlYoung) [reply test/test_other.py:11055]: Has moven the two tests into into `test_symbol_map.cpp` file.

File: test/test_other.py (hunk 6 above)
Comment (LanderlYoung) [reply test/test_other.py]: Sure, but some helps is needed.

How to check an imported JS function, since they don't have wasm code nither do they have address.

We can check if the symbol_map file contains the `out_to_js` string manually, is that OK?

Comment (LanderlYoung) [reply test/test_other.py]: Test code has been updated as described, please review.

**Comment by LanderlYoung** [comment]
Some `other.test_codesize*` tests seemed to fail, but I didn't find a relation with this code change.

File: test/test_other.py (hunk 6 above)
Comment (dschuff) [reply test/test_other.py]: Yes, that's what I meant, thanks.

File: test/test_other.py [hunk 7]
```diff
@@ -11031,6 +11011,29 @@ def check_symbolmap_info(address, func):
     # The name section will not show bar, as it's inlined into main
     check_symbolmap_info(unreachable_addr, '__original_main')
 
+    # 3. Test symbol map on C++ name mangling
```
Comment (dschuff) [inline test/test_other.py]:
```suggestion
    # 3. Test symbol map on demangled C++ names
```

**Review by dschuff — COMMENTED** [review]
If you merge the PR to the tip of the main branch, the code size test failures should go away. And you'll have to do that anyway, since you have a conflict.

File: emsymbolizer.py [hunk 8]
```diff
@@ -218,12 +218,19 @@ def symbolize_address_sourcemap(module, address, force_file):
 
 def symbolize_address_symbolmap(module, address, symbol_map_file):
   """Symbolize using a symbol map file."""
+
+  def split_symbolmap_line(line):
+      index = line.find(':')
```
Comment (sbc100) [inline emsymbolizer.py]: I think you can just do `return line.split(':', 1)`

If you want and explicit error you could also add `assert ':' in line, 'f'invalid symbolmap line: {line}'`

File: test/test_other.py [hunk 9]
```diff
@@ -11031,6 +11011,29 @@ def check_symbolmap_info(address, func):
...
+    def check_symbol_map_contains(func):
+      out = read_file('test_symbol_map.js.symbols')
+      self.assertIn(func, out)
+
+    check_cpp_symbolmap_info(out_to_js_call_addr, 'Namespace::foo')         # the function name
+    check_cpp_symbolmap_info(out_to_js_call_addr, 'Namespace::ClassA')      # the parameter
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::bar')            # the function name
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::ClassA')         # the type parameter
+    check_cpp_symbolmap_info(unreachable_addr, 'Namespace::ClassB')         # the parameter
+    check_symbol_map_contains('out_to_js')                                  # the imported function
```
Comment (sbc100) [inline test/test_other.py]: Actually I think maybe we should be making test_symbol_map any more complex by including emsymbolizer stuff too.   Can we go back adding this to a new or existing test_emsymboliser_xx test?

Comment (dschuff) [reply test/test_other.py]: Or... could we just turn test_dwarf.c into a c++ test and then have the existing symbol map test include C++ symbols? that would make this a very small increment over the existing test.

Comment (LanderlYoung) [reply test/test_other.py]: Sorry for the late reply, have been busy with work this week.

Actually, I first tried to reuse the `test_dwarf.c` file, but since it's used in a lot of other tests, I created a new standalone file instead.

Now, by using `create_file` to generate the source, this test is self-contained and not couple with others.

File: test/test_other.py [hunk 10]
```diff
@@ -11021,6 +11021,57 @@ def check_symbolmap_info(address, func):
     # The name section will not show bar, as it's inlined into main
     check_symbolmap_info(unreachable_addr, '__original_main')
 
+  def test_emsymbolizer_symbol_map_names(self):
+    "Test emsymbolizer with symbol map which contains demangled C++ names"
```
Comment (sbc100) [inline test/test_other.py]: Use triple-quotes for docstrings

**Comment by sbc100** [comment]
Thanks for you patience on this PR.  LGTM with one final comment!

**Comment by dschuff** [comment]
browser test failures are unrelated, I'll go ahead and merge this. Thanks!
