### PR TITLE
Fix emscripten_atomic_exchange_u8,16,32,64. fixes #10654

### LINKED ISSUE #10654: Atomics are miscompiled in wasm backend
Switching from fastcomp backend to wasm backend, atomics begun to fail,
```c++
#include <emscripten/emscripten.h>
#include <emscripten/threading.h>
#include <stdint.h>
#include <stdio.h>
int main()
{
    uint8_t a = 1;
    uint8_t b = 2;
    uint8_t c = emscripten_atomic_exchange_u8(&a, b);
    printf("%d %d %d\n", a, b, c);
    return 0;
}
```

```
em++ a.cpp -pthread -s USE_PTHREADS=1 -std=c++14 -o a.html
```
Running a.html fails with
```
exception thrown: RuntimeError: unaligned memory access,@http://localhost:6931/a.wasm:wasm-function[100]:0x7194
@http://localhost:6931/a.wasm:wasm-function[27]:0xa18
@http://localhost:6931/a.wasm:wasm-function[28]:0xaa7
Module._main@http://localhost:6931/a.js:3415:32
callMain@http://localhost:6931/a.js:3881:28
doRun@http://localhost:6931/a.js:3943:31
run/<@http://localhost:6931/a.js:3954:7
a.html:1246:19
RuntimeError: unaligned memory access a.wasm:29076:1
```

Disassembling says that a `i32.atomic.rmw.cmpxchg`
```
   (i32.atomic.rmw.cmpxchg
    (i32.const 4544)
    (i32.const 0)
    (i32.const 1)
```
whereas it should have generated `i8.atomic.rmw.cmpxchg`? Did not try other atomics, I wonder if they might have similar issues?

### PR DESCRIPTION
**Pull request by kripken**
Looks like we didn't have a test for those, added.

### CODE REVIEW

File: tests/core/pthread/emscripten_atomics.c [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  assert(buffer[1] == OLD);
+
+  uint16_t o16 = emscripten_atomic_exchange_u16(&buffer[0], 2);
+  assert((o16 & 0xff) == 1);
+  assert((o16 >> 8) == OLD);
+  assert(buffer[0] == 2);
+  assert(buffer[1] == 0);
+  assert(buffer[2] == OLD);
+
+  uint16_t o32 = emscripten_atomic_exchange_u32(&buffer[0], 3);
```
Comment (tlively) [inline tests/core/pthread/emscripten_atomics.c]: Should this be a `uint32_t`?

Comment (kripken) [reply tests/core/pthread/emscripten_atomics.c]: Thanks!

Also I realized we should check both the pthreads stubs and the full pthreads version, I added that now too.

**Comment by kripken** [comment]
Not sure of the history of these, or the plan - @juj?
