### PR TITLE
Fix extended Latin-1 chars in AsciiToString

### LINKED ISSUE #8197: AsciiToString doesn't work on extended Latin-1 characters
The docs for `AsciiToString` say:

> Converts an ASCII or Latin-1 encoded string to a JavaScript String object.

However, right now trying to write a string containing one of the Latin-1 characters with code >= 0x80 using `WriteAsciiToMemory` and then reading it back via `AsciiToString` results in a corrupted string.

I suspect the reason is that `AsciiToString` reads signed `i8` integers from the memory, so that all these codes turn into negative numbers, and passing them into `charCodeAt` produces completely different char codes.

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #8197.

### CODE REVIEW

File: tests/utf8.cpp [hunk 1]
```diff
@@ -12,6 +12,13 @@
 
 // This code tests that Unicode std::wstrings can be marshalled between C++ and JS.
 int main() {
+  const char latin1String[] = "\x26\xA0\xF7";
+  EM_ASM({
+    var str = Module.AsciiToString($0);
+    var expected = "\\x26\\xA0\\xF7";
+    if (str !== expected) throw 'string mismatch: "' + str + '" != "' + expected + '"';
```
Comment (kripken) [inline tests/utf8.cpp]: can call `assert(str == expected, 'string mismatch [..]`

Comment (RReverser) [reply tests/utf8.cpp]: Is `assert` available inside the JavaScript? Note that this wouldn't fail outside of the JS block, because from C/C++ point of view, both are decoded to the same array of `char`s after round-trippping, while in JS they are different strings.

I suspect this is the reason this slipped by in the past.

**Comment by RReverser** [comment]
Added myself to AUTHORS.

File: tests/utf8.cpp (hunk 1 above)
Comment (kripken) [reply tests/utf8.cpp]: We define assert in JS, yes (the optimizer might remove it if it's not used, though).

Comment (RReverser) [reply tests/utf8.cpp]: Ah ok then. FWIW I was just looking at other assertions in the same file, which also use custom comparisons.

Comment (RReverser) [reply tests/utf8.cpp]: Updated.

**Comment by kripken** [comment]
Great, thanks!
