### PR TITLE
Ignore -s USE_WEBGL2=1 directive if one is not linking in WebGL at all

### LINKED ISSUE #8673: Can't use STRICT=1 with USE_WEBGL2=1
I get the following error for a simple hello world example when combining `USE_WEBGL2=1` with `STRICT=1`. It appears `library_webgl.js` is not included.

```
emcc helloworld.c -s USE_WEBGL2=1 -s STRICT=1
error: failure to execute js library "library_webgl2.js": ReferenceError: createGLPassthroughFunctions is not defined,
error: use -s VERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "ReferenceError: createGLPassthroughFunctions is not defined" | ReferenceError: createGLPassthroughFunctions is not defined
    at eval (eval at load (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8)), <anonymous>:880:1)
    at Object.load (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8), <anonymous>:169:9)
    at JSify (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8), <anonymous>:59:20)
    at Object.<anonymous> (/<path to>emscripten/1.38.31/src/compiler.js:219:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
shared:ERROR: 'node /<path to>emscripten/1.38.31/src/compiler.js /tmp/tmpd0GksE.txt /<path to>emscripten/1.38.31/src/library_pthread_stub.js' failed (1)

```

### PR DESCRIPTION
**Pull request by juj**
Ignore -s USE_WEBGL2=1 directive if one is not linking in WebGL at all (-lGL was not passed while -s STRICT=1 is used)

Fixes #8673.

Was pondering whether to make `-s USE_WEBGL2=1` without `-lGL` an error, but that does not seem very productive, as missing linked in `gl*` symbols should hint user that they are missing a library they should link in - same as when omitting `-lGL` without `-s USE_WEBGL2=1`.

### CODE REVIEW

File: src/library_webgl2.js [hunk 1]
```diff
@@ -1110,10 +1110,13 @@ var webgl2Funcs = [[0, 'endTransformFeedback pauseTransformFeedback resumeTransf
 
 #if USE_WEBGL2
 
-createGLPassthroughFunctions(LibraryWebGL2, webgl2Funcs);
+// If user passes -s USE_WEBGL2=1 -s STRICT=1 but not -lGL (to link in WebGL 1), then ignore linking in WebGL 2 either.
```
Comment (kripken) [inline src/library_webgl2.js]: `either` => `as well`?

File: src/library_webgl2.js [hunk 2]
```diff
@@ -1110,10 +1110,13 @@ var webgl2Funcs = [[0, 'endTransformFeedback pauseTransformFeedback resumeTransf
...
+if (typeof createGLPassthroughFunctions !== 'undefined') {
```
Comment (kripken) [inline src/library_webgl2.js]: this check seems a little odd here. how about in emcc.py, if strict and no -lGL then disabling `USE_WEBGL*`?

File: src/library_webgl2.js (hunk 1 above)
Comment (juj) [reply src/library_webgl2.js]: check

File: src/library_webgl2.js (hunk 2 above)
Comment (juj) [reply src/library_webgl2.js]: Hmm, I can do that if preferred, though in my mind this kind of check is more preferable since it is more self-contained/cohesive?

Comment (sbc100) [reply src/library_webgl2.js]: What about some kind of "error: USE_WEBGL2 doesn't work without -lGL"?  Or have USE_WEBGL2 imply -lGL?  Having it silently not work seems wrong.

Comment (kripken) [reply src/library_webgl2.js]: I agree it's more self-contained your way. I suspect that there might be other benefits to doing it cleanly in emcc.py, though (that is, other side effects of `USE_WEBGL` would be removed if we disable it at the source). But if you think that's unlikely then lgtm as is.

Comment (juj) [reply src/library_webgl2.js]: Ok, updated with an error message in library_webgl2.js, that should address both comments.

**Comment by juj** [comment]
Browser test failures look intermittent, so landing.
