### PR TITLE
Fix ASan handling of WasmOffsetConverter reading on a pthread

### LINKED ISSUE #13205: ASan hit on background threads broken with "TypeError: Cannot read property 'length' of undefined"
If Asan failure happens on the background thread, "TypeError: Cannot read property 'length' of undefined" is generated instead of the actual ASan output.

Example program:
```
#include <iostream>
#include <thread>
int main() {
  std::thread([]() {
    int* p = new int(1);
    delete p;
    std::cout << *p;
  }).detach();
}
```
Build flags:
```
--std=c++11 -pthread -s INITIAL_MEMORY=67108864 -s PTHREAD_POOL_SIZE=2 -fsanitize=address
```
The full console output when running in the browser:
```
=================================================================
==42==ERROR: AddressSanitizer: heap-use-after-free on address 0x02e00f70 at pc 0x00004403 bp 0x031f4780 sp 0x031f478c
READ of size 4 at 0x02e00f70 thread T1
Pthread 0x3203ec0 exited.
worker.js onmessage() captured an uncaught exception: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at WasmOffsetConverter.getIndex (a.out.js:1427)
    at WasmOffsetConverter.getName (a.out.js:1445)
    at _emscripten_pc_get_function (a.out.js:5136)
    at a.out.wasm:wasm-function[2305]:0x4aa65
    at a.out.wasm:wasm-function[2300]:0x4a79c
    at a.out.wasm:wasm-function[2523]:0x53863
    at a.out.wasm:wasm-function[2112]:0x41123
    at a.out.wasm:wasm-function[2212]:0x456b7
    at a.out.wasm:wasm-function[2210]:0x45450
    at a.out.wasm:wasm-function[2224]:0x46379
```
Emscripten version: ToT (since ASan+pthreads is broken in older releases - see #13183).

### PR DESCRIPTION
**Pull request by kripken**
If ASan wants to show a stack trace on a pthread (like the trace to get to
an allocation that was later used after free), then it needs access to the
WasmOffsetConverter. We had a race there, where it could postMessage
the WasmOffsetConverter before that object was actually filled with the
data it needs (function offsets). See details in comments.

Fixes #13205

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Nice 👍

File: tests/pthread/test_pthread_asan_use_after_free_2.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+      var passed = [
+        'ERROR: AddressSanitizer: heap-use-after-free on address',
+        'READ of size 4',
+        'is located 0 bytes inside of 4-byte region',
+        'freed by thread T1 here:',
+        'previously allocated by thread T1 here:',
+        'Thread T1 created by T0 here:',
+        'SUMMARY: AddressSanitizer: heap-use-after-free',
+        'Shadow bytes around the buggy address:',
+        'Shadow byte legend (one shadow byte represents 8 application bytes):',
```
Comment (sbc100) [inline tests/pthread/test_pthread_asan_use_after_free_2.js:15]: When these tests fail its really hard to know why.. I wonder if we can pipe the stderr back to the server and use the same output comparison methods we use in non-browser tests?

Do you know how common this pattern is in browser tests?  Is it just the sanitizer tests?

Comment (kripken) [reply tests/pthread/test_pthread_asan_use_after_free_2.js:15]: I think I've only seen this pattern in the sanitizer tests. Yeah, I agree it's a little inconvenient, +1 for looking into possible improvements.
