### PR TITLE
Fix umask being ignored on file creation

### LINKED ISSUE #26707: umask seems to be ignored on file creation
**Version of emscripten/emsdk:**

```
5.0.6
```

A process-wide `umask(0077)` seems to be ignored by `open(..., O_CREAT, 0666)` and `mkdir()`. The created file keeps the raw mode instead of `mode & ~umask`.

**Failing command line in full:**

```
$ emcc -O0 -Wall umask.c -o a.out.js
$ node a.out.js
mode: 666 (expect 600)
```

The same program on native Linux prints `mode: 600 (expect 600)`.

**Example code snippet:**
```c
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <stdio.h>

int main(void) {
    mkdir("/tmp/xsv_test", 0755);
    umask(0077);
    int fd = open("/tmp/xsv_test/f.txt", O_WRONLY | O_CREAT | O_TRUNC, 0666);
    write(fd, "x", 1);
    close(fd);

    struct stat st;
    stat("/tmp/xsv_test/f.txt", &st);
    printf("mode: %o (expect 600)\n", st.st_mode & 0777);
    return ((st.st_mode & 0777) == 0600) ? 0 : 1;
}
```

### PR DESCRIPTION
**Pull request by sbc100**
A process-wide umask was being ignored by both the default JavaScript filesystem and the new C++ WasmFS when creating files and directories.

For the default filesystem:
- Moved __syscall_umask implementation from C to JavaScript in libsyscall.js.
- Stored the umask state in $SYSCALLS.currentUmask.
- Applied the umask in __syscall_openat, __syscall_mkdirat, and __syscall_mknodat.
- This makes umask thread-local (per JS instance), consistent with how cwd is handled.

For WasmFS:
- Added umask state and accessors to the WasmFS class in wasmfs.h.
- Implemented __syscall_umask in syscalls.cpp as an extern "C" function to satisfy Musl's umask.c.
- Applied the umask in doOpen and doMkdir in syscalls.cpp.

Fixes: #26707

### CODE REVIEW

File: system/lib/wasmfs/wasmfs.h [hunk 1]
```diff
@@ -53,6 +54,16 @@ class WasmFS {
...
 
+  mode_t getUmask() {
+    const std::lock_guard<std::mutex> lock(mutex);
+    return umask;
+  }
+
+  void setUmask(mode_t mask) {
+    const std::lock_guard<std::mutex> lock(mutex);
+    umask = mask;
+  }
```
Comment (kripken) [inline system/lib/wasmfs/wasmfs.h:63]: Why do we need to lock for this - could we use atomics intead?

Comment (kripken) [reply system/lib/wasmfs/wasmfs.h:63]: (and even atomics are only needed for tearing, correct? or is there another concern?)

Comment (sbc100) [reply system/lib/wasmfs/wasmfs.h:63]: Sure, its not strictly needed I guess

File: test/fs/test_trackingdelegate.out [hunk 2]
```diff
@@ -47,5 +47,5 @@ Opened "/renamed.txt" with flags O_APPEND O_RDONLY and file size 0
 Closed /renamed.txt
 About to delete "/renamed.txt"
 Deleted "/renamed.txt"
-Created directory "/home/test" with mode 16893
+Created directory "/home/test" with mode 16877
```
Comment (sbc100) [inline test/fs/test_trackingdelegate.out]: - Previous behavior: umask was ignored, resulting in 0775 (16893).
   - Current behavior: umask is respected, resulting in 0755 (16877).

**Review by kripken — APPROVED** [review]

**Comment by hoodmane** [comment]
I wonder if this fixes some Python tests that are currently xfailed.

**Comment by hoodmane** [comment]
There are currently three Python tests that are xfailed because "Emscripten's umask is a stub". There's also several others that probably should be xfailed but pass due to the test environment coincidentally having a specific umask.
