### PR TITLE
Round down any canvas-relative mouse event coordinates (fixes SAFE_HEAP asserts)

### LINKED ISSUE #20992: Mouse events crash when SAFE_HEAP is enabled
I just upgraded emsdk and started getting a new crash.

**Version of emscripten/emsdk:**

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)
clang version 18.0.0git (https://github.com/llvm/llvm-project f2464ca317bfeeedddb7cbdea3c2c8ec487890bb)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/mtuser/minetest-wasm/emsdk/upstream/bin

**Here's an example of the stack trace I got:**

Uncaught RuntimeError: Aborted(Assertion failed: attempt to write non-integer (undefined) into integer heap)
    at abort (minetest.js:613:40)
    at assert (minetest.js:375:3)
    at checkInt (minetest.js:887:2)
    at checkInt32 (minetest.js:898:27)
    at setValue_safe (minetest.js:2238:3)
    at SAFE_HEAP_STORE (minetest.js:322:2)
    at Object.uiEventHandlerFunc [as handlerFunc] (minetest.js:10551:3)
    at jsEventHandler (minetest.js:6507:17)

**Another example:**

Uncaught RuntimeError: Aborted(Assertion failed: attempt to write non-integer (1364.4119319915771) into integer heap)
    at abort (minetest.js:613:40)
    at assert (minetest.js:375:3)
    at checkInt (minetest.js:887:2)
    at checkInt32 (minetest.js:898:27)
    at setValue_safe (minetest.js:2238:3)
    at SAFE_HEAP_STORE (minetest.js:322:2)
    at fillMouseEventData (minetest.js:10427:2)
    at Object.mouseEventHandlerFunc [as handlerFunc] (minetest.js:10436:3)
    at HTMLCanvasElement.jsEventHandler (minetest.js:6507:17)

**These are the lines triggering a crash:**

https://github.com/emscripten-core/emscripten/blob/25308a1446bee94c7c1c4dd099fc130f4d6492ca/src/library_html5.js#L479-L480

https://github.com/emscripten-core/emscripten/blob/25308a1446bee94c7c1c4dd099fc130f4d6492ca/src/library_html5.js#L487-L488

https://github.com/emscripten-core/emscripten/blob/25308a1446bee94c7c1c4dd099fc130f4d6492ca/src/library_html5.js#L708

https://github.com/emscripten-core/emscripten/blob/25308a1446bee94c7c1c4dd099fc130f4d6492ca/src/library_html5.js#L1947-L1948

This list may not be exhaustive. Applying Math.round to the values being set made the errors stop. (except for e.detail, which sometimes not a number(?), so needed to be ignored in those cases)

### PR DESCRIPTION
**Pull request by cwoffenden**
This fixes #20992 by explicitly truncating the canvas-relative mouse event coordinates (`canvasX`, `canvasY`, `targetX` and `targetY`).

When using a custom target when registering for mouse events (instead of the built-in targets, e.g.: `EMSCRIPTEN_EVENT_TARGET_DOCUMENT`) coordinates are calculated relative to that target's `getBoundingClientRect()`. The bounds are affected by the browser's zoom and other scaling factors, so may not always be in whole units (CSS pixels). A typical example when Safari with a 4k screen zoomed in being:

Safari's getBoundingClientRect() result

When building with `SAFE_HEAP` and assertions this will error with, for example:
```
Aborted(Assertion failed: attempt to write non-integer (301.73912811279297) into integer heap)
```

Without `SAFE_HEAP` these coordinates are being silently rounded down, all this does is explicitly round ahead of placing the coordinates on the heap. The documentation was also updated to note this.

### CODE REVIEW

File: site/source/docs/api_reference/html5.h.rst [hunk 1]
```diff
@@ -419,13 +419,13 @@ Struct
   .. c:member:: long targetX
      long targetY
 
-    These fields give the mouse coordinates mapped relative to the coordinate space of the target DOM element receiving the input events (Emscripten-specific extension).
+    These fields give the mouse coordinates mapped relative to the coordinate space of the target DOM element receiving the input events (Emscripten-specific extension; coordinates are rounded down to whole units).
```
Comment (sbc100) [inline site/source/docs/api_reference/html5.h.rst:422]: How about `down to the nearest integer`?

**Review by sbc100 — APPROVED** [review]

**Comment by brendandahl** [comment]
Why not change the struct to store a double to match the web idl definition for these values? I imagine coordinates could be off if we truncate in this case.

File: site/source/docs/api_reference/html5.h.rst (hunk 1 above)
Comment (cwoffenden) [reply site/source/docs/api_reference/html5.h.rst]: I wasn't sure of the best wording. It's CSS units without the screen scaling, and I was trying to be concise. I'll make a quick edit.

**Comment by cwoffenden** [comment]
> Why not change the struct to store a double to match the web idl definition for these values? I imagine coordinates could be off if we truncate in this case.

This PR doesn't change the existing behaviour, which was getting implicitly truncated when storing (only now it's explicit).

If the struct changed to double (or float) any calling code would probably break due to the numeric conversions.  One possibility would be to add extra double/float fields, but since all this does is keep the existing behaviour without the assertions, I think it better as an addition and not rolled into this fix.

**Comment by brendandahl** [comment]
> > Why not change the struct to store a double to match the web idl definition for these values? I imagine coordinates could be off if we truncate in this case.
> 
> We could, but that sounds like a breaking change for any user of the API, no?

Yeah, though the behavior of the API is kind of broken if we're truncating. The fractional part is probably pretty important when large scaling factors are used (think accessibility features). What's the usual practice here on breaking html5 emscripten APIs?

Hmm.. If I'm following [this bug](https://issues.chromium.org/issues/40174888) correctly, it appears chrome never returns a double. This may not really matter then.

**Comment by sbc100** [comment]
> > > Why not change the struct to store a double to match the web idl definition for these values? I imagine coordinates could be off if we truncate in this case.
> > 
> > 
> > We could, but that sounds like a breaking change for any user of the API, no?
> 
> Yeah, though the behavior of the API is kind of broken if we're truncating. The fractional part is probably pretty important when large scaling factors are used (think accessibility features). What's the usual practice here on breaking html5 emscripten APIs?

I think if we wanted to change this we could add new fields the struct and mark the old ones as deprecated.

Then we could remove the old ones in strict mode somehow perhaps?

> 
> Hmm.. If I'm following [this bug](https://issues.chromium.org/issues/40174888) correctly, it appears chrome never returns a double. This may not really matter then.

**Comment by sbc100** [comment]
@brendandahl ok if we land this as is then?

**Comment by brendandahl** [comment]
Yeah.
