### PR TITLE
Fix API calls to WebGL where an optional size parameter is zero bytes

### LINKED ISSUE #16799: glBufferSubData overflows when size == 0
The optimization for WebGL2 is incorrect in the case of size == 0, because WebGL2 interprets size 0 as "the entire array buffer from the offset until the end".

https://github.com/emscripten-core/emscripten/blob/ec0d9c7d352d0fb694c3493f21d8ba8279e57589/src/library_webgl.js#L1803A

Original commit that added this line:
https://github.com/emscripten-core/emscripten/commit/38b559ca862264ff939bd297d6211ec47cd0b245

Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/mtuser/emsdk/upstream/bin

### PR DESCRIPTION
**Pull request by juj**
Fix API calls to WebGL where an optional size parameter is zero bytes, which would upload the whole WebAssembly heap since WebGL has a different semantics when zero size is passed. Fixes #16799.

### CODE REVIEW

**Comment by juj** [comment]
We don't have tests for this, so recommend a careful review.

**Review by kainino0x — APPROVED** [review]
Nice catch, and good example of sentinel 0 values being a footgun. Glad we removed them in WebGPU.

File: src/library_webgl.js [hunk 1]
```diff
@@ -2365,12 +2368,12 @@ var LibraryGL = {
 #if GL_ASSERTIONS
     assert(GL.currentContext.version >= 2);
 #endif
-    GLctx.uniform1iv(webglGetUniformLocation(location), HEAP32, value>>2, count);
+    count && GLctx.uniform1iv(webglGetUniformLocation(location), HEAP32, value>>2, count);
```
Comment (sbc100) [inline src/library_webgl.js:2371]: Is this just another way of writing `if (count) ...`. but saving two bytes?

Seems a little odd to do the micro-optimization here but not globally across the codebase.

**Comment by sbc100** [comment]
It seems odd that we don't have tests for any of this .. are they hard to write?

File: src/library_webgl.js (hunk 1 above)
Comment (juj) [reply src/library_webgl.js:2371]: > Is this just another way of writing if (count) .... but saving two bytes?

That's right.

> Seems a little odd to do the micro-optimization here but not globally across the codebase.

Maybe. It is used consistently in WebGL library, and that is probably more on the hot code size path that some of the other libraries.

Comment (sbc100) [reply src/library_webgl.js:2371]: Ah, ok. I didn't realize there was precedent for this.

Comment (kripken) [reply src/library_webgl.js:2371]: I think closure does this? If not, it would be easy to add a js optimizer pass. I think depending on the optimizer for this kind of thing is probably best (keeps code more readable and the optimization applies to more places).

**Comment by juj** [comment]
> It seems odd that we don't have tests for any of this .. are they hard to write?

There are 26 API entry points that are affected, which is a lot of tests to write. Writing tests that check that the whole Wasm heap is not being serialized probably would require some kind of mocking/polyfilling on the ArrayBuffer.
