### PR TITLE
Don't attempt to truncate newly created files during `open`

### LINKED ISSUE #16784: MEMFS `open` applies mode settings to current call
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line in full:**
```c
// test.c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
	char *target_file = "test.out";
	int target_fd;

	remove(target_file);

	// This next call fails, but only in emscripten
	target_fd = openat(AT_FDCWD, target_file, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 33060);

	if (target_fd < 0)
	{
		printf("Couldn't open target, errno %d. Is EACCES: %d\n", errno, errno == EACCES);
		exit(EXIT_FAILURE);
	}

	int status = write(target_fd, "blablabla", 9);
	if (status != 9)
	{
		printf("Couldn't write\n");
		exit(EXIT_FAILURE);
	}

	printf("File written successfully.\n");

	close(target_fd);

	return 0;
}
```
The preceding code runs fine and writes to the file when compiled and run on x86_64 Linux with `gcc test.c -Wall -Wextra && ./a.out`.
But `emcc test.c -Wall -Wextra && node a.out.js` fails with an `EACCES` on the indicated line.

This happens because the mode specified in the last argument to `open` is supposed to only apply to future accesses to the file: 

```
Note that mode applies only to future accesses of the
newly created file; the open() call that creates a read-
only file may well return a read/write file descriptor.
- https://man7.org/linux/man-pages/man2/open.2.html
```

But Emscripten doesn't respect this behavior.

**Full link command and output with `-v` appended:**
```
 "/home/user_folder/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=8 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home/user_folder/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -v -Wall -Wextra test.c -c -o /tmp/emscripten_temp_ys6f0yzy/test_0.o
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/user_folder/emsdk/upstream/bin
 (in-process)
 "/home/user_folder/emsdk/upstream/bin/clang-15" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/user_folder/scratch -resource-dir /home/user_folder/emsdk/upstream/lib/clang/15.0.0 -D EMSCRIPTEN -D __EMSCRIPTEN_major__=3 -D __EMSCRIPTEN_minor__=1 -D __EMSCRIPTEN_tiny__=8 -isysroot /home/user_folder/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/user_folder/emsdk/upstream/lib/clang/15.0.0/include -internal-isystem /home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include -Werror=implicit-function-declaration -Wall -Wextra -fdebug-compilation-dir=/home/user_folder/scratch -ferror-limit 19 -fvisibility default -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics -iwithsysroot/include/SDL -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_ys6f0yzy/test_0.o -x c test.c
clang -cc1 version 15.0.0 based upon LLVM 15.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include/SDL
 /home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/user_folder/emsdk/upstream/lib/clang/15.0.0/include
 /home/user_folder/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/home/user_folder/emsdk/upstream/bin/wasm-ld" -o a.out.wasm /tmp/emscripten_temp_ys6f0yzy/test_0.o -L/home/user_folder/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/home/user_folder/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 a.out.wasm -o a.out.wasm --detect-features
 "/home/user_folder/emsdk/node/14.18.2_64bit/bin/node" /home/user_folder/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpq0h_d57w.json
 "/home/user_folder/emsdk/upstream/bin/llvm-objcopy" a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers
```

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Fixes #16784

### CODE REVIEW

**Comment by sbc100** [comment]
I guess this should be better titled: ``Don't attempt to truncate newly created files during `open` ``? 

Does it fix the bug in case that the file already exists?    lgtm either way since this certainly makes things better.

**Comment by Jules-Bertholet** [comment]
Yes, I suppose the title is misleading. There is no bug when the file already exists, because in that case the `mode` argument is ignored and the permissions of the pre-existing file are used.

**Comment by sbc100** [comment]
Also could you add to one of the existing tests?  Maybe `tests/files.cpp`?  I don't see any existing testing for O_TRUNC :(

**Comment by Jules-Bertholet** [comment]
@sbc100 test added

File: tests/files.cpp [hunk 1]
```diff
@@ -142,6 +146,16 @@ int main()
   FILE *n = fopen("/dev/null", "w");
   printf("5 bytes to dev/null: %zu\n", fwrite(data, 1, 5, n));
   fclose(n);
+  
+  // Test file creation (regression test for #16784)
```
Comment (sbc100) [inline tests/files.cpp:150]: How about `// Test file creation with O_TRUNC`

File: tests/files.cpp [hunk 2]
```diff
@@ -142,6 +146,16 @@ int main()
...
+  const char *target_file = "test.out";
+  int target_fd;
+  remove(target_file);
+  target_fd = openat(AT_FDCWD, target_file, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 33060);
```
Comment (sbc100) [inline tests/files.cpp:154]: I think you can just do `open(target_file` to keep to simple.   Also, I think can you drop the `O_CLOEXEC` and the mode without effecting the test.   

Also since this test is running against an ephemeral MEMFS you can drop the `remove` and just do `open("test.out"...`

Comment (Jules-Bertholet) [reply tests/files.cpp:154]: Omitting the mode when using `open` to create a new file is UB:

```
The mode argument must be supplied if O_CREAT or O_TMPFILE is
specified in flags; if it is not supplied, some arbitrary
bytes from the stack will be applied as the file mode.
- https://man7.org/linux/man-pages/man2/open.2.html
```

Comment (sbc100) [reply tests/files.cpp:154]: OK, can use the S_ macros (e.g. S_IRUSR) rather than a hardcoded constant then?

File: tests/files.cpp [hunk 3]
```diff
@@ -142,6 +146,15 @@ int main()
   FILE *n = fopen("/dev/null", "w");
   printf("5 bytes to dev/null: %zu\n", fwrite(data, 1, 5, n));
   fclose(n);
+  
+  // Test file creation with O_TRUNC (regression test for #16784)
+  const char *target_file = "test.out";
+  int target_fd;
+  target_fd = open(target_file, O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR);
```
Comment (sbc100) [inline tests/files.cpp:153]: Just one line should be fine here:

`int target_fd = open("test.out", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR);`

Otherwise looks good.

Comment (sbc100) [reply tests/files.cpp:153]: In fact maybe just call this `fd`.. I'm not sure `target_fd` has a meaning does it?
