### PR TITLE
Fixes #16913: Don't use fetch() in Node.js environment

### LINKED ISSUE #16913: Node.js implemented `WebAssembly.instantiateStreaming` in v18.1.0
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
```
$ emcc -s ENVIRONMENT=node hello_world.c
$ node a.out.js 
(node:50298) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
…/a.out.js:146
      throw ex;
      ^

TypeError: Failed to parse URL from …/a.out.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at Object.<anonymous> (…/a.out.js:1914:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at instantiateAsync (…/a.out.js:1670:14)
      at createWasm (…/a.out.js:1707:3)
      at Object.<anonymous> (…/a.out.js:1914:11) {
    input: '…/a.out.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.1.0
```

Note that disabling `fetch` does the trick:

```console
$ node --no-experimental-fetch a.out.js 
hello, world!
```

Ideally `instantiateStreaming` should be called only on HTTP URIs.

### PR DESCRIPTION
**Pull request by simnalamburt**
Node.js v18.1.0 has implemented `WebAssembly.instantiateStreaming` API, and it broked all emscriptened js codes since emscripten is using `WebAssembly.instantiateStreaming` as a criterion to distinguish whether it is Node.js environment or a browser environment.

The issue will be fixed if we use `ENVIRONMENT_IS_NODE` as a proper criterion to distinguish Node.js environment.

Fixes #16913, https://github.com/antelle/argon2-browser/issues/81.

###### References
- https://github.com/nodejs/node/pull/42701
- https://github.com/antelle/argon2-browser/issues/81
- https://github.com/simnalamburt/argon2-browser-error-repro
- https://github.com/emscripten-core/emscripten/issues/16913

### CODE REVIEW

**Comment by kripken** [comment]
Interesting, thanks for filing...

I'd hope we can actually use `instantiateStreaming` if node implemented it, but looks like in #16913 that the blocker is that node's `fetch` does not work yet. Sounds good to avoid that path for now.

File: src/preamble.js [hunk 1]
```diff
@@ -1216,6 +1216,7 @@ function createWasm() {
         // Don't use streaming for file:// delivered objects in a webview, fetch them synchronously.
         !isFileURI(wasmBinaryFile) &&
 #endif
+        !ENVIRONMENT_IS_NODE &&
```
Comment (kripken) [inline src/preamble.js:1219]:
```suggestion
 #if ENVIRONMENT_MAY_BE_NODE
        !ENVIRONMENT_IS_NODE &&
#endif
```
(this avoids extra code in non-node builds)

**Review by kripken — COMMENTED** [review]
Also please add a comment, as we'd like to remove this workaround some day. Perhaps something like this:
```
// Avoid instantiateStreaming() on node for now, as while newer node implements it,
// it does not have a full fetch() implementation yet.
// [..link to emscripten and/or node bug..]
```

**Comment by simnalamburt** [comment]
Done!

**Comment by juj** [comment]
What will be the path towards removing this check?

It looks like there is no way to feature test what the bad Node.js versions are/will be?

Does node.js have some kind of synchronous version test that could be used, e.g. "if node.js version >= x.y.z.w (regression first introduced) and node.js version < X.Y.Z.W (bugfix first appeared in), then disable streaming instantiation"?

If not, it will be really hard to evolve out of this check since users of older Node.js versions might break again if this check was ever removed (after latest Node.js fixes things up)?

**Comment by simnalamburt** [comment]
We have several options.

1. In my opinion, there's no big point with using `WebAssembly.instantiateStreaming` in Node.js environment, so we might keep this forever.
2. We can remove this check and wrap `fetch()` call with `try { ... } catch()` clause. This will add small overhead to old Node.js codes.
3. We can check `process.version` only in `ENVIRONMENT_IS_NODE`.
4. etc?

**Comment by juj** [comment]
> Does node.js have some kind of synchronous version test that could be used, e.g. "if node.js version >= x.y.z.w (regression first introduced) and node.js version < X.Y.Z.W (bugfix first appeared in), then disable streaming instantiation"?

E.g. something like

```js
if (!ENVIRONMENT_IS_NODE || (
    versionGreaterOrEqualTo(process.versions.node, [18,1,0]) &&
    versionLessThan(process.versions.node, [999,999,999]
    /* TODO: When Node.js lands a fix, update version range to match accordingly*/)))
   /* enable streaming instantiation */
else
   /* disable streaming instantiation */
```

**Comment by simnalamburt** [comment]
There is no built-in function to compare versions in Node.js, so we have to modify the code a bit much to get the behavior you want. Since applying this patch does not cause problems in future Node.js versions, why don't we discuss the issue of removing this patch again in another PR or another issue?

**Review by kripken — APPROVED** [review]
Makes sense to me to land this, and consider improvements later.

**Comment by RReverser** [comment]
> I'd hope we can actually use `instantiateStreaming` if node implemented it

FWIW, out of curiosity, I tried to use streaming compilation with manual conversion from Node.js file streams, and it does work, but is ~2x slower than the buffer-based variant: https://twitter.com/RReverser/status/1593330290491068416

It's said to be due to the current implementation of Web streams in Node being experimental and not optimised yet, so it might change in the future, but, at least, for now there is no advantage in using streaming compilation.

**Comment by simnalamburt** [comment]
Thanks for the research @RReverser! Looks like we'd be better to sustain this patch for a long time in that case.
