### PR TITLE
[EH] Make Wasm EH rethrow print stack traces

### LINKED ISSUE #20301: [EH] rethrowing current exception from catch lead to loss of callstack
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/emsdk/upstream/bin
```

**test.cpp**
```cpp
#include <emscripten.h>
#include <exception>

void fun2() {
    throw "error";
}

void  EMSCRIPTEN_KEEPALIVE fun1() {
    try {
        fun2();
    } catch(...) {
        auto e = std::current_exception();
        std::rethrow_exception(e);
    }
}
```

Above program is built with `-sEXCEPTION_STACK_TRACES=1`. `fun1` is exported on `Module` & is called from js side as below:

**test.js**
```js
 try {
    console.log(Module._fun1());
  } catch (e) {
    console.log(e.stack);
  }
```

Ideally, full callstack including both `fun2` & `fun1` should get printed. However, in Wasm EH no callstack is obtained while in Emscripten EH below callstack is obtained:
```
char const*
    at ___resumeException (http://localhost:8000/build/test.js:1043:25)
    at fun1 (http://localhost:8000/build/test.wasm:wasm-function[25]:0xb4d)
    at Module._fun1 (http://localhost:8000/build/test.js:1273:69)
```

Both of these scenarios are wrong and should print the actual callStack.

### PR DESCRIPTION
**Pull request by aheejin**
In Wasm EH, even if we set `-sASSERTION` or `-sEXCEPTION_STACK_TRACES`, if we rethrow an exception in the code, we lose the effect of that option because previously we called `__throw_exception_with_stack_trace` only in `__cxa_throw`:
https://github.com/emscripten-core/emscripten/blob/9ce7020632aa6f7578c6e40e197b800a4dd7073f/system/lib/libcxxabi/src/cxa_exception.cpp#L294-L296

This adds the same mechanism to `__cxa_rethrow` (which is used for C++ `throw;`) and `__cxa_rethrow_primary_exception` (which is used for `std::rethrow_exception`).

This does not solve the problem of losing stack traces _before_ the rethrowing. libc++abi's `__cxa_rethrow` and
`__cxa_rethrow_primary_exception` are implemented as throwing a pointer in the same way we first throw it and they are not aware of any metadata. This happens even in the native platform with GDB; GDB's backtrace only shows stack traces after rethrowing. We may try to fix this later by passing `exnref`
(https://github.com/WebAssembly/exception-handling/issues/281) to the library, but this is likely to take some time.

Partially fixes #20301.

### CODE REVIEW

File: system/lib/libcxxabi/src/cxa_exception.cpp [hunk 1]
```diff
@@ -644,6 +644,14 @@ void __cxa_rethrow() {
     }
 #ifdef __USING_SJLJ_EXCEPTIONS__
     _Unwind_SjLj_RaiseException(&exception_header->unwindHeader);
+#elif __USING_WASM_EXCEPTIONS__
```
Comment (sbc100) [inline system/lib/libcxxabi/src/cxa_exception.cpp:647]: How about making this `#elif defined(__USING_WASM_EXCEPTIONS__) && !defined(NDEBUG)` to avoid inner if/else/endif?

File: system/lib/libcxxabi/src/cxa_exception.cpp [hunk 2]
```diff
@@ -769,6 +777,14 @@ __cxa_rethrow_primary_exception(void* thrown_object)
         dep_exception_header->unwindHeader.exception_cleanup = dependent_exception_cleanup;
 #ifdef __USING_SJLJ_EXCEPTIONS__
         _Unwind_SjLj_RaiseException(&dep_exception_header->unwindHeader);
+#elif __USING_WASM_EXCEPTIONS__
+#ifdef NDEBUG
+    _Unwind_RaiseException(&exception_header->unwindHeader);
+#else
+    // In debug mode, call a JS library function to use WebAssembly.Exception JS
+    // API, which enables us to include stack traces
+    __throw_exception_with_stack_trace(&exception_header->unwindHeader);
```
Comment (sbc100) [inline system/lib/libcxxabi/src/cxa_exception.cpp:786]: The indentation looks wrong here compared to the other if/else arms.

File: system/lib/libcxxabi/src/cxa_exception.cpp [hunk 3]
```diff
@@ -644,6 +644,14 @@ void __cxa_rethrow() {
     }
 #ifdef __USING_SJLJ_EXCEPTIONS__
     _Unwind_SjLj_RaiseException(&exception_header->unwindHeader);
+#elif __USING_WASM_EXCEPTIONS__
+#ifdef NDEBUG
+    _Unwind_RaiseException(&exception_header->unwindHeader);
+#else
+    // In debug mode, call a JS library function to use WebAssembly.Exception JS
+    // API, which enables us to include stack traces
+    __throw_exception_with_stack_trace(&exception_header->unwindHeader);
```
Comment (sbc100) [inline system/lib/libcxxabi/src/cxa_exception.cpp:653]: This makes me wonder why `_Unwind_RaiseException` itself doesn't call `__throw_exception_with_stack_trace` under the hood?   I'm sure there is a good reason..

File: test/test_other.py [hunk 4]
```diff
@@ -8593,6 +8593,64 @@ def test_exceptions_stack_trace_and_message(self, wasm_eh):
     for check in stack_trace_checks:
       self.assertFalse(re.search(check, err), 'Expected regex "%s" to not match on:\n%s' % (check, err))
 
+    # Rethrowing exception currently loses the stack trace before the
```
Comment (sbc100) [inline test/test_other.py:8596]: Can this be a separate test?  The existing test is already really long..

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 1 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception.cpp:647]: How? We have
```cpp 
#else
    _Unwind_RaiseException(&exception_header->unwindHeader);
#endif
```
at the end so I'm not sure how to rewrite this without an inner `if`...

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 3 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception.cpp:653]: I have a reason, even though how good that reason is... In native platforms libunwind is mostly used for very low level stack unwinding stuff, so I wanted to limit libunwind to low-level stuff as well, such as throwing exceptions using builtins. Interacting with JS seemed a too high level functionality for libunwind.

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 2 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception.cpp:786]: Fixed.

File: test/test_other.py (hunk 4 above)
Comment (aheejin) [reply test/test_other.py:8596]: Done

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 1 above)
Comment (sbc100) [reply system/lib/libcxxabi/src/cxa_exception.cpp:647]: I was thinking you could write this to avoid the duplication of the ` _Unwind_RaiseException(&exception_header->unwindHeader);` block?  And instead rely on the fall though to that `else` case?

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 3 above)
Comment (sbc100) [reply system/lib/libcxxabi/src/cxa_exception.cpp:653]: I guess it depends if we think there would be other callers of ` _Unwind_RaiseException` that don't want `__throw_exception_with_stack_trace` ?

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 1 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception.cpp:647]: Aha, sorry, I was confused and thought `NDEBUG` as the opposite... Simplified it, and also fixed the existing `__cxa_throw` part, which I copied this code from.

File: system/lib/libcxxabi/src/cxa_exception.cpp (hunk 3 above)
Comment (aheejin) [reply system/lib/libcxxabi/src/cxa_exception.cpp:646]: libunwind can be used by non-Emscripten toolchains, so there are others that don't want to call it. But that's gonna be the same for libc++abi... Maybe we should guard this part as not only `__USING_WASM_EXCEPTIONS__` but also `__EMSCRIPTEN__`? Currently I haven't upstreamed any JS-related parts, including this, to upstream LLVM, so others will not be affected though.

Comment (sbc100) [reply system/lib/libcxxabi/src/cxa_exception.cpp:646]: Yes I think it makes sense to wrap this in `__EMSCRIPTEN__`.    We can consider folding this into `_Unwind_RaiseException` itself, either as part of this PR, or as a followup.

Comment (sbc100) [reply system/lib/libcxxabi/src/cxa_exception.cpp:646]: Also, I don't see any harm in (eventually) upstreaming even the emscripten parts, assuming they are wrapped in `#ifdef __EMSCRIPTEN__`

File: test/test_other.py [hunk 5]
```diff
@@ -8593,6 +8593,80 @@ def test_exceptions_stack_trace_and_message(self, wasm_eh):
...
+    if wasm_eh:
+      # FIXME Node v18.13 (LTS as of Jan 2023) has not yet implemented the new
+      # optional 'traceStack' option in WebAssembly.Exception constructor
+      # (https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Exception/Exception)
+      # and embeds stack traces unconditionally. Change this back to
+      # self.require_wasm_eh() if this issue is fixed later.
+      self.require_v8()
+      emcc_args += ['-fwasm-exceptions']
+    else:
+      emcc_args += ['-fexceptions']
```
Comment (sbc100) [inline test/test_other.py:8611]: You can `self.emcc_args` here and avoid passing this as `emcc_args` to the `self.do_run` calls below.

**Review by sbc100 — APPROVED** [review]

File: test/test_other.py (hunk 5 above)
Comment (aheejin) [reply test/test_other.py:8611]: Ah, thanks. Fixed the same pattern in the original `test_exceptions_stack_trace_and_message` as well.

**Review by sbc100 — APPROVED** [review]
