### PR TITLE
Fix #11005: escape path to Python executable in entry points

### LINKED ISSUE #11005: Syntax errors in em++ when Python is installed in a directory with spaces
Environment: Windows 7, using msys2 Bash, `which python` yields `/c/Program Files (x86)/Python38-32/python`. If I run `em++` in cmd, everything works, but it fails when ran from msys bash:

```
$ em++ a.cpp
/f/Soft/emsdk/upstream/emscripten/em++: line 16: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 20: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 24: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 29: /c/Program: No such file or directory
```

I suspect it broke in #10729 (released in 1.39.12): `tools/run_python.sh` lacks proper quoting of the `$PYTHON` variable.

### PR DESCRIPTION
**Pull request by yeputons**
This fixes #11005 for me

### CODE REVIEW

File: tools/run_python.sh [hunk 1]
```diff
@@ -9,21 +9,21 @@
 # To modify this file, edit `tools/run_python.py` and then run
```
Comment (sbc100) [inline tools/run_python.sh:9]: You would mind correcting the typo here while are you at it:  it should be `.sh`, not `.py` on this line.

Comment (yeputons) [reply tools/run_python.sh]: Done.

**Comment by yeputons** [comment]
I've also added an entry to `ChangeLog.md`.
