### PR TITLE
[WasmFS] Refactor the backend Directory API

### LINKED ISSUE #16630: [WasmFS] Caching directory structure
WasmFS currently does not cache directory children with the expectation that future caching backends will optionally handle that caching as a configurable layer not built into the core system. The lack of cached directory children causes two problems, however:

1. Backend files do not correspond 1:1 with `File` objects. For example, every time `getChild` is called on a directory in the Node backend, it has to allocate a new `DataFile`, `Directory`, or `Symlink` to return, since the system has no record of any previously returned child. With multiple `File` objects pointing to the same underlying file, it is easy to get into a situation where the file metadata is incorrect or inconsistent between different references to what should be the same file. Most importantly, the cached parent pointers can get out of sync when a file is moved or unlinked and one of its corresponding `File` objects is updated accordingly but the others are not. That could lead to the backend receiving read and write requests on files it had thought had already been closed and deleted. It is also the reason that the Node backend cannot currently pass the full `other.test_unlink` test.

2. It is not possible to mount backends together arbitrarily as it is in Unix file systems. Right now we only support mounting backends under the in-memory backend, which explicitly owns `File` objects and keeps them alive for the lifetime of the files. The mount points for other backends are just more `File` objects that the in-memory backend treats the same as any other files. In contrast, mounting a backend under e.g. the Node backend would require actually storing some kind of handle to the other backend in the Node file system. If the mounted backend is an in-memory backend, then this materialized mount handle would outlive the backend it points to when the application is shut down. This all gets so complex that we have given up on supporting arbitrary backend mounting for now.

The Linux virtual file system layer does not have these problems because it caches directory structure in nodes called "dcache entries" or "dentries" ([docs](https://github.com/torvalds/linux/blob/master/Documentation/filesystems/vfs.rst)). These are in-memory cached handles to the underlying inodes and are used for path traversal. They are roughly equivalent to our `File` objects. Although dentries do not necessarily correspond 1:1 with inodes in Linux, the exceptions seem to be for hard links, which we do not support. Mounting a file system in Linux involves returning the dentry for the root of the mounted system and inserting it as a special entry in the parent dentry; the mounting does not actually write anything back to the inode of the parent dentry AFAICT.

To fix these problems, I plan to add a mapping from name to `(isMount: bool, std::shared_ptr<File>)` to `Directory`. This will also pave the path toward letting us allow users to set their own backends as the root backend (since we will be able to mount /proc under their arbitrary backends). The downside will be that fewer external modifications to files in node backends will be picked up automatically, but it was already the case that WasmFS would not always synchronize with such external modifications.

### PR DESCRIPTION
**Pull request by tlively**
Previously new entries were inserted into the file system by calling
`Backend::createDirectory` or `Backend::createFile`, etc. then passing the
result to `Directory::insertChild`. This was suboptimal because it forced `File`
objects to be created with no context and separately from the creation of the
underlying files. Backends would have to create some reasonable default `File`
and then later overwrite its state in the implementation of `insertChild`.

To avoid this spooky action at a distance, simplify the control flow, and reduce
statefulness in the API, replace `insertChild` with separate `insertDataFile`,
`insertDirectory`, and `insertSymlink` methods that both create the underlying
files and allocate and return the corresponding `File` objects.

But removing `insertChild` from the backend API makes it no longer possible for
a backend to contain a reference to a file on a different backend, a capability
we need at least for the root in-memory backend. To fix this (and also to
improve performance and also to fix an entire class of bugs stemming from having
multiple `File` objects corresponding to the same underlying file), add a
directory entry cache inspired by the dcache in Linux's [virtual file
system](https://github.com/torvalds/linux/blob/master/Documentation/filesystems/vfs.rst).

This directory entry cache lives in the base `Directory` class and is
manipulated solely by the `Directory::Handle` layer sitting between the syscall
implementations and the backends. A new method, `Directory::Handle::mountChild`,
can insert `File` objects into this cache without inserting them into the
underlying backend, allowing directories to contain children in different
backends without backends having to worry about how to represent such children.

Finally, add another method, `Directory::insertMove`, that implements an atomic
rename to replace the combination of `removeChild` followed by `insertChild`
that was previously used to implement rename. Although the previous call
sequence worked fine for the in-memory backend, it would have been extremely
awkward to support in any persistent backend and was in general not capable of
gracefully handling rename errors without data loss.

After all these updates to the directory API, there was one additional fix
necessary to keep the tests passing. Now that there is a unique `File`
corresponding to each underlying file in the Node backend, multiple `open`s of a
file will share an underlying file descriptor. But if a file is originally
opened for reading only, for example, and later opened for writing, writes will
fail because the underlying Node file descriptor was only opened for reading.

One possible solution would have been to always have the Node backend open files
for both reading and writing, but that would introduce spurious failures when
the user only has permissions for one or the other on the underlying file.
Instead, detect when the permission on the current underlying file descriptor
are insufficient and dynamically try to increase permissions on demand.

Resolves #16630.

### CODE REVIEW

File: system/lib/wasmfs/file.cpp [hunk 1]
```diff
@@ -40,33 +40,180 @@ void DataFile::Handle::preloadFromJS(int index) {
...
+  auto& dcache = getDir()->dcache;
+  if (auto it = dcache.find(name); it != dcache.end()) {
+    return it->second.file;
+  }
+  // Otherwise check whether the backend knows about the child.
+  auto child = getDir()->getChild(name);
+  if (!child) {
+    return nullptr;
+  }
+  finishInsertingChild(name, child);
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:74]: This surprises me for similar reasons as in the previous PR: we call `getDir()->getChild()`, which seems like it should be a `const` method, but from this code it seems like it has a side effect and that side effect will start to insert a child, but not finish doing so. Is that right?

If so perhaps `getDir()->getChild()` could be `getOrAddChild` or such? But given that the `dcache` appears to be used in this method before that call, there is no chance the child already exists, so perhaps `getDir()->getChild()` is only called to actually create a new child? If so perhaps it could be `createChild`?

File: system/lib/wasmfs/file.h [hunk 2]
```diff
@@ -150,22 +152,43 @@ class Directory : public File {
   };
 
 private:
+  enum class DCacheKind { Normal, Mount };
+  struct DCacheEntry {
+    DCacheKind kind;
```
Comment (kripken) [inline system/lib/wasmfs/file.h:157]: Trying to figure out the meaning of `kind` from the usage, it looks like a mount is another backend, is that right? It would be good to have a comment explaining that and what it means.

**Review by kripken — COMMENTED** [review]
Some initial comments - still not sure I get the overall direction here.

File: system/lib/wasmfs/file.h [hunk 3]
```diff
@@ -266,33 +289,47 @@ class DataFile::Handle : public File::Handle {
...
-      return getParent();
-    }
-    return getDir()->getChild(name);
-  }
+  std::shared_ptr<File> getChild(const std::string& name);
+
+  // Add a child to this directory's entry cache without actually inserting it
+  // in the underlying backend. Assumes a child with this name does not already
+  // exist. Return `true` on success and `false` otherwise.
+  bool mountChild(const std::string& name, std::shared_ptr<File> file);
```
[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/file.h:305]: (I ask because the comment doesn't say anything about mounting or being a mount, just about not actually inserting it, which is not obviously connected to that - except that a mount has a different backend I guess?)

File: system/lib/wasmfs/file.cpp (hunk 1 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:74]: `Directory::getChild` never creates a new child file, but it will create a new child `File` if the underlying file already exists. That new `File` needs to have its metadata (e.g. parent pointer and presence in the dcache) updated before it can be returned to the caller of `Directory::Handle::getChild`.

Perhaps `finishInsertingChild` should instead be `finishInitializingChild` or `updateChildMetadata`?

File: system/lib/wasmfs/file.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/file.h:305]: "Mounting" a directory is synonymous with adding that directory to the dcache without affecting the underlying storage, just like on Linux/POSIX. So calling `mountChild` will result in a dcache entry with `DCacheKind::Mount`. I'll add a comment to the enum.

[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/file.h:309]: This is hopefully clarified by the new comment about the `dcache` that explains mounts.

File: system/lib/wasmfs/file.h [hunk 4]
```diff
@@ -150,22 +152,43 @@ class Directory : public File {
   };
 
 private:
+  enum class DCacheKind { Normal, Mount };
+  struct DCacheEntry {
+    DCacheKind kind;
+    std::shared_ptr<File> file;
+  };
+  // TODO: Use a cache data structure with smaller code size.
+  std::map<std::string, DCacheEntry> dcache;
```
[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/file.h:165]: Comment added, PTAL.

**Comment by tlively** [comment]
The remaining test failures seem to be due to the default implementations of `Backend::createDirectory` and `Backend::createSymlink`, which don't make sense for backends that don't keep data in memory. I'll fix those in a separate precursor PR.

File: system/lib/wasmfs/file.cpp (hunk 1 above)
Comment (kripken) [reply system/lib/wasmfs/file.cpp:74]: Could it be `insertChild`? I'm not sure what part of inserting it is handled beforehand, as it sounds it does everything. That is, what else is there aside from adding the pointer from the child to the parent (and in reverse) and also adding it to the dcache?

File: system/lib/wasmfs/file.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/file.h:165]: Much clearer now, thanks!

File: system/lib/wasmfs/file.h [hunk 5]
```diff
@@ -266,33 +293,47 @@ class DataFile::Handle : public File::Handle {
...
-    }
-    if (name == ".") {
-      return file;
-    }
-    if (name == "..") {
-      return getParent();
-    }
-    return getDir()->getChild(name);
-  }
+  std::shared_ptr<File> getChild(const std::string& name);
```
Comment (kripken) [inline system/lib/wasmfs/file.h:304]: Should we add a comment here saying this will return the child if it is in the dcache, and otherwise will defer to the backend, which may create a new File on the fly and in that case that file would be returned?

File: system/lib/wasmfs/file.cpp [hunk 6]
```diff
@@ -40,33 +40,180 @@ void DataFile::Handle::preloadFromJS(int index) {
...
 
+void Directory::Handle::finishInsertingChild(const std::string& name,
+                                             std::shared_ptr<File> child) {
+  // Update the dcache and set the child's parent.
+  auto& dcache = getDir()->dcache;
+  auto [_, inserted] = dcache.insert({name, {DCacheKind::Normal, child}});
+  assert(inserted && "inserted child already existed!");
+  assert(child->locked().getParent() == nullptr);
+  child->locked().setParent(getDir());
+}
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:51]: How about calling this `cacheChild` as it basically adds it to the dcache? Or `dcacheChild`?

We could have such a function take the DCacheKind as a parameter, and then `mountChild` and this function here would call that with different kinds, and we'd have a single place that adds to the dcache, which seems nice.

File: system/lib/wasmfs/file.cpp [hunk 7]
```diff
@@ -40,33 +40,180 @@ void DataFile::Handle::preloadFromJS(int index) {
...
+  }
+  if (name == "..") {
+    return getParent();
+  }
+  // Check whether the cache already contains this child.
+  auto& dcache = getDir()->dcache;
+  if (auto it = dcache.find(name); it != dcache.end()) {
+    return it->second.file;
+  }
+  // Otherwise check whether the backend knows about the child.
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:69]:
```suggestion
  // Otherwise check whether the backend knows about underlying contents here.
  // If so, it will create a new File for those contents, which we will then
  // insert into the cache and return from here.
```

File: system/lib/wasmfs/file.cpp [hunk 8]
```diff
@@ -40,33 +40,180 @@ void DataFile::Handle::preloadFromJS(int index) {
...
+  }
+  finishInsertingChild(name, child);
+  return child;
+}
+
+bool Directory::Handle::mountChild(const std::string& name,
+                                   std::shared_ptr<File> child) {
+  assert(child);
+  // Cannot insert into an unlinked directory.
+  if (!getParent()) {
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:82]: Doesn't the root have no parent?

File: system/lib/wasmfs/file.cpp [hunk 9]
```diff
@@ -40,33 +40,180 @@ void DataFile::Handle::preloadFromJS(int index) {
...
+}
+
+bool Directory::Handle::insertMove(const std::string& name,
+                                   std::shared_ptr<File> file) {
+  // Cannot insert into an unlinked directory.
+  if (!getParent()) {
+    return false;
+  }
+  // Look up the file in its old parent's cache.
+  auto& oldCache = file->locked().getParent()->dcache;
```
Comment (kripken) [inline system/lib/wasmfs/file.cpp:144]: This locks `file`, and we hold a lock onto this directory (since we are a handle to it), but don't we need to take a lock on the old parent directory (if it is not the same as this directory) before we modify its dcache?

**Review by kripken — COMMENTED** [review]
This is starting to make a lot of sense to me, nice!

File: system/lib/wasmfs/backends/memory_backend.cpp [hunk 10]
```diff
@@ -38,40 +38,12 @@ MemoryDirectory::findEntry(const std::string& name) {
...
-  auto entry =
-    std::find_if(entries.begin(), entries.end(), [&](const auto& entry) {
-      return entry.child == file;
-    });
   if (entry != entries.end()) {
-    return entry->name;
+    entries.erase(entry);
   }
-  return {};
+  return true;
```
[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: Yeah, originally I wanted `MemoryFile` to do nothing like you're thinking. Unfortunately the `getEntries()` method makes that difficult. Since it can't assume all the entries are already in the cache, it has to unconditionally query the backend for the directory entries, which means that the backend needs to know what the entries are. Unfortunately that means `MemoryDirectory` cannot completely abdicate responsibility for keeping track of the entries.

File: system/lib/wasmfs/backends/node_backend.cpp [hunk 11]
```diff
@@ -56,36 +56,74 @@ int _wasmfs_node_write(
...
+    openFlags = flags;
+    ++openCount;
+    return 0;
   }
+
   void close() {
     if (--openCount == 0) {
       _wasmfs_node_close(fd);
+      fd = -1;
+      openFlags = 0;
```
[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/node_backend.cpp:126]: Nice, makes sense to me!

File: system/lib/wasmfs/file.cpp (hunk 6 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:51]: That sounds good, too. `cacheChild` doesn't completely capture the fact that the parent pointer is also updated, but it still communicates the big picture.

File: system/lib/wasmfs/file.cpp (hunk 8 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:82]: No, I "fixed" that at some point and now the root is its own parent. That means we don't need to special case the root in situations like this.

Comment (tlively) [reply system/lib/wasmfs/file.cpp:82]: That change was part of #16409.

File: system/lib/wasmfs/file.cpp (hunk 9 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:144]: No, because we can depend on this only being called by `__syscall_renameat`, which already holds the locks on both directories. It's kind of a code smell to have a dependency like that, working around it would mean bigger changes.

In the future we might consider replacing `insertMove` with a `Backend::move` that does not privilege either the source or destination directories. We might then consider passing `Directory::Handle`s as the arguments to prove that the directories have both been locked.

**Comment by tlively** [comment]
@kripken I believe all the feedback has now been addressed.

File: system/lib/wasmfs/file.cpp (hunk 9 above)
Comment (kripken) [reply system/lib/wasmfs/file.cpp:144]: I see, makes sense. I think a comment and a TODO are enough for now here.

File: system/lib/wasmfs/backends/memory_backend.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: > Since it can't assume all the entries are already in the cache

Hmm, why can't it assume that for `MemoryBackend`?

My understanding was that the dcache is all there is in that backend - there are no extra things not tracked in the dcache. So `MemoryBackend::getEntries()` can return an empty set, etc.

[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: As a special case, it could assume that all entries are in the cache for MemoryBackend, but there is no way to cleanly implement that special case. In the general case across all backends it cannot assume all entries are in the cache because a persistent backend may have entries that have never been requested before.

File: system/lib/wasmfs/file.cpp (hunk 9 above)
Comment (tlively) [reply system/lib/wasmfs/file.cpp:144]: Sounds good. I added a TODO in one of the latest commits.

File: system/lib/wasmfs/backends/memory_backend.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: True, but can't we remove `std::vector<ChildEntry> entries;` from `MemoryDirectory` and then not implement anything? If the default behavior of insert/remove/etc. is to use the dcache, and if not in the dcache to look in the child, then the memory backend would simply do nothing in the latter hooks. And then the dcache would be all there is there.

[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: How would you implement `getEntries()` if you did that?

Here's the logic for arriving at the current implementation of `getEntries`, considering a general persistent backend:
1. We can't know that the cache already contains all the entries, so we have to call out to the backend in `getEntries()`.
2. The backend doesn't know what's in the cache, so it returns all the entries.
3. The backend can't have included the mount points, so we append them to the entries returned by the backend. We don't append any other cached entries because the backend would already have included them.

The standard contract of `Directory::getEntries()` is that the backend returns _all_ the entries. The in-memory backend has to do that as well; it doesn't get to be special.

[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: I agree `getEntries()` should return all the entries. I would imagine it could work like this: it makes a list of the dcache entries. It then appends to that list the results of a call to the backend's `getExtraEntries()` or something like that - where that function only adds "extra" things not in the dcache. In other words, `Directory::getEntries()` would not be virtual, and would call a backend hook that is. Does that make sense? I'm not opposed to calling out to the backend, I just expect to see the backend only add the backend-specific stuff, and so in particular MemoryBackend would have nothing to add.

[the remark this answers is not in the document]
Comment (tlively) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: Having something like `getExtraEntries()` would require every other backend to keep track of which entries are already in the dcache, which is not a good trade off. Another option would be to have `Directory::Handle::getEntries` create entries from the dcache then query all the results from the backend and deduplicate the results. I'm not a huge fan of that either because it's a bunch of extra work that is only useful for the in-memory backend.

[the remark this answers is not in the document]
Comment (kripken) [reply system/lib/wasmfs/backends/memory_backend.cpp:46]: Ah, I see what you mean, when something moved into the dcache it would need to be removed from the "non-dcache" list. That does sound like not the best thing.

File: system/lib/wasmfs/file.h [hunk 12]
```diff
@@ -150,22 +159,48 @@ class Directory : public File {
...
+  virtual std::shared_ptr<Directory> insertDirectory(const std::string& name,
+                                                     mode_t mode) = 0;
+  virtual std::shared_ptr<Symlink> insertSymlink(const std::string& name,
+                                                 const std::string& target) = 0;
+
+  // Move the file represented by `file` from its current directory to this
+  // directory with the new `name`, possibly overwriting another file that
+  // already exists with that name. The old directory may be the same as this
+  // directory. On success, return `true`. Otherwise return `false` without
+  // changing any underlying state.
```
Comment (kripken) [inline system/lib/wasmfs/file.h:192]: I think in another thread we discussed that this is only ever called from `rename`. Maybe that's worth mentioning here, plus that we assume the relevant locks have already been taken, as `rename` does?

**Review by kripken — APPROVED** [review]
Thanks for the explanations!
