### PR TITLE
[GLFW] Add missing checks before GLFW callbacks

### LINKED ISSUE #19145: GLFW zooming the browser window causes getWasmTableEntry(...) is not a function
After zooming the browser window with "ctrl +" or ctrl + scrollwheel, the following exception is thrown:

```
glfw_test.js:1 Uncaught TypeError: getWasmTableEntry(...) is not a function
    at Object.onWindowContentScaleChanged (glfw_test.js:1:86063)
    at MediaQueryList.updatePixelRatio (glfw_test.js:1:95551)
onWindowContentScaleChanged @ glfw_test.js:1
updatePixelRatio @ glfw_test.js:1
```

The getWasmTableEntry function seems to be included in the build, so this is probably some scoping issue.

**Reproduction:**
```c++
#include <GLFW/glfw3.h>
#include <emscripten.h>

void main_loop()
{
    
}

int main(int, char **argv)
{
    glfwInit();

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    GLFWwindow *window = glfwCreateWindow(1920, 1080, "Test", nullptr, nullptr);

    glfwMakeContextCurrent(window);
    
    emscripten_set_main_loop(main_loop, 0, true);
    
    return 0;
}
```

```cmake
cmake_minimum_required(VERSION 3.13)

set(CMAKE_EXECUTABLE_SUFFIX_CXX .html)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXE_LINKER_FLAGS "-v ${CMAKE_EXE_LINKER_FLAGS}")

add_executable(glfw_test
  
  main.cpp
)

target_link_options(
  glfw_test

  PUBLIC

  "SHELL:-s USE_GLFW=3"
)

```

**Compilation commands:**
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/jeremiah/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ../
make
```

Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/jeremiah/emsdk/upstream/bin

**Full link command and output with `-v` appended:**
```
[jeremiah@jeremiah build]$ make VERBOSE=1
/usr/bin/cmake -S/tmp/glfw_test -B/tmp/glfw_test/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/glfw_test/build/CMakeFiles /tmp/glfw_test/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/tmp/glfw_test/build'
make  -f CMakeFiles/glfw_test.dir/build.make CMakeFiles/glfw_test.dir/depend
make[2]: Entering directory '/tmp/glfw_test/build'
cd /tmp/glfw_test/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/glfw_test /tmp/glfw_test /tmp/glfw_test/build /tmp/glfw_test/build /tmp/glfw_test/build/CMakeFiles/glfw_test.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/glfw_test/build'
make  -f CMakeFiles/glfw_test.dir/build.make CMakeFiles/glfw_test.dir/build
make[2]: Entering directory '/tmp/glfw_test/build'
[ 50%] Building CXX object CMakeFiles/glfw_test.dir/main.cpp.o
/home/jeremiah/emsdk/upstream/emscripten/em++   -O3 -DNDEBUG -std=gnu++20 -MD -MT CMakeFiles/glfw_test.dir/main.cpp.o -MF CMakeFiles/glfw_test.dir/main.cpp.o.d -o CMakeFiles/glfw_test.dir/main.cpp.o -c /tmp/glfw_test/main.cpp
[100%] Linking CXX executable glfw_test.html
/usr/bin/cmake -E cmake_link_script CMakeFiles/glfw_test.dir/link.txt --verbose=1
/home/jeremiah/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG -v  -s USE_GLFW=3 @CMakeFiles/glfw_test.dir/objects1.rsp -o glfw_test.html 
 "/home/jeremiah/emsdk/upstream/bin/clang" --version
 "/home/jeremiah/emsdk/upstream/bin/wasm-ld" -o glfw_test.wasm CMakeFiles/glfw_test.dir/main.cpp.o -L/home/jeremiah/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpynjn6vhl.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export=malloc --export=free --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/home/jeremiah/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers glfw_test.wasm -o glfw_test.wasm --detect-features
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpryv8q1r2.json
 "/home/jeremiah/emsdk/upstream/bin/wasm-opt" --strip-dwarf --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers glfw_test.wasm -o glfw_test.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_60uf_8jn/glfw_test.js AJSDCE minifyWhitespace -o /tmp/emscripten_temp_60uf_8jn/glfw_test.jso1.js
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emcc_acorn_info_wud85euk.js emitDCEGraph noPrint
 "/home/jeremiah/emsdk/upstream/bin/wasm-metadce" --graph-file=/tmp/emcc_dce_graph_mtu5mlhw.json glfw_test.wasm -o glfw_test.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emcc_acorn_info_1kocdhof.js applyDCEGraphRemovals minifyWhitespace -o /tmp/emscripten_temp_60uf_8jn/glfw_test.jso2.js
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_60uf_8jn/glfw_test.jso2.js AJSDCE minifyWhitespace -o /tmp/emscripten_temp_60uf_8jn/glfw_test.jso3.js
 "/home/jeremiah/emsdk/upstream/bin/wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules glfw_test.wasm -o glfw_test.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emcc_acorn_info_44nyw_te.js applyImportAndExportNameChanges minifyWhitespace -o /tmp/emscripten_temp_60uf_8jn/glfw_test.jso4.js
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_60uf_8jn/settings.js shell.html
 "/home/jeremiah/emsdk/node/14.18.2_64bit/bin/node" /home/jeremiah/emsdk/upstream/emscripten/node_modules/.bin/html-minifier-terser glfw_test.html -o glfw_test.html --collapse-whitespace --collapse-inline-tag-whitespace --remove-comments --remove-tag-whitespace --sort-attributes --sort-class-name --decode-entities --collapse-boolean-attributes --remove-attribute-quotes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype --minify-css true --minify-js true
make[2]: Leaving directory '/tmp/glfw_test/build'
[100%] Built target glfw_test
make[1]: Leaving directory '/tmp/glfw_test/build'
/usr/bin/cmake -E cmake_progress_start /tmp/glfw_test/build/CMakeFiles 0
[jeremiah@jeremiah build]$ 
```

### PR DESCRIPTION
**Pull request by kripken**
Also convert them all to `if (..) { .. }` notation (diff without whitespace is
smaller). A few were left in the old format if the code benefited from
that due to other reasons in the surrounding logic.

Fixes #19145 Verified this fixes that manually, but perhaps there's a way
to make an automatic test with events somehow..?

### CODE REVIEW

File: src/library_glfw.js [hunk 1]
```diff
@@ -467,19 +467,23 @@ var LibraryGLFW = {
...
-      {{{ makeDynCall('vii', 'GLFW.active.cursorEnterFunc') }}}(GLFW.active.id, 1);
+        {{{ makeDynCall('vii', 'GLFW.active.cursorEnterFunc') }}}(GLFW.active.id, 1);
 #endif
+      }
     },
 
     onMouseleave: function(event) {
       if (!GLFW.active) return;
 
       if (event.target != Module["canvas"] || !GLFW.active.cursorEnterFunc) return;
```
Comment (sbc100) [inline src/library_glfw.js:480]: I guess you can drop the second part of this condition now?

File: src/library_glfw.js [hunk 2]
```diff
@@ -467,19 +467,23 @@ var LibraryGLFW = {
...
```
Comment (sbc100) [inline src/library_glfw.js:469]: Ditto

**Review by sbc100 — APPROVED** [review]

File: src/library_glfw.js (hunk 1 above)
Comment (kripken) [reply src/library_glfw.js]: Good catch, done.

**Review by sbc100 — APPROVED** [review]
