### PR TITLE
Make AVX types castable

### LINKED ISSUE #24076: AVX 256 functions accepting `__m{128,256}i_u` should accept `__m{128,256}i`
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 4.0.6 (1ddaae4d2d6dfbb678ecc193bc988820d1fc4633)
clang version 21.0.0git (https:/github.com/llvm/llvm-project 4775e6d9099467df9363e1a3cd5950cc3d2fde05)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /data/home/sliphua/open/emsdk/upstream/bin
```

**Failing command line in full:**
It fails to compile [astc-encoder](https://github.com/ARM-software/astc-encoder) x86-64 AVX2 version. Below is the error and a working solution. The other steps to adapt to emscripten AVX seem irrelevant, so they are not written here.

The error:
```
$ cd ~/open/astc-encoder/build_avx2
$ emcmake cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../ -DASTCENC_ISA_AVX2=ON ..
$ emmake make
make: make
[  2%] Building CXX object Source/CMakeFiles/astcenc-avx2-static.dir/astcenc_averages_and_directions.cpp.o
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_averages_and_directions.cpp:23:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_internal.h:35:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_mathlib.h:460:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib.h:86:
/data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib_avx2_8.h:137:7: error: no matching function for call to '_mm256_loadu_si256'
  137 |                 m = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(p));
      |                     ^~~~~~~~~~~~~~~~~~
/data/home/sliphua/open/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1276:1: note: candidate function not viable: no known conversion from 'const __m256i *' to 'const __m256i_u *' for 1st argument
 1276 | _mm256_loadu_si256(__m256i_u const* __p) {
      | ^                  ~~~~~~~~~~~~~~~~~~~~
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_averages_and_directions.cpp:23:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_internal.h:35:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_mathlib.h:460:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib.h:86:
/data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib_avx2_8.h:189:16: error: no matching function for call to '_mm256_lddqu_si256'
  189 |                 return vint8(_mm256_lddqu_si256(reinterpret_cast<const __m256i*>(p)));
      |                              ^~~~~~~~~~~~~~~~~~
/data/home/sliphua/open/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1284:1: note: candidate function not viable: no known conversion from 'const __m256i *' to 'const __m256i_u *' for 1st argument
 1284 | _mm256_lddqu_si256(__m256i_u const* __p) {
      | ^                  ~~~~~~~~~~~~~~~~~~~~
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_averages_and_directions.cpp:23:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_internal.h:35:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_mathlib.h:460:
In file included from /data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib.h:86:
/data/home/sliphua/open/astc-encoder/Source/astcenc_vecmathlib_avx2_8.h:522:2: error: no matching function for call to '_mm256_storeu_si256'
  522 |         _mm256_storeu_si256(reinterpret_cast<__m256i*>(p), a.m);
      |         ^~~~~~~~~~~~~~~~~~~
/data/home/sliphua/open/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1322:1: note: candidate function not viable: no known conversion from '__m256i *' to '__m256i_u *' for 1st argument
 1322 | _mm256_storeu_si256(__m256i_u* __p, __m256i __a) {
      | ^                   ~~~~~~~~~~~~~~
3 errors generated.
make[2]: *** [Source/CMakeFiles/astcenc-avx2-static.dir/build.make:77: Source/CMakeFiles/astcenc-avx2-static.dir/astcenc_averages_and_directions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:860: Source/CMakeFiles/astcenc-avx2-static.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
emmake: error: 'make' failed (returned 2)
```

A working solution:
Manually adding the `__m256i*` overloads of the functions suggested by the error message to `avxintrin.h` resolves the error.

SIMDe uses `void*`, so it appears they don't have the issue.
https://github.com/simd-everywhere/simde/blob/2af3dce9b2481b6b32139b1022cdfc02a633c898/simde/x86/avx.h#L4361

### LINKED ISSUE #26352: AVX types (`__m256{,i,d}`) should be castable to each other
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.1-git (8c5f43157a3f069ade75876e23061330521eabde)
clang version 23.0.0git (/startdir/llvm-project b447f5d9763010f8c6806c578533291aef2bd484)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emscripten-llvm/bin
```

**Failing command line in full:**
For the file test.c:
```c
#include <immintrin.h>

int
main(int argc, char** argv) {
  __m256i data, mask;
  data = _mm256_setzero_si256();
  mask = _mm256_setzero_si256();
  data = (__m256i)_mm256_and_ps((__m256)data, (__m256)mask);
  return 0;
}
```
```
$ emcc -msimd128 -mavx test.c
test.c:8:33: error: used type '__m256' where arithmetic or pointer type is required
    8 |   data = (__m256i)_mm256_and_ps((__m256)data, (__m256)mask);
      |                                 ^       ~~~~
test.c:8:47: error: used type '__m256' where arithmetic or pointer type is required
    8 |   data = (__m256i)_mm256_and_ps((__m256)data, (__m256)mask);
      |                                               ^       ~~~~
2 errors generated.
emcc: error: '/opt/emscripten-llvm/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
 --sysroot=/home/btolsch/.cache/emscripten/sysroot -DEMSCRIPTEN -D__SSE__=1 -D__SSE2__=1 -D__SSE3__=1 -D__SSSE3__=1 -D__SSE4_1__=1 -D__SSE4_2__=1 -D__AVX__=1 -Xclang -iwithsysroot/include/fakesd
l -Xclang -iwithsysroot/include/compat -msimd128 -c test.c -o /tmp/emscripten_temp_xnre9uu1/test.o' failed (returned 1)

```

**Desired behavior**
Both clang and gcc allow casting between `__m256`, `__m256i`, and `__m256d`.  This is because they are declared as vector types (i.e. `__attribute__((__vector_size(n)))`) and not structs or unions.  The emscripten definitions are structs like:
```c
typedef struct {
  __m128d v0;
  __m128d v1;
} __m256d;
```
These can't be cast to each other, so instead you have to do something like `*(__m256*)&data` or `memcpy` to a new variable (which is hopefully optimized out).  Moreover, the `__m128*` definitions _are_ vectors, so this problem is specific to the AVX types.

The struct definitions are convenient for the implementation, which entirely falls back to 128-bit operations, but can break existing AVX code which has no SSE or scalar fallback of its own.

### PR DESCRIPTION
**Pull request by btolsch**
This change makes `__m256*` defined as vector types (i.e. `__attribute__((__vector_size(32)))`) so they can be cast to each other.  The implementation of all the AVX functions are unchanged, but require conversion internally to the old struct types in order to call m128 functions on each lane.

Fixes #24076, fixes #26352.

### CODE REVIEW

File: system/include/compat/avxintrin.h [hunk 1]
```diff
@@ -16,27 +16,81 @@
...
+typedef int32_t __m256i __attribute__((__vector_size__(32), __aligned__(32)));
+
+typedef int32_t __m128i_u __attribute__((__vector_size__(16), __aligned__(1)));
+typedef int32_t __m256i_u __attribute__((__vector_size__(32), __aligned__(1)));
+
 typedef struct {
   __m128d v0;
   __m128d v1;
-} __m256d;
+} __m256d_private;
```
Comment (sbc100) [inline system/include/compat/avxintrin.h]: Would `_internal` make more sense the `_private` here?

**Comment by tlively** [comment]
This makes sense to me.

File: system/include/compat/avxintrin.h (hunk 1 above)
Comment (btolsch) [reply system/include/compat/avxintrin.h]: Fine with me.  Done.

File: system/include/compat/avx2intrin.h [hunk 2]
```diff
@@ -18,641 +18,762 @@
 
 #define _mm256_mpsadbw_epu8(__A, __B, __imm)                                   \
   __extension__({                                                              \
-    __m256i __a = (__A);                                                       \
-    __m256i __b = (__B);                                                       \
+    __m256i_internal __a = __m256i_to_internal(__A);                             \
+    __m256i_internal __b = __m256i_to_internal(__B);                             \
```
Comment (sbc100) [inline system/include/compat/avx2intrin.h]: Can you fix the alignment of the trailing `\` here?

Comment (btolsch) [reply system/include/compat/avx2intrin.h]: Done

**Comment by btolsch** [comment]
> Could you add a test for this casting? Maybe modify one of the existing tests?

I added basic compile tests for both the regular casting and the unaligned pointer casting.
