### PR TITLE
Define EMSCRIPTEN in the wasm backend

### LINKED ISSUE #8921: llvm upstream EMSCRIPTEN is not defined
Hi. I know that llvm-upstream should became default soon and now I want to test it over all projects that I have. I am started with very simple one, and I can't compile it.
I am using emsdk with installed latest-upstream, latest-fastcomp. 
I found that in upstream `#define EMSCRIPTEN` is missed (looks like it ships somewhere internally in fastcomp).  If it's true, then it's breaking change but I have not success with googling it.

**My testcase:**
CMakeLists.txt
```
add_executable(main "main.cpp")
```

main.cpp
```
#ifdef EMSCRIPTEN
    emscripten defined
#else
    emscripten NOT defined
#endif
```

To build I used this commands:
```
./emsdk activate --embded latest-upstream/latest
source ./emsdk_env.sh
emcmake cmake -GNinja ..
ninja -v
```

Output for fastcomp:
```
[1/2] /home/caiiiycuk/emscripten/sdk/emsdk/fastcomp/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
FAILED: CMakeFiles/main.dir/main.cpp.o 
/home/caiiiycuk/emscripten/sdk/emsdk/fastcomp/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
../main.cpp:2:5: error: unknown type name 'emscripten'
    emscripten defined
    ^
../main.cpp:2:23: error: expected ';' after top level declarator
    emscripten defined
                      ^
                      ;
2 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
ninja: build stopped: subcommand failed.
```

output for upstream:
```
[1/2] /usr/bin/c++    -g -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
FAILED: CMakeFiles/main.dir/main.cpp.o 
/usr/bin/c++    -g -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
../main.cpp:4:5: error: ‘emscripten’ does not name a type
     emscripten NOT defined
     ^~~~~~~~~~
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by kripken**
This is useful for fastcomp backwards compatibility.

This is in addition to the more proper `__EMSCRIPTEN__` that the backend defines by itself.

Alternatively, perhaps we can not do this, and document in a prominent place that this is a breaking change.

Fixes #8921

### CODE REVIEW

**Comment by VirtualTim** [comment]
There is a comment about this hidden deep in the code, so a more obvious place would be good.

https://github.com/emscripten-core/emscripten/blob/9aff7f29885ed34ea42f129ec718f3c0f0fdd018/emcc.py#L672-L673

**Comment by sbc100** [comment]
Yeah, it looks like it should be defined unless you build with `-s STRICT`

**Comment by kripken** [comment]
Thanks @VirtualTim and @sbc100, very good points. Fixed in that commit.

We actually did have code to do this, but it was just wrong (it added the define in the wrong place) and had no test. Fixed it and added testing.

File: src/settings.js [hunk 1]
```diff
@@ -746,6 +746,11 @@ var LINKABLE = 0;
 // Emscripten 'strict' build mode: Drop supporting any deprecated build options.
 // Set the environment variable EMCC_STRICT=1 or pass -s STRICT=1 to test that a
 // codebase builds nicely in forward compatible manner.
+// Changes enabled by this:
+//   * ERROR_ON_MISSING_LIBRARIES is enabled
+//   * DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR is enabled
+//   * The C define EMSCRIPTEN is not defined (__EMSCRIPTEN__ always is, and
+//     is the correct thing to use).
```
Comment (VirtualTim) [inline src/settings.js]: 👍 This is much more obvious.

File: emcc.py [hunk 2]
```diff
@@ -1082,10 +1086,6 @@ def check(input_file):
 
     if shared.Settings.STRICT:
       shared.Settings.DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR = 1
-    else:
-      # The preprocessor define EMSCRIPTEN is deprecated. Don't pass it to code
-      # in strict mode. Code should use the define __EMSCRIPTEN__ instead.
-      shared.COMPILER_OPTS += ['-DEMSCRIPTEN']
```
Comment (sbc100) [inline emcc.py]: Why is this location wrong?

Comment (kripken) [reply emcc.py]: It was wrong because `shared.COMPILER_OPTS` is read and added to `newargs`. Modifying it after that point is never noticed.
