### PR TITLE
Restore the musl pthread circular thread list, in order to fix the pthread key recreation zero-initialization issue

### LINKED ISSUE #8740: pthread_key_create does not initialize thread local variable with null
The following code fails with emscripten right now:

```
pthread_key_t k;
pthread_key_create(&k, NULL);
assert(pthread_getspecific(k) == 0); // fine

pthread_setspecific(k, (void*)1);
pthread_key_delete(k);

pthread_key_create(&k, NULL);
assert(pthread_getspecific(k) == 0); // fails
```

According to POSIX specification, after creation of a thread local key, the value should be zero on key creation on all threads.
See: http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_key_create.html

### PR DESCRIPTION
**Pull request by mannk123**
Restored the musl circular thread list, and added a test case.

One notably adjustment needed for emscripten is, in pthread_create, to add the new thread to the list *prior* to handing off to a worker using __pthread_create_js, as there is a race condition otherwise since the new thread can potentially run and exit via _emscripten_thread_exit, before the call returns to pthread_create.

On top of that, there is one code path specific to emscripten (and not musl) - when workers are returned to the pool (returnWorkerToPool), _emscripten_thread_free_data is called to free the associated __pthread structure. It's possible for this to happen without the _emscripten_thread_exit cleanup code (removal from the list) having been called. So I also modified _emscripten_thread_free_data to perform the necessary adjustments to the thread list pointers.

Fixes: #8740

### CODE REVIEW

File: system/lib/libc/musl/src/thread/pthread_key_create.c [hunk 1]
```diff
@@ -26,7 +26,7 @@ weak_alias(dummy_0, __tl_unlock);
 
 int __pthread_key_create(pthread_key_t *k, void (*dtor)(void *))
 {
-	pthread_t self = __pthread_self();
+        pthread_t self = __pthread_self(), td=self;
```
Comment (kleisauke) [inline system/lib/libc/musl/src/thread/pthread_key_create.c:29]: This change should not be needed, since `td` is not used in this function.

File: system/lib/pthread/pthread_create.c [hunk 2]
```diff
@@ -68,6 +68,31 @@ static int dummy_getpid(void) {
...
+
+void __tl_unlock(void) {
+  if (tl_lock_count) {
+    tl_lock_count--;
+    return;
+  }
+  a_store(&__thread_list_lock, 0);
+  if (tl_lock_waiters) __wake(&__thread_list_lock, 1, 0);
+}
+
```
Comment (kleisauke) [inline system/lib/pthread/pthread_create.c:95]: Should the `__tl_sync` function also be implemented here?
https://github.com/emscripten-core/emscripten/blob/8647224628dfc10dec6e5c6f3621d625a5f16eda/system/lib/libc/musl/src/thread/pthread_create.c#L45-L52

`pthread_join` seems to use this.
https://github.com/emscripten-core/emscripten/blob/8647224628dfc10dec6e5c6f3621d625a5f16eda/system/lib/libc/musl/src/thread/pthread_join.c#L45

Comment (mannk123) [reply system/lib/pthread/pthread_create.c:95]: You are right, that was a bad oversight from me. Let me try to fix this.

**Comment by mannk123** [comment]
@kleisauke Thanks for the review, I have made the changes. After some investigation, also modified _emscripten_thread_free_data to adjust the thead list.

File: system/lib/pthread/pthread_create.c [hunk 3]
```diff
@@ -232,6 +263,13 @@ void _emscripten_thread_free_data(pthread_t t) {
   }
 #endif
 
+  __tl_lock();
+
+  t->next->prev = t->prev;
+  t->prev->next = t->next;
```
Comment (sbc100) [inline system/lib/pthread/pthread_create.c:269]: Why is this needed in addition to the block in _emscripten_thread_exit?  All threads should call _emscripten_thread_exit shouldn't they?

Comment (mannk123) [reply system/lib/pthread/pthread_create.c:280]: There was a race condition, and that block was supposed to be a fix for it.

What was happening was that, inside pthread_create, the new pthread gets added to the circular list *after* the call to __pthread_create_js. This leads to a race where the new thread starts running and exits (i.e. calls _emscripten_thread_exit), before it gets added to the list inside pthread_create, meaning the list now contains a DT_EXITED thread that should not be there. 

The proper fix here is for the list to be updated *before* calling __pthread_create_js. If the call fails, the new pthread is then removed from the list. I have made that change.

However, I think it may still make sense to keep the block above, as there are cases where a pthread structure is freed using _emscripten_thread_free_data, without having called _emscripten_thread_exit:
i) In exitRuntime, terminateAllThreads is called which returns all workers to the thread pool and calls _emscripten_thread_free_data on them, regardless of whether they have exited. 
ii) Any thread that calls exit() *does not* call _emscripten_thread_exit either (see e=='unwind' in worker.js), which may be potentially problematic when EXIT_RUNTIME is not enabled.  Notably, in the PROXY_TO_PTHREAD case, the "main" thread is itself a pthread that ends up calling exit(), meaning it won't perform _emscripten_thread_exit cleanup either.

Given the above, it seems more correct to have that block above in _emscripten_thread_free_data.

Anyway, the above is just my beginner's understanding of the code, eager to know what you think!

Comment (sbc100) [reply system/lib/pthread/pthread_create.c:280]: If a thread doesn't exit with `_emscripten_thread_exit` that would be a bug, and I don't think we should try to work around it unless we have to.

I suggest we leave `_emscripten_thread_free_data` alone, unless that change is needs to make a particular test pass?

File: system/lib/libc/musl/src/thread/pthread_key_create.c [hunk 4]
```diff
@@ -26,7 +26,7 @@ weak_alias(dummy_0, __tl_unlock);
 
 int __pthread_key_create(pthread_key_t *k, void (*dtor)(void *))
 {
-	pthread_t self = __pthread_self();
+        pthread_t self = __pthread_self();
```
Comment (sbc100) [inline system/lib/libc/musl/src/thread/pthread_key_create.c:29]: Revert his line

File: test/test_browser.py [hunk 5]
```diff
@@ -5434,6 +5434,10 @@ def test_pthread_unhandledrejection(self):
                      test_file('pthread/test_pthread_unhandledrejection.post.js')],
                expected='exception:Uncaught [object ErrorEvent] / undefined')
 
+  @requires_threads
+  def test_pthread_key_recreation(self):
+    self.btest_exit(test_file('pthread/test_pthread_key_recreation.cpp'), args=['-sUSE_PTHREADS', '-sPTHREAD_POOL_SIZE'])
```
Comment (sbc100) [inline test/test_browser.py:5439]: `-sPTHREAD_POOL_SIZE=1` I think would be more clear here.

File: test/pthread/test_pthread_key_recreation.cpp [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+//  pthread_key_delete of key k
+//  pthread_key_create returning the same key k
+// , that the thread local slot is correctly initialized to 0 in all threads
+
+// overall structure based on test_pthread_reltime.cpp
+
+static pthread_key_t key;
+
+static std::mutex mutex;
+static std::condition_variable cond_var;
```
Comment (sbc100) [inline test/pthread/test_pthread_key_recreation.cpp:23]: It seems a little odd to make pthread-API stuff with C++ threed API stuff, but maybe its fine?

The alternative would be to use `pthread_mutex_t` and `pthread_cond_t` here (you could also then make this in a pure C test without any C++).

**Review by sbc100 — COMMENTED** [review]
Thanks for working on this!  Looks good aside from a few of comments.

**Comment by mannk123** [comment]
@sbc100 Thanks, I have made all the suggested changes.

**Review by sbc100 — APPROVED** [review]
