### PR TITLE
Fix for mktime + ASSERTIONS=2

### LINKED ISSUE #26704: mktime can trigger an assert if using -s ASSERTIONS=2
**Version of emscripten/emsdk:**
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.3 (285c424dfa9e83b03cf8490c65ceadb7c45f28eb)
clang version 23.0.0git (https:/github.com/llvm/llvm-project e5927fecf8a6ce89e1a4eac5b828e7d42676452a)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/emsdk/upstream/bin

**Failing command line in full:**
$ emrun index.html 

'''
...
Time 9223372036854502091 -> -8639883276808 [index.js:1589:16](http://localhost:6931/index.js)
 Time 9223372036854502090 -> -8639914812808 [index.js:1589:16](http://localhost:6931/index.js)
 Time 9223372036854502089 -> -8639946348808 [index.js:1589:16](http://localhost:6931/index.js)
 Time 9223372036854502088 -> -8639977971208 [index.js:1589:16](http://localhost:6931/index.js)
Aborted(Assertion failed: attempt to write non-integer (NaN) into integer heap) [index.js:595:6](http://localhost:6931/index.js)
Uncaught RuntimeError: Aborted(Assertion failed: attempt to write non-integer (NaN) into integer heap)
    abort http://localhost:6931/index.js:613
    assert http://localhost:6931/index.js:271
    checkInt http://localhost:6931/index.js:469
    checkInt32 http://localhost:6931/index.js:477
    ret http://localhost:6931/index.js:1002
    __mktime_js http://localhost:6931/index.js:1019
    createExportWrapper http://localhost:6931/index.js:628
    callMain http://localhost:6931/index.js:5069
    doRun http://localhost:6931/index.js:5122
    run http://localhost:6931/index.js:5131
[index.js:613:11](http://localhost:6931/index.js)

**Full link command and output with `-v` appended:**
$ emcc -o index.html main.cpp -s ASSERTIONS=2 -v

'''
 /usr/local/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/usr/local/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v -c main.cpp -o /tmp/emscripten_temp_fs68ul96/main.o
clang version 23.0.0git (https:/github.com/llvm/llvm-project e5927fecf8a6ce89e1a4eac5b828e7d42676452a)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/emsdk/upstream/bin
 (in-process)
 "/usr/local/emsdk/upstream/bin/clang-23" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb -fdebug-compilation-dir=/media/evenan/LaCie/lnx/source/repos/QTBUG/QTBUG-mktime -v -fcoverage-compilation-dir=/media/evenan/LaCie/lnx/source/repos/QTBUG/QTBUG-mktime -resource-dir /usr/local/emsdk/upstream/lib/clang/23 -D EMSCRIPTEN -isysroot /usr/local/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/noeh/c++/v1 -internal-isystem /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /usr/local/emsdk/upstream/lib/clang/23/include -internal-isystem /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /usr/local/emsdk/upstream/emscripten/cache/sysroot/include -fdeprecated-macro -ferror-limit 19 -fmessage-length=126 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_fs68ul96/main.o -x c++ main.cpp
clang -cc1 version 23.0.0git based upon LLVM 23.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/noeh/c++/v1"
ignoring nonexistent directory "/usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/usr/local/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /usr/local/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /usr/local/emsdk/upstream/lib/clang/23/include
 /usr/local/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 /usr/local/emsdk/upstream/bin/clang --version
 /usr/local/emsdk/upstream/bin/wasm-ld -o index.wasm /tmp/tmpi922fjyolibemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1 /tmp/emscripten_temp_fs68ul96/main.o -L/usr/local/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -L/usr/local/emsdk/upstream/emscripten/src/lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-debug-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
 /usr/local/emsdk/upstream/bin/llvm-objcopy index.wasm index.wasm '--remove-section=llvm.func_attr.annotate.*' --remove-section=producers --remove-section=name '--remove-section=.debug*'
 /usr/local/emsdk/upstream/bin/wasm-emscripten-finalize --bigint --no-dyncalls --no-legalize-javascript-ffi --check-stack-overflow index.wasm -o index.wasm --detect-features
 /usr/local/emsdk/node/22.16.0_64bit/bin/node /usr/local/emsdk/upstream/emscripten/tools/compiler.mjs -
 /usr/local/emsdk/node/22.16.0_64bit/bin/node /usr/local/emsdk/upstream/emscripten/tools/preprocessor.mjs - shell.html
'''

[main.cpp](https://github.com/user-attachments/files/26810276/main.cpp)

### PR DESCRIPTION
**Pull request by sbc100**
There were two issues with the existing code:

1. Values were being written even when the Data was invalid.
2. In ASSERTIONS=2 these invalid values were causing assertions.

Fixes: #26704

### CODE REVIEW

File: test/other/test_time.c [hunk 1]
```diff
@@ -218,12 +219,28 @@ void test_yday() {
 }
 
 void test_year_overflow() {
-  // Verify that timestamps outside of the range supported by date.getNow()
-  // cause failure with EOVERFLOW.
+  // Verify that timestamps outside of the range supported JavaScript Date
+  // object with result in gracefull failure with EOVERFLOW.
```
Comment (kripken) [inline test/other/test_time.c]:
```suggestion
  // object with result in graceful failure with EOVERFLOW.
```

**Review by kripken — APPROVED** [review]
