### PR TITLE
Fix inode number overflow in readdir test

### LINKED ISSUE #26090: test_fs_readdir_ino_matches_stat_ino_rawfs is flaky
```
Aborted(Assertion failed: a_ino >= 0, at: /root/project/test/fs/test_fs_readdir_ino_matches_stat_ino.c,54,main)
/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1
var Module=typeof Module!="undefined"?Module:{};var ENVIRONMENT_IS_WEB=!!globalThis.window;var ENVIRONMENT_IS_WORKER=!!globalThis.WorkerGlobalScope;var ENVIRONMENT_IS_NODE=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";var arguments_=[];var thisProgram="./this.program";var quit_=(status,toThrow)=>{throw toThrow};var _scriptName=globalThis.document?.currentScript?.src;if(typeof __filename!="undefined"){_scriptName=__filename}else if(ENVIRONMENT_IS_WORKER){_scriptName=sel[..]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [..]

RuntimeError: Aborted(Assertion failed: a_ino >= 0, at: /root/project/test/fs/test_fs_readdir_ino_matches_stat_ino.c,54,main). Build with -sASSERTIONS for more info.
    at abort (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:3429)
    at ___assert_fail (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:7274)
    at wasm://wasm/ad62121a:wasm-function[15]:0x1c65
    at callMain (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:68603)
    at doRun (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:69007)
    at run (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:69161)
    at removeRunDependency (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:6041)
    at receiveInstance (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:4920)
    at receiveInstantiationResult (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:5067)
    at createWasm (/tmp/emtest_h7ymn5ui/emscripten_test_core2_g4hh0yj7/test_fs_readdir_ino_matches_stat_ino.js:1:5392)
Thrown at:
```

### PR DESCRIPTION
**Pull request by brendandahl**
The test was failing intermittently on Linux because inode numbers were stored in signed 32-bit integers. On modern Linux filesystems, inode numbers frequently exceed the range of a signed 32-bit integer, leading to narrowing overflows and negative values which triggered assertion failures.

This change updates the test to use ino_t (which is 64-bit in Emscripten).

Fixes #26090

### CODE REVIEW

File: test/fs/test_fs_readdir_ino_matches_stat_ino.c [hunk 1]
```diff
@@ -51,10 +51,10 @@ int main() {
...
   }
   assert(errno == 0);
-  assert(a_ino >= 0);
-  assert(b_ino >= 0);
-  printf("readdir a_ino: %d, b_ino: %d\n", a_ino, b_ino);
-  printf("stat    a_ino: %llu, b_ino: %llu\n", sta.st_ino, stb.st_ino);
+  assert(a_ino > 0);
+  assert(b_ino > 0);
+  printf("readdir a_ino: %llu, b_ino: %llu\n", (unsigned long long)a_ino, (unsigned long long)b_ino);
+  printf("stat    a_ino: %llu, b_ino: %llu\n", (unsigned long long)sta.st_ino, (unsigned long long)stb.st_ino);
```
Comment (sbc100) [inline test/fs/test_fs_readdir_ino_matches_stat_ino.c]: Presumably if we fix the foramt string we don't need those casts?

It looks like `ino_t` is always 64-bit under emscripten.

**Review by sbc100 — APPROVED** [review]
